-- CREATE TABLE PARAMS
DECLARE
tbl_count number;
sql_stmt long;

BEGIN
    SELECT COUNT(*) INTO tbl_count 
    FROM dba_tables
    WHERE owner = 'COSWIN'
    AND table_name = 'STE_MIGRATION_PARAMS';

    IF(tbl_count <= 0)
    THEN
    	sql_stmt:='
		CREATE TABLE COSWIN.STE_MIGRATION_PARAMS(
			id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
			package_name varchar2(250) NOT NULL,
			parameter_name varchar2(250) NOT NULL,
			parameter_value varchar2(250) NOT NULL,
			created_on DATE DEFAULT CURRENT_TIMESTAMP,
			created_by varchar2(250) NULL,
			modified_on DATE NULL,
			modified_by varchar2(250) NULL
		)';
		EXECUTE IMMEDIATE sql_stmt;
    END IF;
END;

-- UPDATE PARAMS
INSERT INTO COSWIN.STE_MIGRATION_PARAMS
           (package_name
           ,parameter_name
           ,parameter_value
           ,created_by
	   )
     VALUES
           ('0001_Check_CoswinDB'
           ,'version'
           ,'1'
           ,'ssis'
           )
;

