ALTER TABLE ASSET
ADD STE_MIGRATIONID bigint default null,
    STE_MIGRATIONDATE datetime NOT NULL DEFAULT (GETDATE())
	;
	
ALTER TABLE ASSET
ADD STE_MIGRATIONPRCD VARCHAR(20) default null,
	STE_MIGRATIONLEVEL int default null
	;
	
ALTER TABLE ASSETLOCUSERCUST
ADD STE_MIGRATIONASSETID varchar(40) NULL,
	STE_MIGRATIONID bigint default null,
    STE_MIGRATIONDATE datetime NOT NULL DEFAULT (GETDATE())
	;

ALTER TABLE ASSETLOCUSERCUST
ADD STE_MIGRATIONEQCD varchar(20) NULL
	;
	
ALTER TABLE ASSETMETER
ADD STE_MIGRATIONASSETID varchar(40) NULL,
	STE_MIGRATIONID bigint default null,
    STE_MIGRATIONDATE datetime NOT NULL DEFAULT (GETDATE())
	;

ALTER TABLE ASSETMETER
ADD STE_MIGRATIONEQCD varchar(40) NULL
	;
	
CREATE TABLE [dbo].[ste_assetsrno](
	[assetnum] [varchar](12) NOT NULL,
	[serialno] [varchar](30) NOT NULL,
	[siteid] [varchar](8) NOT NULL,
	[orgid] [varchar](8) NOT NULL,
	[ste_cswnsnodate] [datetime] NULL,
	[assetsrnoid] [bigint] NOT NULL,
	[STE_MIGRATIONID] [bigint] NULL,
	[STE_MIGRATIONDATE] [datetime] NOT NULL
) ON [PRIMARY]
;

ALTER TABLE [dbo].[ste_assetsrno]
ADD STE_MIGRATIONASSETID varchar(40) NULL;

ALTER TABLE [ste_assetsrno]
ADD STE_MIGRATIONEQCD varchar(20) NULL
	;
	
ALTER TABLE ASSETTRANS
ADD STE_MIGRATIONASSETID varchar(40) NULL,
	STE_MIGRATIONID bigint default null,
    STE_MIGRATIONDATE datetime NOT NULL DEFAULT (GETDATE())
	;
	
ALTER TABLE ASSETTRANS
ADD STE_MIGRATIONEQCD varchar(20) NULL;

ALTER TABLE ASSETSPEC
ADD STE_MIGRATIONASSETID varchar(40) NULL,
	STE_MIGRATIONID bigint default null,
    STE_MIGRATIONDATE datetime NOT NULL DEFAULT (GETDATE())
	;
	
ALTER TABLE ASSETSPEC
ADD STE_MIGRATIONEQCD varchar(20) NULL;

ALTER TABLE SPAREPART
ADD STE_MIGRATIONEQCD varchar(40) default null, 
	STE_MIGRATIONASSETID varchar(40) default null,
	STE_MIGRATIONID bigint default null,
    STE_MIGRATIONDATE datetime NOT NULL DEFAULT (GETDATE());

ALTER TABLE [ROUTE_STOP]
ADD STE_MIGRATIONID bigint default null,
    STE_MIGRATIONDATE datetime NOT NULL DEFAULT (GETDATE());

ALTER TABLE [ROUTE_STOP]
ADD STE_MIGRATIONEQCD varchar(20) default null,
	STE_MIGRATIONASSETID varchar(40) default null,
	STE_MIGRATIONGRCD varchar(20) default null;

ALTER TABLE COMPANIES
ADD STE_MIGRATIONID bigint default null,
    STE_MIGRATIONDATE datetime NOT NULL DEFAULT (GETDATE());
;

ALTER TABLE COMPCONTACT
ADD STE_MIGRATIONID bigint default null,
    STE_MIGRATIONDATE datetime NOT NULL DEFAULT (GETDATE());
;

ALTER TABLE COMPMASTER
ADD STE_MIGRATIONID bigint default null,
    STE_MIGRATIONDATE datetime NOT NULL DEFAULT (GETDATE());
;

;
ALTER TABLE COMPMASTER
ADD STE_MIGRATIONRMK1 IMAGE default null,
    STE_MIGRATIONRMK2 IMAGE default null,
	STE_MIGRATIONRMK3 IMAGE default null
;

ALTER TABLE COMPCONTACTMSTR
ADD STE_MIGRATIONID bigint default null,
    STE_MIGRATIONDATE datetime NOT NULL DEFAULT (GETDATE());
;

ALTER TABLE ITEM
ADD STE_MIGRATIONSOURCE VARCHAR(100) default null;

ALTER TABLE ITEM
ADD STE_MIGRATIONID bigint default null,
    STE_MIGRATIONDATE datetime NOT NULL DEFAULT (GETDATE());

ALTER TABLE [ROUTES]
ADD STE_MIGRATIONGRCD varchar(20) default null;

ALTER TABLE [ROUTES]
ADD STE_MIGRATIONID bigint default null,
    STE_MIGRATIONDATE datetime NOT NULL DEFAULT (GETDATE());
	
ALTER TABLE FailureList
ADD STE_MIGRATIONID bigint default null,
    STE_MIGRATIONDATE datetime NOT NULL DEFAULT (GETDATE());
	
ALTER TABLE FailureCode
ADD STE_MIGRATIONID bigint default null,
    STE_MIGRATIONDATE datetime NOT NULL DEFAULT (GETDATE());
	
ALTER TABLE AssetAttribute
ADD STE_MIGRATIONID bigint default null,
    STE_MIGRATIONDATE datetime NOT NULL DEFAULT (GETDATE());

ALTER TABLE [CLASSIFICATION]
ADD STE_MIGRATIONID bigint default null,
    STE_MIGRATIONDATE datetime NOT NULL DEFAULT (GETDATE());
	
ALTER TABLE ClassStructure
ADD STE_MIGRATIONID varchar(25) default null,
    STE_MIGRATIONDATE datetime NOT NULL DEFAULT (GETDATE());
	
ALTER TABLE METER
ADD STE_MIGRATIONID bigint default null,
    STE_MIGRATIONDATE datetime NOT NULL DEFAULT (GETDATE());
	
ALTER TABLE PERSON
ADD STE_MIGRATIONID bigint default null,
    STE_MIGRATIONDATE datetime NOT NULL DEFAULT (GETDATE());
	
ALTER TABLE LOCATIONS
ADD STE_MIGRATIONSOURCE VARCHAR(250) default null,
    STE_MIGRATIONSTOREAUTHORITY VARCHAR(250) DEFAULT NULL;
;

ALTER TABLE LOCATIONS
ADD STE_MIGRATIONID bigint default null,
    STE_MIGRATIONDATE datetime NOT NULL DEFAULT (GETDATE());
;