--#SET TERMINATOR /

CREATE OR REPLACE PROCEDURE MIGRATION.STE_START_PATCH(
	IN P_PATCHNAME VARCHAR(50)
)
LANGUAGE SQL
SPECIFIC STE_START_PATCH
BEGIN

	INSERT INTO MIGRATION.ste_migration_logs (
	 package_name
	 ,version
	 ,start_date
	 ,hostname 
	)
	VALUES (
	 P_PATCHNAME
	 , '1.0'
	 , add_hours(CURRENT_TIMESTAMP,8)
	 , NULL
	);

END;
/

--#SET TERMINATOR /

CREATE OR REPLACE PROCEDURE MIGRATION.STE_FINISH_PATCH(
	IN P_PATCHNAME VARCHAR(50)
)
LANGUAGE SQL
SPECIFIC STE_FINISH_PATCH
BEGIN
	DECLARE V_MAX INTEGER DEFAULT 0;
	
	SET V_MAX = (SELECT ID FROM MIGRATION.ste_migration_logs WHERE package_name=P_PATCHNAME ORDER BY ID DESC LIMIT 1);
	
	UPDATE MIGRATION.ste_migration_logs 
	SET
	 end_date = add_hours(CURRENT_TIMESTAMP,8)
	 , success = 1
	WHERE id = V_MAX
	;

END;
/

--#SET TERMINATOR ;

CALL MIGRATION.STE_START_PATCH('20250409-01-UPDATE-SEQ');

CALL MIGRATION.STE_UPDATE_SEQ('ASSETSEQ', 'ASSET', 'ASSETUID');
CALL MIGRATION.STE_UPDATE_SEQ('ASSETIDSEQ', 'ASSET', 'ASSETID');

update maximo.autokey 
set seed=(SELECT MAX(CAST(REPLACE(ASSETNUM, 'A1', '') AS BIGINT)) + 100000000000 AS MAX_ID from maximo.ASSET a WHERE ASSETNUM LIKE 'A1%')
where autokeyname='ASSETNUM' and orgid='SBST' AND prefix='A';

CALL MIGRATION.STE_UPDATE_SEQ('PLUSTASSETALIASSEQ', 'PLUSTASSETALIAS', 'PLUSTASSETALIASID');
CALL MIGRATION.STE_UPDATE_SEQ('PLUSTASSETSTHISTSEQ', 'PLUSTASSETSTHIST', 'PLUSTASSETSTHISTID');
CALL MIGRATION.STE_UPDATE_SEQ('ASSETANCESTORSEQ', 'ASSETANCESTOR', 'ASSETANCESTORID');
CALL MIGRATION.STE_UPDATE_SEQ('ASSETTRANSSEQ', 'ASSETTRANS', 'ASSETTRANSID');

CALL MIGRATION.STE_UPDATE_SEQ('INVBALANCESSEQ', 'INVBALANCES', 'INVBALANCESID');
CALL MIGRATION.STE_UPDATE_SEQ('INVCOSTSEQ', 'INVCOST', 'INVCOSTID');
CALL MIGRATION.STE_UPDATE_SEQ('INVENTORYSEQ', 'INVENTORY', 'INVENTORYID');

CALL MIGRATION.STE_FINISH_PATCH('20250409-01-UPDATE-SEQ');
