CALL MIGRATION.STE_START_PATCH('20250427-02-RFQ-VENDREPLYDATE-CLOSEONDATE');

-- BRING MAXIMO.CSWN_PO FROM ON-PREM
-- BRING MAXIMO.CSWN_RFQ FROM ON-PREM

-- UPDATE RFQ.CLOSEDONDATE (44.928)
MERGE INTO MAXIMO.RFQ A
USING (
	SELECT A.RFQID, A.RFQNUM, A.CLOSEONDATE AS ORIG_CLOSEONDATE, B.DV_EXP_RET
		, CASE WHEN COALESCE(B.DV_EXP_RET,0)=0 THEN NULL ELSE TO_DATE('31-12-1899', 'DD-MM-YYYY') + B.DV_EXP_RET END AS CLOSEONDATE
	FROM MAXIMO.RFQ A
	JOIN MAXIMO.CSWN_RFQ B ON A.STE_MIGRATIONID=B.PK_DEVIS
		--AND A.RFQNUM='SO04586524000'
) B ON B.RFQID=A.RFQID
WHEN MATCHED THEN
UPDATE SET
	CLOSEONDATE=B.CLOSEONDATE
;

-- UPDATE RFQVENDOR.REPLIEDDATE (19.807)
MERGE INTO MAXIMO.RFQVENDOR A
USING (
	SELECT A.RFQNUM, A.RFQLINEID, A.PONUM, B.VENDOR, D.RFQVENDORID, D.REPLIEDDATE AS ORIG_REPLIEDDATE, C.RFQCLOSEDATE AS REPLIEDDATE
		, ROW_NUMBER() OVER (PARTITION BY A.RFQNUM, B.VENDOR ORDER BY A.RFQLINEID) RN
	FROM MAXIMO.RFQLINE A
	JOIN MAXIMO.PO B ON B.PONUM=A.PONUM
	JOIN MAXIMO.CSWN_PO C ON C.PK_PORDER_=B.STE_MIGRATIONID
	JOIN MAXIMO.RFQVENDOR D ON D.RFQNUM=A.RFQNUM AND D.VENDOR=B.VENDOR
	WHERE C.RFQCLOSEDATE IS NOT NULL
		--AND A.RFQNUM='SO04586524000'
) B ON B.RN=1 AND B.RFQVENDORID=A.RFQVENDORID
WHEN MATCHED THEN
UPDATE SET
	REPLIEDDATE=B.REPLIEDDATE
;

CALL MIGRATION.STE_FINISH_PATCH('20250427-02-RFQ-VENDREPLYDATE-CLOSEONDATE');