CALL MIGRATION.STE_START_PATCH('20250403-04-RFQ-MAPPING');

CREATE TABLE MIGRATION."PATCH_20250403_RFQ"  (
		  "RFQNUM" VARCHAR(15 OCTETS) NOT NULL , 
		  "DESCRIPTION" VARCHAR(100 OCTETS) , 
		  "STATUS" VARCHAR(12 OCTETS) NOT NULL , 
		  "STATUSDATE" TIMESTAMP NOT NULL , 
		  "ENTERDATE" TIMESTAMP , 
		  "ENTERBY" VARCHAR(100 OCTETS) , 
		  "REPLYDATE" DATE , 
		  "CLOSEONDATE" DATE , 
		  "PURCHASEAGENT" VARCHAR(100 OCTETS) , 
		  "RFQTYPE" VARCHAR(16 OCTETS) , 
		  "REQUIREDDATE" TIMESTAMP , 
		  "REQUESTEDBY" VARCHAR(100 OCTETS) , 
		  "SHIPTO" VARCHAR(30 OCTETS) , 
		  "SHIPTOATTN" VARCHAR(100 OCTETS) , 
		  "BILLTO" VARCHAR(30 OCTETS) , 
		  "BILLTOATTN" VARCHAR(100 OCTETS) , 
		  "REPLYTO" VARCHAR(30 OCTETS) , 
		  "REPLYTOATTN" VARCHAR(100 OCTETS) , 
		  "FOB" VARCHAR(20 OCTETS) , 
		  "FREIGHTTERMS" VARCHAR(50 OCTETS) , 
		  "SHIPVIA" VARCHAR(20 OCTETS) , 
		  "PAYMENTTERMS" VARCHAR(20 OCTETS) , 
		  "CHANGEBY" VARCHAR(100 OCTETS) NOT NULL , 
		  "CHANGEDATE" TIMESTAMP NOT NULL , 
		  "PRIORITY" INTEGER NOT NULL , 
		  "HISTORYFLAG" INTEGER NOT NULL , 
		  "RFQ1" VARCHAR(10 OCTETS) , 
		  "RFQ2" VARCHAR(10 OCTETS) , 
		  "RFQ3" VARCHAR(10 OCTETS) , 
		  "RFQ4" VARCHAR(10 OCTETS) , 
		  "RFQ5" VARCHAR(10 OCTETS) , 
		  "RFQ6" DECIMAL(13,5) , 
		  "RFQ7" TIMESTAMP , 
		  "RFQ8" DECIMAL(15,2) , 
		  "RFQ9" INTEGER , 
		  "RFQ10" INTEGER NOT NULL , 
		  "PRINTDATE" TIMESTAMP , 
		  "BUYERCOMPANY" VARCHAR(30 OCTETS) , 
		  "ORGID" VARCHAR(8 OCTETS) NOT NULL , 
		  "SITEID" VARCHAR(8 OCTETS) NOT NULL , 
		  "RFQID" BIGINT NOT NULL , 
		  "LANGCODE" VARCHAR(4 OCTETS) NOT NULL , 
		  "HASLD" INTEGER NOT NULL , 
		  "STE_SUBMISSION" VARCHAR(5 OCTETS) , 
		  "STE_TOTALBASECOST" DECIMAL(16,2) , 
		  "STE_MIGRATIONID" BIGINT , 
		  "STE_MIGRATIONDATE" TIMESTAMP , 
		  "ROWSTAMP" BIGINT NOT NULL , 
		  "STE_PAYTERMS" VARCHAR(50 OCTETS) , 
		  "STE_SHIPTERMS" VARCHAR(50 OCTETS) , 
		  "STE_REMARKS" VARCHAR(100 OCTETS) , 
		  "STE_CSWNSAPGL" VARCHAR(20 OCTETS) , 
		  "STE_PRNUM" VARCHAR(10 OCTETS) , 
		  "STE_MIGRATIONTS" INTEGER , 
		  "STE_CSWNRFQREF" VARCHAR(13 OCTETS) , 
		  "STE_PONUM" VARCHAR(10 OCTETS) 
)   
 IN "MAXDATA"  
 ORGANIZE BY ROW;

CREATE TABLE MIGRATION."PATCH_20250403_RFQLINE"  (
		  "RFQNUM" VARCHAR(15 OCTETS) NOT NULL , 
		  "RFQLINENUM" INTEGER NOT NULL , 
		  "ITEMNUM" VARCHAR(30 OCTETS) , 
		  "STORELOC" VARCHAR(16 OCTETS) , 
		  "DESCRIPTION" VARCHAR(200 OCTETS) , 
		  "ORDERQTY" DECIMAL(15,2) , 
		  "ORDERUNIT" VARCHAR(16 OCTETS) , 
		  "REQDELIVERYDATE" DATE , 
		  "ENTERDATE" TIMESTAMP NOT NULL , 
		  "ENTERBY" VARCHAR(100 OCTETS) NOT NULL , 
		  "RFQL1" VARCHAR(10 OCTETS) , 
		  "RFQL2" VARCHAR(10 OCTETS) , 
		  "RFQL3" VARCHAR(10 OCTETS) , 
		  "RFQL4" DECIMAL(15,2) , 
		  "RFQL5" VARCHAR(10 OCTETS) , 
		  "PONUM" VARCHAR(10 OCTETS) , 
		  "POLINENUM" INTEGER , 
		  "ASSETNUM" VARCHAR(13 OCTETS) , 
		  "REQUESTEDBY" VARCHAR(100 OCTETS) , 
		  "ISSUE" INTEGER NOT NULL , 
		  "RFQLIN1" VARCHAR(10 OCTETS) , 
		  "RFQLIN2" VARCHAR(10 OCTETS) , 
		  "RFQLIN3" VARCHAR(10 OCTETS) , 
		  "RFQLIN4" TIMESTAMP , 
		  "RFQLIN5" DECIMAL(15,2) , 
		  "CHARGESTORE" INTEGER NOT NULL , 
		  "GLDEBITACCT" VARCHAR(110 OCTETS) , 
		  "RECEIPTREQD" INTEGER NOT NULL , 
		  "CATEGORY" VARCHAR(16 OCTETS) , 
		  "REMARK" VARCHAR(50 OCTETS) , 
		  "LOCATION" VARCHAR(16 OCTETS) , 
		  "MANUFACTURER" VARCHAR(20 OCTETS) , 
		  "MODELNUM" VARCHAR(8 OCTETS) , 
		  "AWARDDATE" TIMESTAMP , 
		  "VENDOR" VARCHAR(20 OCTETS) , 
		  "SUPERVISOR" VARCHAR(100 OCTETS) , 
		  "PRORATESERVICE" INTEGER NOT NULL , 
		  "UNITCOST" DECIMAL(10,2) , 
		  "LINECOST" DECIMAL(10,2) , 
		  "RFQLINEID" BIGINT NOT NULL , 
		  "INSPECTIONREQUIRED" INTEGER NOT NULL , 
		  "POLINEID" BIGINT , 
		  "MRNUM" VARCHAR(10 OCTETS) , 
		  "MRLINENUM" INTEGER , 
		  "RFQL6" VARCHAR(10 OCTETS) , 
		  "RFQL7" VARCHAR(10 OCTETS) , 
		  "RFQL8" VARCHAR(10 OCTETS) , 
		  "RFQL9" VARCHAR(10 OCTETS) , 
		  "RFQL10" VARCHAR(10 OCTETS) , 
		  "RFQLIN6" VARCHAR(10 OCTETS) , 
		  "RFQLIN7" VARCHAR(10 OCTETS) , 
		  "RFQLIN8" VARCHAR(10 OCTETS) , 
		  "RFQLIN9" VARCHAR(10 OCTETS) , 
		  "FINCNTRLID" VARCHAR(8 OCTETS) , 
		  "VENDORPACKCODE" VARCHAR(12 OCTETS) , 
		  "VENDORPACKQUANTITY" VARCHAR(12 OCTETS) , 
		  "VENDORWAREHOUSE" VARCHAR(12 OCTETS) , 
		  "ORGID" VARCHAR(8 OCTETS) NOT NULL , 
		  "SITEID" VARCHAR(8 OCTETS) NOT NULL , 
		  "REFWO" VARCHAR(10 OCTETS) , 
		  "ENTEREDASTASK" INTEGER NOT NULL , 
		  "LINETYPE" VARCHAR(15 OCTETS) NOT NULL , 
		  "ITEMSETID" VARCHAR(8 OCTETS) , 
		  "CONDITIONCODE" VARCHAR(30 OCTETS) , 
		  "CONTRACTNUM" VARCHAR(10 OCTETS) , 
		  "CONTRACTLINENUM" INTEGER , 
		  "CONTRACTLINEID" BIGINT , 
		  "COMMODITYGROUP" VARCHAR(10 OCTETS) , 
		  "COMMODITY" VARCHAR(10 OCTETS) , 
		  "CONVERTTOCONTRACT" INTEGER NOT NULL , 
		  "CONTRACTREV" INTEGER , 
		  "LANGCODE" VARCHAR(4 OCTETS) NOT NULL , 
		  "CONVERSION" DECIMAL(18,5) , 
		  "CONTRACTID" BIGINT , 
		  "HASLD" INTEGER NOT NULL , 
		  "MKTPLCITEM" INTEGER NOT NULL , 
		  "CLASSSTRUCTUREID" VARCHAR(20 OCTETS) , 
		  "POREVISIONNUM" INTEGER , 
		  "PLUSTCOMP" VARCHAR(15 OCTETS) , 
		  "PLUSTREASON" VARCHAR(10 OCTETS) , 
		  "PLUSTFAILURE" VARCHAR(10 OCTETS) , 
		  "PLUSTPOS" VARCHAR(15 OCTETS) , 
		  "PLUSTACCOMP" VARCHAR(10 OCTETS) , 
		  "PLUSTHASWARRANTY" VARCHAR(2 OCTETS) , 
		  "STE_ALITEMALLOWED" INTEGER NOT NULL , 
		  "STE_ALTITEMDESC" VARCHAR(250 OCTETS) , 
		  "STE_ALTITEMNUM" VARCHAR(30 OCTETS) , 
		  "STE_ALTITEMQUOTED" INTEGER NOT NULL , 
		  "STE_WBSNO" VARCHAR(50 OCTETS) , 
		  "ROWSTAMP" BIGINT NOT NULL , 
		  "STE_CSWNCC" VARCHAR(16 OCTETS) , 
		  "STE_MIGRATIONID" BIGINT , 
		  "STE_MIGRATIONDATE" TIMESTAMP , 
		  "STE_MIGRATIONITEMPK" VARCHAR(200 OCTETS) , 
		  "STE_MIGRATIONNSITEMPK" VARCHAR(200 OCTETS) , 
		  "STE_COSC" VARCHAR(16 OCTETS) , 
		  "STE_CSWNSAPGL" VARCHAR(20 OCTETS) , 
		  "STE_MIGRATIONTS" INTEGER 
 )   
 IN "MAXDATA"  
 ORGANIZE BY ROW;

CREATE TABLE MIGRATION."PATCH_20250403_RFQVENDOR"  (
		  "RFQNUM" VARCHAR(15 OCTETS) NOT NULL , 
		  "VENDOR" VARCHAR(20 OCTETS) NOT NULL , 
		  "CONTACT" VARCHAR(50 OCTETS) , 
		  "PHONE" VARCHAR(20 OCTETS) , 
		  "FAXPHONE" VARCHAR(20 OCTETS) , 
		  "EMAIL" VARCHAR(60 OCTETS) , 
		  "CUSTOMERNUM" VARCHAR(16 OCTETS) , 
		  "FOB" VARCHAR(20 OCTETS) , 
		  "FREIGHTTERMS" VARCHAR(50 OCTETS) , 
		  "SHIPVIA" VARCHAR(20 OCTETS) , 
		  "PAYMENTTERMS" VARCHAR(20 OCTETS) , 
		  "CURRENCYCODE" VARCHAR(8 OCTETS) NOT NULL , 
		  "EXCHANGERATE" DECIMAL(14,7) , 
		  "EXCHANGEDATE" DATE , 
		  "BUYAHEAD" INTEGER NOT NULL , 
		  "INTERNAL" INTEGER NOT NULL , 
		  "REPLIEDDATE" TIMESTAMP , 
		  "GLCREDITACCT" VARCHAR(110 OCTETS) , 
		  "INCLUSIVE1" INTEGER NOT NULL , 
		  "INCLUSIVE2" INTEGER NOT NULL , 
		  "INCLUSIVE3" INTEGER NOT NULL , 
		  "INCLUSIVE4" INTEGER NOT NULL , 
		  "INCLUSIVE5" INTEGER NOT NULL , 
		  "VENDORQUOTENUM" VARCHAR(15 OCTETS) , 
		  "ORGID" VARCHAR(8 OCTETS) NOT NULL , 
		  "SITEID" VARCHAR(8 OCTETS) NOT NULL , 
		  "RFQVENDORID" BIGINT NOT NULL , 
		  "LANGCODE" VARCHAR(4 OCTETS) NOT NULL , 
		  "HASLD" INTEGER NOT NULL , 
		  "ROWSTAMP" BIGINT NOT NULL , 
		  "STE_CSWNNOTES" VARCHAR(100 OCTETS) , 
		  "STE_CSWNSAPGL" VARCHAR(20 OCTETS) , 
		  "STE_CSWNWBSNUM" VARCHAR(20 OCTETS) , 
		  "STE_PRNUM" VARCHAR(10 OCTETS) , 
		  "STE_MIGRATIONID" BIGINT , 
		  "STE_MIGRATIONDATE" TIMESTAMP , 
		  "STE_MIGRATIONTS" INTEGER 
)   
 IN "MAXDATA"  
 ORGANIZE BY ROW;

CREATE TABLE MIGRATION."PATCH_20250403_QUOTATIONLINE"  (
		  "RFQNUM" VARCHAR(15 OCTETS) NOT NULL , 
		  "RFQLINENUM" INTEGER NOT NULL , 
		  "VENDOR" VARCHAR(20 OCTETS) NOT NULL , 
		  "QUOTATIONLINEID" BIGINT NOT NULL , 
		  "ITEMNUM" VARCHAR(30 OCTETS) , 
		  "MANUFACTURER" VARCHAR(20 OCTETS) , 
		  "MODELNUM" VARCHAR(8 OCTETS) , 
		  "ORDERQTY" DECIMAL(15,2) , 
		  "ORDERUNIT" VARCHAR(16 OCTETS) , 
		  "UNITCOST" DECIMAL(12,2) , 
		  "LINECOST" DECIMAL(12,2) , 
		  "EOQ" DECIMAL(15,2) NOT NULL , 
		  "DELIVERYTIME" INTEGER , 
		  "DELIVERYDATE" DATE , 
		  "ENTERDATE" TIMESTAMP NOT NULL , 
		  "ENTERBY" VARCHAR(100 OCTETS) NOT NULL , 
		  "ISAWARDED" INTEGER NOT NULL , 
		  "SELECTEDFORDISPLAY" INTEGER NOT NULL , 
		  "GLCREDITACCT" VARCHAR(110 OCTETS) , 
		  "TAX1CODE" VARCHAR(8 OCTETS) , 
		  "TAX1" DECIMAL(10,2) NOT NULL , 
		  "TAX2CODE" VARCHAR(8 OCTETS) , 
		  "TAX2" DECIMAL(10,2) NOT NULL , 
		  "TAX3CODE" VARCHAR(8 OCTETS) , 
		  "TAX3" DECIMAL(10,2) NOT NULL , 
		  "TAX4CODE" VARCHAR(8 OCTETS) , 
		  "TAX4" DECIMAL(10,2) NOT NULL , 
		  "TAX5CODE" VARCHAR(8 OCTETS) , 
		  "TAX5" DECIMAL(10,2) NOT NULL , 
		  "CATALOGCODE" VARCHAR(30 OCTETS) , 
		  "MEMO" VARCHAR(50 OCTETS) , 
		  "DESCRIPTION" VARCHAR(200 OCTETS) , 
		  "QUOTESTARTDATE" DATE , 
		  "QUOTEENDDATE" DATE , 
		  "LINECOST2" DECIMAL(12,2) , 
		  "VENDORPACKCODE" VARCHAR(12 OCTETS) , 
		  "VENDORPACKQUANTITY" VARCHAR(12 OCTETS) , 
		  "VENDORWAREHOUSE" VARCHAR(12 OCTETS) , 
		  "SITEID" VARCHAR(8 OCTETS) NOT NULL , 
		  "ORGID" VARCHAR(8 OCTETS) NOT NULL , 
		  "LINETYPE" VARCHAR(15 OCTETS) NOT NULL , 
		  "ITEMSETID" VARCHAR(8 OCTETS) , 
		  "CONDITIONCODE" VARCHAR(30 OCTETS) , 
		  "COMMODITYGROUP" VARCHAR(10 OCTETS) , 
		  "COMMODITY" VARCHAR(10 OCTETS) , 
		  "LANGCODE" VARCHAR(4 OCTETS) NOT NULL , 
		  "HASLD" INTEGER NOT NULL , 
		  "MKTPLCITEM" INTEGER NOT NULL , 
		  "STE_ALTITEMALLOWED" INTEGER NOT NULL , 
		  "STE_ALTITEMDESC" VARCHAR(200 OCTETS) , 
		  "STE_ALTITEMNUM" VARCHAR(30 OCTETS) , 
		  "STE_ALTITEMQUOTED" INTEGER NOT NULL , 
		  "STE_ORIGINALITEMDESC" VARCHAR(200 OCTETS) , 
		  "STE_ORIGINALITEMNUM" VARCHAR(30 OCTETS) , 
		  "ROWSTAMP" BIGINT NOT NULL , 
		  "STE_CSWNALTPRICE1" DECIMAL(10,2) , 
		  "STE_CSWNALTPRICE2" DECIMAL(10,2) , 
		  "STE_MIGRATIONDATE" TIMESTAMP , 
		  "STE_MIGRATIONNSITEMPK" VARCHAR(200 OCTETS) , 
		  "STE_MIGRATIONITEMPK" VARCHAR(200 OCTETS) , 
		  "STE_MIGRATIONID" BIGINT , 
		  "STE_MIGRATIONTS" INTEGER )   
		 IN "MAXDATA"  
		 ORGANIZE BY ROW;

CREATE TABLE MIGRATION.PATCH_20250403_LD_RFQ  (
		  "LDKEY" BIGINT NOT NULL , 
		  "LDOWNERTABLE" VARCHAR(30 OCTETS) NOT NULL , 
		  "LDOWNERCOL" VARCHAR(30 OCTETS) NOT NULL , 
		  "LANGCODE" VARCHAR(4 OCTETS) NOT NULL , 
		  "LONGDESCRIPTIONID" BIGINT NOT NULL , 
		  "CONTENTUID" VARCHAR(50 OCTETS) NOT NULL , 
		  "ROWSTAMP" BIGINT NOT NULL , 
		  "STE_MIGRATIONID" BIGINT WITH DEFAULT NULL , 
		  "STE_MIGRATIONDATE" TIMESTAMP NOT NULL 
);

CREATE TABLE MIGRATION.PATCH_20250403_LD_RFQLINE  (
		  "LDKEY" BIGINT NOT NULL , 
		  "LDOWNERTABLE" VARCHAR(30 OCTETS) NOT NULL , 
		  "LDOWNERCOL" VARCHAR(30 OCTETS) NOT NULL , 
		  "LANGCODE" VARCHAR(4 OCTETS) NOT NULL , 
		  "LONGDESCRIPTIONID" BIGINT NOT NULL , 
		  "CONTENTUID" VARCHAR(50 OCTETS) NOT NULL , 
		  "ROWSTAMP" BIGINT NOT NULL , 
		  "STE_MIGRATIONID" BIGINT WITH DEFAULT NULL , 
		  "STE_MIGRATIONDATE" TIMESTAMP NOT NULL 
);

-- BACKUP
INSERT INTO MIGRATION."PATCH_20250403_RFQ"
(
	RFQNUM, DESCRIPTION, STATUS, STATUSDATE, ENTERDATE, ENTERBY, REPLYDATE, CLOSEONDATE, PURCHASEAGENT, 
	RFQTYPE, REQUIREDDATE, REQUESTEDBY, SHIPTO, SHIPTOATTN, BILLTO, BILLTOATTN, REPLYTO, REPLYTOATTN, FOB, 
	FREIGHTTERMS, SHIPVIA, PAYMENTTERMS, CHANGEBY, CHANGEDATE, PRIORITY, HISTORYFLAG, 
	RFQ1, RFQ2, RFQ3, RFQ4, RFQ5, RFQ6, RFQ7, RFQ8, RFQ9, RFQ10, PRINTDATE, BUYERCOMPANY, ORGID, SITEID, 
	RFQID, LANGCODE, HASLD, STE_SUBMISSION, STE_TOTALBASECOST, STE_MIGRATIONID, STE_MIGRATIONDATE, ROWSTAMP, 
	STE_PAYTERMS, STE_SHIPTERMS, STE_REMARKS, STE_CSWNSAPGL, STE_PRNUM, STE_MIGRATIONTS, STE_CSWNRFQREF, STE_PONUM
)
SELECT
	RFQNUM, DESCRIPTION, STATUS, STATUSDATE, ENTERDATE, ENTERBY, REPLYDATE, CLOSEONDATE, PURCHASEAGENT, 
	RFQTYPE, REQUIREDDATE, REQUESTEDBY, SHIPTO, SHIPTOATTN, BILLTO, BILLTOATTN, REPLYTO, REPLYTOATTN, FOB, 
	FREIGHTTERMS, SHIPVIA, PAYMENTTERMS, CHANGEBY, CHANGEDATE, PRIORITY, HISTORYFLAG, 
	RFQ1, RFQ2, RFQ3, RFQ4, RFQ5, RFQ6, RFQ7, RFQ8, RFQ9, RFQ10, PRINTDATE, BUYERCOMPANY, ORGID, SITEID, 
	RFQID, LANGCODE, HASLD, STE_SUBMISSION, STE_TOTALBASECOST, STE_MIGRATIONID, STE_MIGRATIONDATE, ROWSTAMP, 
	STE_PAYTERMS, STE_SHIPTERMS, STE_REMARKS, STE_CSWNSAPGL, STE_PRNUM, STE_MIGRATIONTS, STE_CSWNRFQREF, STE_PONUM
FROM MAXIMO.RFQ
WHERE STE_MIGRATIONID IS NOT NULL
;

INSERT INTO MIGRATION.PATCH_20250403_RFQLINE
(
	RFQNUM, RFQLINENUM, ITEMNUM, STORELOC, DESCRIPTION, ORDERQTY, ORDERUNIT, REQDELIVERYDATE, ENTERDATE, ENTERBY, 
	RFQL1, RFQL2, RFQL3, RFQL4, RFQL5, PONUM, POLINENUM, ASSETNUM, REQUESTEDBY, ISSUE, RFQLIN1, RFQLIN2, RFQLIN3, RFQLIN4, RFQLIN5, 
	CHARGESTORE, GLDEBITACCT, RECEIPTREQD, CATEGORY, REMARK, LOCATION, MANUFACTURER, MODELNUM, AWARDDATE, VENDOR, SUPERVISOR, 
	PRORATESERVICE, UNITCOST, LINECOST, RFQLINEID, INSPECTIONREQUIRED, POLINEID, MRNUM, MRLINENUM, 
	RFQL6, RFQL7, RFQL8, RFQL9, RFQL10, RFQLIN6, RFQLIN7, RFQLIN8, RFQLIN9, FINCNTRLID, VENDORPACKCODE, VENDORPACKQUANTITY, 
	VENDORWAREHOUSE, ORGID, SITEID, REFWO, ENTEREDASTASK, LINETYPE, ITEMSETID, CONDITIONCODE, 
	CONTRACTNUM, CONTRACTLINENUM, CONTRACTLINEID, COMMODITYGROUP, COMMODITY, CONVERTTOCONTRACT, CONTRACTREV, LANGCODE, 
	CONVERSION, CONTRACTID, HASLD, MKTPLCITEM, CLASSSTRUCTUREID, POREVISIONNUM, PLUSTCOMP, PLUSTREASON, PLUSTFAILURE, 
	PLUSTPOS, PLUSTACCOMP, PLUSTHASWARRANTY, STE_ALITEMALLOWED, STE_ALTITEMDESC, STE_ALTITEMNUM, STE_ALTITEMQUOTED, STE_WBSNO, ROWSTAMP, 
	STE_CSWNCC, STE_MIGRATIONID, STE_MIGRATIONDATE, STE_MIGRATIONITEMPK, STE_MIGRATIONNSITEMPK, STE_COSC, STE_CSWNSAPGL, STE_MIGRATIONTS
)
SELECT 
	RFQNUM, RFQLINENUM, ITEMNUM, STORELOC, DESCRIPTION, ORDERQTY, ORDERUNIT, REQDELIVERYDATE, ENTERDATE, ENTERBY, 
	RFQL1, RFQL2, RFQL3, RFQL4, RFQL5, PONUM, POLINENUM, ASSETNUM, REQUESTEDBY, ISSUE, RFQLIN1, RFQLIN2, RFQLIN3, RFQLIN4, RFQLIN5, 
	CHARGESTORE, GLDEBITACCT, RECEIPTREQD, CATEGORY, REMARK, LOCATION, MANUFACTURER, MODELNUM, AWARDDATE, VENDOR, SUPERVISOR, 
	PRORATESERVICE, UNITCOST, LINECOST, RFQLINEID, INSPECTIONREQUIRED, POLINEID, MRNUM, MRLINENUM, 
	RFQL6, RFQL7, RFQL8, RFQL9, RFQL10, RFQLIN6, RFQLIN7, RFQLIN8, RFQLIN9, FINCNTRLID, VENDORPACKCODE, VENDORPACKQUANTITY, 
	VENDORWAREHOUSE, ORGID, SITEID, REFWO, ENTEREDASTASK, LINETYPE, ITEMSETID, CONDITIONCODE, 
	CONTRACTNUM, CONTRACTLINENUM, CONTRACTLINEID, COMMODITYGROUP, COMMODITY, CONVERTTOCONTRACT, CONTRACTREV, LANGCODE, 
	CONVERSION, CONTRACTID, HASLD, MKTPLCITEM, CLASSSTRUCTUREID, POREVISIONNUM, PLUSTCOMP, PLUSTREASON, PLUSTFAILURE, 
	PLUSTPOS, PLUSTACCOMP, PLUSTHASWARRANTY, STE_ALITEMALLOWED, STE_ALTITEMDESC, STE_ALTITEMNUM, STE_ALTITEMQUOTED, STE_WBSNO, ROWSTAMP, 
	STE_CSWNCC, STE_MIGRATIONID, STE_MIGRATIONDATE, STE_MIGRATIONITEMPK, STE_MIGRATIONNSITEMPK, STE_COSC, STE_CSWNSAPGL, STE_MIGRATIONTS
FROM MAXIMO.RFQLINE
WHERE STE_MIGRATIONID IS NOT NULL
;

INSERT INTO MIGRATION.PATCH_20250403_RFQVENDOR
(
	RFQNUM, VENDOR, CONTACT, PHONE, FAXPHONE, EMAIL, CUSTOMERNUM, FOB, FREIGHTTERMS, SHIPVIA, PAYMENTTERMS, CURRENCYCODE, 
	EXCHANGERATE, EXCHANGEDATE, BUYAHEAD, INTERNAL, REPLIEDDATE, GLCREDITACCT, 
	INCLUSIVE1, INCLUSIVE2, INCLUSIVE3, INCLUSIVE4, INCLUSIVE5, VENDORQUOTENUM, ORGID, SITEID, RFQVENDORID, LANGCODE, HASLD, ROWSTAMP, 
	STE_CSWNNOTES, STE_CSWNSAPGL, STE_CSWNWBSNUM, STE_MIGRATIONID, STE_MIGRATIONDATE, STE_MIGRATIONTS,
	STE_PRNUM
)
SELECT 
	A.RFQNUM, A.VENDOR, A.CONTACT, A.PHONE, A.FAXPHONE, A.EMAIL, A.CUSTOMERNUM, A.FOB, A.FREIGHTTERMS, A.SHIPVIA, A.PAYMENTTERMS, A.CURRENCYCODE, 
	A.EXCHANGERATE, A.EXCHANGEDATE, A.BUYAHEAD, A.INTERNAL, A.REPLIEDDATE, A.GLCREDITACCT, 
	A.INCLUSIVE1, A.INCLUSIVE2, A.INCLUSIVE3, A.INCLUSIVE4, A.INCLUSIVE5, A.VENDORQUOTENUM, A.ORGID, A.SITEID, A.RFQVENDORID, A.LANGCODE, A.HASLD, A.ROWSTAMP, 
	A.STE_CSWNNOTES, A.STE_CSWNSAPGL, A.STE_CSWNWBSNUM, A.STE_MIGRATIONID, A.STE_MIGRATIONDATE, A.STE_MIGRATIONTS,
	B.STE_PRNUM
FROM MAXIMO.RFQVENDOR A
JOIN MAXIMO.RFQ B ON B.RFQNUM=A.RFQNUM
WHERE A.STE_MIGRATIONID IS NOT NULL
;

INSERT INTO MIGRATION.PATCH_20250403_QUOTATIONLINE
(
	RFQNUM, RFQLINENUM, VENDOR, QUOTATIONLINEID, ITEMNUM, MANUFACTURER, MODELNUM, ORDERQTY, ORDERUNIT, UNITCOST, 
	LINECOST, EOQ, DELIVERYTIME, DELIVERYDATE, ENTERDATE, ENTERBY, ISAWARDED, SELECTEDFORDISPLAY, GLCREDITACCT, 
	TAX1CODE, TAX1, TAX2CODE, TAX2, TAX3CODE, TAX3, TAX4CODE, TAX4, TAX5CODE, TAX5, CATALOGCODE, MEMO, DESCRIPTION, 
	QUOTESTARTDATE, QUOTEENDDATE, LINECOST2, VENDORPACKCODE, VENDORPACKQUANTITY, VENDORWAREHOUSE, SITEID, ORGID, 
	LINETYPE, ITEMSETID, CONDITIONCODE, COMMODITYGROUP, COMMODITY, LANGCODE, HASLD, MKTPLCITEM, STE_ALTITEMALLOWED, 
	STE_ALTITEMDESC, STE_ALTITEMNUM, STE_ALTITEMQUOTED, STE_ORIGINALITEMDESC, STE_ORIGINALITEMNUM, ROWSTAMP, 
	STE_CSWNALTPRICE1, STE_CSWNALTPRICE2, STE_MIGRATIONDATE, STE_MIGRATIONNSITEMPK, STE_MIGRATIONITEMPK, STE_MIGRATIONID, STE_MIGRATIONTS
)
SELECT
	RFQNUM, RFQLINENUM, VENDOR, QUOTATIONLINEID, ITEMNUM, MANUFACTURER, MODELNUM, ORDERQTY, ORDERUNIT, UNITCOST, 
	LINECOST, EOQ, DELIVERYTIME, DELIVERYDATE, ENTERDATE, ENTERBY, ISAWARDED, SELECTEDFORDISPLAY, GLCREDITACCT, 
	TAX1CODE, TAX1, TAX2CODE, TAX2, TAX3CODE, TAX3, TAX4CODE, TAX4, TAX5CODE, TAX5, CATALOGCODE, MEMO, DESCRIPTION, 
	QUOTESTARTDATE, QUOTEENDDATE, LINECOST2, VENDORPACKCODE, VENDORPACKQUANTITY, VENDORWAREHOUSE, SITEID, ORGID, 
	LINETYPE, ITEMSETID, CONDITIONCODE, COMMODITYGROUP, COMMODITY, LANGCODE, HASLD, MKTPLCITEM, STE_ALTITEMALLOWED, 
	STE_ALTITEMDESC, STE_ALTITEMNUM, STE_ALTITEMQUOTED, STE_ORIGINALITEMDESC, STE_ORIGINALITEMNUM, ROWSTAMP, 
	STE_CSWNALTPRICE1, STE_CSWNALTPRICE2, STE_MIGRATIONDATE, STE_MIGRATIONNSITEMPK, STE_MIGRATIONITEMPK, STE_MIGRATIONID, STE_MIGRATIONTS
FROM MAXIMO.QUOTATIONLINE
WHERE STE_MIGRATIONID IS NOT NULL
;

INSERT INTO MIGRATION.PATCH_20250403_LD_RFQ
(
	LDKEY, LDOWNERTABLE, LDOWNERCOL, LANGCODE, LONGDESCRIPTIONID, CONTENTUID, ROWSTAMP, 
	STE_MIGRATIONID, STE_MIGRATIONDATE
)
SELECT
	LDKEY, LDOWNERTABLE, LDOWNERCOL, LANGCODE, LONGDESCRIPTIONID, CONTENTUID, ROWSTAMP, 
	STE_MIGRATIONID, STE_MIGRATIONDATE
FROM MAXIMO.LONGDESCRIPTION
WHERE STE_MIGRATIONID IS NOT NULL AND LDOWNERTABLE='RFQ'
;

INSERT INTO MIGRATION.PATCH_20250403_LD_RFQLINE
(
	LDKEY, LDOWNERTABLE, LDOWNERCOL, LANGCODE, LONGDESCRIPTIONID, CONTENTUID, ROWSTAMP, 
	STE_MIGRATIONID, STE_MIGRATIONDATE
)
SELECT
	LDKEY, LDOWNERTABLE, LDOWNERCOL, LANGCODE, LONGDESCRIPTIONID, CONTENTUID, ROWSTAMP, 
	STE_MIGRATIONID, STE_MIGRATIONDATE
FROM MAXIMO.LONGDESCRIPTION
WHERE STE_MIGRATIONID IS NOT NULL AND LDOWNERTABLE='RFQLINE'
;

-- CREATE NEW TABLE
DROP TABLE MAXIMO.CSWN_RFQ IF EXISTS;
CREATE TABLE MAXIMO.CSWN_RFQ 
   (	
   	"PK_DEVIS" BIGINT, 
	"TIMESTAMP" BIGINT, 
	"S_SUPL_DV" BIGINT, 
	"DT_DEVIS" BIGINT, 
	"TM_DEVIS" BIGINT, 
	"DEVIS_CD" VARCHAR(13), 
	"DEVIS_DATE" BIGINT, 
	"DV_INCHARGE" VARCHAR(16), 
	"DV_TEXT" VARCHAR(100), 
	"DV_CC_CD" VARCHAR(16), 
	"DV_STATUS" INTEGER, 
	"DV_PO_CD" VARCHAR(10), 
	"DV_PREQ_REF" VARCHAR(10), 
	"DV_PAY_MOD" VARCHAR(6), 
	"DV_WOID" VARCHAR(10), 
	"DV_STRING1" VARCHAR(20), 
	"DV_STRING2" VARCHAR(20), 
	"DV_EXP_RET" BIGINT, 
	"REF_DEVIS_CD" VARCHAR(13),
	PK_SUPPLIER_ BIGINT,
	SUPL_CD VARCHAR(20),
	SUPL_NAME VARCHAR(100),
	S_CURR_CD VARCHAR(6)
) 
IN "MAXDATA" ORGANIZE BY ROW;
;

-- COPY THE DATA IN MAXIMO.CSWN_RFQ FROM ON-PREM
-- MANUAL IMPORT

-- ADD CUSTOM COLUMNS TO RFQVENDOR
ALTER TABLE MAXIMO.RFQVENDOR ADD "STE_MIGRATIONDEVISCD" VARCHAR(13);
ALTER TABLE MAXIMO.RFQVENDOR ADD "STE_MIGRATIONREFDEVISCD" VARCHAR(13);
ALTER TABLE MAXIMO.RFQVENDOR ADD "STE_MIGRATIONPOREF" VARCHAR(10);
ALTER TABLE MAXIMO.RFQVENDOR ADD "STE_MIGRATIONPRREF" VARCHAR(10);
ALTER TABLE MAXIMO.RFQVENDOR ADD "STE_REMARKS" VARCHAR(100);

ALTER TABLE MAXIMO.QUOTATIONLINE ADD "STE_MIGRATIONDEVISCD" VARCHAR(13);
ALTER TABLE MAXIMO.QUOTATIONLINE ADD "STE_MIGRATIONREFDEVISCD" VARCHAR(13);

-- CREATE MISSING RFQ PARENT
INSERT INTO MAXIMO.RFQ
(
	RFQNUM, DESCRIPTION, STATUS, STATUSDATE, ENTERDATE, ENTERBY, REPLYDATE, CLOSEONDATE, PURCHASEAGENT, RFQTYPE, 
	REQUIREDDATE, REQUESTEDBY, SHIPTO, SHIPTOATTN, BILLTO, BILLTOATTN, REPLYTO, REPLYTOATTN, FOB, FREIGHTTERMS, 
	SHIPVIA, PAYMENTTERMS, CHANGEBY, CHANGEDATE, PRIORITY, HISTORYFLAG, 
	RFQ1, RFQ2, RFQ3, RFQ4, RFQ5, RFQ6, RFQ7, RFQ8, RFQ9, RFQ10, PRINTDATE, BUYERCOMPANY, ORGID, SITEID, 
	LANGCODE, HASLD, STE_SUBMISSION, STE_TOTALBASECOST, 
	STE_PAYTERMS, STE_SHIPTERMS, STE_REMARKS, STE_CSWNSAPGL, STE_PRNUM, STE_CSWNRFQREF, STE_PONUM,
	STE_MIGRATIONID, STE_MIGRATIONDATE, STE_MIGRATIONTS, 
	RFQID
)
SELECT 
	B.REF_DEVIS_CD AS RFQNUM, 
	DESCRIPTION, STATUS, STATUSDATE, ENTERDATE, ENTERBY, REPLYDATE, CLOSEONDATE, PURCHASEAGENT, RFQTYPE, 
	REQUIREDDATE, REQUESTEDBY, SHIPTO, SHIPTOATTN, BILLTO, BILLTOATTN, REPLYTO, REPLYTOATTN, FOB, FREIGHTTERMS, 
	SHIPVIA, PAYMENTTERMS, CHANGEBY, CHANGEDATE, PRIORITY, HISTORYFLAG, 
	RFQ1, RFQ2, RFQ3, RFQ4, RFQ5, RFQ6, RFQ7, RFQ8, RFQ9, RFQ10, PRINTDATE, BUYERCOMPANY, ORGID, SITEID, 
	LANGCODE, HASLD, STE_SUBMISSION, STE_TOTALBASECOST, 
	STE_PAYTERMS, STE_SHIPTERMS, STE_REMARKS, STE_CSWNSAPGL, STE_PRNUM, STE_CSWNRFQREF, STE_PONUM,
	20250404 AS STE_MIGRATIONID, ADD_HOURS(CURRENT_TIMESTAMP,8) AS STE_MIGRATIONDATE, -1 AS STE_MIGRATIONTS, 
	C.MAX_ID + ROW_NUMBER() OVER (ORDER BY A.RFQID) AS RFQID
FROM MAXIMO.RFQ A
JOIN (
	SELECT A.RFQNUM, B.REF_DEVIS_CD
		, ROW_NUMBER() OVER (PARTITION BY B.REF_DEVIS_CD ORDER BY A.RFQNUM) RN
	FROM MAXIMO.RFQVENDOR A
	JOIN MAXIMO.CSWN_RFQ B ON B.PK_DEVIS=A.STE_MIGRATIONID
	LEFT JOIN MAXIMO.RFQ C ON C.RFQNUM=B.REF_DEVIS_CD
	WHERE A.STE_MIGRATIONID IS NOT NULL
		AND C.RFQNUM IS NULL
	ORDER BY B.REF_DEVIS_CD, A.RFQNUM
) B ON B.RN=1 AND B.RFQNUM=A.RFQNUM 
JOIN (
	SELECT COALESCE(MAX(RFQID),0) AS MAX_ID FROM MAXIMO.RFQ
) C ON 1=1
;

INSERT INTO MAXIMO.RFQLINE
(
	RFQNUM, RFQLINENUM, ITEMNUM, STORELOC, DESCRIPTION, ORDERQTY, ORDERUNIT, REQDELIVERYDATE, 
	ENTERDATE, ENTERBY, RFQL1, RFQL2, RFQL3, RFQL4, RFQL5, PONUM, POLINENUM, ASSETNUM, REQUESTEDBY, 
	ISSUE, RFQLIN1, RFQLIN2, RFQLIN3, RFQLIN4, RFQLIN5, CHARGESTORE, GLDEBITACCT, RECEIPTREQD, CATEGORY, 
	REMARK, LOCATION, MANUFACTURER, MODELNUM, AWARDDATE, VENDOR, SUPERVISOR, PRORATESERVICE, 
	UNITCOST, LINECOST, INSPECTIONREQUIRED, POLINEID, MRNUM, MRLINENUM, 
	RFQL6, RFQL7, RFQL8, RFQL9, RFQL10, RFQLIN6, RFQLIN7, RFQLIN8, RFQLIN9, FINCNTRLID, 
	VENDORPACKCODE, VENDORPACKQUANTITY, VENDORWAREHOUSE, ORGID, SITEID, REFWO, ENTEREDASTASK, 
	LINETYPE, ITEMSETID, CONDITIONCODE, CONTRACTNUM, CONTRACTLINENUM, CONTRACTLINEID, COMMODITYGROUP, 
	COMMODITY, CONVERTTOCONTRACT, CONTRACTREV, LANGCODE, CONVERSION, CONTRACTID, HASLD, MKTPLCITEM, 
	CLASSSTRUCTUREID, POREVISIONNUM, PLUSTCOMP, PLUSTREASON, PLUSTFAILURE, PLUSTPOS, PLUSTACCOMP, PLUSTHASWARRANTY, 
	STE_ALITEMALLOWED, STE_ALTITEMDESC, STE_ALTITEMNUM, STE_ALTITEMQUOTED, STE_WBSNO, ROWSTAMP, STE_CSWNCC,
	STE_COSC, STE_CSWNSAPGL, STE_MIGRATIONITEMPK, STE_MIGRATIONNSITEMPK, 
	STE_MIGRATIONID, STE_MIGRATIONDATE, STE_MIGRATIONTS,
	RFQLINEID
)
SELECT 
	B.REF_DEVIS_CD AS RFQNUM, RFQLINENUM, ITEMNUM, STORELOC, DESCRIPTION, ORDERQTY, ORDERUNIT, REQDELIVERYDATE, 
	ENTERDATE, ENTERBY, RFQL1, RFQL2, RFQL3, RFQL4, RFQL5, PONUM, POLINENUM, ASSETNUM, REQUESTEDBY, 
	ISSUE, RFQLIN1, RFQLIN2, RFQLIN3, RFQLIN4, RFQLIN5, CHARGESTORE, GLDEBITACCT, RECEIPTREQD, CATEGORY, 
	REMARK, LOCATION, MANUFACTURER, MODELNUM, AWARDDATE, VENDOR, SUPERVISOR, PRORATESERVICE, 
	UNITCOST, LINECOST, INSPECTIONREQUIRED, POLINEID, MRNUM, MRLINENUM, 
	RFQL6, RFQL7, RFQL8, RFQL9, RFQL10, RFQLIN6, RFQLIN7, RFQLIN8, RFQLIN9, FINCNTRLID, 
	VENDORPACKCODE, VENDORPACKQUANTITY, VENDORWAREHOUSE, ORGID, SITEID, REFWO, ENTEREDASTASK, 
	LINETYPE, ITEMSETID, CONDITIONCODE, CONTRACTNUM, CONTRACTLINENUM, CONTRACTLINEID, COMMODITYGROUP, 
	COMMODITY, CONVERTTOCONTRACT, CONTRACTREV, LANGCODE, CONVERSION, CONTRACTID, HASLD, MKTPLCITEM, 
	CLASSSTRUCTUREID, POREVISIONNUM, PLUSTCOMP, PLUSTREASON, PLUSTFAILURE, PLUSTPOS, PLUSTACCOMP, PLUSTHASWARRANTY, 
	STE_ALITEMALLOWED, STE_ALTITEMDESC, STE_ALTITEMNUM, STE_ALTITEMQUOTED, STE_WBSNO, ROWSTAMP, STE_CSWNCC,
	STE_COSC, STE_CSWNSAPGL, STE_MIGRATIONITEMPK, STE_MIGRATIONNSITEMPK, 
	20250404 AS STE_MIGRATIONID, ADD_HOURS(CURRENT_TIMESTAMP,8) AS STE_MIGRATIONDATE, -1 AS STE_MIGRATIONTS, 
	C.MAX_ID + ROW_NUMBER() OVER (ORDER BY A.RFQNUM, A.RFQLINENUM) AS RFQLINEID
FROM MAXIMO.RFQLINE A
JOIN (
	SELECT A.RFQNUM, B.REF_DEVIS_CD
		, ROW_NUMBER() OVER (PARTITION BY B.REF_DEVIS_CD ORDER BY A.RFQNUM) RN
	FROM MAXIMO.RFQVENDOR A
	JOIN MAXIMO.CSWN_RFQ B ON B.PK_DEVIS=A.STE_MIGRATIONID
	LEFT JOIN MAXIMO.RFQ C ON C.RFQNUM=B.REF_DEVIS_CD
	WHERE A.STE_MIGRATIONID IS NOT NULL
		AND C.RFQNUM IS NULL
	ORDER BY B.REF_DEVIS_CD, A.RFQNUM
) B ON B.RN=1 AND B.RFQNUM=A.RFQNUM 
JOIN (
	SELECT COALESCE(MAX(RFQLINEID),0) AS MAX_ID FROM MAXIMO.RFQLINE
) C ON 1=1
ORDER BY A.RFQNUM, A.RFQLINENUM;

-- UPDATE RFQVENDOR
MERGE INTO MAXIMO.RFQVENDOR A
USING (
	SELECT A.RFQVENDORID, A.RFQNUM AS ORIG_RFQNUM
		, B.DEVIS_CD, B.REF_DEVIS_CD, B.DV_PO_CD, B.DV_PREQ_REF, B.SUPL_CD
		, C.RFQNUM
	FROM MAXIMO.RFQVENDOR A
	JOIN MAXIMO.CSWN_RFQ B ON B.PK_DEVIS=A.STE_MIGRATIONID
	JOIN MAXIMO.RFQ C ON C.RFQNUM=B.REF_DEVIS_CD
	WHERE A.STE_MIGRATIONID IS NOT NULL
) B ON B.RFQVENDORID=A.RFQVENDORID
WHEN MATCHED THEN
UPDATE SET
	RFQNUM=B.RFQNUM,
	STE_MIGRATIONDEVISCD=B.DEVIS_CD,
	STE_MIGRATIONREFDEVISCD=B.RFQNUM,
	STE_MIGRATIONPOREF=B.DV_PO_CD,
	STE_MIGRATIONPRREF=B.DV_PREQ_REF
;

-- UPDATE QUOTATIONLINE
MERGE INTO MAXIMO.QUOTATIONLINE A
USING (
	SELECT A.QUOTATIONLINEID, A.RFQNUM AS ORIG_RFQNUM
		, B.DEVIS_CD, B.REF_DEVIS_CD, B.SUPL_CD, C.RFQNUM
	FROM MAXIMO.QUOTATIONLINE A
	JOIN MAXIMO.CSWN_RFQ B ON B.DEVIS_CD=A.RFQNUM
	JOIN MAXIMO.RFQ C ON C.RFQNUM=B.REF_DEVIS_CD
	WHERE A.STE_MIGRATIONID IS NOT NULL
) B ON B.QUOTATIONLINEID=A.QUOTATIONLINEID
WHEN MATCHED THEN
UPDATE SET
	RFQNUM=B.RFQNUM,
	STE_MIGRATIONDEVISCD=B.DEVIS_CD,
	STE_MIGRATIONREFDEVISCD=B.RFQNUM
;

-- REDIRECT LD (RFQ)
MERGE INTO MAXIMO.LONGDESCRIPTION A
USING (
	SELECT A.LONGDESCRIPTIONID, A.LDKEY AS ORIG_LDKEY, B.RFQID, B.RFQNUM
		, C.RFQVENDORID AS LDKEY, C.RFQNUM, C.STE_MIGRATIONREFDEVISCD
	FROM MAXIMO.LONGDESCRIPTION A
	JOIN MAXIMO.RFQ B ON B.RFQID=A.LDKEY
	JOIN MAXIMO.RFQVENDOR C ON C.STE_MIGRATIONID=B.STE_MIGRATIONID
		--C.STE_MIGRATIONDEVISCD=B.RFQNUM
	WHERE A.STE_MIGRATIONID IS NOT NULL
		AND A.LDOWNERTABLE='RFQ' AND A.LDOWNERCOL='STE_REMARKS'
) B ON B.LONGDESCRIPTIONID=A.LONGDESCRIPTIONID
WHEN MATCHED THEN
UPDATE SET
	LDOWNERTABLE='RFQVENDOR',
	LDKEY=B.LDKEY
;

-- REDIRECT LD (RFQLINE)
MERGE INTO MAXIMO.LONGDESCRIPTION A
USING (
	SELECT A.LONGDESCRIPTIONID, A.LDKEY AS ORIG_LDKEY, B.RFQLINEID, B.RFQNUM, B.RFQLINENUM
		, C.QUOTATIONLINEID AS LDKEY, C.RFQNUM, C.STE_MIGRATIONREFDEVISCD, C.RFQLINENUM
	FROM MAXIMO.LONGDESCRIPTION A
	JOIN MAXIMO.RFQLINE B ON B.RFQLINEID=A.LDKEY
	JOIN MAXIMO.QUOTATIONLINE C ON C.STE_MIGRATIONID=B.STE_MIGRATIONID
		--C.STE_MIGRATIONDEVISCD=B.RFQNUM AND C.RFQLINENUM=B.RFQLINENUM
	WHERE A.STE_MIGRATIONID IS NOT NULL
		AND A.LDOWNERTABLE='RFQLINE' AND A.LDOWNERCOL='DESCRIPTION'
) B ON B.LONGDESCRIPTIONID=A.LONGDESCRIPTIONID
WHEN MATCHED THEN
UPDATE SET
	LDOWNERTABLE='QUOTATIONLINE',
	LDKEY=B.LDKEY
;

-- UPDATE RFQVENDOR.HASLD
MERGE INTO MAXIMO.RFQVENDOR A
USING (
	SELECT B.RFQVENDORID
	FROM MAXIMO.LONGDESCRIPTION A
	JOIN MAXIMO.RFQVENDOR B ON B.RFQVENDORID=A.LDKEY
	WHERE A.STE_MIGRATIONID IS NOT NULL
		AND A.LDOWNERTABLE='RFQVENDOR' AND A.LDOWNERCOL='STE_REMARKS'
) B ON B.RFQVENDORID=A.RFQVENDORID
WHEN MATCHED THEN
UPDATE SET
	HASLD=1
;

-- UPDATE QUOTATIONLINE.HASLD
MERGE INTO MAXIMO.QUOTATIONLINE A
USING (
	SELECT B.QUOTATIONLINEID
	FROM MAXIMO.LONGDESCRIPTION A
	JOIN MAXIMO.QUOTATIONLINE B ON B.QUOTATIONLINEID=A.LDKEY
	WHERE A.STE_MIGRATIONID IS NOT NULL
		AND A.LDOWNERTABLE='QUOTATIONLINE' AND A.LDOWNERCOL='DESCRIPTION'
) B ON B.QUOTATIONLINEID=A.QUOTATIONLINEID
WHEN MATCHED THEN
UPDATE SET
	HASLD=1
;

-- MARK RFQ FOR DELETION
MERGE INTO MAXIMO.RFQ A
USING (
	SELECT B.RFQID, B.RFQNUM
	FROM MAXIMO.RFQVENDOR A
	JOIN MAXIMO.RFQ B ON B.RFQNUM=A.STE_MIGRATIONDEVISCD
	WHERE A.STE_MIGRATIONDEVISCD!=STE_MIGRATIONREFDEVISCD
		AND B.STE_MIGRATIONID IS NOT NULL
) B ON B.RFQID=A.RFQID
WHEN MATCHED THEN
UPDATE SET
	STE_MIGRATIONTS=-99
;

--SELECT * FROM MAXIMO.RFQ A WHERE STE_MIGRATIONTS!=-99;

-- MARK RFQLINE FOR DELETION
MERGE INTO MAXIMO.RFQLINE A
USING (
	SELECT A.RFQLINEID, A.RFQNUM, A.RFQLINENUM
	FROM MAXIMO.RFQLINE A
	JOIN MAXIMO.RFQ B ON B.RFQNUM=A.RFQNUM
	WHERE A.STE_MIGRATIONID IS NOT NULL
		AND B.STE_MIGRATIONTS=-99
) B ON B.RFQLINEID=A.RFQLINEID
WHEN MATCHED THEN
UPDATE SET
	STE_MIGRATIONTS=-99
;

-- DELETE
DELETE FROM MAXIMO.RFQLINE WHERE STE_MIGRATIONTS=-99;
DELETE FROM MAXIMO.RFQ WHERE STE_MIGRATIONTS=-99;

-- UPDATE POREF IN PARENT RFQ
MERGE INTO MAXIMO.RFQ A
USING (
	SELECT A.RFQNUM, A.STE_MIGRATIONPOREF AS POREF
		 	, ROW_NUMBER() OVER (PARTITION BY A.RFQNUM ORDER BY RFQVENDORID DESC) RN
	FROM MAXIMO.RFQVENDOR A
	WHERE A.STE_MIGRATIONPOREF IS NOT NULL
	ORDER BY A.RFQNUM
) B ON B.RN=1 AND B.RFQNUM=A.RFQNUM
WHEN MATCHED THEN
UPDATE SET
	STE_PONUM=B.POREF
; 

-- UPDATE RFQ-PO LINKAGE
MERGE INTO MAXIMO.RFQLINE A
USING (
	SELECT C.RFQLINEID, A.RFQNUM, B.PONUM, B.REVISIONNUM, D.POLINENUM, D.POLINEID
  		, ROW_NUMBER() OVER (PARTITION BY C.RFQLINEID ORDER BY B.POID DESC) RN
	--  , A.STATUS AS RFQSTATUS, B.STATUS AS POSTATUS
	--  , C.ITEMNUM, E.STE_CSWNITEMNO, E.DESCRIPTION, C.ORDERQTY AS RFQQTY, D.ORDERQTY AS POQTY
	FROM MAXIMO.RFQ A
	JOIN MAXIMO.PO B ON B.STE_CSWNPOREF=A.STE_PONUM
	JOIN MAXIMO.RFQLINE C ON C.RFQNUM=A.RFQNUM
	JOIN MAXIMO.POLINE D ON D.PONUM=B.PONUM AND D.ITEMNUM=C.ITEMNUM
	LEFT JOIN MAXIMO.ITEM E ON E.ITEMNUM=C.ITEMNUM
	WHERE A.STE_MIGRATIONID IS NOT NULL AND A.STE_PONUM IS NOT NULL
	--  AND (A.STATUS!='CAN' AND B.STATUS!='CAN')
	--  AND NOT (B.STATUS='CLOSE' AND A.STATUS='INPRG')
) B ON B.RFQLINEID=A.RFQLINEID AND B.RN=1
WHEN MATCHED THEN
UPDATE SET
 PONUM=B.PONUM,
 POREVISIONNUM=B.REVISIONNUM,
 POLINENUM=B.POLINENUM,
 POLINEID=B.POLINEID
; 

CALL MIGRATION.STE_FINISH_PATCH('20250403-04-RFQ-MAPPING');