--#SET TERMINATOR /

CREATE OR REPLACE PROCEDURE MIGRATION.STE_START_PATCH(
	IN P_PATCHNAME VARCHAR(50)
)
LANGUAGE SQL
SPECIFIC STE_START_PATCH
BEGIN

	INSERT INTO MIGRATION.ste_migration_logs (
	 package_name
	 ,version
	 ,start_date
	 ,hostname 
	)
	VALUES (
	 P_PATCHNAME
	 , '1.0'
	 , add_hours(CURRENT_TIMESTAMP,8)
	 , NULL
	);

END;
/

--#SET TERMINATOR /

CREATE OR REPLACE PROCEDURE MIGRATION.STE_FINISH_PATCH(
	IN P_PATCHNAME VARCHAR(50)
)
LANGUAGE SQL
SPECIFIC STE_FINISH_PATCH
BEGIN
	DECLARE V_MAX INTEGER DEFAULT 0;
	
	SET V_MAX = (SELECT ID FROM MIGRATION.ste_migration_logs WHERE package_name=P_PATCHNAME ORDER BY ID DESC LIMIT 1);
	
	UPDATE MIGRATION.ste_migration_logs 
	SET
	 end_date = add_hours(CURRENT_TIMESTAMP,8)
	 , success = 1
	WHERE id = V_MAX
	;

END;
/

--#SET TERMINATOR ;

CALL MIGRATION.STE_START_PATCH('20250404-RFQ-VENDOR-CONTACT');

MERGE INTO MAXIMO.RFQVENDOR A
USING (
	SELECT A.RFQVENDORID, TRIM(C.CONTACT) AS CONTACT
		, COALESCE(C.CELLPHONE, COALESCE(C.HOMEPHONE, C.VOICEPHONE)) AS PHONE
		, C.FAXPHONE, C.EMAIL
		, ROW_NUMBER() OVER (PARTITION BY A.RFQVENDORID ORDER BY 
			COALESCE(C.CELLPHONE, COALESCE(C.HOMEPHONE, C.VOICEPHONE)) ASC) RN
	FROM MAXIMO.RFQVENDOR A
	JOIN MAXIMO.COMPCONTACT C ON C.COMPANY=A.VENDOR 
	WHERE A.STE_MIGRATIONID IS NOT NULL
		--AND C.EMAIL IS NOT NULL
) B ON B.RN=1 AND B.RFQVENDORID=A.RFQVENDORID
WHEN MATCHED THEN
UPDATE SET
	CONTACT=B.CONTACT,
	PHONE=B.PHONE,
	FAXPHONE=B.FAXPHONE
;

UPDATE MAXIMO.COMPCONTACT
SET CONTACT=TRIM(CONTACT);

UPDATE MAXIMO.COMPCONTACTMSTR
SET CONTACT=TRIM(CONTACT);

CALL MIGRATION.STE_FINISH_PATCH('20250404-RFQ-VENDOR-CONTACT');