MERGE INTO MAXIMO.ASSET AS A
USING (
	SELECT A.ASSETUID, A.ASSETNUM, A.ITEMNUM AS OLDITEMNUM, B.ITEMNUM 
	FROM maximo.ASSET A
	JOIN MAXIMO.ITEM B ON B.ste_cswnitemno=A.ITEMNUM
	WHERE B.ITEMNUM!=A.ITEMNUM
) AS B ON B.ASSETUID=A.ASSETUID
WHEN MATCHED THEN 
UPDATE SET 
	ITEMNUM=B.ITEMNUM
;

MERGE INTO MAXIMO.SPAREPART AS A
USING (
	SELECT A.SPAREPARTID, A.ITEMNUM AS OLDITEMNUM, B.ITEMNUM 
	FROM maximo.SPAREPART A
	JOIN MAXIMO.ITEM B ON B.ste_cswnitemno=A.ITEMNUM
	WHERE B.ITEMNUM!=A.ITEMNUM
) AS B ON B.SPAREPARTID=A.SPAREPARTID
WHEN MATCHED THEN 
UPDATE SET 
	ITEMNUM=B.ITEMNUM
;

MERGE INTO MAXIMO.ALTITEM AS A
USING (
	SELECT A.ALTITEMID, A.ITEMNUM AS OLDITEMNUM, B.ITEMNUM 
	FROM maximo.ALTITEM A
	JOIN MAXIMO.ITEM B ON B.ste_cswnitemno=A.ITEMNUM
	WHERE B.ITEMNUM!=A.ITEMNUM
) AS B ON B.ALTITEMID=A.ALTITEMID
WHEN MATCHED THEN 
UPDATE SET 
	ITEMNUM=B.ITEMNUM
;

MERGE INTO MAXIMO.ALTITEM AS A
USING (
	SELECT A.ALTITEMID, A.ALTITEMNUM AS OLDALTITEMNUM, B.ITEMNUM AS ALTITEMNUM
	FROM maximo.ALTITEM A
	JOIN MAXIMO.ITEM B ON B.ste_cswnitemno=A.ALTITEMNUM
	WHERE B.ITEMNUM!=A.ALTITEMNUM
) AS B ON B.ALTITEMID=A.ALTITEMID
WHEN MATCHED THEN 
UPDATE SET 
	ALTITEMNUM=B.ALTITEMNUM
;

MERGE INTO MAXIMO.INVBALANCES AS A
USING (
	SELECT A.INVBALANCESID, A.ITEMNUM AS OLDITEMNUM, B.ITEMNUM
	FROM maximo.INVBALANCES A
	JOIN MAXIMO.ITEM B ON B.ste_cswnitemno=A.ITEMNUM
	WHERE B.ITEMNUM!=A.ITEMNUM
) AS B ON B.INVBALANCESID=A.INVBALANCESID
WHEN MATCHED THEN 
UPDATE SET 
	ITEMNUM=B.ITEMNUM
;

MERGE INTO MAXIMO.INVLOT AS A
USING (
	SELECT A.INVLOTID, A.ITEMNUM AS OLDITEMNUM, B.ITEMNUM
	FROM maximo.INVLOT A
	JOIN MAXIMO.ITEM B ON B.ste_cswnitemno=A.ITEMNUM
	WHERE B.ITEMNUM!=A.ITEMNUM
) AS B ON B.INVLOTID=A.INVLOTID
WHEN MATCHED THEN 
UPDATE SET 
	ITEMNUM=B.ITEMNUM
;

--MERGE INTO MAXIMO.INVCOST AS A
--USING (
--	SELECT A.INVCOSTID, A.ITEMNUM AS OLDITEMNUM, B.ITEMNUM
--	FROM maximo.INVCOST A
--	JOIN MAXIMO.ITEM B ON B.ste_cswnitemno=A.ITEMNUM
--	WHERE B.ITEMNUM!=A.ITEMNUM
--) AS B ON B.INVCOSTID=A.INVCOSTID
--WHEN MATCHED THEN 
--UPDATE SET 
--	ITEMNUM=B.ITEMNUM
--;

MERGE INTO MAXIMO.JOBITEM AS A
USING (
	SELECT A.JOBITEMID, A.ITEMNUM AS OLDITEMNUM, B.ITEMNUM
	FROM maximo.JOBITEM A
	JOIN MAXIMO.ITEM B ON B.ste_cswnitemno=A.ITEMNUM
	WHERE B.ITEMNUM!=A.ITEMNUM
) AS B ON B.JOBITEMID=A.JOBITEMID
WHEN MATCHED THEN 
UPDATE SET 
	ITEMNUM=B.ITEMNUM
;

MERGE INTO MAXIMO.QUOTATIONLINE AS A
USING (
	SELECT A.QUOTATIONLINEID, A.ITEMNUM AS OLDITEMNUM, B.ITEMNUM
	FROM maximo.QUOTATIONLINE A
	JOIN MAXIMO.ITEM B ON B.ste_cswnitemno=A.ITEMNUM
	WHERE B.ITEMNUM!=A.ITEMNUM
) AS B ON B.QUOTATIONLINEID=A.QUOTATIONLINEID
WHEN MATCHED THEN 
UPDATE SET 
	ITEMNUM=B.ITEMNUM
;


--SELECT A.ITEMNUM AS OLDITEMNUM, B.ITEMNUM 
--FROM maximo.WPSERVICE A
--JOIN MAXIMO.ITEM B ON B.ste_cswnitemno=A.ITEMNUM
--WHERE B.ITEMNUM!=A.ITEMNUM
--	
--SELECT * FROM MAXIMO.WPTOOL;
