-- UPDATE GL
UPDATE maximo.glcomponents
SET ACTIVE=1
WHERE glorder=0 AND COMPVALUE IN ('NEL');

UPDATE maximo.glcomponents
SET ACTIVE=1
WHERE glorder=1 AND COMPVALUE IN ('0000000', '9', '99', '9999999');

UPDATE MAXIMO.CHARTOFACCOUNTS
SET ACTIVE=1
WHERE GLACCOUNT LIKE 'NEL-0000000%' 
	OR GLACCOUNT LIKE 'NEL-9%'
;

-- UPDATE MR
MERGE INTO MAXIMO.MR AS A
USING (
	SELECT A.MRID, A.STE_CSWNCC, B.MAXIMO_CC
		, C.STE_COSTCENTREDEPT AS DEPT, C.COMPVALUE AS COSTCENTRE
		, CONCAT(COALESCE(C.STE_COSTCENTREDEPT, 'NEL'), CONCAT('-', COALESCE(C.COMPVALUE,'0000000'))) AS GLACCOUNT
	FROM maximo.MR A
	LEFT JOIN MIGRATION.SBST_COSTCENTER_INVALID_MAPPING B ON B.COSWIN_CC=A.STE_CSWNCC
	LEFT JOIN MAXIMO.GLCOMPONENTS C ON C.GLORDER AND C.ACTIVE=1
		AND C.COMPVALUE=COALESCE(B.MAXIMO_CC, A.STE_CSWNCC)
	WHERE A.STE_MIGRATIONID IS NOT NULL
) B ON B.MRID=A.MRID
WHEN MATCHED THEN
UPDATE SET
	GLDEBITACCT=B.GLACCOUNT
;

UPDATE MAXIMO.CHARTOFACCOUNTS
SET ACTIVE=1
WHERE CHARTOFACCOUNTSID IN (
	SELECT DISTINCT B.CHARTOFACCOUNTSID
	FROM MAXIMO.MR A
	JOIN MAXIMO.CHARTOFACCOUNTS B ON B.GLACCOUNT=A.GLDEBITACCT
	WHERE A.STE_MIGRATIONID IS NOT NULL AND B.ACTIVE=0
);

-- UPDATE MRLINE
MERGE INTO MAXIMO.MRLINE AS A
USING (
	SELECT A.MRLINEID, B.GLDEBITACCT 
	FROM MAXIMO.MRLINE A
	JOIN MAXIMO.MR B ON B.MRNUM=A.MRNUM
	WHERE A.STE_MIGRATIONID IS NOT NULL
) B ON B.MRLINEID=A.MRLINEID
WHEN MATCHED THEN
UPDATE SET
	GLDEBITACCT=B.GLDEBITACCT
;

-- UPDATE INVRESERVE
MERGE INTO MAXIMO.INVRESERVE AS A
USING (
	SELECT A.INVRESERVEID, B.GLDEBITACCT
	FROM MAXIMO.INVRESERVE A
	JOIN MAXIMO.MRLINE B ON B.MRNUM=A.MRNUM AND B.MRLINENUM=A.MRLINENUM
	WHERE A.STE_MIGRATIONID IS NOT NULL
) B ON B.INVRESERVEID=A.INVRESERVEID
WHEN MATCHED THEN
UPDATE SET
	GLACCOUNT=B.GLDEBITACCT
;

-- UPDATE INVUSELINE
MERGE INTO MAXIMO.INVUSELINE AS A
USING (
	SELECT A.INVUSELINEID, B.GLDEBITACCT
	FROM MAXIMO.INVUSELINE A
	JOIN MAXIMO.MRLINE B ON B.MRNUM=A.MRNUM AND B.MRLINENUM=A.MRLINENUM
	WHERE A.STE_MIGRATIONID IS NOT NULL
) B ON B.INVUSELINEID=A.INVUSELINEID
WHEN MATCHED THEN
UPDATE SET
	GLDEBITACCT=B.GLDEBITACCT
;

-- UPDATE MATUSETRANS
MERGE INTO MAXIMO.MATUSETRANS AS A
USING (
	SELECT A.MATUSETRANSID, B.GLDEBITACCT
	FROM MAXIMO.MATUSETRANS A
	JOIN MAXIMO.INVUSELINE B ON B.INVUSELINEID=A.INVUSELINEID
	WHERE A.STE_MIGRATIONID IS NOT NULL
) B ON B.MATUSETRANSID=A.MATUSETRANSID
WHEN MATCHED THEN
UPDATE SET
	GLDEBITACCT=B.GLDEBITACCT
;