CALL MIGRATION.STE_START_PATCH('20251201-02-INVOICEMATCH-INVOICETRANS');

/**
 * UPDATE POLINE.LINETYPE
 */
DROP TABLE "MIGRATION"."BAK_20251201_POLINE";
CREATE TABLE "MIGRATION"."BAK_20251201_POLINE"  (
  "POLINEID" BIGINT NOT NULL , 
  "PONUM" VARCHAR(10 OCTETS) NOT NULL , 
  "REVISIONNUM" INTEGER NOT NULL , 
  "POLINENUM" INTEGER NOT NULL , 
  "ITEMNUM" VARCHAR(30 OCTETS) , 
  "LINETYPE" VARCHAR(15 OCTETS) NOT NULL , 
  "NEWLINETYPE" VARCHAR(15 OCTETS) NOT NULL , 
  "ITEMSETID" VARCHAR(8 OCTETS) 
)   
ORGANIZE BY ROW;

INSERT INTO "MIGRATION"."BAK_20251201_POLINE" (
	POLINEID, PONUM, REVISIONNUM, POLINENUM, ITEMNUM, LINETYPE, NEWLINETYPE, ITEMSETID
)
SELECT a.polineid, a.ponum, a.revisionnum, a.polinenum, a.itemnum, a.linetype, 'STDSERVICE' AS newlinetype, b.itemsetid
FROM maximo.poline a
JOIN maximo.item b ON b.itemnum=a.itemnum
WHERE b.itemtype='STDSERVICE'
;

MERGE INTO MAXIMO.POLINE A
USING MIGRATION.BAK_20251201_POLINE B ON B.POLINEID=A.POLINEID
WHEN MATCHED THEN
UPDATE SET
	A.LINETYPE=B.NEWLINETYPE
;

/**
 * UPDATE STE_RPT_PO_LIST TO ADD STDSERVICE STATUS
 */
CREATE OR REPLACE VIEW MAXIMO.STE_RPT_PO_LIST AS
SELECT 
   '1.5' AS VERSION,
	A.POID, B.POLINEID,
	A.PONUM,
	A.REVISIONNUM,
	A.ORDERDATE,
	COALESCE(h.displayname,a.purchaseagent) AS purchaseagent, 
	a.vendor,
	A.STATUS,
	a.statusdate,
	a.currencycode, a.exchangerate, a.exchangedate,
	B.POLINENUM,
	C.ITEMNUM,
	C.DESCRIPTION,
	B.ORDERQTY,
	B.RECEIVEDQTY AS PO_RECEIVEDQTY,
	B.REJECTEDQTY AS PO_REJECTEDQTY,
	b.orderunit, b.gldebitacct, b.glcreditacct, b.unitcost, b.linecost,
	b.receiptscomplete, b.reqdeliverydate, b.vendeliverydate,
	COALESCE(D.QUANTITY,0) AS RECEIVEDQTY,
	COALESCE(D.ACCEPTEDQTY,0) AS ACCEPTEDQTY,
	COALESCE(D.REJECTQTY,0) AS REJECTQTY,
	COALESCE(D.RETURNEDQTY,0) AS RETURNEDQTY,
	COALESCE(G.QUANTITY,0) AS DIRECT_RECEIVEDQTY,
	COALESCE(G.RETURNEDQTY,0) AS DIRECT_RETURNEDQTY,
	COALESCE(G.ACCEPTEDQTY,0) AS DIRECT_ACCEPTEDQTY,
	COALESCE(K.QUANTITY,0) AS SERVICE_RECEIVEDQTY,
	COALESCE(K.RETURNEDQTY,0) AS SERVICE_RETURNEDQTY,
	COALESCE(K.ACCEPTEDQTY,0) AS SERVICE_ACCEPTEDQTY,
	COALESCE(D.QUANTITY,0)+COALESCE(G.QUANTITY,0)+COALESCE(K.QUANTITY,0) AS TOTAL_RECEIVEDQTY,
	COALESCE(D.ACCEPTEDQTY,0)+COALESCE(G.ACCEPTEDQTY,0)+COALESCE(K.ACCEPTEDQTY,0) AS TOTAL_ACCEPTEDQTY,
	COALESCE(D.RETURNEDQTY,0)+COALESCE(G.RETURNEDQTY,0)+COALESCE(K.RETURNEDQTY,0) AS TOTAL_RETURNEDQTY,
	COALESCE(D.QUANTITY,0)-COALESCE(D.TRANSFERREDQTY,0)-COALESCE(D.REJECTQTY,0) AS WINSPQTY,
	-- some old data in coswin is inconsistent >> receivedqty more than orderqty
	CASE WHEN (B.ORDERQTY - COALESCE(D.QUANTITY,0) + COALESCE(D.RETURNEDQTY,0) - COALESCE(G.ACCEPTEDQTY,0) - COALESCE(K.ACCEPTEDQTY,0)) < 0 THEN 0
	     ELSE (B.ORDERQTY - COALESCE(D.QUANTITY,0) + COALESCE(D.RETURNEDQTY,0) - COALESCE(G.ACCEPTEDQTY,0) - COALESCE(K.ACCEPTEDQTY,0))
	END AS PENDINGQTY,
	COALESCE(D.INVOICEQTY,0) AS INVOICEQTY,
	COALESCE(G.INVOICEQTY,0) AS DIRECT_INVOICEQTY,
	COALESCE(K.INVOICEQTY,0) AS SERVICE_INVOICEQTY,
	COALESCE(D.INVOICEQTY,0)+COALESCE(G.INVOICEQTY,0)+COALESCE(K.INVOICEQTY,0) AS TOTAL_INVOICEQTY,
	C.STE_CSWNITEMNO,
	C.STE_CSWNITEMCAT,
	C.STE_CSWNAUTHORITY,
	C.STE_OWNERDEPARTMENT,
	C.STE_SYSTEM,
	C.STE_ITEMGROUP,
	C.STE_CSWNITEMCC,
	A.STE_CSWNPOTYPE
FROM MAXIMO.PO A
JOIN MAXIMO.POLINE B ON B.PONUM=A.PONUM AND B.REVISIONNUM=A.REVISIONNUM 
JOIN MAXIMO.ITEM C ON C.ITEMNUM=B.ITEMNUM
LEFT JOIN (
	-- receive with inspection
	SELECT
		m.PONUM, m.porevisionnum,
		m.ITEMNUM,
		-- received: actual delivered qty 
		sum(m.quantity) AS quantity,
		-- reject: reject during inspection - before being accepted >> received = transfered + rejected
		sum(m.rejectqty) AS REJECTQTY,
		-- return: return after inspection + rejected >> total returned
		sum(COALESCE(y.quantity,0)) AS returnedqty,
		-- transferred: pass inspection
		sum(COALESCE(x.quantity,0)) AS transferredqty,
		-- accepted: tranferred - (returned - rejected)
		sum(COALESCE(x.quantity,0) - COALESCE(y.quantity,0) + m.rejectqty) AS acceptedqty,
		-- invoiced
	    SUM(im.quantity) AS invoiceqty
    FROM maximo.MATRECTRANS m
	LEFT JOIN (
	    -- transferred >> passed inspection >> received - rejected
	    SELECT
	        m.receiptref,
	        SUM(m.quantity) AS quantity
	    FROM
	        maximo.MATRECTRANS m
	    WHERE
	    	-- transfer from HOLDING to STORE
	        m.ISSUETYPE = 'TRANSFER'
	        AND m.STATUS = 'COMP'
	        AND m.FROMSTORELOC = 'L100000019292'
	        AND m.TOSTORELOC IS NOT NULL
	        AND m.TOSTORELOC != 'L100000019292'
	        --AND m.ponum='AA10016094'
	        --and r.STE_CSWNGRNNUM='GRN25/0307'
		GROUP BY m.receiptref
	) x ON x.receiptref=m.matrectransid
	LEFT JOIN (
	    -- return
	    SELECT
	        m.receiptref,
	        -- return qty is negative
	        -1 * SUM(m.quantity) AS quantity
	    FROM
	        maximo.MATRECTRANS m
	    WHERE
	        m.ISSUETYPE = 'RETURN'
	        AND m.STATUS = 'COMP'
		GROUP BY m.receiptref
	) y ON y.receiptref=m.matrectransid
    LEFT JOIN maximo.INVOICEMATCH im ON im.matrectransid=m.matrectransid 
    -- TODO: patch the data to insert to maximo.INVOICEMATCH for migrated data
    LEFT JOIN (
		-- total invoiced
	    SELECT m.matrectransid
	    	, m.quantity, m.rejectqty
	    	, CASE WHEN l.invoiceqty > m.quantity-m.rejectqty THEN m.quantity-m.rejectqty ELSE l.invoiceqty END AS invoiceqty
	    	, l.invoicelineid
	    FROM maximo.MATRECTRANS m
		LEFT JOIN (
			SELECT l.PONUM, l.POLINENUM, l.POREVISIONNUM, SUM(INVOICEQTY) AS INVOICEQTY, MAX(INVOICELINEID) AS INVOICELINEID
			FROM maximo.INVOICELINE l
			GROUP BY l.PONUM, l.POLINENUM, l.POREVISIONNUM
		) l ON l.PONUM=m.PONUM AND l.POLINENUM=m.POLINENUM AND l.POREVISIONNUM=m.POREVISIONNUM
		WHERE 1=1
			AND m.STATUSDATE<='2025-03-30'
			AND m.ISSUETYPE='RECEIPT' AND m.STATUS='COMP' AND m.FROMSTORELOC IS NULL AND m.TOSTORELOC!='L100000019292'
	) im2 ON im2.matrectransid=m.matrectransid
    WHERE
        m.ISSUETYPE = 'RECEIPT'
        AND m.STATUS in ('COMP','WINSP')
        AND m.FROMSTORELOC IS NULL
        AND m.TOSTORELOC = 'L100000019292'
	GROUP BY m.PONUM, m.porevisionnum, m.ITEMNUM
) D ON D.PONUM=A.PONUM AND D.POREVISIONNUM=A.REVISIONNUM AND D.ITEMNUM=B.ITEMNUM
LEFT JOIN (
    -- direct receive with no inspection
    SELECT
        m.ponum, m.porevisionnum,
        m.itemnum,
		sum(m.quantity) AS quantity,
		sum(m.rejectqty) AS returnedqty,
		sum(m.quantity-m.rejectqty) AS acceptedqty,
		-- invoiced
	    SUM(COALESCE(im.quantity, COALESCE(im2.invoiceqty,0))) AS invoiceqty
    FROM maximo.MATRECTRANS m
    LEFT JOIN maximo.INVOICEMATCH im ON im.matrectransid=m.matrectransid 
    -- TODO: patch the data to insert to maximo.INVOICEMATCH for migrated data
    -- TODO: need to patch data invoicelineid=5852 and matrectransid=1620074
    LEFT JOIN (
		-- total invoiced
	    SELECT m.matrectransid
	    	, m.quantity, m.rejectqty
	    	, CASE WHEN l.invoiceqty > m.quantity-m.rejectqty THEN m.quantity-m.rejectqty ELSE l.invoiceqty END AS invoiceqty
	    	, l.invoicelineid
	    FROM maximo.MATRECTRANS m
		LEFT JOIN (
			SELECT l.PONUM, l.POLINENUM, l.POREVISIONNUM, SUM(INVOICEQTY) AS INVOICEQTY, MAX(INVOICELINEID) AS INVOICELINEID
			FROM maximo.INVOICELINE l
			GROUP BY l.PONUM, l.POLINENUM, l.POREVISIONNUM
		) l ON l.PONUM=m.PONUM AND l.POLINENUM=m.POLINENUM AND l.POREVISIONNUM=m.POREVISIONNUM
		WHERE 1=1
			AND m.STATUSDATE<='2025-03-30'
			AND m.ISSUETYPE='RECEIPT' AND m.STATUS='COMP' AND m.FROMSTORELOC IS NULL AND m.TOSTORELOC!='L100000019292'
	) im2 ON im2.matrectransid=m.matrectransid
    WHERE
    	-- receive directly to STORE (not via HOLDING)
        m.ISSUETYPE = 'RECEIPT'
        AND m.STATUS = 'COMP'
        AND m.FROMSTORELOC IS NULL
        AND m.TOSTORELOC != 'L100000019292'
	GROUP BY m.ponum, m.porevisionnum, m.itemnum
) G ON G.PONUM=A.PONUM AND G.POREVISIONNUM=A.REVISIONNUM AND G.ITEMNUM=B.ITEMNUM
LEFT JOIN (
    -- service receipts
    SELECT
        m.ponum, m.porevisionnum,
        m.itemnum,
		sum(m.quantity) AS quantity,
		sum(m.rejectqty) AS returnedqty,
		sum(m.quantity-m.rejectqty) AS acceptedqty,
		-- invoiced
		sum(im.quantity) AS invoicematchqty,
		sum(im2.invoiceqty) AS calcinvoiceqty,
	    SUM(COALESCE(im.quantity, COALESCE(im2.invoiceqty,0))) AS invoiceqty
    FROM maximo.SERVRECTRANS m
    LEFT JOIN maximo.INVOICEMATCH im ON im.SERVRECTRANSID=m.SERVRECTRANSID 
    -- TODO: patch the data to insert to maximo.INVOICEMATCH for migrated data
    LEFT JOIN (
		-- total invoiced
	    SELECT m.SERVRECTRANSID
	    	, m.quantity, m.rejectqty
	    	, CASE WHEN l.invoiceqty > m.quantity-m.rejectqty THEN m.quantity-m.rejectqty ELSE l.invoiceqty END AS invoiceqty
	    	, l.invoicelineid
	    FROM maximo.SERVRECTRANS m
		LEFT JOIN (
			SELECT l.PONUM, l.POLINENUM, l.POREVISIONNUM, SUM(INVOICEQTY) AS INVOICEQTY, MAX(INVOICELINEID) AS INVOICELINEID
			FROM maximo.INVOICELINE l
			GROUP BY l.PONUM, l.POLINENUM, l.POREVISIONNUM
		) l ON l.PONUM=m.PONUM AND l.POLINENUM=m.POLINENUM AND l.POREVISIONNUM=m.POREVISIONNUM
		WHERE 1=1
			--AND m.TRANSDATE>'2025-03-30'
			AND m.ISSUETYPE='RECEIPT' AND m.STATUS='COMP'
	) im2 ON im2.SERVRECTRANSID=m.SERVRECTRANSID
    WHERE
        m.ISSUETYPE = 'RECEIPT'
        AND m.STATUS = 'COMP'
	GROUP BY m.ponum, m.porevisionnum, m.itemnum
) K ON K.PONUM=A.PONUM AND K.POREVISIONNUM=A.REVISIONNUM AND K.ITEMNUM=B.ITEMNUM
LEFT JOIN maximo.person h ON h.personid=a.purchaseagent
WHERE 1=1
	AND a.status IN (SELECT VALUE FROM MAXIMO.SYNONYMDOMAIN WHERE DOMAINID = 'POSTATUS' AND MAXVALUE IN ('APPR', 'INPRG', 'CLOSE'))
;

/**
 * UPDATE PO.RECEIPTS AND PO.STATUS
 */
DROP TABLE "MIGRATION"."BAK_20251201_PO";
CREATE TABLE "MIGRATION"."BAK_20251201_PO"  (
  "POID" BIGINT NOT NULL , 
  "PONUM" VARCHAR(10 OCTETS) NOT NULL , 
  "REVISIONNUM" INTEGER NOT NULL , 
  "NUMOFLINES" INTEGER NOT NULL , 
  "SUMOFRECEIPTS" INTEGER NOT NULL , 
  "RECEIPTS" VARCHAR(20 OCTETS),
  "NEWRECEIPTS" VARCHAR(20 OCTETS),
  "STATUS" VARCHAR(20 OCTETS),
  "NEWSTATUS" VARCHAR(20 OCTETS)
)   
ORGANIZE BY ROW;

INSERT INTO "MIGRATION"."BAK_20251201_PO" (
	POID, PONUM, REVISIONNUM, NUMOFLINES, SUMOFRECEIPTS, RECEIPTS, NEWRECEIPTS, STATUS, NEWSTATUS
)
SELECT 
	A.POID, A.PONUM, A.REVISIONNUM, 
	C.NUMOFLINES, C.SUMOFRECEIPTS,
	A.RECEIPTS, C.PORECEIPTS AS NEWRECEIPTS, 
	A.STATUS, CASE WHEN A.STATUS='WAPPR' AND C.POSTATUS='APPR' THEN C.POSTATUS ELSE A.STATUS END AS NEWSTATUS
FROM MAXIMO.PO A
JOIN (
	SELECT B.PONUM, B.REVISIONNUM,
		COUNT(B.POLINEID) AS NUMOFLINES,
		SUM(B.PORECEIPTS) AS SUMOFRECEIPTS,
		CASE WHEN SUM(B.PORECEIPTS) = 2 * COUNT(B.POLINEID) THEN 'COMPLETE'
			 WHEN SUM(B.PORECEIPTS) > 0 THEN 'PARTIAL'
			 ELSE 'NONE'
		END AS PORECEIPTS,
		CASE WHEN SUM(B.PORECEIPTS) > 0 THEN 'APPR'
			 ELSE 'WAPPR'
		END AS POSTATUS
	FROM (
		SELECT
			A.POLINEID, A.PONUM, A.REVISIONNUM, A.POLINENUM, A.ITEMNUM, 
			A.ORDERQTY, A.TOTAL_RECEIVEDQTY, A.TOTAL_ACCEPTEDQTY, A.TOTAL_RETURNEDQTY, A.WINSPQTY, A.PENDINGQTY, A.TOTAL_INVOICEQTY,
			CASE WHEN A.PENDINGQTY=0 AND A.WINSPQTY=0 THEN 2
				 WHEN A.TOTAL_ACCEPTEDQTY>0 THEN 1
				 ELSE 0
			END AS PORECEIPTS
		FROM  (
			SELECT 
				A.POID, B.POLINEID,
				A.PONUM,
				A.REVISIONNUM,
				A.STATUS,
				B.POLINENUM,
				C.ITEMNUM,
				B.ORDERQTY,
				B.RECEIVEDQTY AS PO_RECEIVEDQTY,
				B.REJECTEDQTY AS PO_REJECTEDQTY,
				COALESCE(D.QUANTITY,0) AS RECEIVEDQTY,
				COALESCE(D.ACCEPTEDQTY,0) AS ACCEPTEDQTY,
				COALESCE(D.REJECTQTY,0) AS REJECTQTY,
				COALESCE(D.RETURNEDQTY,0) AS RETURNEDQTY,
				COALESCE(G.QUANTITY,0) AS DIRECT_RECEIVEDQTY,
				COALESCE(G.RETURNEDQTY,0) AS DIRECT_RETURNEDQTY,
				COALESCE(G.ACCEPTEDQTY,0) AS DIRECT_ACCEPTEDQTY,
				COALESCE(K.QUANTITY,0) AS SERVICE_RECEIVEDQTY,
				COALESCE(K.RETURNEDQTY,0) AS SERVICE_RETURNEDQTY,
				COALESCE(K.ACCEPTEDQTY,0) AS SERVICE_ACCEPTEDQTY,
				COALESCE(D.QUANTITY,0)+COALESCE(G.QUANTITY,0)+COALESCE(K.QUANTITY,0) AS TOTAL_RECEIVEDQTY,
				COALESCE(D.ACCEPTEDQTY,0)+COALESCE(G.ACCEPTEDQTY,0)+COALESCE(K.ACCEPTEDQTY,0) AS TOTAL_ACCEPTEDQTY,
				COALESCE(D.RETURNEDQTY,0)+COALESCE(G.RETURNEDQTY,0)+COALESCE(K.RETURNEDQTY,0) AS TOTAL_RETURNEDQTY,
				COALESCE(D.QUANTITY,0)-COALESCE(D.TRANSFERREDQTY,0)-COALESCE(D.REJECTQTY,0) AS WINSPQTY,
				-- some old data in coswin is inconsistent >> receivedqty more than orderqty
				CASE WHEN (B.ORDERQTY - COALESCE(D.QUANTITY,0) + COALESCE(D.RETURNEDQTY,0) - COALESCE(G.ACCEPTEDQTY,0) - COALESCE(K.ACCEPTEDQTY,0)) < 0 THEN 0
				     ELSE (B.ORDERQTY - COALESCE(D.QUANTITY,0) + COALESCE(D.RETURNEDQTY,0) - COALESCE(G.ACCEPTEDQTY,0) - COALESCE(K.ACCEPTEDQTY,0))
				END AS PENDINGQTY,
				COALESCE(D.INVOICEQTY,0) AS INVOICEQTY,
				COALESCE(G.INVOICEQTY,0) AS DIRECT_INVOICEQTY,
				COALESCE(K.INVOICEQTY,0) AS SERVICE_INVOICEQTY,
				COALESCE(D.INVOICEQTY,0)+COALESCE(G.INVOICEQTY,0)+COALESCE(K.INVOICEQTY,0) AS TOTAL_INVOICEQTY
			FROM MAXIMO.PO A
			JOIN MAXIMO.POLINE B ON B.PONUM=A.PONUM AND B.REVISIONNUM=A.REVISIONNUM 
			JOIN MAXIMO.ITEM C ON C.ITEMNUM=B.ITEMNUM
			LEFT JOIN (
				-- receive with inspection
				SELECT
					m.PONUM, m.porevisionnum,
					m.ITEMNUM,
					-- received: actual delivered qty 
					sum(m.quantity) AS quantity,
					-- reject: reject during inspection - before being accepted >> received = transfered + rejected
					sum(m.rejectqty) AS REJECTQTY,
					-- return: return after inspection + rejected >> total returned
					sum(COALESCE(y.quantity,0)) AS returnedqty,
					-- transferred: pass inspection
					sum(COALESCE(x.quantity,0)) AS transferredqty,
					-- accepted: tranferred - (returned - rejected)
					sum(COALESCE(x.quantity,0) - COALESCE(y.quantity,0) + m.rejectqty) AS acceptedqty,
					-- invoiced
				    SUM(im.quantity) AS invoiceqty
			    FROM maximo.MATRECTRANS m
				LEFT JOIN (
				    -- transferred >> passed inspection >> received - rejected
				    SELECT
				        m.receiptref,
				        SUM(m.quantity) AS quantity
				    FROM
				        maximo.MATRECTRANS m
				    WHERE
				    	-- transfer from HOLDING to STORE
				        m.ISSUETYPE = 'TRANSFER'
				        AND m.STATUS = 'COMP'
				        AND m.FROMSTORELOC = 'L100000019292'
				        AND m.TOSTORELOC IS NOT NULL
				        AND m.TOSTORELOC != 'L100000019292'
				        --AND m.ponum='AA10016094'
				        --and r.STE_CSWNGRNNUM='GRN25/0307'
					GROUP BY m.receiptref
				) x ON x.receiptref=m.matrectransid
				LEFT JOIN (
				    -- return
				    SELECT
				        m.receiptref,
				        -- return qty is negative
				        -1 * SUM(m.quantity) AS quantity
				    FROM
				        maximo.MATRECTRANS m
				    WHERE
				        m.ISSUETYPE = 'RETURN'
				        AND m.STATUS = 'COMP'
					GROUP BY m.receiptref
				) y ON y.receiptref=m.matrectransid
			    LEFT JOIN maximo.INVOICEMATCH im ON im.matrectransid=m.matrectransid 
			    -- TODO: patch the data to insert to maximo.INVOICEMATCH for migrated data
			    LEFT JOIN (
					-- total invoiced
				    SELECT m.matrectransid
				    	, m.quantity, m.rejectqty
				    	, CASE WHEN l.invoiceqty > m.quantity-m.rejectqty THEN m.quantity-m.rejectqty ELSE l.invoiceqty END AS invoiceqty
				    	, l.invoicelineid
				    FROM maximo.MATRECTRANS m
					LEFT JOIN (
						SELECT l.PONUM, l.POLINENUM, l.POREVISIONNUM, SUM(INVOICEQTY) AS INVOICEQTY, MAX(INVOICELINEID) AS INVOICELINEID
						FROM maximo.INVOICELINE l
						GROUP BY l.PONUM, l.POLINENUM, l.POREVISIONNUM
					) l ON l.PONUM=m.PONUM AND l.POLINENUM=m.POLINENUM AND l.POREVISIONNUM=m.POREVISIONNUM
					WHERE 1=1
						AND m.STATUSDATE<='2025-03-30'
						AND m.ISSUETYPE='RECEIPT' AND m.STATUS='COMP' AND m.FROMSTORELOC IS NULL AND m.TOSTORELOC!='L100000019292'
				) im2 ON im2.matrectransid=m.matrectransid
			    WHERE
			        m.ISSUETYPE = 'RECEIPT'
			        AND m.STATUS in ('COMP','WINSP')
			        AND m.FROMSTORELOC IS NULL
			        AND m.TOSTORELOC = 'L100000019292'
				GROUP BY m.PONUM, m.porevisionnum, m.ITEMNUM
			) D ON D.PONUM=A.PONUM AND D.POREVISIONNUM=A.REVISIONNUM AND D.ITEMNUM=B.ITEMNUM
			LEFT JOIN (
			    -- direct receive with no inspection
			    SELECT
			        m.ponum, m.porevisionnum,
			        m.itemnum,
					sum(m.quantity) AS quantity,
					sum(m.rejectqty) AS returnedqty,
					sum(m.quantity-m.rejectqty) AS acceptedqty,
					-- invoiced
				    SUM(COALESCE(im.quantity, im2.invoiceqty)) AS invoiceqty
			    FROM maximo.MATRECTRANS m
			    LEFT JOIN maximo.INVOICEMATCH im ON im.matrectransid=m.matrectransid 
			    -- TODO: patch the data to insert to maximo.INVOICEMATCH for migrated data
			    -- TODO: need to patch data invoicelineid=5852 and matrectransid=1620074
			    LEFT JOIN (
					-- total invoiced
				    SELECT m.matrectransid
				    	, m.quantity, m.rejectqty
				    	, CASE WHEN l.invoiceqty > m.quantity-m.rejectqty THEN m.quantity-m.rejectqty ELSE l.invoiceqty END AS invoiceqty
				    	, l.invoicelineid
				    FROM maximo.MATRECTRANS m
					LEFT JOIN (
						SELECT l.PONUM, l.POLINENUM, l.POREVISIONNUM, SUM(INVOICEQTY) AS INVOICEQTY, MAX(INVOICELINEID) AS INVOICELINEID
						FROM maximo.INVOICELINE l
						GROUP BY l.PONUM, l.POLINENUM, l.POREVISIONNUM
					) l ON l.PONUM=m.PONUM AND l.POLINENUM=m.POLINENUM AND l.POREVISIONNUM=m.POREVISIONNUM
					WHERE 1=1
						AND m.STATUSDATE<='2025-03-30'
						AND m.ISSUETYPE='RECEIPT' AND m.STATUS='COMP' AND m.FROMSTORELOC IS NULL AND m.TOSTORELOC!='L100000019292'
				) im2 ON im2.matrectransid=m.matrectransid
			    WHERE
			    	-- receive directly to STORE (not via HOLDING)
			        m.ISSUETYPE = 'RECEIPT'
			        AND m.STATUS = 'COMP'
			        AND m.FROMSTORELOC IS NULL
			        AND m.TOSTORELOC != 'L100000019292'
				GROUP BY m.ponum, m.porevisionnum, m.itemnum
			) G ON G.PONUM=A.PONUM AND G.POREVISIONNUM=A.REVISIONNUM AND G.ITEMNUM=B.ITEMNUM
			LEFT JOIN (
			    -- service receipts
			    SELECT
			        m.ponum, m.porevisionnum,
			        m.itemnum,
					sum(m.quantity) AS quantity,
					sum(m.rejectqty) AS returnedqty,
					sum(m.quantity-m.rejectqty) AS acceptedqty,
					-- invoiced
					sum(im.quantity) AS invoicematchqty,
					sum(im2.invoiceqty) AS calcinvoiceqty,
				    SUM(COALESCE(im.quantity, COALESCE(im2.invoiceqty,0))) AS invoiceqty
			    FROM maximo.SERVRECTRANS m
			    LEFT JOIN maximo.INVOICEMATCH im ON im.SERVRECTRANSID=m.SERVRECTRANSID 
			    -- TODO: patch the data to insert to maximo.INVOICEMATCH for migrated data
			    LEFT JOIN (
					-- total invoiced
				    SELECT m.SERVRECTRANSID
				    	, m.quantity, m.rejectqty
				    	, CASE WHEN l.invoiceqty > m.quantity-m.rejectqty THEN m.quantity-m.rejectqty ELSE l.invoiceqty END AS invoiceqty
				    	, l.invoicelineid
				    FROM maximo.SERVRECTRANS m
					LEFT JOIN (
						SELECT l.PONUM, l.POLINENUM, l.POREVISIONNUM, SUM(INVOICEQTY) AS INVOICEQTY, MAX(INVOICELINEID) AS INVOICELINEID
						FROM maximo.INVOICELINE l
						GROUP BY l.PONUM, l.POLINENUM, l.POREVISIONNUM
					) l ON l.PONUM=m.PONUM AND l.POLINENUM=m.POLINENUM AND l.POREVISIONNUM=m.POREVISIONNUM
					WHERE 1=1
						--AND m.TRANSDATE>'2025-03-30'
						AND m.ISSUETYPE='RECEIPT' AND m.STATUS='COMP'
				) im2 ON im2.SERVRECTRANSID=m.SERVRECTRANSID
			    WHERE
			        m.ISSUETYPE = 'RECEIPT'
			        AND m.STATUS = 'COMP'
				GROUP BY m.ponum, m.porevisionnum, m.itemnum
			) K ON K.PONUM=A.PONUM AND K.POREVISIONNUM=A.REVISIONNUM AND K.ITEMNUM=B.ITEMNUM
			WHERE A.STE_MIGRATIONID IS NOT NULL
		) A
		--WHERE PONUM='BB60010185'
	) B
	GROUP BY B.PONUM, B.REVISIONNUM
) C ON C.PONUM=A.PONUM AND C.REVISIONNUM=A.REVISIONNUM
WHERE C.PORECEIPTS!=A.RECEIPTS
	AND (
		(A.RECEIPTS='NONE' AND C.PORECEIPTS IN ('PARTIAL', 'COMPLETE'))
		OR (A.RECEIPTS='PARTIAL' AND C.PORECEIPTS IN ('COMPLETE'))
		OR (A.STATUS='WAPPR' AND C.POSTATUS='APPR')
	) 
;

-- PATCH PO.RECEIPTS
MERGE INTO MAXIMO.PO A
USING (
	SELECT POID, RECEIPTS, NEWRECEIPTS
	FROM "MIGRATION"."BAK_20251201_PO"
	WHERE RECEIPTS!=NEWRECEIPTS
) B ON B.POID=A.POID
WHEN MATCHED THEN
UPDATE SET
	A.RECEIPTS=B.NEWRECEIPTS
;

-- PATCH PO.STATUS
MERGE INTO MAXIMO.PO A
USING (
	SELECT POID, STATUS, NEWSTATUS
	FROM "MIGRATION"."BAK_20251201_PO"
	WHERE STATUS!=NEWSTATUS
) B ON B.POID=A.POID
WHEN MATCHED THEN
UPDATE SET
	A.STATUS=B.NEWSTATUS
;

/**
 * INSERT INVOICEMATCH
 */
CALL SYSPROC.ADMIN_CMD('REORG TABLE MAXIMO.INVOICEMATCH');

DELETE FROM MAXIMO.INVOICEMATCH WHERE STE_MIGRATIONID IS NOT NULL;

INSERT INTO MAXIMO.INVOICEMATCH
(
	VENDOR, INVOICENUM, INVOICELINENUM, PONUM, POLINENUM, 
	TRANSTYPE, TRANSDATE, QUANTITY, LINECOST, COSTLINENUM, MATRECTRANSID, SERVRECTRANSID, 
	SITEID, ORGID, USERMATCHED, INVOICEMATCHID, CONVERSION, POREVISIONNUM, POSITEID, REVERSED,
	STE_MIGRATIONID, STE_MIGRATIONDATE
)
SELECT A.VENDOR, A.INVOICENUM, A.INVOICELINENUM, A.PONUM, A.POLINENUM
	, 'PURCHORDR' AS TRANSTYPE
	, COALESCE(B.TRANSDATE, C.TRANSDATE) AS TRANSDATE
	, COALESCE(B.QUANTITY, C.QUANTITY) AS QUANTITY
	, COALESCE(B.LINECOST, C.LINECOST) AS LINECOST
	, A.COSTLINENUM, B.MATRECTRANSID, C.SERVRECTRANSID
	, 'NEL' AS SITEID, 'SBST' AS ORGID, 1 AS USERMATCHED
	, D.MAXID + ROW_NUMBER() OVER (ORDER BY A.PONUM, B.POLINENUM) AS INVOICEMATCHID
	, COALESCE(B.CONVERSION, 0) AS CONVERSION
	, A.REVISIONNUM AS POREVISIONNUM, 'NEL' AS POSITEID
	, 0 AS REVERSED
	, 20251201 AS STE_MIGRATIONID
	, ADD_HOURS(CURRENT_TIMESTAMP, 8) AS STE_MIGRATIONDATE
FROM 
(
	SELECT A.PONUM, A.REVISIONNUM, B.POLINENUM
		, B.ITEMNUM, B.ORDERQTY AS QUANTITY, B.LINECOST
		, C.INVOICENUM, D.INVOICELINENUM, E.COSTLINENUM
		, A.STATUS AS POSTATUS, A.RECEIPTS AS PORECEIPTS, C.STATUS AS INVSTATUS
		, CASE 
			WHEN C.INVOICENUM IS NULL OR D.INVOICELINENUM IS NULL THEN 'N'
			/* #1 */ WHEN C.STATUS='PAID' AND A.RECEIPTS='COMPLETE' AND A.STATUS='CLOSE' THEN 'Y'
			/* #2 */ WHEN C.STATUS='PAID' AND A.RECEIPTS='COMPLETE' AND A.STATUS='APPR' THEN 'Y'
			/* #3 */ WHEN C.STATUS='PAID' AND A.RECEIPTS='PARTIAL' AND A.STATUS='APPR' THEN 'Y'
			/* #4 */ WHEN C.STATUS='APPR' AND A.RECEIPTS='COMPLETE' AND A.STATUS='CLOSE' THEN 'Y'
			/* #5 */ WHEN C.STATUS='APPR' AND A.RECEIPTS='COMPLETE' AND A.STATUS='APPR' THEN 'Y'
			/* #7 */ WHEN C.STATUS='ENTERED' AND A.RECEIPTS='PARTIAL' AND A.STATUS='APPR' THEN 'Y'
			/* #8 */ WHEN C.STATUS='ENTERED' AND A.RECEIPTS='COMPLETE' AND A.STATUS='APPR' THEN 'Y'
			-- ADDITIONAL USE CASES
			/* #9 */ WHEN C.STATUS='APPR' AND A.RECEIPTS='PARTIAL' AND A.STATUS='CLOSE' THEN 'Y'
			/* #10 -- DEPENDANCE ON PATCH FOR PORECEIPT/POSTATUS */ --WHEN C.STATUS='APPR' AND A.RECEIPTS='NONE' AND A.STATUS='WAPPR' THEN 'Y'
			/* #11 */ WHEN C.STATUS='APPR' AND A.RECEIPTS='PARTIAL' AND A.STATUS='APPR' THEN 'Y'
			ELSE 'N'
		  END INVMATCH
		, CASE 
			WHEN C.INVOICENUM IS NULL OR D.INVOICELINENUM IS NULL THEN 'N'
			/* #1 */ WHEN C.STATUS='PAID' AND A.RECEIPTS='COMPLETE' AND A.STATUS='CLOSE' THEN 'Y'
			/* #2 */ WHEN C.STATUS='PAID' AND A.RECEIPTS='COMPLETE' AND A.STATUS='APPR' THEN 'Y'
			/* #3 */ WHEN C.STATUS='PAID' AND A.RECEIPTS='PARTIAL' AND A.STATUS='APPR' THEN 'Y'
			/* #4 */ WHEN C.STATUS='APPR' AND A.RECEIPTS='COMPLETE' AND A.STATUS='CLOSE' THEN 'Y'
			/* #5 */ WHEN C.STATUS='APPR' AND A.RECEIPTS='COMPLETE' AND A.STATUS='APPR' THEN 'Y'
			/* #7 */ WHEN C.STATUS='ENTERED' AND A.RECEIPTS='PARTIAL' AND A.STATUS='APPR' THEN 'N'
			/* #8 */ WHEN C.STATUS='ENTERED' AND A.RECEIPTS='COMPLETE' AND A.STATUS='APPR' THEN 'N'
			-- ADDITIONAL USE CASES
			/* #9 */ WHEN C.STATUS='APPR' AND A.RECEIPTS='PARTIAL' AND A.STATUS='CLOSE' THEN 'Y'
			/* #10 -- DEPENDANCE ON PATCH FOR PORECEIPT/POSTATUS */ --WHEN C.STATUS='APPR' AND A.RECEIPTS='NONE' AND A.STATUS='WAPPR' THEN 'Y'
			/* #11 */ WHEN C.STATUS='APPR' AND A.RECEIPTS='PARTIAL' AND A.STATUS='APPR' THEN 'Y'
			ELSE 'N'
		  END INVTRANS
		/*, F.receivedqty, F.acceptedqty, F.returnedqty, F.winspqty, F.pendingqty */
		/*, CASE WHEN G.MATRECTRANSID IS NOT NULL THEN 'Y' ELSE 'N' END AS ACCRUAL */
		, ROW_NUMBER() OVER (PARTITION BY A.PONUM, A.REVISIONNUM, B.POLINENUM 
			ORDER BY (CASE WHEN D.INVOICELINENUM IS NOT NULL THEN 1 ELSE 0 END) DESC, 
				C.INVOICENUM DESC, D.INVOICELINENUM DESC, E.COSTLINENUM DESC) RN
		, A.VENDOR, A.STATUSDATE
	FROM MAXIMO.PO A
	JOIN MAXIMO.POLINE B ON B.PONUM=A.PONUM AND B.REVISIONNUM=A.REVISIONNUM
	LEFT JOIN MAXIMO.INVOICE C ON C.PONUM=A.PONUM
	LEFT JOIN MAXIMO.INVOICELINE D ON D.INVOICENUM=C.INVOICENUM AND D.POLINENUM=B.POLINENUM
	LEFT JOIN MAXIMO.INVOICECOST E ON E.INVOICENUM=C.INVOICENUM AND E.INVOICELINENUM=D.INVOICELINENUM
	/* LEFT JOIN MAXIMO.STE_RPT_PO_LIST F ON F.PONUM=A.PONUM AND F.POLINENUM=B.POLINENUM */
	/*
	LEFT JOIN (
		SELECT 
			A.MATRECTRANSID,
			M.PONUM, M.POREVISIONNUM, A.ITEMNUM, L.POLINENUM 
		FROM MAXIMO.STE_RPT_ACCRUAL_STK A
		JOIN MAXIMO.MATRECTRANS M ON M.MATRECTRANSID=A.MATRECTRANSID
		JOIN MAXIMO.POLINE L ON L.PONUM=M.PONUM AND L.REVISIONNUM=M.POREVISIONNUM AND L.ITEMNUM=A.ITEMNUM	
	) G ON G.PONUM=A.PONUM AND G.POLINENUM=B.POLINENUM
	*/
	WHERE A.STE_MIGRATIONID IS NOT NULL
) A
LEFT JOIN MAXIMO.MATRECTRANS B ON B.PONUM=A.PONUM AND B.POLINENUM=A.POLINENUM AND B.POREVISIONNUM=A.REVISIONNUM
	AND B.ISSUETYPE='RECEIPT' AND B.INVOICENUM=A.INVOICENUM
LEFT JOIN MAXIMO.SERVRECTRANS C ON C.PONUM=A.PONUM AND C.POLINENUM=A.POLINENUM AND C.POREVISIONNUM=A.REVISIONNUM
	AND C.ISSUETYPE IN ('RECEIPT','INVOICE') AND C.INVOICENUM=A.INVOICENUM
JOIN (
	SELECT MAX(INVOICEMATCHID) AS MAXID FROM MAXIMO.INVOICEMATCH
) D ON 1=1
WHERE 1=1
	AND A.INVMATCH='Y'
	--AND A.ACCEPTEDQTY=0
	AND (B.MATRECTRANSID IS NOT NULL OR C.SERVRECTRANSID IS NOT NULL)
	--NOTE: TOTAL 625 INVOICE-INVOICELINE HAS NO MATCHING RECEIPT
	--AND B.MATRECTRANSID IS NULL AND C.SERVRECTRANSID IS NULL
	--NOTE: VALIDATE SAMPLING
	--AND A.PONUM IN ('BB60019435', 'BB60010185', 'BB60024345', 'BB60023513', 'BB60020914', 'OS0146/018')
ORDER BY A.PONUM, A.POLINENUM
;

CALL MIGRATION.STE_UPDATE_SEQ('INVOICEMATCHSEQ', 'INVOICEMATCH', 'INVOICEMATCHID');

-- SELECT * FROM MAXIMO.MATRECTRANS WHERE MATRECTRANSID IN (1620069, 1620074);

/**
 * INSERT INVOICETRANS
 */
CALL SYSPROC.ADMIN_CMD('REORG TABLE MAXIMO.INVOICETRANS');

DELETE FROM MAXIMO.INVOICETRANS WHERE STE_MIGRATIONID IS NOT NULL;

INSERT INTO MAXIMO.INVOICETRANS
(
	INVOICENUM, VENDOR, INVOICELINENUM, COSTLINENUM, GLDEBITACCT, GLCREDITACCT, 
	CURRENCYCODE, LINECOST, TRANSDATE, ENTERBY, TRANSTYPE, CURRENCYLINECOST, EXCHANGERATE, FINANCIALPERIOD, 
	SITEID, ORGID, ACTUALDATE,
	STE_MIGRATIONID, STE_MIGRATIONDATE, INVOICETRANSID
)
SELECT 
	B.INVOICENUM, B.VENDOR, B.INVOICELINENUM, B.COSTLINENUM, B.GLDEBITACCT, B.GLCREDITACCT
	, B.CURRENCYCODE, B.LINECOST, B.TRANSDATE, B.ENTERBY, B.TRANSTYPE, B.CURRENCYLINECOST, B.EXCHANGERATE, FINANCIALPERIOD
	, B.SITEID, B.ORGID, B.ACTUALDATE
	, 20251201 AS STE_MIGRATIONID
	, ADD_HOURS(CURRENT_TIMESTAMP, 8) AS STE_MIGRATIONDATE
	, D.MAXID + ROW_NUMBER() OVER (ORDER BY B.INVOICENUM) AS INVOICETRANSID
FROM (
	SELECT A.INVOICENUM, A.INVOICEID
		, MAX(A.VENDOR) AS VENDOR
		, NULL AS INVOICELINENUM, NULL AS COSTLINENUM
		, NULL AS GLDEBITACCT, NULL AS GLCREDITACCT
		, MAX(A.CURRENCYCODE) AS CURRENCYCODE
		, SUM(A.LINECOST) * MAX(A.EXCHANGERATE) AS LINECOST
		, MAX(A.TRANSDATE) AS TRANSDATE
		, 'MAXADMIN' AS ENTERBY
		, 'TOTAL' AS TRANSTYPE
		, SUM(A.LINECOST) AS CURRENCYLINECOST
		, MAX(A.EXCHANGERATE) AS EXCHANGERATE
		, YEAR(MAX(A.ACTUALDATE)) AS FINANCIALPERIOD
		, 'NEL' AS SITEID, 'SBST' AS ORGID
		, MAX(A.ACTUALDATE) AS ACTUALDATE
	FROM 
	(
		SELECT A.PONUM, A.REVISIONNUM
			, C.INVOICENUM, C.INVOICEID
			, A.STATUS AS POSTATUS, A.RECEIPTS AS PORECEIPTS, C.STATUS AS INVSTATUS
			, CASE 
				/* #1 */ WHEN C.STATUS='PAID' AND A.RECEIPTS='COMPLETE' AND A.STATUS='CLOSE' THEN 'Y'
				/* #2 */ WHEN C.STATUS='PAID' AND A.RECEIPTS='COMPLETE' AND A.STATUS='APPR' THEN 'Y'
				/* #3 */ WHEN C.STATUS='PAID' AND A.RECEIPTS='PARTIAL' AND A.STATUS='APPR' THEN 'Y'
				/* #4 */ WHEN C.STATUS='APPR' AND A.RECEIPTS='COMPLETE' AND A.STATUS='CLOSE' THEN 'Y'
				/* #5 */ WHEN C.STATUS='APPR' AND A.RECEIPTS='COMPLETE' AND A.STATUS='APPR' THEN 'Y'
				/* #7 */ WHEN C.STATUS='ENTERED' AND A.RECEIPTS='PARTIAL' AND A.STATUS='APPR' THEN 'N'
				/* #8 */ WHEN C.STATUS='ENTERED' AND A.RECEIPTS='COMPLETE' AND A.STATUS='APPR' THEN 'N'
				-- ADDITIONAL USE CASES
				/* #9 */ WHEN C.STATUS='APPR' AND A.RECEIPTS='PARTIAL' AND A.STATUS='CLOSE' THEN 'Y'
				/* #10 -- DEPENDANCE ON PATCH FOR PORECEIPT/POSTATUS */ --WHEN C.STATUS='APPR' AND A.RECEIPTS='NONE' AND A.STATUS='WAPPR' THEN 'Y'
				/* #11 */ WHEN C.STATUS='APPR' AND A.RECEIPTS='PARTIAL' AND A.STATUS='APPR' THEN 'Y'
				ELSE 'N'
			  END INVTRANS
			/*, F.receivedqty, F.acceptedqty, F.returnedqty, F.winspqty, F.pendingqty */
			/*, CASE WHEN G.MATRECTRANSID IS NOT NULL THEN 'Y' ELSE 'N' END AS ACCRUAL */
			, ROW_NUMBER() OVER (PARTITION BY A.PONUM, A.REVISIONNUM 
				ORDER BY C.INVOICENUM DESC) RN
			, A.VENDOR, C.CHANGEDATE AS TRANSDATE, C.ENTERDATE AS ACTUALDATE
			, C.CURRENCYCODE, C.EXCHANGERATE, C.EXCHANGEDATE
			, COALESCE(D.LINECOST,0) AS LINECOST
		FROM MAXIMO.PO A
		-- JOIN MAXIMO.POLINE B ON B.PONUM=A.PONUM AND B.REVISIONNUM=A.REVISIONNUM
		JOIN MAXIMO.INVOICE C ON C.PONUM=A.PONUM
		LEFT JOIN MAXIMO.INVOICELINE D ON D.PONUM=A.PONUM AND D.INVOICENUM=C.INVOICENUM
		/* LEFT JOIN MAXIMO.STE_RPT_PO_LIST F ON F.PONUM=A.PONUM AND F.POLINENUM=B.POLINENUM */
		/*
		LEFT JOIN (
			SELECT 
				A.MATRECTRANSID,
				M.PONUM, M.POREVISIONNUM, A.ITEMNUM, L.POLINENUM 
			FROM MAXIMO.STE_RPT_ACCRUAL_STK A
			JOIN MAXIMO.MATRECTRANS M ON M.MATRECTRANSID=A.MATRECTRANSID
			JOIN MAXIMO.POLINE L ON L.PONUM=M.PONUM AND L.REVISIONNUM=M.POREVISIONNUM AND L.ITEMNUM=A.ITEMNUM	
		) G ON G.PONUM=A.PONUM AND G.POLINENUM=B.POLINENUM
		*/
		WHERE A.STE_MIGRATIONID IS NOT NULL
	) A
	WHERE 1=1
		AND A.INVTRANS='Y'
		--AND A.ACCEPTEDQTY=0
	--ORDER BY A.PONUM, A.POLINENUM
	GROUP BY A.INVOICENUM, A.INVOICEID
) B
JOIN (
	SELECT MAX(INVOICETRANSID) AS MAXID FROM MAXIMO.INVOICETRANS
) D ON 1=1
;

CALL MIGRATION.STE_UPDATE_SEQ('INVOICETRANSSEQ', 'INVOICETRANS', 'INVOICETRANSID');

CALL MIGRATION.STE_FINISH_PATCH('20251201-02-INVOICEMATCH-INVOICETRANS');