CALL MIGRATION.STE_START_PATCH('20250527-02-INVENTORY-MATUSETRANS');

-- UPDATE ISSUE UNITCOST WHEN UNITCOST=0 AND ACTUALCOST!=0
-- NOTE: ONLY UPDATE RECORDS WITH LINECOST<=99999999 BECAUSE CURRENTLY LINECOST DATATYPE IS DECIMAL(13,5) WHICH ONLY ALLOW 8 DIGIT NUMBER
INSERT INTO "MIGRATION"."BAK_20250527_MATUSETRANS"(
	MATUSETRANSID, ITEMNUM, STORELOC, TRANSDATE, UNITCOST, ACTUALCOST, LINECOST, CURRENCYCODE, CURRENCYUNITCOST, CURRENCYLINECOST,
	NEW_UNITCOST, NEW_LINECOST
)
SELECT 
	MATUSETRANSID, ITEMNUM, STORELOC, TRANSDATE, UNITCOST, ACTUALCOST, LINECOST, CURRENCYCODE, CURRENCYUNITCOST, CURRENCYLINECOST,
	ACTUALCOST AS NEW_UNITCOST, ABS(ACTUALCOST*QUANTITY) AS NEW_LINECOST
	--, ISSUETYPE, QUANTITY
FROM maximo.matusetrans
WHERE UNITCOST=0 AND ACTUALCOST!=0
	AND ABS(ACTUALCOST*QUANTITY)<=99999999
;

UPDATE maximo.matusetrans
SET
	UNITCOST=ACTUALCOST,
	LINECOST=-1*ACTUALCOST*QUANTITY,
	CURRENCYUNITCOST=ACTUALCOST,
	CURRENCYLINECOST=-1*ACTUALCOST*QUANTITY,
	EXCHANGERATE=1
WHERE UNITCOST=0 AND ACTUALCOST!=0
	AND ABS(ACTUALCOST*QUANTITY)<=99999999
;

CALL MIGRATION.STE_FINISH_PATCH('20250527-02-INVENTORY-MATUSETRANS');