MERGE INTO MAXIMO.ASSET A
USING (
	SELECT 
		A.ASSETUID, A.ASSETNUM, A.ITEMNUM, A.LOCATION, B.BINNUM, B.CURBAL
		, ROW_NUMBER() OVER (PARTITION BY A.ASSETNUM ORDER BY B.CURBAL DESC) RN
	FROM maximo.asset A
	JOIN MAXIMO.INVBALANCES B ON B.LOCATION=A.LOCATION AND B.ITEMNUM=A.ITEMNUM AND B.CURBAL>0
	WHERE A.STE_MIGRATIONID=20250402 AND A.STE_MIGRATIONTS=-1
	ORDER BY A.ASSETNUM
) B ON B.RN=1 AND B.ASSETUID=A.ASSETUID
WHEN MATCHED THEN
UPDATE SET
	BINNUM=B.BINNUM
;
