CREATE TABLE "MIGRATION"."PATCH_20250330_INVCOST"  (
		  "ITEMNUM" VARCHAR(30 OCTETS) NOT NULL , 
		  "LOCATION" VARCHAR(16 OCTETS) NOT NULL , 
		  "CONDITIONCODE" VARCHAR(30 OCTETS) , 
		  "CONDRATE" INTEGER NOT NULL , 
		  "ITEMSETID" VARCHAR(8 OCTETS) NOT NULL , 
		  "SITEID" VARCHAR(8 OCTETS) NOT NULL , 
		  "STDCOST" DECIMAL(13,5) NOT NULL , 
		  "AVGCOST" DECIMAL(13,5) NOT NULL , 
		  "LASTCOST" DECIMAL(13,5) NOT NULL , 
		  "GLACCOUNT" VARCHAR(110 OCTETS) , 
		  "CONTROLACC" VARCHAR(110 OCTETS) , 
		  "SHRINKAGEACC" VARCHAR(110 OCTETS) , 
		  "INVCOSTADJACC" VARCHAR(110 OCTETS) , 
		  "ORGID" VARCHAR(8 OCTETS) NOT NULL , 
		  "INVCOSTID" BIGINT NOT NULL , 
		  "STE_MIGRATIONID" BIGINT , 
		  "STE_MIGRATIONDATE" TIMESTAMP , 
		  "ROWSTAMP" BIGINT NOT NULL , 
		  "STE_COSC" VARCHAR(16 OCTETS) , 
		  "STE_MIGRATIONTS" INTEGER 
	)   
	IN "MAXDATA"  
	ORGANIZE BY ROW;

ALTER TABLE MIGRATION.PATCH_20250330_INVCOST ADD CREATED_ON TIMESTAMP NOT NULL DEFAULT current_timestamp;

INSERT INTO MIGRATION.PATCH_20250330_INVCOST (
	ITEMNUM, LOCATION, CONDITIONCODE, CONDRATE, ITEMSETID, SITEID, STDCOST, AVGCOST, LASTCOST, 
	GLACCOUNT, CONTROLACC, SHRINKAGEACC, INVCOSTADJACC, ORGID, INVCOSTID, 
	STE_MIGRATIONID, STE_MIGRATIONDATE, ROWSTAMP, STE_COSC, STE_MIGRATIONTS
)
SELECT ITEMNUM, LOCATION, CONDITIONCODE, CONDRATE, ITEMSETID, SITEID, STDCOST, AVGCOST, LASTCOST, 
	GLACCOUNT, CONTROLACC, SHRINKAGEACC, INVCOSTADJACC, ORGID, INVCOSTID, 
	STE_MIGRATIONID, STE_MIGRATIONDATE, ROWSTAMP, STE_COSC, STE_MIGRATIONTS
FROM MAXIMO.INVCOST;

UPDATE MAXIMO.INVCOST SET AVGCOST=STDCOST WHERE STE_MIGRATIONID IS NOT NULL;

MERGE INTO MAXIMO.INVCOST A
USING (
	SELECT B.INVCOSTID, A.TOSTORELOC, A.ITEMNUM, A.TRANSDATE, A.STE_MIGRATIONID, A.UNITCOST
		, ROW_NUMBER() OVER (PARTITION BY B.INVCOSTID ORDER BY A.TRANSDATE DESC, A.STE_MIGRATIONID DESC) RN
	FROM MAXIMO.MATRECTRANS A 
	JOIN MAXIMO.INVCOST B ON B.LOCATION=A.TOSTORELOC AND B.ITEMNUM=A.ITEMNUM
	WHERE A.ISSUETYPE='RECEIPT' AND A.PONUM!='CSWN_NONPO'
	ORDER BY B.INVCOSTID
) B ON B.RN=1 AND B.INVCOSTID=A.INVCOSTID
WHEN MATCHED THEN
UPDATE SET
	LASTCOST=B.UNITCOST
;