CALL MIGRATION.STE_START_PATCH('20251201-01-INVOICESTATUS');

/**
 * BRING INVOICE DATA FROM COSWIN AS-IS
 */

--DROP TABLE "MAXIMO"."CSWN_INVOICE_";
--DROP TABLE IF EXISTS "MIGRATION"."CSWN_INVOICE_";
--
--CREATE TABLE "MIGRATION"."CSWN_INVOICE_" 
--(	
--   	"PK_INVOICE_" BIGINT, 
--	"TIMESTAMP" BIGINT NOT NULL, 
--	"S_RCL_INVOICE" BIGINT, 
--	"S_SUPL_INV" BIGINT, 
--	"S_NEG_INV" BIGINT, 
--	"DT_INVOICE" BIGINT, 
--	"TM_INVOICE" BIGINT, 
--	"INV_REF" VARCHAR(10), 
--	"INV_DT" BIGINT, 
--	"INV_RCT_DT" BIGINT, 
--	"INV_CUR" VARCHAR(6), 
--	"INV_BASE_VAL" NUMERIC(31,12), 
--	"INV_DISC" NUMERIC(31,12), 
--	"INV_FRT" NUMERIC(31,12), 
--	"INV_OTHR_CHRG" NUMERIC(31,12), 
--	"INV_TAX1" NUMERIC(31,12), 
--	"INV_TAX2" NUMERIC(31,12), 
--	"INV_ADJ" NUMERIC(31,12), 
--	"INV_STAT" INTEGER, 
--	"INV_DN_REF" VARCHAR(10), 
--	"INV_RCL_FLG" INTEGER, 
--	"INV_STRING1" VARCHAR(20), 
--	"INV_STRING2" VARCHAR(20), 
--	"INV_NUMBER1" NUMERIC(31,12), 
--	"INV_DATE1" BIGINT, 
--	"INV_STATUS" INTEGER, 
--	"INV_ISSUE_DATE" BIGINT, 
--	"INV_DATE2" BIGINT, 
--	"INV_NUMBER2" NUMERIC(31,12), 
--	"INV_NUMBER3" NUMERIC(31,12), 
--	"INV_NUMBER4" NUMERIC(31,12), 
--	"INV_NUMBER5" NUMERIC(31,12), 
--	"INV_STRING3" VARCHAR(20), 
--	"INV_STRING4" VARCHAR(20)
--)
--ORGANIZE BY ROW;

--
-- BRING DATA FROM ON-PREM "MIGRATION"."CSWN_INVOICE_"
--

/**
 * PATCH INVOICE.STATUS WITH NEW MAPPING
 */

-- DROP TABLE IF EXISTS "MIGRATION"."BAK_20251201_INVOICE";

CREATE TABLE "MIGRATION"."BAK_20251201_INVOICE" 
(	
   	"INVOICEID" BIGINT, 
	"INVOICENUM" VARCHAR(15), 
	"STATUS" VARCHAR(10), 
	"NEWSTATUS" VARCHAR(10)
)
ORGANIZE BY ROW;

INSERT INTO "MIGRATION"."BAK_20251201_INVOICE" (
	INVOICEID, INVOICENUM, STATUS, NEWSTATUS
)
SELECT
	B.INVOICEID, B.INVOICENUM, B.STATUS, A.NEWSTATUS
FROM (
	SELECT
		A.PK_INVOICE_ AS STE_MIGRATIONID
		, A.INV_REF AS INVOICENUM
		, CASE WHEN A.INV_STATUS=48 THEN 'APPR'
			   WHEN A.INV_STATUS=49 THEN 'APPR'
			   WHEN A.INV_STATUS=50 THEN 'APPR'
			   WHEN A.INV_STATUS=51 THEN 'PAID'
			   WHEN A.INV_STATUS=52 THEN 'CANCEL'
			   WHEN A.INV_STATUS=53 THEN 'PAID'
			   ELSE 'NA'
		  END AS OLDSTATUS
		, CASE WHEN A.INV_STATUS=48 THEN 'WAPPR'
			   WHEN A.INV_STATUS=49 THEN 'APPR'
			   WHEN A.INV_STATUS=50 THEN 'APPR'
			   WHEN A.INV_STATUS=51 THEN 'CANCEL'
			   ELSE 'NA'
		  END AS NEWSTATUS
	FROM "MIGRATION"."CSWN_INVOICE_" A
) A
JOIN MAXIMO.INVOICE B ON 1=1
	-- ONLY MIGRATED DATA
	AND B.STE_MIGRATIONID=A.STE_MIGRATIONID 
	-- ONLY WHEN STATUS HAS NOT CHANGED AFTER MIGRATION
	AND B.STATUS=A.OLDSTATUS
	-- JUST AS ADDITIONAL PRECAUTION
	AND B.INVOICENUM=A.INVOICENUM
WHERE A.OLDSTATUS!=A.NEWSTATUS
;

-- PATCH INVOICE.STATUS
MERGE INTO MAXIMO.INVOICE A
USING "MIGRATION"."BAK_20251201_INVOICE" B ON B.INVOICEID=A.INVOICEID
WHEN MATCHED THEN
UPDATE SET
	A.STATUS=B.NEWSTATUS
;

/**
 * DELETE RECEIPT (MATRECTRANS) FOR CANCELLED INVOICE
 */
-- DROP TABLE IF EXISTS "MIGRATION"."BAK_20251201_MATRECTRANS";

CREATE TABLE "MIGRATION"."BAK_20251201_MATRECTRANS"  (
  "ITEMNUM" VARCHAR(30 OCTETS) , 
  "TOSTORELOC" VARCHAR(16 OCTETS) , 
  "TRANSDATE" TIMESTAMP NOT NULL , 
  "ACTUALDATE" TIMESTAMP NOT NULL , 
  "QUANTITY" DECIMAL(15,2) , 
  "RECEIVEDUNIT" VARCHAR(16 OCTETS) , 
  "ISSUETYPE" VARCHAR(20 OCTETS) , 
  "UNITCOST" DECIMAL(13,5) NOT NULL , 
  "ACTUALCOST" DECIMAL(13,5) NOT NULL , 
  "PONUM" VARCHAR(10 OCTETS) , 
  "INVOICENUM" VARCHAR(15 OCTETS) , 
  "REJECTCODE" VARCHAR(6 OCTETS) , 
  "REJECTQTY" DECIMAL(15,2) NOT NULL , 
  "CONVERSION" DECIMAL(18,5) , 
  "ASSETNUM" VARCHAR(13 OCTETS) , 
  "ENTERBY" VARCHAR(100 OCTETS) NOT NULL , 
  "IT1" VARCHAR(10 OCTETS) , 
  "IT2" VARCHAR(10 OCTETS) , 
  "IT3" VARCHAR(10 OCTETS) , 
  "IT4" DECIMAL(15,2) , 
  "IT5" VARCHAR(10 OCTETS) , 
  "OUTSIDE" INTEGER NOT NULL , 
  "ISSUETO" VARCHAR(100 OCTETS) , 
  "PACKINGSLIPNUM" VARCHAR(50 OCTETS) , 
  "POLINENUM" INTEGER , 
  "ISSUE" INTEGER NOT NULL , 
  "REQUESTEDBY" VARCHAR(100 OCTETS) , 
  "TOTALCURBAL" DECIMAL(15,2) , 
  "OLDAVGCOST" DECIMAL(13,5) , 
  "ITIN1" VARCHAR(10 OCTETS) , 
  "ITIN2" VARCHAR(10 OCTETS) , 
  "ITIN3" VARCHAR(10 OCTETS) , 
  "TOBIN" VARCHAR(16 OCTETS) , 
  "GLDEBITACCT" VARCHAR(110 OCTETS) , 
  "GLCREDITACCT" VARCHAR(110 OCTETS) , 
  "LINECOST" DECIMAL(13,5) NOT NULL , 
  "FINANCIALPERIOD" VARCHAR(6 OCTETS) , 
  "CURRENCYCODE" VARCHAR(8 OCTETS) NOT NULL , 
  "EXCHANGERATE" DECIMAL(14,7) , 
  "CURRENCYUNITCOST" DECIMAL(10,2) , 
  "MANUFACTURER" VARCHAR(20 OCTETS) , 
  "MODELNUM" VARCHAR(8 OCTETS) , 
  "CURRENCYLINECOST" DECIMAL(10,2) , 
  "LOCATION" VARCHAR(16 OCTETS) , 
  "DESCRIPTION" VARCHAR(200 OCTETS) , 
  "REMARK" VARCHAR(254 OCTETS) , 
  "FROMSTORELOC" VARCHAR(16 OCTETS) , 
  "FROMBIN" VARCHAR(16 OCTETS) , 
  "QTYHELD" DECIMAL(15,2) , 
  "FROMLOT" VARCHAR(12 OCTETS) , 
  "TOLOT" VARCHAR(12 OCTETS) , 
  "LOADEDCOST" DECIMAL(10,2) NOT NULL , 
  "TAX1CODE" VARCHAR(8 OCTETS) , 
  "TAX1" DECIMAL(10,2) , 
  "TAX2CODE" VARCHAR(8 OCTETS) , 
  "TAX2" DECIMAL(10,2) , 
  "TAX3CODE" VARCHAR(8 OCTETS) , 
  "TAX3" DECIMAL(10,2) , 
  "TAX4CODE" VARCHAR(8 OCTETS) , 
  "TAX4" DECIMAL(10,2) , 
  "TAX5CODE" VARCHAR(8 OCTETS) , 
  "TAX5" DECIMAL(10,2) , 
  "PRORATED" INTEGER NOT NULL , 
  "PRORATECOST" DECIMAL(10,2) , 
  "STATUS" VARCHAR(12 OCTETS) , 
  "STATUSDATE" TIMESTAMP , 
  "STATUSCHANGEBY" VARCHAR(100 OCTETS) , 
  "SOURCESYSID" VARCHAR(10 OCTETS) , 
  "QTYREQUESTED" DECIMAL(15,2) , 
  "CURBAL" DECIMAL(15,2) NOT NULL , 
  "EXCHANGERATE2" DECIMAL(14,7) , 
  "LINECOST2" DECIMAL(10,2) , 
  "MRNUM" VARCHAR(10 OCTETS) , 
  "MRLINENUM" INTEGER , 
  "MATRECTRANSID" BIGINT NOT NULL , 
  "OWNERSYSID" VARCHAR(10 OCTETS) , 
  "EXTERNALREFID" VARCHAR(10 OCTETS) , 
  "IT6" VARCHAR(10 OCTETS) , 
  "IT7" VARCHAR(10 OCTETS) , 
  "IT8" VARCHAR(10 OCTETS) , 
  "IT9" VARCHAR(10 OCTETS) , 
  "IT10" VARCHAR(10 OCTETS) , 
  "ITIN4" VARCHAR(10 OCTETS) , 
  "ITIN5" VARCHAR(10 OCTETS) , 
  "ITIN6" VARCHAR(10 OCTETS) , 
  "ITIN7" VARCHAR(10 OCTETS) , 
  "SENDERSYSID" VARCHAR(50 OCTETS) , 
  "FINCNTRLID" VARCHAR(8 OCTETS) , 
  "ORGID" VARCHAR(8 OCTETS) NOT NULL , 
  "SITEID" VARCHAR(8 OCTETS) NOT NULL , 
  "COSTINFO" INTEGER NOT NULL , 
  "BELONGSTO" BIGINT , 
  "REFWO" VARCHAR(10 OCTETS) , 
  "ENTEREDASTASK" INTEGER NOT NULL , 
  "FROMSITEID" VARCHAR(8 OCTETS) NOT NULL , 
  "RECEIPTREF" BIGINT , 
  "LINETYPE" VARCHAR(15 OCTETS) NOT NULL , 
  "ITEMSETID" VARCHAR(8 OCTETS) , 
  "CONDITIONCODE" VARCHAR(30 OCTETS) , 
  "FROMCONDITIONCODE" VARCHAR(30 OCTETS) , 
  "CONDRATE" INTEGER , 
  "COMMODITYGROUP" VARCHAR(10 OCTETS) , 
  "COMMODITY" VARCHAR(10 OCTETS) , 
  "MATUSETRANSID" BIGINT , 
  "COURIER" VARCHAR(30 OCTETS) , 
  "LANGCODE" VARCHAR(4 OCTETS) NOT NULL , 
  "INSPECTEDQTY" DECIMAL(15,2) , 
  "POSITEID" VARCHAR(8 OCTETS) , 
  "HASLD" INTEGER NOT NULL , 
  "ROTASSETNUM" VARCHAR(13 OCTETS) , 
  "POREVISIONNUM" INTEGER , 
  "INVUSELINEID" BIGINT , 
  "INVUSEID" BIGINT , 
  "INVUSELINENUM" INTEGER , 
  "INVUSELINESPLITID" BIGINT , 
  "SHIPMENTNUM" VARCHAR(50 OCTETS) , 
  "SHIPMENTLINENUM" VARCHAR(50 OCTETS) , 
  "QTYOVERRECEIVED" DECIMAL(15,2) , 
  "COSTOVERRECEIVED" DECIMAL(13,5) , 
  "CONSIGNMENT" INTEGER NOT NULL , 
  "CONSINVOICENUM" VARCHAR(15 OCTETS) , 
  "CONSVENDOR" VARCHAR(20 OCTETS) , 
  "ORGRCVEXTERNALREFID" VARCHAR(10 OCTETS) , 
  "INVPICKLISTID" BIGINT , 
  "PLUSTPOS" VARCHAR(15 OCTETS) , 
  "PLUSTACCOMP" VARCHAR(10 OCTETS) , 
  "PLUSTHASWARRANTY" VARCHAR(2 OCTETS) , 
  "PLUSTFAILURE" VARCHAR(10 OCTETS) , 
  "PLUSTREASON" VARCHAR(10 OCTETS) , 
  "PLUSTCOMP" VARCHAR(15 OCTETS) , 
  "STE_DODATE" TIMESTAMP , 
  "STE_GRNREFTYPE" VARCHAR(50 OCTETS) , 
  "STE_CSWNCC" VARCHAR(16 OCTETS) , 
  "STE_CSWNDNDATE" TIMESTAMP , 
  "STE_CSWNGRNDATE" TIMESTAMP , 
  "STE_CSWNGRNNUM" VARCHAR(10 OCTETS) , 
  "STE_CSWNINSPREF" VARCHAR(10 OCTETS) , 
  "STE_CSWNINSPSTATUS" INTEGER , 
  "STE_CSWNRCTSTATUS" INTEGER , 
  "STE_CSWNRECEIPTTYPE" INTEGER , 
  "STE_CSWNSAPGL" VARCHAR(20 OCTETS) , 
  "STE_MIGRATIONDATE" TIMESTAMP , 
  "STE_MIGRATIONNSITEMPK" VARCHAR(200 OCTETS) , 
  "STE_MIGRATIONITEMPK" VARCHAR(200 OCTETS) , 
  "STE_MIGRATIONID" BIGINT , 
  "ROWSTAMP" BIGINT NOT NULL , 
  "STE_CSWNRECEIPTREMARK" VARCHAR(100 OCTETS) , 
  "STE_MIGRATIONSOURCE" VARCHAR(50 OCTETS) , 
  "STE_MIGRATIONTS" INTEGER , 
  "STE_PENDINGQTY" DECIMAL(15,2) , 
  "STE_CSWNACPQTY" DECIMAL(15,2) , 
  "STE_CSWNRTNTOSUPL" DECIMAL(15,2) , 
  "STE_CSWNRCTQTY" DECIMAL(15,2) , 
  "STE_CSWNRCTVAL" DECIMAL(13,5) 
)   
ORGANIZE BY ROW;

INSERT INTO "MIGRATION"."BAK_20251201_MATRECTRANS"
(
	ITEMNUM, TOSTORELOC, TRANSDATE, ACTUALDATE, QUANTITY, RECEIVEDUNIT, ISSUETYPE, UNITCOST, ACTUALCOST, 
	PONUM, INVOICENUM, REJECTCODE, REJECTQTY, CONVERSION, ASSETNUM, ENTERBY, IT1, IT2, IT3, IT4, IT5, OUTSIDE, 
	ISSUETO, PACKINGSLIPNUM, POLINENUM, ISSUE, REQUESTEDBY, TOTALCURBAL, OLDAVGCOST, ITIN1, ITIN2, ITIN3, TOBIN, 
	GLDEBITACCT, GLCREDITACCT, LINECOST, FINANCIALPERIOD, CURRENCYCODE, EXCHANGERATE, CURRENCYUNITCOST, 
	MANUFACTURER, MODELNUM, CURRENCYLINECOST, LOCATION, DESCRIPTION, REMARK, 
	FROMSTORELOC, FROMBIN, QTYHELD, FROMLOT, TOLOT, LOADEDCOST, 
	TAX1CODE, TAX1, TAX2CODE, TAX2, TAX3CODE, TAX3, TAX4CODE, TAX4, TAX5CODE, TAX5, PRORATED, PRORATECOST, 
	STATUS, STATUSDATE, STATUSCHANGEBY, SOURCESYSID, QTYREQUESTED, CURBAL, EXCHANGERATE2, LINECOST2, 
	MRNUM, MRLINENUM, MATRECTRANSID, OWNERSYSID, EXTERNALREFID, IT6, IT7, IT8, IT9, IT10, ITIN4, ITIN5, ITIN6, ITIN7, 
	SENDERSYSID, FINCNTRLID, ORGID, SITEID, COSTINFO, BELONGSTO, REFWO, ENTEREDASTASK, FROMSITEID, RECEIPTREF, 
	LINETYPE, ITEMSETID, CONDITIONCODE, FROMCONDITIONCODE, CONDRATE, COMMODITYGROUP, COMMODITY, MATUSETRANSID, 
	COURIER, LANGCODE, INSPECTEDQTY, POSITEID, HASLD, ROTASSETNUM, POREVISIONNUM, 
	INVUSELINEID, INVUSEID, INVUSELINENUM, INVUSELINESPLITID, SHIPMENTNUM, SHIPMENTLINENUM, 
	QTYOVERRECEIVED, COSTOVERRECEIVED, CONSIGNMENT, CONSINVOICENUM, CONSVENDOR, ORGRCVEXTERNALREFID, 
	INVPICKLISTID, PLUSTPOS, PLUSTACCOMP, PLUSTHASWARRANTY, PLUSTFAILURE, PLUSTREASON, PLUSTCOMP, 
	STE_DODATE, STE_GRNREFTYPE, STE_CSWNCC, STE_CSWNDNDATE, STE_CSWNGRNDATE, STE_CSWNGRNNUM, STE_CSWNINSPREF, 
	STE_CSWNINSPSTATUS, STE_CSWNRCTSTATUS, STE_CSWNRECEIPTTYPE, STE_CSWNSAPGL, 
	STE_MIGRATIONDATE, STE_MIGRATIONNSITEMPK, STE_MIGRATIONITEMPK, STE_MIGRATIONID, ROWSTAMP, 
	STE_CSWNRECEIPTREMARK, STE_MIGRATIONSOURCE, STE_MIGRATIONTS, STE_PENDINGQTY, STE_CSWNACPQTY, 
	STE_CSWNRTNTOSUPL, STE_CSWNRCTQTY, STE_CSWNRCTVAL
)
select 
	B.ITEMNUM, B.TOSTORELOC, B.TRANSDATE, B.ACTUALDATE, B.QUANTITY, B.RECEIVEDUNIT, B.ISSUETYPE, B.UNITCOST, B.ACTUALCOST,
	B.PONUM, B.INVOICENUM, B.REJECTCODE, B.REJECTQTY, B.CONVERSION, B.ASSETNUM, B.ENTERBY, B.IT1, B.IT2, B.IT3, B.IT4, B.IT5, B.OUTSIDE,
	B.ISSUETO, B.PACKINGSLIPNUM, B.POLINENUM, B.ISSUE, B.REQUESTEDBY, B.TOTALCURBAL, B.OLDAVGCOST, B.ITIN1, B.ITIN2, B.ITIN3, B.TOBIN,
	B.GLDEBITACCT, B.GLCREDITACCT, B.LINECOST, B.FINANCIALPERIOD, B.CURRENCYCODE, B.EXCHANGERATE, B.CURRENCYUNITCOST,
	B.MANUFACTURER, B.MODELNUM, B.CURRENCYLINECOST, B.LOCATION, B.DESCRIPTION, B.REMARK,
	B.FROMSTORELOC, B.FROMBIN, B.QTYHELD, B.FROMLOT, B.TOLOT, B.LOADEDCOST,
	B.TAX1CODE, B.TAX1, B.TAX2CODE, B.TAX2, B.TAX3CODE, B.TAX3, B.TAX4CODE, B.TAX4, B.TAX5CODE, B.TAX5, B.PRORATED, B.PRORATECOST,
	B.STATUS, B.STATUSDATE, B.STATUSCHANGEBY, B.SOURCESYSID, B.QTYREQUESTED, B.CURBAL, B.EXCHANGERATE2, B.LINECOST2,
	B.MRNUM, B.MRLINENUM, B.MATRECTRANSID, B.OWNERSYSID, B.EXTERNALREFID, B.IT6, B.IT7, B.IT8, B.IT9, B.IT10, B.ITIN4, B.ITIN5, B.ITIN6, B.ITIN7,
	B.SENDERSYSID, B.FINCNTRLID, B.ORGID, B.SITEID, B.COSTINFO, B.BELONGSTO, B.REFWO, B.ENTEREDASTASK, B.FROMSITEID, B.RECEIPTREF,
	B.LINETYPE, B.ITEMSETID, B.CONDITIONCODE, B.FROMCONDITIONCODE, B.CONDRATE, B.COMMODITYGROUP, B.COMMODITY, B.MATUSETRANSID,
	B.COURIER, B.LANGCODE, B.INSPECTEDQTY, B.POSITEID, B.HASLD, B.ROTASSETNUM, B.POREVISIONNUM,
	B.INVUSELINEID, B.INVUSEID, B.INVUSELINENUM, B.INVUSELINESPLITID, B.SHIPMENTNUM, B.SHIPMENTLINENUM,
	B.QTYOVERRECEIVED, B.COSTOVERRECEIVED, B.CONSIGNMENT, B.CONSINVOICENUM, B.CONSVENDOR, B.ORGRCVEXTERNALREFID,
	B.INVPICKLISTID, B.PLUSTPOS, B.PLUSTACCOMP, B.PLUSTHASWARRANTY, B.PLUSTFAILURE, B.PLUSTREASON, B.PLUSTCOMP,
	B.STE_DODATE, B.STE_GRNREFTYPE, B.STE_CSWNCC, B.STE_CSWNDNDATE, B.STE_CSWNGRNDATE, B.STE_CSWNGRNNUM, B.STE_CSWNINSPREF,
	B.STE_CSWNINSPSTATUS, B.STE_CSWNRCTSTATUS, B.STE_CSWNRECEIPTTYPE, B.STE_CSWNSAPGL,
	B.STE_MIGRATIONDATE, B.STE_MIGRATIONNSITEMPK, B.STE_MIGRATIONITEMPK, B.STE_MIGRATIONID, B.ROWSTAMP,
	B.STE_CSWNRECEIPTREMARK, B.STE_MIGRATIONSOURCE, B.STE_MIGRATIONTS, B.STE_PENDINGQTY, B.STE_CSWNACPQTY,
	B.STE_CSWNRTNTOSUPL, B.STE_CSWNRCTQTY, B.STE_CSWNRCTVAL
from maximo.invoice a 
JOIN maximo.matrectrans b ON b.invoicenum=a.invoicenum
WHERE a.status='CANCEL'
;

INSERT INTO "MIGRATION"."BAK_20251201_MATRECTRANS"
(
	ITEMNUM, TOSTORELOC, TRANSDATE, ACTUALDATE, QUANTITY, RECEIVEDUNIT, ISSUETYPE, UNITCOST, ACTUALCOST, 
	PONUM, INVOICENUM, REJECTCODE, REJECTQTY, CONVERSION, ASSETNUM, ENTERBY, IT1, IT2, IT3, IT4, IT5, OUTSIDE, 
	ISSUETO, PACKINGSLIPNUM, POLINENUM, ISSUE, REQUESTEDBY, TOTALCURBAL, OLDAVGCOST, ITIN1, ITIN2, ITIN3, TOBIN, 
	GLDEBITACCT, GLCREDITACCT, LINECOST, FINANCIALPERIOD, CURRENCYCODE, EXCHANGERATE, CURRENCYUNITCOST, 
	MANUFACTURER, MODELNUM, CURRENCYLINECOST, LOCATION, DESCRIPTION, REMARK, 
	FROMSTORELOC, FROMBIN, QTYHELD, FROMLOT, TOLOT, LOADEDCOST, 
	TAX1CODE, TAX1, TAX2CODE, TAX2, TAX3CODE, TAX3, TAX4CODE, TAX4, TAX5CODE, TAX5, PRORATED, PRORATECOST, 
	STATUS, STATUSDATE, STATUSCHANGEBY, SOURCESYSID, QTYREQUESTED, CURBAL, EXCHANGERATE2, LINECOST2, 
	MRNUM, MRLINENUM, MATRECTRANSID, OWNERSYSID, EXTERNALREFID, IT6, IT7, IT8, IT9, IT10, ITIN4, ITIN5, ITIN6, ITIN7, 
	SENDERSYSID, FINCNTRLID, ORGID, SITEID, COSTINFO, BELONGSTO, REFWO, ENTEREDASTASK, FROMSITEID, RECEIPTREF, 
	LINETYPE, ITEMSETID, CONDITIONCODE, FROMCONDITIONCODE, CONDRATE, COMMODITYGROUP, COMMODITY, MATUSETRANSID, 
	COURIER, LANGCODE, INSPECTEDQTY, POSITEID, HASLD, ROTASSETNUM, POREVISIONNUM, 
	INVUSELINEID, INVUSEID, INVUSELINENUM, INVUSELINESPLITID, SHIPMENTNUM, SHIPMENTLINENUM, 
	QTYOVERRECEIVED, COSTOVERRECEIVED, CONSIGNMENT, CONSINVOICENUM, CONSVENDOR, ORGRCVEXTERNALREFID, 
	INVPICKLISTID, PLUSTPOS, PLUSTACCOMP, PLUSTHASWARRANTY, PLUSTFAILURE, PLUSTREASON, PLUSTCOMP, 
	STE_DODATE, STE_GRNREFTYPE, STE_CSWNCC, STE_CSWNDNDATE, STE_CSWNGRNDATE, STE_CSWNGRNNUM, STE_CSWNINSPREF, 
	STE_CSWNINSPSTATUS, STE_CSWNRCTSTATUS, STE_CSWNRECEIPTTYPE, STE_CSWNSAPGL, 
	STE_MIGRATIONDATE, STE_MIGRATIONNSITEMPK, STE_MIGRATIONITEMPK, STE_MIGRATIONID, ROWSTAMP, 
	STE_CSWNRECEIPTREMARK, STE_MIGRATIONSOURCE, STE_MIGRATIONTS, STE_PENDINGQTY, STE_CSWNACPQTY, 
	STE_CSWNRTNTOSUPL, STE_CSWNRCTQTY, STE_CSWNRCTVAL
)
select 
	C.ITEMNUM, C.TOSTORELOC, C.TRANSDATE, C.ACTUALDATE, C.QUANTITY, C.RECEIVEDUNIT, C.ISSUETYPE, C.UNITCOST, C.ACTUALCOST,
	C.PONUM, C.INVOICENUM, C.REJECTCODE, C.REJECTQTY, C.CONVERSION, C.ASSETNUM, C.ENTERBY, C.IT1, C.IT2, C.IT3, C.IT4, C.IT5, C.OUTSIDE,
	C.ISSUETO, C.PACKINGSLIPNUM, C.POLINENUM, C.ISSUE, C.REQUESTEDBY, C.TOTALCURBAL, C.OLDAVGCOST, C.ITIN1, C.ITIN2, C.ITIN3, C.TOBIN,
	C.GLDEBITACCT, C.GLCREDITACCT, C.LINECOST, C.FINANCIALPERIOD, C.CURRENCYCODE, C.EXCHANGERATE, C.CURRENCYUNITCOST,
	C.MANUFACTURER, C.MODELNUM, C.CURRENCYLINECOST, C.LOCATION, C.DESCRIPTION, C.REMARK,
	C.FROMSTORELOC, C.FROMBIN, C.QTYHELD, C.FROMLOT, C.TOLOT, C.LOADEDCOST,
	C.TAX1CODE, C.TAX1, C.TAX2CODE, C.TAX2, C.TAX3CODE, C.TAX3, C.TAX4CODE, C.TAX4, C.TAX5CODE, C.TAX5, C.PRORATED, C.PRORATECOST,
	C.STATUS, C.STATUSDATE, C.STATUSCHANGEBY, C.SOURCESYSID, C.QTYREQUESTED, C.CURBAL, C.EXCHANGERATE2, C.LINECOST2,
	C.MRNUM, C.MRLINENUM, C.MATRECTRANSID, C.OWNERSYSID, C.EXTERNALREFID, C.IT6, C.IT7, C.IT8, C.IT9, C.IT10, C.ITIN4, C.ITIN5, C.ITIN6, C.ITIN7,
	C.SENDERSYSID, C.FINCNTRLID, C.ORGID, C.SITEID, C.COSTINFO, C.BELONGSTO, C.REFWO, C.ENTEREDASTASK, C.FROMSITEID, C.RECEIPTREF,
	C.LINETYPE, C.ITEMSETID, C.CONDITIONCODE, C.FROMCONDITIONCODE, C.CONDRATE, C.COMMODITYGROUP, C.COMMODITY, C.MATUSETRANSID,
	C.COURIER, C.LANGCODE, C.INSPECTEDQTY, C.POSITEID, C.HASLD, C.ROTASSETNUM, C.POREVISIONNUM,
	C.INVUSELINEID, C.INVUSEID, C.INVUSELINENUM, C.INVUSELINESPLITID, C.SHIPMENTNUM, C.SHIPMENTLINENUM,
	C.QTYOVERRECEIVED, C.COSTOVERRECEIVED, C.CONSIGNMENT, C.CONSINVOICENUM, C.CONSVENDOR, C.ORGRCVEXTERNALREFID,
	C.INVPICKLISTID, C.PLUSTPOS, C.PLUSTACCOMP, C.PLUSTHASWARRANTY, C.PLUSTFAILURE, C.PLUSTREASON, C.PLUSTCOMP,
	C.STE_DODATE, C.STE_GRNREFTYPE, C.STE_CSWNCC, C.STE_CSWNDNDATE, C.STE_CSWNGRNDATE, C.STE_CSWNGRNNUM, C.STE_CSWNINSPREF,
	C.STE_CSWNINSPSTATUS, C.STE_CSWNRCTSTATUS, C.STE_CSWNRECEIPTTYPE, C.STE_CSWNSAPGL,
	C.STE_MIGRATIONDATE, C.STE_MIGRATIONNSITEMPK, C.STE_MIGRATIONITEMPK, C.STE_MIGRATIONID, C.ROWSTAMP,
	C.STE_CSWNRECEIPTREMARK, C.STE_MIGRATIONSOURCE, C.STE_MIGRATIONTS, C.STE_PENDINGQTY, C.STE_CSWNACPQTY,
	C.STE_CSWNRTNTOSUPL, C.STE_CSWNRCTQTY, C.STE_CSWNRCTVAL
from maximo.invoice a 
JOIN maximo.matrectrans b ON b.invoicenum=a.invoicenum
JOIN maximo.matrectrans c ON c.receiptref=b.matrectransid
WHERE a.status='CANCEL';
;

-- DELETE DATA
DELETE FROM MAXIMO.MATRECTRANS WHERE MATRECTRANSID IN (SELECT DISTINCT MATRECTRANSID FROM "MIGRATION"."BAK_20251201_MATRECTRANS");

/**
 * DELETE RECEIPT (SERVRECTRANS) FOR CANCELLED INVOICE
 */
-- DROP TABLE IF EXISTS "MIGRATION"."BAK_20251201_SERVRECTRANS";

CREATE TABLE "MIGRATION"."BAK_20251201_SERVRECTRANS"  (
  "PONUM" VARCHAR(10 OCTETS) , 
  "ASSETNUM" VARCHAR(13 OCTETS) , 
  "LOCATION" VARCHAR(16 OCTETS) , 
  "CLAIMNUM" VARCHAR(8 OCTETS) , 
  "REJECTQTY" DECIMAL(15,2) , 
  "QUANTITY" DECIMAL(15,2) , 
  "UNITCOST" DECIMAL(13,5) , 
  "REJECTCOST" DECIMAL(15,2) , 
  "LINECOST" DECIMAL(13,5) NOT NULL , 
  "GLDEBITACCT" VARCHAR(110 OCTETS) , 
  "GLCREDITACCT" VARCHAR(110 OCTETS) , 
  "FINANCIALPERIOD" VARCHAR(6 OCTETS) , 
  "TRANSDATE" TIMESTAMP NOT NULL , 
  "ENTERDATE" TIMESTAMP NOT NULL , 
  "ENTERBY" VARCHAR(100 OCTETS) NOT NULL , 
  "DESCRIPTION" VARCHAR(200 OCTETS) , 
  "CURRENCYUNITCOST" DECIMAL(10,2) , 
  "CURRENCYLINECOST" DECIMAL(10,2) NOT NULL , 
  "CURRENCYCODE" VARCHAR(8 OCTETS) NOT NULL , 
  "POLINENUM" INTEGER , 
  "REMARK" VARCHAR(254 OCTETS) , 
  "SSPL1" VARCHAR(10 OCTETS) , 
  "ROLLUP" INTEGER NOT NULL , 
  "SSPL2" VARCHAR(10 OCTETS) , 
  "SSPL3" VARCHAR(10 OCTETS) , 
  "INVOICENUM" VARCHAR(15 OCTETS) , 
  "EXCHANGERATE" DECIMAL(14,7) , 
  "LOADEDCOST" DECIMAL(10,2) NOT NULL , 
  "TAX1CODE" VARCHAR(8 OCTETS) , 
  "TAX1" DECIMAL(10,2) , 
  "TAX2CODE" VARCHAR(8 OCTETS) , 
  "TAX2" DECIMAL(10,2) , 
  "TAX3CODE" VARCHAR(8 OCTETS) , 
  "TAX3" DECIMAL(10,2) , 
  "TAX4CODE" VARCHAR(8 OCTETS) , 
  "TAX4" DECIMAL(10,2) , 
  "TAX5CODE" VARCHAR(8 OCTETS) , 
  "TAX5" DECIMAL(10,2) , 
  "PRORATED" INTEGER NOT NULL , 
  "PRORATECOST" DECIMAL(10,2) , 
  "SOURCESYSID" VARCHAR(10 OCTETS) , 
  "EXCHANGERATE2" DECIMAL(14,7) , 
  "LINECOST2" DECIMAL(10,2) , 
  "MRNUM" VARCHAR(10 OCTETS) , 
  "MRLINENUM" INTEGER , 
  "SERVRECTRANSID" BIGINT NOT NULL , 
  "OWNERSYSID" VARCHAR(10 OCTETS) , 
  "EXTERNALREFID" VARCHAR(10 OCTETS) , 
  "SSPL4" VARCHAR(10 OCTETS) , 
  "SSPL5" VARCHAR(10 OCTETS) , 
  "SSPL6" VARCHAR(10 OCTETS) , 
  "SSPL7" VARCHAR(10 OCTETS) , 
  "SENDERSYSID" VARCHAR(50 OCTETS) , 
  "FINCNTRLID" VARCHAR(8 OCTETS) , 
  "ORGID" VARCHAR(8 OCTETS) NOT NULL , 
  "SITEID" VARCHAR(8 OCTETS) NOT NULL , 
  "ISSUETYPE" VARCHAR(20 OCTETS) NOT NULL , 
  "COSTINFO" INTEGER NOT NULL , 
  "BELONGSTO" BIGINT , 
  "REFWO" VARCHAR(10 OCTETS) , 
  "ENTEREDASTASK" INTEGER NOT NULL , 
  "LINETYPE" VARCHAR(15 OCTETS) NOT NULL , 
  "ITEMNUM" VARCHAR(30 OCTETS) , 
  "ITEMSETID" VARCHAR(8 OCTETS) , 
  "LANGCODE" VARCHAR(4 OCTETS) NOT NULL , 
  "STATUS" VARCHAR(12 OCTETS) , 
  "CHANGEBY" VARCHAR(100 OCTETS) , 
  "CHANGEDATE" DATE , 
  "INSPECTEDQTY" DECIMAL(15,2) , 
  "INSPECTIONCOST" DECIMAL(15,2) , 
  "ACCEPTEDCOST" DECIMAL(15,2) , 
  "COMMODITY" VARCHAR(10 OCTETS) , 
  "COMMODITYGROUP" VARCHAR(10 OCTETS) , 
  "HASLD" INTEGER NOT NULL , 
  "POSITEID" VARCHAR(8 OCTETS) , 
  "POREVISIONNUM" INTEGER , 
  "RECEIPTREF" BIGINT , 
  "QTYOVERRECEIVED" DECIMAL(15,2) , 
  "COSTOVERRECEIVED" DECIMAL(13,5) , 
  "FROMSITEID" VARCHAR(8 OCTETS) , 
  "ORGRCVEXTERNALREFID" VARCHAR(10 OCTETS) , 
  "PLUSTCONTRACTNUM" VARCHAR(10 OCTETS) , 
  "PLUSTPOS" VARCHAR(15 OCTETS) , 
  "PLUSTREASON" VARCHAR(10 OCTETS) , 
  "PLUSTWARRVALUE" DECIMAL(13,5) , 
  "PLUSTHASWARRANTY" VARCHAR(2 OCTETS) , 
  "PLUSTACCOMP" VARCHAR(10 OCTETS) , 
  "PLUSTCOMP" VARCHAR(15 OCTETS) , 
  "PLUSTREPORD" INTEGER NOT NULL , 
  "PLUSTFAILURE" VARCHAR(10 OCTETS) , 
  "PLUSTHASCUSTWARR" VARCHAR(2 OCTETS) , 
  "STE_DODATE" TIMESTAMP , 
  "STE_GRNREFTYPE" VARCHAR(50 OCTETS) , 
  "STE_CSWNCC" VARCHAR(16 OCTETS) , 
  "STE_CSWNSAPGL" VARCHAR(20 OCTETS) , 
  "STE_CSWNDNDATE" TIMESTAMP , 
  "STE_CSWNFWDR" VARCHAR(15 OCTETS) , 
  "STE_CSWNGRNDATE" TIMESTAMP , 
  "STE_CSWNGRNNUM" VARCHAR(10 OCTETS) , 
  "STE_CSWNINSPSTATUS" VARCHAR(20 OCTETS) , 
  "STE_CSWNINSPDATE" TIMESTAMP , 
  "STE_CSWNINSPREF" VARCHAR(10 OCTETS) , 
  "STE_CSWNINSPSTAT" INTEGER , 
  "STE_CSWNRCTSTATUS" INTEGER , 
  "STE_CSWNRECEIPTCHANGEDATE" TIMESTAMP , 
  "STE_CSWNRECEIPTFORWARDER" VARCHAR(15 OCTETS) , 
  "STE_CSWNRECEIPTTYPE" INTEGER , 
  "STE_MIGRATIONID" BIGINT , 
  "STE_MIGRATIONDATE" TIMESTAMP , 
  "STE_CSWNRECEIPTREMARK" VARCHAR(50 OCTETS) , 
  "ROWSTAMP" BIGINT NOT NULL , 
  "STE_MIGRATIONTS" INTEGER , 
  "PACKINGSLIPNUM" VARCHAR(50 OCTETS) , 
  "STE_DONO" VARCHAR(50 OCTETS) , 
  "STE_CSWNACPQTY" DECIMAL(15,2) , 
  "STE_CSWNRTNTOSUPL" DECIMAL(15,2) , 
  "STE_CSWNRCTQTY" DECIMAL(15,2) , 
  "STE_CSWNRCTVAL" DECIMAL(13,5) 
)   
ORGANIZE BY ROW;

INSERT INTO "MIGRATION"."BAK_20251201_SERVRECTRANS"
(
	PONUM, ASSETNUM, LOCATION, CLAIMNUM, REJECTQTY, QUANTITY, UNITCOST, REJECTCOST,
	LINECOST, GLDEBITACCT, GLCREDITACCT, FINANCIALPERIOD, TRANSDATE, ENTERDATE, ENTERBY,
	DESCRIPTION, CURRENCYUNITCOST, CURRENCYLINECOST, CURRENCYCODE, POLINENUM, REMARK,
	SSPL1, "ROLLUP", SSPL2, SSPL3, INVOICENUM, EXCHANGERATE, LOADEDCOST,
	TAX1CODE, TAX1, TAX2CODE, TAX2, TAX3CODE, TAX3, TAX4CODE, TAX4, TAX5CODE, TAX5, PRORATED, PRORATECOST,
	SOURCESYSID, EXCHANGERATE2, LINECOST2, MRNUM, MRLINENUM, SERVRECTRANSID, OWNERSYSID, EXTERNALREFID,
	SSPL4, SSPL5, SSPL6, SSPL7, SENDERSYSID, FINCNTRLID, ORGID, SITEID, ISSUETYPE, COSTINFO, BELONGSTO,
	REFWO, ENTEREDASTASK, LINETYPE, ITEMNUM, ITEMSETID, LANGCODE, STATUS, CHANGEBY, CHANGEDATE,
	INSPECTEDQTY, INSPECTIONCOST, ACCEPTEDCOST, COMMODITY, COMMODITYGROUP, HASLD,
	POSITEID, POREVISIONNUM, RECEIPTREF, QTYOVERRECEIVED, COSTOVERRECEIVED, FROMSITEID,
	ORGRCVEXTERNALREFID, PLUSTCONTRACTNUM, PLUSTPOS, PLUSTREASON, PLUSTWARRVALUE, PLUSTHASWARRANTY,
	PLUSTACCOMP, PLUSTCOMP, PLUSTREPORD, PLUSTFAILURE, PLUSTHASCUSTWARR,
	STE_DODATE, STE_GRNREFTYPE, STE_CSWNCC, STE_CSWNSAPGL, STE_CSWNDNDATE, STE_CSWNFWDR, STE_CSWNGRNDATE,
	STE_CSWNGRNNUM, STE_CSWNINSPSTATUS, STE_CSWNINSPDATE, STE_CSWNINSPREF, STE_CSWNINSPSTAT, STE_CSWNRCTSTATUS,
	STE_CSWNRECEIPTCHANGEDATE, STE_CSWNRECEIPTFORWARDER, STE_CSWNRECEIPTTYPE,
	STE_MIGRATIONID, STE_MIGRATIONDATE, STE_CSWNRECEIPTREMARK, ROWSTAMP, STE_MIGRATIONTS,
	PACKINGSLIPNUM, STE_DONO, STE_CSWNACPQTY, STE_CSWNRTNTOSUPL, STE_CSWNRCTQTY, STE_CSWNRCTVAL
)
SELECT 
	B.PONUM, B.ASSETNUM, B.LOCATION, B.CLAIMNUM, B.REJECTQTY, B.QUANTITY, B.UNITCOST, B.REJECTCOST,
	B.LINECOST, B.GLDEBITACCT, B.GLCREDITACCT, B.FINANCIALPERIOD, B.TRANSDATE, B.ENTERDATE, B.ENTERBY,
	B.DESCRIPTION, B.CURRENCYUNITCOST, B.CURRENCYLINECOST, B.CURRENCYCODE, B.POLINENUM, B.REMARK,
	B.SSPL1, B."ROLLUP", B.SSPL2, B.SSPL3, B.INVOICENUM, B.EXCHANGERATE, B.LOADEDCOST,
	B.TAX1CODE, B.TAX1, B.TAX2CODE, B.TAX2, B.TAX3CODE, B.TAX3, B.TAX4CODE, B.TAX4, B.TAX5CODE, B.TAX5, B.PRORATED, B.PRORATECOST,
	B.SOURCESYSID, B.EXCHANGERATE2, B.LINECOST2, B.MRNUM, B.MRLINENUM, B.SERVRECTRANSID, B.OWNERSYSID, B.EXTERNALREFID,
	B.SSPL4, B.SSPL5, B.SSPL6, B.SSPL7, B.SENDERSYSID, B.FINCNTRLID, B.ORGID, B.SITEID, B.ISSUETYPE, B.COSTINFO, B.BELONGSTO,
	B.REFWO, B.ENTEREDASTASK, B.LINETYPE, B.ITEMNUM, B.ITEMSETID, B.LANGCODE, B.STATUS, B.CHANGEBY, B.CHANGEDATE,
	B.INSPECTEDQTY, B.INSPECTIONCOST, B.ACCEPTEDCOST, B.COMMODITY, B.COMMODITYGROUP, B.HASLD,
	B.POSITEID, B.POREVISIONNUM, B.RECEIPTREF, B.QTYOVERRECEIVED, B.COSTOVERRECEIVED, B.FROMSITEID,
	B.ORGRCVEXTERNALREFID, B.PLUSTCONTRACTNUM, B.PLUSTPOS, B.PLUSTREASON, B.PLUSTWARRVALUE, B.PLUSTHASWARRANTY,
	B.PLUSTACCOMP, B.PLUSTCOMP, B.PLUSTREPORD, B.PLUSTFAILURE, B.PLUSTHASCUSTWARR,
	B.STE_DODATE, B.STE_GRNREFTYPE, B.STE_CSWNCC, B.STE_CSWNSAPGL, B.STE_CSWNDNDATE, B.STE_CSWNFWDR, B.STE_CSWNGRNDATE,
	B.STE_CSWNGRNNUM, B.STE_CSWNINSPSTATUS, B.STE_CSWNINSPDATE, B.STE_CSWNINSPREF, B.STE_CSWNINSPSTAT, B.STE_CSWNRCTSTATUS,
	B.STE_CSWNRECEIPTCHANGEDATE, B.STE_CSWNRECEIPTFORWARDER, B.STE_CSWNRECEIPTTYPE,
	B.STE_MIGRATIONID, B.STE_MIGRATIONDATE, B.STE_CSWNRECEIPTREMARK, B.ROWSTAMP, B.STE_MIGRATIONTS,
	B.PACKINGSLIPNUM, B.STE_DONO, B.STE_CSWNACPQTY, B.STE_CSWNRTNTOSUPL, B.STE_CSWNRCTQTY, B.STE_CSWNRCTVAL
from maximo.invoice a 
JOIN maximo.servrectrans b ON b.invoicenum=a.invoicenum
WHERE a.status='CANCEL';

-- DELETE DATA
DELETE FROM MAXIMO.SERVRECTRANS WHERE SERVRECTRANSID IN (SELECT DISTINCT SERVRECTRANSID FROM "MIGRATION"."BAK_20251201_SERVRECTRANS");

CALL MIGRATION.STE_FINISH_PATCH('20251201-01-INVOICESTATUS');