CALL MIGRATION.STE_UPDATE_SEQ('ALNDOMAINSEQ', 'ALNDOMAIN', 'ALNDOMAINID');

update maximo.alndomain m 
SET orgid=NULL, siteid=null
WHERE domainid IN ('SKILLLEVEL', 'STE_CSWNEQPFUNCTN', 'STE_ITEMCAT',
 'STE_ITEMGROUP', 'STE_STATION', 'STE_TUNNEL', 'STE_VIADUCT');