CALL MIGRATION.STE_START_PATCH('20250428-03-COSTCENTRE-MR');

-- BACKUP MR, INVUSELINE, MATUSETRANS
--DROP TABLE "MIGRATION"."BAK_20250428_MR_GLACCOUNT" IF EXISTS;
CREATE TABLE "MIGRATION"."BAK_20250428_MR_GLACCOUNT"  (
		  "MRID" BIGINT,	
		  "MRNUM" VARCHAR(10 OCTETS),
		  "STE_CSWNCC" VARCHAR(16 OCTETS),	
		  "GLDEBITACCT" VARCHAR(110 OCTETS)
	)   
;
 
INSERT INTO "MIGRATION"."BAK_20250428_MR_GLACCOUNT" (
	MRID, MRNUM, STE_CSWNCC, GLDEBITACCT
)
SELECT A.MRID, A.MRNUM, A.STE_CSWNCC, A.GLDEBITACCT
FROM MAXIMO.MR A
JOIN MIGRATION.SBST_COSTCENTER_INVALID_MAPPING X ON X.COSWIN_CC=A.STE_CSWNCC
JOIN MAXIMO.GLCOMPONENTS Y ON Y.GLORDER=1 AND Y.COMPVALUE=X.MAXIMO_CC
WHERE A.STE_MIGRATIONID IS NOT NULL
;

--DROP TABLE "MIGRATION"."BAK_20250428_INVUSELINE_GLDEBITACCT" IF EXISTS;
CREATE TABLE "MIGRATION"."BAK_20250428_INVUSELINE_GLDEBITACCT"  (
		  "INVUSELINEID" BIGINT,	
		  "MRNUM" VARCHAR(10 OCTETS),
		  "GLDEBITACCT" VARCHAR(110 OCTETS),	
		  "GLDEBITACCT_MR" VARCHAR(110 OCTETS)
	)   
;

INSERT INTO "MIGRATION"."BAK_20250428_INVUSELINE_GLDEBITACCT" (
	INVUSELINEID, MRNUM, GLDEBITACCT, GLDEBITACCT_MR
)
SELECT A.INVUSELINEID, A.MRNUM, A.GLDEBITACCT, B.GLDEBITACCT
FROM MAXIMO.INVUSELINE A
JOIN MAXIMO.MR B ON B.MRNUM=A.MRNUM
WHERE COALESCE(A.GLDEBITACCT,'')!=COALESCE(B.GLDEBITACCT,'')
	AND B.STE_MIGRATIONID IS NOT NULL
;

--DROP TABLE "MIGRATION"."BAK_20250428_MATUSETRANS_GLDEBITACCT" IF EXISTS;
CREATE TABLE "MIGRATION"."BAK_20250428_MATUSETRANS_GLDEBITACCT"  (
		  "MATUSETRANSID" BIGINT,	
		  "MRNUM" VARCHAR(10 OCTETS),
		  "GLDEBITACCT" VARCHAR(110 OCTETS),	
		  "GLDEBITACCT_MR" VARCHAR(110 OCTETS)
	)   
;

INSERT INTO "MIGRATION"."BAK_20250428_MATUSETRANS_GLDEBITACCT" (
	MATUSETRANSID, MRNUM, GLDEBITACCT, GLDEBITACCT_MR
)
SELECT A.MATUSETRANSID, A.MRNUM, A.GLDEBITACCT, B.GLDEBITACCT
FROM MAXIMO.MATUSETRANS A
JOIN MAXIMO.MR B ON B.MRNUM=A.MRNUM
WHERE COALESCE(A.GLDEBITACCT,'')!=COALESCE(B.GLDEBITACCT,'')
	AND B.STE_MIGRATIONID IS NOT NULL
;

-- MR (61.878)
MERGE INTO MAXIMO.MR A
USING (
	SELECT A.MRID, A.MRNUM, A.STE_CSWNCC, A.GLDEBITACCT
		, X.MAXIMO_CC, Y.STE_COSTCENTREDEPT
		, CONCAT(Y.STE_COSTCENTREDEPT, CONCAT('-', X.MAXIMO_CC)) AS NEW_GLACCOUNT
	FROM MAXIMO.MR A
	JOIN MIGRATION.SBST_COSTCENTER_INVALID_MAPPING X ON X.COSWIN_CC=A.STE_CSWNCC
	JOIN MAXIMO.GLCOMPONENTS Y ON Y.GLORDER=1 AND Y.COMPVALUE=X.MAXIMO_CC
	WHERE A.STE_MIGRATIONID IS NOT NULL
) B ON B.MRID=A.MRID
WHEN MATCHED THEN
UPDATE SET
	GLDEBITACCT=B.NEW_GLACCOUNT
;

-- NEW DATA: 22
INSERT INTO MAXIMO.CHARTOFACCOUNTS (
	GLACCOUNT, GLCOMP01, GLCOMP02, GLCOMP03, ACCOUNTNAME, ORGID, ACTIVE
	, LANGCODE, HASLD, ACTIVEDATE
	, STE_MIGRATIONID, STE_MIGRATIONDATE, STE_MIGRATIONSOURCE
	, CHARTOFACCOUNTSID
)
SELECT A.GLDEBITACCT AS GLACCOUNT
	, CASE WHEN A.GLDEBITACCT IS NULL THEN NULL
		   ELSE SUBSTR(A.GLDEBITACCT, 1, LOCATE('-', A.GLDEBITACCT)-1)
	  END AS Department
	, CASE WHEN A.GLDEBITACCT IS NULL THEN NULL
	       WHEN length(A.GLDEBITACCT) - length(replace(A.GLDEBITACCT,'-','')) >= 2 THEN
				SUBSTR(A.GLDEBITACCT, LOCATE('-', A.GLDEBITACCT)+1, LOCATE('-', A.GLDEBITACCT, LOCATE('-', A.GLDEBITACCT)+1)-LOCATE('-', A.GLDEBITACCT)-1)
		   ELSE SUBSTR(A.GLDEBITACCT, LOCATE('-', A.GLDEBITACCT)+1)
	  END AS Costcentre
	, CASE WHEN A.GLDEBITACCT IS NULL THEN NULL
	       WHEN length(A.GLDEBITACCT) - length(replace(A.GLDEBITACCT,'-','')) < 2 THEN NULL
		   ELSE SUBSTR(A.GLDEBITACCT, LOCATE('-', A.GLDEBITACCT, LOCATE('-', A.GLDEBITACCT)+1)+1)
	  END AS SAPGL
	, 'CostCenter' AS ACCOUNTNAME
	, 'SBST' AS ORGID
	, 1 AS ACTIVE
	, 'EN' AS LANGCODE
	, 0 AS HASLD
	, '2000-01-01' AS ACTIVEDATE
	, A.STE_MIGRATIONID
	, ADD_HOURS(CURRENT_TIMESTAMP, 8) AS STE_MIGRATIONDATE
	, 'MR' AS STE_MIGRATIONSOURCE
	, X.MAXID + ROW_NUMBER() OVER (ORDER BY A.STE_MIGRATIONID) AS CHARTOFACCOUNTSID
FROM (
	SELECT GLDEBITACCT, MIN(STE_MIGRATIONID) AS STE_MIGRATIONID FROM MAXIMO.MR 
	GROUP BY GLDEBITACCT
) A
LEFT JOIN MAXIMO.CHARTOFACCOUNTS B ON B.GLACCOUNT=A.GLDEBITACCT
JOIN (
	SELECT MAX(CHARTOFACCOUNTSID) AS MAXID FROM MAXIMO.CHARTOFACCOUNTS
) X ON 1=1
WHERE A.GLDEBITACCT IS NOT NULL AND B.CHARTOFACCOUNTSID IS NULL
;

-- MRLINE (130.343)
MERGE INTO MAXIMO.MRLINE A
USING (
	SELECT A.MRLINEID, A.MRNUM, A.GLDEBITACCT, B.GLDEBITACCT AS NEW_GLACCOUNT
	FROM MAXIMO.MRLINE A
	JOIN MAXIMO.MR B ON B.MRNUM=A.MRNUM
	WHERE COALESCE(A.GLDEBITACCT,'')!=COALESCE(B.GLDEBITACCT,'')
		AND B.STE_MIGRATIONID IS NOT NULL
) B ON B.MRLINEID=A.MRLINEID
WHEN MATCHED THEN
UPDATE SET
	GLDEBITACCT=B.NEW_GLACCOUNT
;

-- MRCOST (130.343)
MERGE INTO MAXIMO.MRCOST A
USING (
	SELECT A.MRCOSTID, A.MRNUM, A.GLDEBITACCT, B.GLDEBITACCT AS NEW_GLACCOUNT
	FROM MAXIMO.MRCOST A
	JOIN MAXIMO.MR B ON B.MRNUM=A.MRNUM
	WHERE COALESCE(A.GLDEBITACCT,'')!=COALESCE(B.GLDEBITACCT,'')
		AND B.STE_MIGRATIONID IS NOT NULL
) B ON B.MRCOSTID=A.MRCOSTID
WHEN MATCHED THEN
UPDATE SET
	GLDEBITACCT=B.NEW_GLACCOUNT
;

-- INVRESERVE (9.509)
MERGE INTO MAXIMO.INVRESERVE A
USING (
	SELECT A.INVRESERVEID, A.MRNUM, A.GLACCOUNT, B.GLDEBITACCT AS NEW_GLACCOUNT
	FROM MAXIMO.INVRESERVE A
	JOIN MAXIMO.MR B ON B.MRNUM=A.MRNUM
	WHERE COALESCE(A.GLACCOUNT,'')!=COALESCE(B.GLDEBITACCT,'')
		AND B.STE_MIGRATIONID IS NOT NULL
) B ON B.INVRESERVEID=A.INVRESERVEID
WHEN MATCHED THEN
UPDATE SET
	GLACCOUNT=B.NEW_GLACCOUNT
;

-- INVUSELINE (121.325)
MERGE INTO MAXIMO.INVUSELINE A
USING (
	SELECT A.INVUSELINEID, A.MRNUM, A.GLDEBITACCT, B.GLDEBITACCT AS NEW_GLACCOUNT
	FROM MAXIMO.INVUSELINE A
	JOIN MAXIMO.MR B ON B.MRNUM=A.MRNUM
	WHERE COALESCE(A.GLDEBITACCT,'')!=COALESCE(B.GLDEBITACCT,'')
		AND B.STE_MIGRATIONID IS NOT NULL 
		-- AND A.STE_MIGRATIONID IS NOT NULL
) B ON B.INVUSELINEID=A.INVUSELINEID
WHEN MATCHED THEN
UPDATE SET
	GLDEBITACCT=B.NEW_GLACCOUNT
;

-- MATUSETRANS (121.393)
MERGE INTO MAXIMO.MATUSETRANS A
USING (
	SELECT A.MATUSETRANSID, A.MRNUM, A.GLDEBITACCT, B.GLDEBITACCT AS NEW_GLACCOUNT
	FROM MAXIMO.MATUSETRANS A
	JOIN MAXIMO.MR B ON B.MRNUM=A.MRNUM
	WHERE COALESCE(A.GLDEBITACCT,'')!=COALESCE(B.GLDEBITACCT,'')
		AND B.STE_MIGRATIONID IS NOT NULL
		-- AND A.STE_MIGRATIONID IS NOT NULL
) B ON B.MATUSETRANSID=A.MATUSETRANSID
WHEN MATCHED THEN
UPDATE SET
	GLDEBITACCT=B.NEW_GLACCOUNT
;

-- MATRECTRANS (TRANSFER): NO NEED! NO CHANGE IN EXISTING RECORDS!
--SELECT A.MATRECTRANSID, B.MRNUM, A.GLDEBITACCT, B.GLDEBITACCT
--FROM MAXIMO.MATRECTRANS A
--JOIN MAXIMO.INVUSELINE B ON B.INVUSELINEID=A.INVUSELINEID
----JOIN MAXIMO.MR C ON C.MRNUM=B.MRNUM
--WHERE A.STE_MIGRATIONSOURCE='DEM-TRANSFER' AND A.GLDEBITACCT!=B.GLDEBITACCT
--;

-- UPDATE COA MAXID
CALL MIGRATION.STE_UPDATE_SEQ('CHARTOFACCOUNTSSEQ', 'CHARTOFACCOUNTS', 'CHARTOFACCOUNTSID');

CALL MIGRATION.STE_FINISH_PATCH('20250428-03-COSTCENTRE-MR');