CALL MIGRATION.STE_START_PATCH('20250408-04-INVOICE-BASETOTALCOST');

-- UPDATE EXCHANGE RATE FROM RECEIPT (MATRECTRANS)
MERGE INTO MAXIMO.INVOICE A
USING (
	SELECT C.POID, A.PONUM, A.ITEMNUM, A.UNITCOST, A.ACTUALCOST, A.INVOICENUM, B.UNITCOST, C.CURRENCYCODE
		, (A.UNITCOST/B.UNITCOST) AS EXCHANGERATE
		, A.TRANSDATE
		, ROW_NUMBER() OVER (PARTITION BY A.INVOICENUM ORDER BY A.MATRECTRANSID ASC) RN
	FROM MAXIMO.MATRECTRANS A
	JOIN MAXIMO.POLINE B ON B.PONUM=A.PONUM AND B.ITEMNUM=A.ITEMNUM
	JOIN MAXIMO.PO C ON C.PONUM=A.PONUM
	JOIN MAXIMO.INVOICE D ON D.INVOICENUM=A.INVOICENUM
	WHERE C.CURRENCYCODE!='SGD' 
		AND A.UNITCOST>0
		AND D.STE_MIGRATIONID IS NOT NULL
		--AND D.INVOICEID IS NULL AND A.INVOICENUM IS NOT NULL
	ORDER BY A.INVOICENUM
) B ON B.RN=1 AND B.INVOICENUM=A.INVOICENUM
WHEN MATCHED THEN
UPDATE SET
	EXCHANGERATE=B.EXCHANGERATE,
	EXCHANGEDATE=B.TRANSDATE
;

-- UPDATE EXCHANGE RATE FROM MONTHLY AVG RATE
MERGE INTO MAXIMO.INVOICE A
USING (
	SELECT A.INVOICENUM, A.CURRENCYCODE, A.EXCHANGERATE, B.RATE
		, A.INVOICEDATE AS EXCHANGEDATE
	FROM MAXIMO.INVOICE A
	JOIN MIGRATION.SBST_EXCHANGE_RATE B ON B.CURRENCY=A.CURRENCYCODE 
		AND B.YEAR=YEAR(A.INVOICEDATE) AND B.MONTH=MONTH(A.INVOICEDATE)
	WHERE A.CURRENCYCODE!='SGD'
		AND A.EXCHANGERATE IS NULL
		AND A.STE_MIGRATIONID IS NOT NULL
) B ON B.INVOICENUM=A.INVOICENUM
WHEN MATCHED THEN
UPDATE SET
	EXCHANGERATE=B.RATE,
	EXCHANGEDATE=B.EXCHANGEDATE
;

-- UPDATE EXCHANGE RATE FOR SGD
UPDATE MAXIMO.INVOICE
SET EXCHANGERATE=1, EXCHANGEDATE=INVOICEDATE
WHERE CURRENCYCODE='SGD'
;

-- UPDATE BASETOTALCOST
UPDATE MAXIMO.INVOICE
SET BASETOTALCOST=TOTALCOST * EXCHANGERATE
WHERE STE_MIGRATIONID IS NOT NULL;

CALL MIGRATION.STE_FINISH_PATCH('20250408-04-INVOICE-BASETOTALCOST');