MERGE INTO MAXIMO.LOCATIONS A
USING (
	SELECT B.LOCATIONSID, B.STE_LOCCODE, A.DESCRIPTION, B.DESCRIPTION AS OLDDESCRIPTION
	FROM MIGRATION.SBST_LOCATION_REF_TRAIN_CAR A
	JOIN MAXIMO.LOCATIONS B ON B.STE_LOCCODE=A.CODE
	WHERE B.DESCRIPTION IS NULL
) B ON B.LOCATIONSID=A.LOCATIONSID
WHEN MATCHED THEN
UPDATE SET
	DESCRIPTION=B.DESCRIPTION
;