CALL MIGRATION.STE_START_PATCH('20250519-01-MATUSETRANS-INVUSELINE');

-- MAXIMO.MATUSETRANS definition
CREATE TABLE "MIGRATION"."BAK_20250519_MATUSETRANS"  (
	  "ITEMNUM" VARCHAR(30 OCTETS) , 
	  "STORELOC" VARCHAR(16 OCTETS) , 
	  "TRANSDATE" TIMESTAMP NOT NULL , 
	  "ACTUALDATE" TIMESTAMP NOT NULL , 
	  "QUANTITY" DECIMAL(15,2) NOT NULL , 
	  "CURBAL" DECIMAL(15,2) NOT NULL , 
	  "PHYSCNT" DECIMAL(15,2) NOT NULL , 
	  "UNITCOST" DECIMAL(13,5) NOT NULL , 
	  "ACTUALCOST" DECIMAL(13,5) NOT NULL , 
	  "PONUM" VARCHAR(10 OCTETS) , 
	  "CONVERSION" DECIMAL(18,5) , 
	  "ASSETNUM" VARCHAR(13 OCTETS) , 
	  "ENTERBY" VARCHAR(100 OCTETS) NOT NULL , 
	  "IT1" VARCHAR(10 OCTETS) , 
	  "IT2" VARCHAR(10 OCTETS) , 
	  "IT3" VARCHAR(10 OCTETS) , 
	  "IT4" DECIMAL(15,2) , 
	  "IT5" VARCHAR(10 OCTETS) , 
	  "MEMO" VARCHAR(254 OCTETS) , 
	  "OUTSIDE" INTEGER NOT NULL , 
	  "ISSUETO" VARCHAR(100 OCTETS) , 
	  "PACKINGSLIPNUM" VARCHAR(50 OCTETS) , 
	  "POLINENUM" INTEGER , 
	  "ROLLUP" INTEGER NOT NULL , 
	  "ITIN1" VARCHAR(10 OCTETS) , 
	  "ITIN2" VARCHAR(10 OCTETS) , 
	  "ITIN3" VARCHAR(10 OCTETS) , 
	  "BINNUM" VARCHAR(16 OCTETS) , 
	  "LOTNUM" VARCHAR(12 OCTETS) , 
	  "ISSUETYPE" VARCHAR(20 OCTETS) NOT NULL , 
	  "GLDEBITACCT" VARCHAR(110 OCTETS) , 
	  "GLCREDITACCT" VARCHAR(110 OCTETS) , 
	  "LINECOST" DECIMAL(13,5) NOT NULL , 
	  "FINANCIALPERIOD" VARCHAR(6 OCTETS) , 
	  "CURRENCYCODE" VARCHAR(8 OCTETS) NOT NULL , 
	  "CURRENCYUNITCOST" DECIMAL(10,2) , 
	  "ROTASSETNUM" VARCHAR(13 OCTETS) , 
	  "CURRENCYLINECOST" DECIMAL(10,2) , 
	  "LOCATION" VARCHAR(16 OCTETS) , 
	  "DESCRIPTION" VARCHAR(200 OCTETS) , 
	  "EXCHANGERATE" DECIMAL(14,7) , 
	  "SPAREPARTADDED" INTEGER NOT NULL , 
	  "QTYREQUESTED" DECIMAL(15,2) , 
	  "EXCHANGERATE2" DECIMAL(14,7) , 
	  "LINECOST2" DECIMAL(10,2) , 
	  "MRNUM" VARCHAR(10 OCTETS) , 
	  "MRLINENUM" INTEGER , 
	  "MATUSETRANSID" BIGINT NOT NULL , 
	  "MATRECTRANSID" BIGINT , 
	  "IT6" VARCHAR(10 OCTETS) , 
	  "IT7" VARCHAR(10 OCTETS) , 
	  "IT8" VARCHAR(10 OCTETS) , 
	  "IT9" VARCHAR(10 OCTETS) , 
	  "IT10" VARCHAR(10 OCTETS) , 
	  "ITIN4" VARCHAR(10 OCTETS) , 
	  "ITIN5" VARCHAR(10 OCTETS) , 
	  "ITIN6" VARCHAR(10 OCTETS) , 
	  "ITIN7" VARCHAR(10 OCTETS) , 
	  "SOURCESYSID" VARCHAR(10 OCTETS) , 
	  "OWNERSYSID" VARCHAR(10 OCTETS) , 
	  "EXTERNALREFID" VARCHAR(10 OCTETS) , 
	  "SENDERSYSID" VARCHAR(50 OCTETS) , 
	  "FINCNTRLID" VARCHAR(8 OCTETS) , 
	  "ISSUEID" BIGINT , 
	  "QTYRETURNED" DECIMAL(15,2) , 
	  "ORGID" VARCHAR(8 OCTETS) NOT NULL , 
	  "SITEID" VARCHAR(8 OCTETS) NOT NULL , 
	  "REFWO" VARCHAR(10 OCTETS) , 
	  "ENTEREDASTASK" INTEGER NOT NULL , 
	  "LINETYPE" VARCHAR(15 OCTETS) NOT NULL , 
	  "ITEMSETID" VARCHAR(8 OCTETS) , 
	  "CONDITIONCODE" VARCHAR(30 OCTETS) , 
	  "CONDRATE" INTEGER , 
	  "COMMODITYGROUP" VARCHAR(10 OCTETS) , 
	  "COMMODITY" VARCHAR(10 OCTETS) , 
	  "TOSITEID" VARCHAR(8 OCTETS) NOT NULL , 
	  "LANGCODE" VARCHAR(4 OCTETS) NOT NULL , 
	  "HASLD" INTEGER NOT NULL , 
	  "POREVISIONNUM" INTEGER , 
	  "INVUSELINEID" BIGINT , 
	  "INVUSEID" BIGINT , 
	  "CONSIGNMENT" INTEGER NOT NULL , 
	  "CONSINVOICENUM" VARCHAR(15 OCTETS) , 
	  "CONSVENDOR" VARCHAR(20 OCTETS) , 
	  "ISSUEUNIT" VARCHAR(16 OCTETS) , 
	  "WPITEMID" BIGINT NOT NULL , 
	  "INVPICKLISTID" BIGINT , 
	  "INVUSELINESPLITID" BIGINT , 
	  "ANYWHEREREFID" BIGINT , 
	  "PLUSTPOS" VARCHAR(15 OCTETS) , 
	  "PLUSTACCOMP" VARCHAR(10 OCTETS) , 
	  "PLUSTFAILURE" VARCHAR(10 OCTETS) , 
	  "PLUSTREASON" VARCHAR(10 OCTETS) , 
	  "PLUSTHASWARRANTY" VARCHAR(2 OCTETS) , 
	  "PLUSTCOMP" VARCHAR(15 OCTETS) , 
	  "PLUSTQUALMET" VARCHAR(24 OCTETS) , 
	  "PLUSTHASCUSTWARR" VARCHAR(2 OCTETS) , 
	  "STE_DATEUSED" DATE , 
	  "STE_MIGRATIONDATE" TIMESTAMP , 
	  "STE_MIGRATIONID" BIGINT , 
	  "STE_MIGRATIONREFWO" VARCHAR(200 OCTETS) , 
	  "ROWSTAMP" BIGINT NOT NULL , 
	  "STE_ISSUENUM" VARCHAR(8 OCTETS) , 
	  "STE_MIGRATIONTS" INTEGER,
	  RN INTEGER
)   
ORGANIZE BY ROW;

INSERT INTO "MIGRATION"."BAK_20250519_MATUSETRANS" (
	ITEMNUM, STORELOC, TRANSDATE, ACTUALDATE, QUANTITY, CURBAL, PHYSCNT, UNITCOST, ACTUALCOST, 
	PONUM, CONVERSION, ASSETNUM, ENTERBY, IT1, IT2, IT3, IT4, IT5, MEMO, OUTSIDE, ISSUETO, 
	PACKINGSLIPNUM, POLINENUM, "ROLLUP", ITIN1, ITIN2, ITIN3, BINNUM, LOTNUM, ISSUETYPE, 
	GLDEBITACCT, GLCREDITACCT, LINECOST, FINANCIALPERIOD, CURRENCYCODE, CURRENCYUNITCOST, ROTASSETNUM, 
	CURRENCYLINECOST, LOCATION, DESCRIPTION, EXCHANGERATE, SPAREPARTADDED, QTYREQUESTED, 
	EXCHANGERATE2, LINECOST2, MRNUM, MRLINENUM, MATUSETRANSID, MATRECTRANSID, 
	IT6, IT7, IT8, IT9, IT10, ITIN4, ITIN5, ITIN6, ITIN7, SOURCESYSID, OWNERSYSID, EXTERNALREFID, SENDERSYSID, 
	FINCNTRLID, ISSUEID, QTYRETURNED, ORGID, SITEID, REFWO, ENTEREDASTASK, LINETYPE, ITEMSETID, 
	CONDITIONCODE, CONDRATE, COMMODITYGROUP, COMMODITY, TOSITEID, LANGCODE, HASLD, 
	POREVISIONNUM, INVUSELINEID, INVUSEID, CONSIGNMENT, CONSINVOICENUM, CONSVENDOR, ISSUEUNIT, 
	WPITEMID, INVPICKLISTID, INVUSELINESPLITID, ANYWHEREREFID, 
	PLUSTPOS, PLUSTACCOMP, PLUSTFAILURE, PLUSTREASON, PLUSTHASWARRANTY, PLUSTCOMP, PLUSTQUALMET, PLUSTHASCUSTWARR, 
	STE_DATEUSED, STE_MIGRATIONDATE, STE_MIGRATIONID, STE_MIGRATIONREFWO, ROWSTAMP, STE_ISSUENUM, STE_MIGRATIONTS,
	RN
)
SELECT 
	ITEMNUM, STORELOC, TRANSDATE, ACTUALDATE, QUANTITY, CURBAL, PHYSCNT, UNITCOST, ACTUALCOST, 
	PONUM, CONVERSION, ASSETNUM, ENTERBY, IT1, IT2, IT3, IT4, IT5, MEMO, OUTSIDE, ISSUETO, 
	PACKINGSLIPNUM, POLINENUM, "ROLLUP", ITIN1, ITIN2, ITIN3, BINNUM, LOTNUM, ISSUETYPE, 
	GLDEBITACCT, GLCREDITACCT, LINECOST, FINANCIALPERIOD, CURRENCYCODE, CURRENCYUNITCOST, ROTASSETNUM, 
	CURRENCYLINECOST, LOCATION, DESCRIPTION, EXCHANGERATE, SPAREPARTADDED, QTYREQUESTED, 
	EXCHANGERATE2, LINECOST2, MRNUM, MRLINENUM, MATUSETRANSID, MATRECTRANSID, 
	IT6, IT7, IT8, IT9, IT10, ITIN4, ITIN5, ITIN6, ITIN7, SOURCESYSID, OWNERSYSID, EXTERNALREFID, SENDERSYSID, 
	FINCNTRLID, ISSUEID, QTYRETURNED, ORGID, SITEID, REFWO, ENTEREDASTASK, LINETYPE, ITEMSETID, 
	CONDITIONCODE, CONDRATE, COMMODITYGROUP, COMMODITY, TOSITEID, LANGCODE, HASLD, 
	POREVISIONNUM, INVUSELINEID, INVUSEID, CONSIGNMENT, CONSINVOICENUM, CONSVENDOR, ISSUEUNIT, 
	WPITEMID, INVPICKLISTID, INVUSELINESPLITID, ANYWHEREREFID, 
	PLUSTPOS, PLUSTACCOMP, PLUSTFAILURE, PLUSTREASON, PLUSTHASWARRANTY, PLUSTCOMP, PLUSTQUALMET, PLUSTHASCUSTWARR, 
	STE_DATEUSED, STE_MIGRATIONDATE, STE_MIGRATIONID, STE_MIGRATIONREFWO, ROWSTAMP, STE_ISSUENUM, STE_MIGRATIONTS,
	RN
FROM (
	SELECT A.*
		, ROW_NUMBER() OVER (PARTITION BY A.STE_MIGRATIONID ORDER BY A.MATUSETRANSID) RN
	FROM MAXIMO.MATUSETRANS A
	WHERE A.STE_MIGRATIONID IS NOT NULL
) A
WHERE A.RN>1
;

DELETE FROM MAXIMO.MATUSETRANS WHERE MATUSETRANSID IN (SELECT MATUSETRANSID FROM "MIGRATION"."BAK_20250519_MATUSETRANS");

-- update invuseline.issueid
MERGE INTO maximo.invuseline a
USING (
	SELECT b.invuselineid, b.issueid, c.matusetransid 
		, row_number() OVER (PARTITION BY a.matusetransid ORDER BY c.matusetransid desc) rn
	FROM MAXIMO.MATUSETRANS a
	JOIN maximo.invuseline b ON b.invuselineid=a.invuselineid
	JOIN maximo.matusetrans c ON c.mrnum=a.mrnum AND c.itemnum=a.itemnum AND c.ste_migrationid<a.ste_migrationid AND c.qtyreturned=a.quantity
	WHERE a.ISSUETYPE='RETURN'
		AND a.ste_migrationid IS NOT NULL AND b.issueid IS null
) b ON b.rn=1 AND b.invuselineid=a.invuselineid
WHEN MATCHED THEN 
UPDATE SET 
	issueid=b.matusetransid
;

-- special case
MERGE INTO maximo.invuseline a
USING (
	SELECT b.invuselineid, b.issueid, c.matusetransid 
		, row_number() OVER (PARTITION BY a.matusetransid ORDER BY c.matusetransid desc) rn
	FROM MAXIMO.MATUSETRANS a
	JOIN maximo.invuseline b ON b.invuselineid=a.invuselineid
	JOIN maximo.matusetrans c ON c.mrnum=a.mrnum AND c.itemnum=a.itemnum AND c.qtyreturned=a.quantity
		AND ((a.ste_migrationid=319241 AND c.ste_migrationid=316494) OR (a.ste_migrationid=319242 AND c.ste_migrationid=316622))
	WHERE a.ISSUETYPE='RETURN'
		AND a.ste_migrationid IN (319241, 319242) 
) b ON b.rn=1 AND b.invuselineid=a.invuselineid
WHEN MATCHED THEN 
UPDATE SET 
	issueid=b.matusetransid
;

CALL MIGRATION.STE_FINISH_PATCH('20250519-01-MATUSETRANS-INVUSELINE');