CALL MIGRATION.STE_START_PATCH('20250917-FAILUREREPORT-ALTFAILURECODE');

-- NEED TO BRING TABLE STE_PATCH_FAILUREREPORT FROM ON-PREM
-- NEED TO BRING TABLE STE_PATCH_ALTFAILURECODE FROM ON-PREM

DELETE FROM MAXIMO.FAILUREREPORT WHERE STE_MIGRATIONID IS NOT NULL;
INSERT INTO MAXIMO.FAILUREREPORT
(
	WONUM, FAILURECODE, ASSETNUM, LINENUM, "TYPE", ORGID, SITEID, TICKETID, TICKETCLASS, ANYWHEREREFID, 
	FAILUREREPORTID, 
	STE_MIGRATIONTYPE, STE_MIGRATIONID, STE_MIGRATIONWOID, STE_MIGRATIONEQLEVL, STE_MIGRATIONEQCD, STE_MIGRATIONDATE, STE_MIGRATIONTS
)
SELECT
	A.WONUM, A.FAILURECODE, A.ASSETNUM, A.LINENUM, A."TYPE", A.ORGID, A.SITEID, A.TICKETID, A.TICKETCLASS, A.ANYWHEREREFID, 
	B.MAXID + ROW_NUMBER() OVER (ORDER BY A.FAILUREREPORTID) AS FAILUREREPORTID, 
	A.STE_MIGRATIONTYPE, A.STE_MIGRATIONID, A.STE_MIGRATIONWOID, A.STE_MIGRATIONEQLEVL, A.STE_MIGRATIONEQCD, A.STE_MIGRATIONDATE, A.STE_MIGRATIONTS
FROM MIGRATION.STE_PATCH_FAILUREREPORT A
JOIN (
	SELECT COALESCE(MAX(FAILUREREPORTID),0) AS MAXID FROM MAXIMO.FAILUREREPORT
) B ON 1=1
ORDER BY A.FAILUREREPORTID
;

CALL MIGRATION.STE_UPDATE_SEQ('FAILUREREPORTSEQ', 'FAILUREREPORT', 'FAILUREREPORTID');

DELETE FROM MAXIMO.STE_ALTFAILURECODE WHERE STE_MIGRATIONID IS NOT NULL;
INSERT INTO MAXIMO.STE_ALTFAILURECODE
(
	STE_ALTFAILURECODEID, 
	STE_CAUSECODE, STE_PROBLEMCODE, STE_REMEDYCODE, WONUM, FAILURECODE, STE_MIGRATIONID, STE_MIGRATIONDATE
)
SELECT
	B.MAXID + ROW_NUMBER() OVER (ORDER BY A.STE_ALTFAILURECODEID) AS STE_ALTFAILURECODEID, 
	STE_CAUSECODE, STE_PROBLEMCODE, STE_REMEDYCODE, WONUM, FAILURECODE, STE_MIGRATIONID, STE_MIGRATIONDATE
FROM MIGRATION.STE_PATCH_ALTFAILURECODE A
JOIN (
	SELECT COALESCE(MAX(STE_ALTFAILURECODEID),0) AS MAXID FROM MAXIMO.STE_ALTFAILURECODE
) B ON 1=1
ORDER BY A.STE_ALTFAILURECODEID
;

CALL MIGRATION.STE_UPDATE_SEQ('STE_ALTFAILURECODEIDSEQ', 'STE_ALTFAILURECODE', 'STE_ALTFAILURECODEID');

CALL MIGRATION.STE_FINISH_PATCH('20250917-FAILUREREPORT-ALTFAILURECODE');