CALL MIGRATION.STE_START_PATCH('20250808-IMAGE-CATALOG');

-- ADD CUSTOM COLUMNS TO DOCINFO, DOCLINKS
--ALTER TABLE MAXIMO.DOCINFO ADD "STE_MIGRATIONID" BIGINT;
--ALTER TABLE MAXIMO.DOCINFO ADD "STE_MIGRATIONDATE" TIMESTAMP;
--ALTER TABLE MAXIMO.DOCLINKS ADD "STE_MIGRATIONID" BIGINT;
--ALTER TABLE MAXIMO.DOCLINKS ADD "STE_MIGRATIONDATE" TIMESTAMP;

--
-- BRING MIGRATION.PATCH_20250808_ITEM_CATALOG FROM ON-PREM
--

-- DELETE OLD MIGRATED DATA
DELETE FROM MAXIMO.DOCINFO WHERE STE_MIGRATIONID IS NOT NULL;
DELETE FROM MAXIMO.DOCLINKS WHERE STE_MIGRATIONID IS NOT NULL;

-- ADD ATTACHMENTS
-- select * from MAXIMO.DOCINFO
INSERT INTO MAXIMO.DOCINFO
(
	DOCUMENT, DESCRIPTION, DOCTYPE, CREATEDATE, CREATEBY, CHANGEDATE, CHANGEBY, 
	URLTYPE, URLNAME, PRINTTHRULINKDFLT, USEDEFAULTFILEPATH, SHOW, LANGCODE, HASLD, 
	DOCINFOID, CONTENTUID, 
	STE_MIGRATIONID, STE_MIGRATIONDATE
)
SELECT 
	'IMAGE' AS DOCUMENT, A.PATH AS DESCRIPTION, 'Images' AS DOCTYPE
	, ADD_HOURS(CURRENT_TIMESTAMP,8) AS CREATEDATE, 'MAXADMIN' AS CREATEBY
	, ADD_HOURS(CURRENT_TIMESTAMP,8) AS CHANGEDATE, 'MAXADMIN' AS CHANGEBY
	, 'FILE' AS URLTYPE, CONCAT('/DOCLINKS/IMAGES/',"PATH") AS URLNAME
	, 0 AS PRINTTHRULINKDFLT, 0 AS USEDEFAULTFILEPATH, 0 AS SHOW, 'EN' AS LANGCODE, 0 AS HASLD
	, B.MAX_ID + ROW_NUMBER() OVER (ORDER BY ID) AS DOCINFOID
	, B.MAX_ID + ROW_NUMBER() OVER (ORDER BY ID) AS CONTENTUID
	, ID AS STE_MIGRATIONID, ADD_HOURS(CURRENT_TIMESTAMP,8) AS STE_MIGRATIONDATE
FROM MIGRATION.PATCH_20250808_ITEM_CATALOG A
LEFT JOIN (
	SELECT COALESCE(MAX(DOCINFOID),0) AS MAX_ID FROM MAXIMO.DOCINFO
) B ON 1=1
WHERE COALESCE(A.ITEMID,0)!=0 AND A.RN=1;

INSERT INTO MAXIMO.DOCLINKS
(
	DOCUMENT, OWNERTABLE, OWNERID, DOCTYPE, GETLATESTVERSION, 
	CREATEDATE, CREATEBY, CHANGEDATE, CHANGEBY, 
	PRINTTHRULINK, COPYLINKTOWO, DOCINFOID,  
	DOCLINKSID, 
	STE_MIGRATIONID, STE_MIGRATIONDATE
)
SELECT 
	'IMAGE' AS DOCUMENT, 'ITEM' AS OWNERTABLE, A.ITEMID AS OWNERID, 'Images' AS DOCTYPE, 1 AS GETLATESTVERSION
	, ADD_HOURS(CURRENT_TIMESTAMP,8) AS CREATEDATE, 'MAXADMIN' AS CREATEBY
	, ADD_HOURS(CURRENT_TIMESTAMP,8) AS CHANGEDATE, 'MAXADMIN' AS CHANGEBY
	, 0 AS PRINTTHRULINK, 0 AS COPYLINKTOWO, C.DOCINFOID
	, B.MAX_ID + ROW_NUMBER() OVER (ORDER BY A.ID) AS DOCLINKSID
	, ID AS STE_MIGRATIONID, ADD_HOURS(CURRENT_TIMESTAMP,8) AS STE_MIGRATIONDATE
FROM MIGRATION.PATCH_20250808_ITEM_CATALOG A
LEFT JOIN (
	SELECT COALESCE(MAX(DOCLINKSID),0) AS MAX_ID FROM MAXIMO.DOCLINKS
) B ON 1=1
JOIN MAXIMO.DOCINFO C ON C.STE_MIGRATIONID=A.ID
WHERE COALESCE(A.ITEMID,0)!=0 AND A.RN=1;

-- BACKUP CURRENT IMAGE CATALOG (IF ANY)
CREATE TABLE "MIGRATION"."BAK_20250808_IMGLIB"  (
	  "IMGLIBID" BIGINT NOT NULL , 
	  "REFOBJECT" VARCHAR(30 OCTETS) NOT NULL , 
	  "REFOBJECTID" BIGINT NOT NULL , 
	  "IMAGENAME" VARCHAR(100 OCTETS) NOT NULL , 
	  "IMAGE" BLOB(1073741824) LOGGED NOT COMPACT , 
	  "MIMETYPE" VARCHAR(50 OCTETS) NOT NULL , 
	  "IMGURI" VARCHAR(200 OCTETS) , 
	  "ENDPOINTNAME" VARCHAR(20 OCTETS) , 
	  "ROWSTAMP" BIGINT NOT NULL 
 )   
 ORGANIZE BY ROW;

--SELECT * FROM "MIGRATION"."BAK_20250808_IMGLIB";

INSERT INTO "MIGRATION"."BAK_20250808_IMGLIB"(
	IMGLIBID, REFOBJECT, REFOBJECTID, IMAGENAME, IMAGE, MIMETYPE, IMGURI, ENDPOINTNAME, ROWSTAMP
)
SELECT A.IMGLIBID, A.REFOBJECT, A.REFOBJECTID, A.IMAGENAME, A.IMAGE, A.MIMETYPE, A.IMGURI, A.ENDPOINTNAME, A.ROWSTAMP
FROM MAXIMO.IMGLIB A
JOIN MIGRATION.PATCH_20250808_ITEM_CATALOG B ON B.IMAGE IS NOT NULL AND B.ITEMID=A.REFOBJECTID
WHERE A.REFOBJECT='ITEM';

-- DELETE OLD VALUES
DELETE FROM MAXIMO.IMGLIB
WHERE IMGLIBID IN (
	SELECT A.IMGLIBID
	FROM MAXIMO.IMGLIB A
	JOIN MIGRATION.PATCH_20250808_ITEM_CATALOG B ON B.IMAGE IS NOT NULL AND B.ITEMID=A.REFOBJECTID
	WHERE A.REFOBJECT='ITEM'
);

-- INSERT IMAGE CATALOG
INSERT INTO MAXIMO.IMGLIB (
	IMGLIBID, REFOBJECT, REFOBJECTID, IMAGENAME, IMAGE, MIMETYPE
)
SELECT 
	B.MAX_ID + ROW_NUMBER() OVER (ORDER BY A.ID) AS IMGLIBID
	, 'ITEM' AS REFOBJECT
	, A.ITEMID AS REFOBJECTID, A.IMAGENAME, A.IMAGE, A.MIMETYPE
FROM MIGRATION.PATCH_20250808_ITEM_CATALOG A
LEFT JOIN (
	SELECT COALESCE(MAX(IMGLIBID),0) AS MAX_ID FROM MAXIMO.IMGLIB
) B ON 1=1
WHERE A.IMAGE IS NOT NULL AND COALESCE(A.ITEMID,0)>0
ORDER BY A.ID;

CALL MIGRATION.STE_FINISH_PATCH('20250808-IMAGE-CATALOG');