CALL MIGRATION.STE_START_PATCH('20250424-01-INVVENDOR');

--DROP TABLE "MAXIMO"."CSWN_INVVENDOR";
--CREATE TABLE "MAXIMO"."CSWN_INVVENDOR" 
--   (	
--   	"PK_SUPL_ITEMS" BIGINT, 
--	"TIMESTAMP" BIGINT, 
--	"DT_SUPL_ITEMS" BIGINT, 
--	"TM_SUPL_ITEMS" BIGINT, 
--	"S_ITEM_REF" VARCHAR(20), 
--	"S_ITEM_UNIT" VARCHAR(6), 
--	"YTD_QTY" DECIMAL(18,6), 
--	"TOD_QTY" DECIMAL(18,6), 
--	"LYR_QTY" DECIMAL(18,6), 
--	"YTD_PO_VAL" DECIMAL(18,6), 
--	"TOD_PO_VAL" DECIMAL(18,6), 
--	"LYR_PO_VAL" DECIMAL(18,6), 
--	"YTD_REJ_QTY" DECIMAL(18,6), 
--	"TOD_REJ_QTY" DECIMAL(18,6), 
--	"LYR_REJ_QTY" DECIMAL(18,6), 
--	"YTD_PO_NO" INTEGER, 
--	"TOD_PO_NO" INTEGER, 
--	"LYR_PO_NO" INTEGER, 
--	"YTD_DEL_NO" INTEGER, 
--	"TOD_DEL_NO" INTEGER, 
--	"LYR_DEL_NO" INTEGER, 
--	"YTD_REJ_NO" INTEGER, 
--	"TOD_REJ_NO" INTEGER, 
--	"LYR_REJ_NO" INTEGER, 
--	"S_L_PO" VARCHAR(10), 
--	"S_L_DT_PO" BIGINT, 
--	"PRI_TRND" DECIMAL(18,6), 
--	"S_AVG_LEAD_DYS" INTEGER, 
--	"REP_ORDR_FLG" INTEGER, 
--	"S_LAT_UNIT_RATE" DECIMAL(18,6), 
--	"S_BASE_MIN_ORD" DECIMAL(18,6), 
--	"S_DISC_QORV" INTEGER, 
--	"S_PRT_RMK_FLG" INTEGER, 
--	ITEM_CD VARCHAR(20),
--	ITEM_DS VARCHAR(104),
--	BUY_PRICE DECIMAL(18,6),
--	I_VAT_CD INTEGER,
--	PLAN_DAYS INTEGER,
--	SUPL_CD VARCHAR(20), 
--	AVG_LEAD_TIME INTEGER,
--	MIN_LEAD_TIME INTEGER,
--	MAX_LEAD_TIME INTEGER
--);

-- BRING MAXIMO.CSWN_INVVENDOR FROM ON-PREM

-- add custom columns
--ALTER TABLE MAXIMO.INVVENDOR ADD "STE_CSWNLATUNITRATE" DECIMAL(18,6);
--ALTER TABLE MAXIMO.INVVENDOR ADD "STE_CSWNBUYPRICE" DECIMAL(18,6);
--ALTER TABLE MAXIMO.INVVENDOR ADD "STE_CSWNLASTDATE" DATE;

-- update invvendor lastunitrate and buyrate from coswin
MERGE INTO MAXIMO.INVVENDOR A
USING (
	SELECT A.INVVENDORID, A.LASTDATE, B.S_LAT_UNIT_RATE, B.BUY_PRICE
	FROM MAXIMO.INVVENDOR A
	JOIN MAXIMO.CSWN_INVVENDOR B ON B.PK_SUPL_ITEMS=A.STE_MIGRATIONID
) B ON B.INVVENDORID=A.INVVENDORID
WHEN MATCHED THEN
UPDATE SET
	LASTCOST=B.S_LAT_UNIT_RATE,
	STE_CSWNLASTDATE=B.LASTDATE,
	STE_CSWNLATUNITRATE=B.S_LAT_UNIT_RATE,
	STE_CSWNBUYPRICE=B.BUY_PRICE
;

-- UPDATE INVVENDOR LASTCOST AND LASTDATE FROM LAST PO ORDERDATE AND UNITCOST
MERGE INTO MAXIMO.INVVENDOR A
USING (
	SELECT A.INVVENDORID, A.VENDOR, A.LASTCOST, A.LASTDATE, A.STE_CSWNLATUNITRATE, A.STE_CSWNBUYPRICE
		, B.ORDERDATE, B.UNITCOST 
	FROM maximo.invvendor A
	JOIN (
		SELECT C.PONUM, C.ORDERDATE, B.ITEMNUM, B.UNITCOST, C.EXCHANGERATE, C.VENDOR
			, ROW_NUMBER() OVER(PARTITION BY B.ITEMNUM, C.VENDOR ORDER BY C.ORDERDATE DESC) RN
		FROM maximo.poline b
		JOIN maximo.po c ON c.ponum=b.ponum
	) B ON B.RN=1 AND B.ITEMNUM=A.ITEMNUM AND B.VENDOR=A.VENDOR
	-- WHERE A.ITEMNUM='NEDELE/ELE/LF/13' AND A.VENDOR='NEDELE/GT'
) B ON B.INVVENDORID=A.INVVENDORID
WHEN MATCHED THEN
UPDATE SET
	STE_CSWNLASTDATE=B.LASTDATE,
	LASTDATE=B.ORDERDATE,
	LASTCOST=B.UNITCOST
;

CALL MIGRATION.STE_FINISH_PATCH('20250424-01-INVVENDOR');
