CALL MIGRATION.STE_START_PATCH('20250805-02-CSWN-PROBLEMCODE');

-- BRING MIGRATION.STE_CSWN_FAILURECODE FROM ON-PREM

INSERT INTO MAXIMO.FAILURECODE
	(FAILURECODE, DESCRIPTION, ORGID, FAILURECODEID, LANGCODE, HASLD, STE_MIGRATIONDATE, STE_MIGRATIONID)
SELECT A.FAILURECODE, A.DESCRIPTION
	, 'SBST' AS ORGID
	, C.MAXID + ROW_NUMBER() OVER (ORDER BY A."SOURCE", A.FAILURECODE) AS FAILURECODEID
	, 'EN' AS LANGCODE
	, 0 AS HASLD
	, ADD_HOURS(CURRENT_TIMESTAMP, 8) AS STE_MIGRATIONDATE
	, 20250805 AS STE_MIGRATIONID
FROM MIGRATION.STE_CSWN_FAILURECODE A
LEFT JOIN MAXIMO.FAILURECODE B ON B.FAILURECODE=A.FAILURECODE
LEFT JOIN (
	SELECT MAX(FAILURECODEID) AS MAXID FROM MAXIMO.FAILURECODE
) C ON 1=1
WHERE B.FAILURECODE IS NULL
;

CALL MIGRATION.STE_FINISH_PATCH('20250805-02-CSWN-PROBLEMCODE');