CALL MIGRATION.STE_START_PATCH('20250502-01-QUOTATIONLINE');

--CREATE TABLE "MAXIMO"."CSWN_RFQLINE" 
--   (	
--   	"PK_DV_ITEMS" BIGINT, 
--	"TIMESTAMP" BIGINT, 
--	"S_DV_ITEM" BIGINT, 
--	"S_ITEM_DV" BIGINT, 
--	"S_NSITEM_DV" BIGINT, 
--	"S_DV_ITEM_GEN" BIGINT, 
--	"DT_DV_ITEMS" BIGINT, 
--	"TM_DV_ITEMS" BIGINT, 
--	"DV_QTY" DECIMAL(28,12), 
--	"DV_UNIT" VARCHAR(6), 
--	"DV_UNIT_RATE" DECIMAL(28,12), 
--	"DV_DELAY" INTEGER, 
--	"DV_VALUE" DECIMAL(28,12), 
--	"DV_DISCNT" INTEGER, 
--	"DV_TO_ORDER" INTEGER, 
--	"DV_IT_NUMBER1" DECIMAL(28,12), 
--	"DV_IT_STRING1" VARCHAR(20), 
--	"DV_STOR_CD" VARCHAR(10),
--	ISAWARDED SMALLINT,
--	PK_DEVIS BIGINT,
--	DEVIS_CD VARCHAR(13),
--	ITEM_CD VARCHAR(20),
--	ITEM_DS VARCHAR(104),
--	SUPL_CD VARCHAR(20),
--	S_ITEM_REF VARCHAR(20),
--	LINENUM INTEGER
--)

-- BRING MAXIMO.CSWN_RFQLINE FROM ON-PREM

-- UPDATE QUOATIONLINE.UNITCOST AND LINECOST 
MERGE INTO MAXIMO.QUOTATIONLINE A
USING (
	SELECT A.QUOTATIONLINEID, A.RFQNUM, A.UNITCOST, A.LINECOST, A.ORDERQTY, A.STE_CSWNALTPRICE1
		, B.DV_UNIT_RATE AS NEW_UNITCOST, B.DV_VALUE AS NEW_LINECOST, B.DV_QTY AS NEW_ORDERQTY, B.DV_IT_NUMBER1 AS NEW_CSWNALTPRICE1
	FROM MAXIMO.QUOTATIONLINE A
	JOIN MAXIMO.CSWN_RFQLINE B ON A.STE_MIGRATIONID=B.PK_DV_ITEMS
	WHERE A.STE_MIGRATIONID IS NOT NULL
		--AND A.RFQNUM='SO04598825000'
) B ON B.QUOTATIONLINEID=A.QUOTATIONLINEID
WHEN MATCHED THEN
UPDATE SET
	UNITCOST=B.NEW_UNITCOST,
	LINECOST=B.NEW_LINECOST,
	ORDERQTY=B.NEW_ORDERQTY,
	STE_CSWNALTPRICE1=B.NEW_CSWNALTPRICE1
;

CALL MIGRATION.STE_FINISH_PATCH('20250502-01-QUOTATIONLINE');