CALL MIGRATION.STE_START_PATCH('20251201-03-POSTATUS-AUDIT');

--ALTER TABLE MAXIMO.POSTATUS ADD "STE_MIGRATIONID" BIGINT;
--ALTER TABLE MAXIMO.POSTATUS ADD "STE_MIGRATIONDATE" TIMESTAMP;

DELETE FROM MAXIMO.POSTATUS WHERE STE_MIGRATIONID IS NOT NULL;

INSERT INTO MAXIMO.POSTATUS
(
	PONUM, STATUS, CHANGEDATE, CHANGEBY, MEMO, ORGID, SITEID, REVISIONNUM, POSTATUSID, 
	STE_MIGRATIONID, STE_MIGRATIONDATE
)
SELECT
	A.PONUM, A.STATUSTEXT AS STATUS, A.MODIFICATIONDATE AS CHANGEDATE, A.PERSONID AS CHANGEBY,
	NULL AS MEMO, 'SBST' AS ORGID, 'NEL' AS SITEID, A.REVISIONNUM,
	B.MAXID + ROW_NUMBER() OVER (ORDER BY A.MODIFICATIONDATE, A.PONUM) AS POSTATUSID,
	20251201 AS STE_MIGRATIONID, ADD_HOURS(CURRENT_TIMESTAMP, 8) AS STE_MIGRATIONDATE
FROM (
	SELECT B.PONUM
		, A.MODIFICATIONDATE
		, A.STATUS
		, A.STATUSTEXT
		, A.USERNAME
		, A.PERSONID
		, B.REVISIONNUM
		, ROW_NUMBER() OVER (PARTITION BY B.PONUM, A.STATUSTEXT, A.MODIFICATIONDATE) AS RN
	FROM (
		SELECT 
			A.PK_VALUE
			, UPPER(TRIM(A.USERNAME)) AS USERNAME
			, COALESCE(C.PERSONID, 'MAXADMIN') AS PERSONID
			, A.MODIFICATIONDATE, A.OPERATION
			, A.STATUS
			, CASE WHEN A.STATUS='0' THEN 'WAPPR'
			       WHEN A.STATUS='1' OR A.STATUS='2' OR A.STATUS='3' THEN 'APPR'
			       WHEN A.STATUS='4' THEN 'CLOSE'
			       WHEN A.STATUS='5' THEN 'CAN'
			       WHEN A.STATUS='6' THEN 'WAPPR'
			       ELSE A.STATUS
			  END STATUSTEXT
			, A.DETAILS
			, B.PO_REF
			-- , LOCATE_IN_STRING(A.DETAILS, 'PO_REF:') AS STARTPOS
			-- , LOCATE_IN_STRING(A.DETAILS, ' ', LOCATE_IN_STRING(A.DETAILS, 'PO_REF:')) AS ENDPOS
			, TRIM(REPLACE(SUBSTR(A.DETAILS, 
							LOCATE_IN_STRING(A.DETAILS, 'PO_REF:'), 
							LOCATE_IN_STRING(A.DETAILS, ' ', LOCATE_IN_STRING(A.DETAILS, 'PO_REF:')) - LOCATE_IN_STRING(A.DETAILS, 'PO_REF:')
					 		),
					  'PO_REF:', ''
			  )) AS PO_REF2
		FROM MAXIMO.CSWN_AUDIT_PORDER_ A
		LEFT JOIN MAXIMO.CSWN_PO B ON B.PK_PORDER_=A.PK_VALUE
		LEFT JOIN MIGRATION.STE_MIGRATION_USER_LOOKUP C ON C.DISPLAY_NAME=UPPER(TRIM(A.USERNAME))
		WHERE A.DETAILS LIKE '%PO_STATUS%'
			--AND B.PO_REF IS NULL
	) A
	JOIN MAXIMO.PO B ON B.PONUM=COALESCE(A.PO_REF, A.PO_REF2)
	ORDER BY B.PONUM, A.STATUSTEXT, A.MODIFICATIONDATE
) A
JOIN (
	SELECT MAX(POSTATUSID) AS MAXID FROM MAXIMO.POSTATUS
) B ON 1=1
WHERE A.RN=1
;

CALL MIGRATION.STE_UPDATE_SEQ('POSTATUSSEQ', 'POSTATUS', 'POSTATUSID');

CALL MIGRATION.STE_FINISH_PATCH('20251201-03-POSTATUS-AUDIT');