MERGE INTO MAXIMO.WORKORDER AS A
USING (
	SELECT 
		A.WORKORDERID, B.STE_ASSETCODE, B.STE_LINE, B.STE_SYSTEM, B.STE_SUBSYSTEM, B.STE_CSWNAUTHORITY 
	FROM MAXIMO.WORKORDER A 
	JOIN MAXIMO.ASSET B ON B.ASSETNUM=A.ASSETNUM 
	WHERE A.ASSETNUM IS NOT NULL
) AS B ON B.WORKORDERID=A.WORKORDERID
WHEN MATCHED THEN
UPDATE SET
	STE_LINE=B.STE_LINE,
	STE_SYSTEM=B.STE_SYSTEM,
	STE_SUBSYSTEM=B.STE_SUBSYSTEM,
	STE_CSWNEQAUTHORITY=B.STE_CSWNAUTHORITY
;

MERGE INTO MAXIMO.WORKORDER AS A
USING (
	SELECT 
		A.WORKORDERID, B.STE_LINE, B.STE_SYSTEM, B.STE_SUBSYSTEM, B.STE_CSWNAUTHORITY 
	FROM MAXIMO.WORKORDER A 
	JOIN MAXIMO.ROUTES B ON B.ROUTE=A.ROUTE 
	WHERE A.ROUTE IS NOT NULL
) AS B ON B.WORKORDERID=A.WORKORDERID
WHEN MATCHED THEN
UPDATE SET
	STE_LINE=B.STE_LINE,
	STE_SYSTEM=B.STE_SYSTEM,
	STE_SUBSYSTEM=B.STE_SUBSYSTEM,
	STE_CSWNEQAUTHORITY=B.STE_CSWNAUTHORITY
;

MERGE INTO MAXIMO.WORKORDER AS A
USING (
	SELECT 
		A.WORKORDERID, B.MAINT_ENTITY
	FROM MAXIMO.WORKORDER A 
	JOIN MIGRATION.SBST_DEPT_ENTITY_MAPPING B ON B.COSWIN_ENTITY=COALESCE(A.STE_CSWNACTIONAUTH, A.STE_CSWNEQAUTHORITY)
) AS B ON B.WORKORDERID=A.WORKORDERID
WHEN MATCHED THEN
UPDATE SET
	STE_MAINTENTITY=B.MAINT_ENTITY
;