CALL MIGRATION.STE_START_PATCH('20250426-02-MATRECTRANS-RCTVAL');

--CREATE TABLE "MAXIMO"."CSWN_INVBALANCES"  (
--		  "PK_LOCATIONS_" BIGINT , 
--		  "IS_STOR_CD" VARCHAR(10 OCTETS) , 
--		  "BIN_REF" VARCHAR(16 OCTETS) , 
--		  "ITEM_CD" VARCHAR(20 OCTETS) , 
--		  "L_SCNT_DT" BIGINT , 
--		  "DT_LOCATION" BIGINT , 
--		  "LOC_PROC_DT" BIGINT , 
--		  "LOC_FREE_QTY" INTEGER , 
--		  "LOC_RES_QTY" INTEGER , 
--		  "LOC_FROZEN_QTY" INTEGER , 
--		  "TIMESTAMP" BIGINT )   
--;
--
--CREATE TABLE "MAXIMO"."CSWN_MATRECTRANS" 
--   (	
--   	"PK_RCT_ITEMS" BIGINT, 
--   	TIMESTAMP BIGINT,
--   	DT_RCT_ITEMS BIGINT,
--   	TM_RCT_ITEMS BIGINT,
--	"RCT_QTY" DECIMAL(28,12), 
--	"ACP_QTY" DECIMAL(28,12), 
--	"RTN_TO_SUPL" DECIMAL(28,12), 
--	"RCT_UNIT" VARCHAR(6), 
--	"RCT_UNIT_RATE" DECIMAL(28,12), 
--	"RCT_VAL" DECIMAL(28,12), 
--	"INSP_REF" VARCHAR(9), 
--	"INSP_DT" BIGINT, 
--	"INSP_STAT" INTEGER, 
--	"RCT_TP_FLG" INTEGER, 
--	"RCT_INV_QTY" DECIMAL(28,12), 
--	"RCT_RCL_QTY" DECIMAL(28,12), 
--	"RCT_ACT_NO" INTEGER, 
--	"RCT_IT_NUMBER1" DECIMAL(28,12), 
--	"RCT_IT_STRING1" VARCHAR(20), 
--	"RCT_PO_REF" VARCHAR(10), 
--	MRSTATUS VARCHAR(12),
--	DN_REF VARCHAR(10),
-- 	RCT_TYPE INTEGER,
--	RCT_TYPE_TXT VARCHAR(12),
--	RCT_DT BIGINT,		
--	DT_RECEIPT BIGINT,
--	TM_RECEIPT BIGINT,
--	GRN_REF VARCHAR(10),
--	GRN_DT BIGINT, 		
--	RCT_STATUS INTEGER,
--	RCT_STRING1 VARCHAR(20),
--	RCT_STRING2 VARCHAR(20),
--	DN_DT BIGINT,		
--	TRANSPORT VARCHAR(15),
--	RCT_DEM_WO_REF VARCHAR(10),
--	RCT_SUPL_CD VARCHAR(20),
--	RECEIPT_CODE VARCHAR(10),
--	RCT_PACKAGE VARCHAR(20),
--	LINENUM SMALLINT,
--	S_CURR_CD VARCHAR(6),
--	ITEM_CD VARCHAR(20),
--	INV_REF VARCHAR(16), 
--	PO_AMD_NO INTEGER,
--	RN INTEGER
--);

-- BRING CSWN_INVBALANCES MANUALLY FROM ON-PREM
-- BRING CSWN_MATRECTRANS MANUALLY FROM ON-PREM

-- update matrectrans rctval to fix 1cent discrepancy
MERGE INTO MAXIMO.MATRECTRANS A
USING (
	SELECT m.matrectransid, m.LINECOST, m.STE_CSWNRCTVAL, a.RCT_VAL
	FROM maximo.MATRECTRANS m 
	JOIN maximo.CSWN_MATRECTRANS a ON a.PK_RCT_ITEMS=m.STE_MIGRATIONID
) B ON B.MATRECTRANSID=A.MATRECTRANSID
WHEN MATCHED THEN
UPDATE SET
	STE_CSWNRCTVAL=B.RCT_VAL
;

ALL MIGRATION.STE_FINISH_PATCH('20250426-02-MATRECTRANS-RCTVAL');
