CALL MIGRATION.STE_START_PATCH('20250430-01-ITEM-ITEMGROUP');

UPDATE MAXIMO.ITEM
SET
	STE_CSWNITEMGROUP='PUBLICATION'
WHERE 
	STE_CSWNITEMGROUP='PUBLICATIO';

UPDATE MAXIMO.ITEM
SET
	STE_CSWNITEMGROUP=NULL
WHERE 
	STE_CSWNITEMGROUP='\';

UPDATE MAXIMO.ITEM
SET
	STE_CSWNITEMGROUP='SCS'
WHERE 
	STE_CSWNITEMGROUP='SCS`';

UPDATE MAXIMO.ITEM
SET
	STE_CSWNITEMGROUP='TOOLS'
WHERE 
	STE_CSWNITEMGROUP='TOOS';

CALL MIGRATION.STE_FINISH_PATCH('20250430-01-ITEM-ITEMGROUP');