CALL MIGRATION.STE_START_PATCH('20250423-03-RFQ-PURCHASEAGENT');

-- BRING MIGRATION.SBST_USER_DISPLAYNAME_MAPPING FROM ON-PREM

-- UPDATE USER LOOKUP
INSERT INTO MIGRATION.ste_migration_user_lookup (display_name, personid, persistent, status, STE_MIGRATIONID)
SELECT A.DISPLAYNAME, A.USERID, 0 AS PERSISTENT, 1 AS STATUS, 20250423 AS STE_MIGRATIONID
FROM MIGRATION.SBST_USER_DISPLAYNAME_MAPPING A
LEFT JOIN MIGRATION.STE_MIGRATION_USER_LOOKUP B ON B.DISPLAY_NAME=A.DISPLAYNAME
WHERE B.PKEY IS NULL
;

-- UPDATE RFQ PURCHASEAGENT
MERGE INTO maximo.rfq a
USING (
	SELECT A.DEVIS_CD, B.PERSONID
	FROM MAXIMO.CSWN_RFQ A
	LEFT JOIN MIGRATION.STE_MIGRATION_USER_LOOKUP B ON B.DISPLAY_NAME=UPPER(TRIM(A.DV_INCHARGE))
	WHERE B.PKEY IS NOT NULL
) b ON b.DEVIS_CD=a.rfqnum
WHEN MATCHED THEN 
UPDATE SET
	purchaseagent=B.PERSONID
;

--SELECT DISTINCT UPPER(TRIM(A.DV_INCHARGE)) AS DV_INCHARGE, B.PERSONID
--FROM MAXIMO.CSWN_RFQ A
--LEFT JOIN MIGRATION.STE_MIGRATION_USER_LOOKUP B ON B.DISPLAY_NAME=UPPER(TRIM(A.DV_INCHARGE))
--WHERE B.PKEY IS NULL
--;
	
CALL MIGRATION.STE_FINISH_PATCH('20250423-03-RFQ-PURCHASEAGENT');