--#SET TERMINATOR /

CREATE OR REPLACE PROCEDURE MIGRATION.STE_START_PATCH(
	IN P_PATCHNAME VARCHAR(50)
)
LANGUAGE SQL
SPECIFIC STE_START_PATCH
BEGIN

	INSERT INTO MIGRATION.ste_migration_logs (
	 package_name
	 ,version
	 ,start_date
	 ,hostname 
	)
	VALUES (
	 P_PATCHNAME
	 , '1.0'
	 , add_hours(CURRENT_TIMESTAMP,8)
	 , NULL
	);

END;
/

--#SET TERMINATOR /

CREATE OR REPLACE PROCEDURE MIGRATION.STE_FINISH_PATCH(
	IN P_PATCHNAME VARCHAR(50)
)
LANGUAGE SQL
SPECIFIC STE_FINISH_PATCH
BEGIN
	DECLARE V_MAX INTEGER DEFAULT 0;
	
	SET V_MAX = (SELECT ID FROM MIGRATION.ste_migration_logs WHERE package_name=P_PATCHNAME ORDER BY ID DESC LIMIT 1);
	
	UPDATE MIGRATION.ste_migration_logs 
	SET
	 end_date = add_hours(CURRENT_TIMESTAMP,8)
	 , success = 1
	WHERE id = V_MAX
	;

END;
/

--#SET TERMINATOR ;

CALL MIGRATION.STE_START_PATCH('20250406-RFQ-STATUS');

-- UPDATED COMPLETED RFQ
MERGE INTO MAXIMO.RFQ A
USING (
	SELECT A.RFQNUM
	FROM (
		SELECT A.RFQNUM, COUNT(B.RFQLINENUM) AS RFQLINECNT, SUM(COALESCE(C.ISAWARDED,0)) AS AWARDEDCNT
		FROM MAXIMO.RFQ A
		JOIN MAXIMO.RFQLINE B ON B.RFQNUM=A.RFQNUM
		LEFT JOIN (
			SELECT RFQNUM, RFQLINENUM, ITEMNUM, 1 AS ISAWARDED, B.STE_CSWNPOREF
			FROM MAXIMO.QUOTATIONLINE A
			JOIN MAXIMO.RFQVENDOR B ON B.RFQNUM=A.RFQNUM AND B.VENDOR=A.VENDOR
			WHERE A.ISAWARDED=1
			GROUP BY RFQNUM, RFQLINENUM, ITEMNUM
		) C ON C.RFQNUM=A.RFQNUM AND C.ITEMNUM=B.ITEMNUM
		GROUP BY A.RFQNUM
		ORDER BY A.RFQNUM
	) A
	WHERE A.RFQLINECNT=A.AWARDEDCNT
) B ON B.RFQNUM=A.RFQNUM
WHEN MATCHED THEN
UPDATE SET
	STATUS='COMP';

-- SET INPROGRESS RFQ TO STATUS=SENT
UPDATE MAXIMO.RFQ SET STATUS='SENT' WHERE STATUS='INPRG';

CALL MIGRATION.STE_FINISH_PATCH('20250406-RFQ-STATUS');
