CALL MIGRATION.STE_START_PATCH('20250408-02-BLANKET-CONTRACT-CREATIONDATE');

UPDATE MAXIMO.CONTRACT
SET
	STE_CREATIONDATE=STE_CSWNDATE
WHERE CONTRACTTYPE='BLANKET' AND STE_MIGRATIONID IS NOT NULL;

CALL MIGRATION.STE_FINISH_PATCH('20250408-02-BLANKET-CONTRACT-CREATIONDATE');

