CALL MIGRATION.STE_START_PATCH('20250408-01-RFQ-REFERENCE');

-- COSWIN.PORDER_ definition
DROP TABLE "MAXIMO"."CSWN_PO" IF EXISTS;
CREATE TABLE "MAXIMO"."CSWN_PO" 
(	
   "PK_PORDER_" BIGINT, 
	"TIMESTAMP" BIGINT, 
	"S_SUPL_PO" BIGINT, 
	"DT_PORDER" BIGINT, 
	"TM_PORDER" BIGINT, 
	"PO_REF" VARCHAR(10), 
	"PO_DT" BIGINT, 
	"PO_TYPE" INTEGER, 
	"PO_STATUS" INTEGER, 
	"PO_AUT_BY" VARCHAR(16), 
	"PO_CURR_CD" VARCHAR(6), 
	"PO_APR_QORV" INTEGER, 
	"PO_AMD_NO" INTEGER, 
	"PO_AMD_DT" BIGINT, 
	"PO_AMD_WHO" VARCHAR(16), 
	"PO_CHASE_DT" BIGINT, 
	"PO_VALUE" DECIMAL(15,2), 
	"PO_DEM_WO_REF" VARCHAR(10), 
	"PO_BLKT_REF" VARCHAR(10), 
	"PO_VALID_FM" BIGINT, 
	"PO_VALID_TO" BIGINT, 
	"PO_DELVD_VALUE" DECIMAL(15,2), 
	"PO_PENDG_VALUE" DECIMAL(15,2), 
	"PO_PRT_NOS" INTEGER, 
	"DR_TXT1" VARCHAR(13), 
	"DR_TXT2" VARCHAR(10), 
	"PO_PREQ_REF" VARCHAR(10), 
	"PO_PART_VALUE" DECIMAL(15,2), 
	"PO_PAY_DET" VARCHAR(6), 
	"PO_REQ_BY" VARCHAR(16), 
	"PO_PRT_DT" BIGINT, 
	"PO_STRING1" VARCHAR(20), 
	"PO_STRING2" VARCHAR(20), 
	"PO_ORIG_ORDER" VARCHAR(10),
	PK_SUPPLIER_ BIGINT,
	SUPL_CD VARCHAR(20),
	SUPL_NAME VARCHAR(100), 
	S_CURR_CD VARCHAR(6),
	PO_ITEM_DEL_DT BIGINT,
	PO_STATUS_TEXT VARCHAR(20),
	RECEIPT_TEXT VARCHAR(20),
	REQ_BY_ID VARCHAR(100),
	BLKT_RN INTEGER,
	VENDDELIVERYDATE TIMESTAMP,
	RFQCLOSEDATE TIMESTAMP
) 
IN "MAXDATA" ORGANIZE BY ROW;

-- IMPORT CSWN_PO MANUALLY FROM ON-PREM

-- UPDATE RFQVENDOR
MERGE INTO MAXIMO.RFQVENDOR A
USING (
	SELECT A.RFQVENDORID, A.RFQNUM AS ORIG_RFQNUM
		, B.DEVIS_CD, B.REF_DEVIS_CD, B.DV_PO_CD, B.DV_PREQ_REF, B.SUPL_CD
		, C.RFQNUM
	FROM MAXIMO.RFQVENDOR A
	JOIN MAXIMO.CSWN_RFQ B ON B.PK_DEVIS=A.STE_MIGRATIONID
	JOIN MAXIMO.RFQ C ON C.RFQNUM=B.REF_DEVIS_CD
	WHERE A.STE_MIGRATIONID IS NOT NULL
) B ON B.RFQVENDORID=A.RFQVENDORID
WHEN MATCHED THEN
UPDATE SET
	STE_CSWNDEVISCD=B.DEVIS_CD,
	STE_CSWNREFDEVISCD=B.RFQNUM,
	STE_CSWNPOREF=B.DV_PO_CD,
	STE_CSWNPRREF=B.DV_PREQ_REF
;

-- UPDATE QUOTATIONLINE
MERGE INTO MAXIMO.QUOTATIONLINE A
USING (
	SELECT A.QUOTATIONLINEID, A.RFQNUM AS ORIG_RFQNUM
		, B.DEVIS_CD, B.REF_DEVIS_CD, B.SUPL_CD, C.RFQNUM
	FROM MAXIMO.QUOTATIONLINE A
	JOIN MAXIMO.CSWN_RFQ B ON B.DEVIS_CD=A.RFQNUM
	JOIN MAXIMO.RFQ C ON C.RFQNUM=B.REF_DEVIS_CD
	WHERE A.STE_MIGRATIONID IS NOT NULL
) B ON B.QUOTATIONLINEID=A.QUOTATIONLINEID
WHEN MATCHED THEN
UPDATE SET
	STE_CSWNDEVISCD=B.DEVIS_CD,
	STE_CSWNREFDEVISCD=B.RFQNUM
;

-- UPDATE RFQ-PO LINKAGE
MERGE INTO MAXIMO.RFQLINE A
USING (
	SELECT C.RFQNUM, C.RFQLINENUM, C.ITEMNUM, B.RFQLINEID
		, C.POREF, C.PONUM, C.POLINENUM, C.POLINEID, C.REVISIONNUM
	FROM (
		SELECT A.RFQNUM, A.RFQLINENUM, A.ITEMNUM, 1 AS ISAWARDED, B.STE_CSWNPOREF AS POREF
			, D.PONUM, D.POLINENUM, D.POLINEID, D.REVISIONNUM
			, ROW_NUMBER() OVER (PARTITION BY A.RFQNUM, A.ITEMNUM ORDER BY D.POLINEID, B.STE_MIGRATIONID DESC) RN
		FROM MAXIMO.QUOTATIONLINE A
		JOIN MAXIMO.RFQVENDOR B ON B.RFQNUM=A.RFQNUM AND B.VENDOR=A.VENDOR
		LEFT JOIN MAXIMO.POLINE D ON D.PONUM=B.STE_CSWNPOREF AND D.ITEMNUM=A.ITEMNUM
		WHERE A.ISAWARDED=1 
			AND B.STE_CSWNPOREF IS NOT NULL
	) C
	LEFT JOIN MAXIMO.RFQLINE B ON C.RFQNUM=B.RFQNUM AND C.ITEMNUM=B.ITEMNUM
	WHERE C.RN=1
		--AND C.PONUM IS NULL
		-- AND B.RFQLINEID IS NULL
	ORDER BY C.RFQNUM
) B ON B.RFQLINEID=A.RFQLINEID
WHEN MATCHED THEN
UPDATE SET
	PONUM=B.POREF,
	POREVISIONNUM=B.REVISIONNUM,
	POLINENUM=B.POLINENUM,
	POLINEID=B.POLINEID
;

-- UPDATED RFQ CLOSEONDATE
MERGE INTO MAXIMO.RFQ A
USING (
	SELECT *
	FROM (
		SELECT A.RFQID, A.RFQNUM, COUNT(B.RFQLINENUM) AS RFQLINECNT
			, SUM(CASE WHEN B.PONUM IS NOT NULL THEN 1 ELSE 0 END) AS PONUMCNT
			, MAX(C.RFQCLOSEDATE) AS RFQCLOSEDATE
		FROM MAXIMO.RFQ A
		JOIN MAXIMO.RFQLINE B ON B.RFQNUM=A.RFQNUM
		LEFT JOIN MAXIMO.CSWN_PO C ON C.PO_REF=B.PONUM
		WHERE (A.STATUS='COMP' OR A.STATUS='CLOSE')
		GROUP BY A.RFQID, A.RFQNUM
	) A
	WHERE A.RFQLINECNT=A.PONUMCNT AND A.RFQCLOSEDATE IS NOT NULL
) B ON B.RFQID=A.RFQID
WHEN MATCHED THEN
UPDATE SET
	CLOSEONDATE=B.RFQCLOSEDATE
;

-- clean up old columns
ALTER TABLE MAXIMO.RFQVENDOR DROP COLUMN STE_MIGRATIONDEVISCD;
ALTER TABLE MAXIMO.RFQVENDOR DROP COLUMN STE_MIGRATIONREFDEVISCD;
ALTER TABLE MAXIMO.RFQVENDOR DROP COLUMN STE_MIGRATIONPOREF;
ALTER TABLE MAXIMO.RFQVENDOR DROP COLUMN STE_MIGRATIONPRREF;

ALTER TABLE MAXIMO.QUOTATIONLINE DROP COLUMN STE_MIGRATIONDEVISCD;
ALTER TABLE MAXIMO.QUOTATIONLINE DROP COLUMN STE_MIGRATIONREFDEVISCD;

--SELECT * FROM MAXIMO.RFQ A WHERE A.STATUS='CLOSE'

-- GENERATE LIST OF RFQLINE WITH MULTIPLE PO
--WITH FILT AS (
--	SELECT DISTINCT A.RFQNUM, A.ITEMNUM
--	FROM (
--			SELECT A.RFQNUM, A.RFQLINENUM, A.ITEMNUM, A.VENDOR, 1 AS ISAWARDED, B.STE_CSWNPOREF AS POREF
--				, D.PONUM, D.POLINENUM, D.POLINEID, D.REVISIONNUM
--				, ROW_NUMBER() OVER (PARTITION BY A.RFQNUM, A.ITEMNUM ORDER BY D.POLINEID, B.STE_MIGRATIONID DESC) RN
--			FROM MAXIMO.QUOTATIONLINE A
--			JOIN MAXIMO.RFQVENDOR B ON B.RFQNUM=A.RFQNUM AND B.VENDOR=A.VENDOR
--			LEFT JOIN MAXIMO.POLINE D ON D.PONUM=B.STE_CSWNPOREF AND D.ITEMNUM=A.ITEMNUM
--			WHERE A.ISAWARDED=1 
--				AND B.STE_CSWNPOREF IS NOT NULL
--	) A
--	WHERE 
--		A.RN>1
--)
--SELECT A.RFQNUM, A.RFQLINENUM, A.ITEMNUM, F.DESCRIPTION, A.VENDOR, 1 AS ISAWARDED, B.STE_CSWNPOREF AS POREF
--	, D.PONUM, D.POLINENUM, D.POLINEID, D.REVISIONNUM
--	, ROW_NUMBER() OVER (PARTITION BY A.RFQNUM, A.ITEMNUM ORDER BY D.POLINEID, B.STE_MIGRATIONID DESC) RN
--FROM MAXIMO.QUOTATIONLINE A
--JOIN MAXIMO.RFQVENDOR B ON B.RFQNUM=A.RFQNUM AND B.VENDOR=A.VENDOR
--LEFT JOIN MAXIMO.POLINE D ON D.PONUM=B.STE_CSWNPOREF AND D.ITEMNUM=A.ITEMNUM
--JOIN FILT E ON E.RFQNUM=A.RFQNUM AND E.ITEMNUM=A.ITEMNUM
--JOIN maximo.item F ON F.ITEMNUM=A.ITEMNUM
--WHERE A.ISAWARDED=1 
--	AND B.STE_CSWNPOREF IS NOT NULL
--ORDER BY A.RFQNUM, A.ITEMNUM
--;

-- GENERATE LIST OF INVALID PO REF/POLINE REF FROM RFQ
--SELECT C.RFQNUM, E.STATUSDATE, C.RFQLINENUM, C.ITEMNUM, D.DESCRIPTION, B.RFQLINEID
--	, C.ISAWARDED, C.VENDOR, C.POREF, C.PONUM, C.POLINENUM, C.POLINEID, C.REVISIONNUM
--FROM (
--	SELECT A.RFQNUM, A.RFQLINENUM, A.ITEMNUM, 1 AS ISAWARDED, A.VENDOR, B.STE_CSWNPOREF AS POREF
--		, E.PONUM, D.POLINENUM, D.POLINEID, E.REVISIONNUM
--		, ROW_NUMBER() OVER (PARTITION BY A.RFQNUM, A.ITEMNUM ORDER BY D.POLINEID, B.STE_MIGRATIONID DESC) RN
--	FROM MAXIMO.QUOTATIONLINE A
--	JOIN MAXIMO.RFQVENDOR B ON B.RFQNUM=A.RFQNUM AND B.VENDOR=A.VENDOR
--	LEFT JOIN MAXIMO.POLINE D ON D.PONUM=B.STE_CSWNPOREF AND D.ITEMNUM=A.ITEMNUM
--	LEFT JOIN MAXIMO.PO E ON E.PONUM=B.STE_CSWNPOREF
--	WHERE A.ISAWARDED=1 
--		AND B.STE_CSWNPOREF IS NOT NULL
--		--AND A.RFQNUM='SY00076503000'
--) C
--LEFT JOIN MAXIMO.RFQLINE B ON C.RFQNUM=B.RFQNUM AND C.ITEMNUM=B.ITEMNUM
--LEFT JOIN MAXIMO.RFQ E ON E.RFQNUM=C.RFQNUM
--JOIN MAXIMO.ITEM D ON D.ITEMNUM=C.ITEMNUM
--WHERE C.RN=1
--	AND (C.PONUM IS NULL OR C.POLINENUM IS NULL)
--ORDER BY B.STE_MIGRATIONID

CALL MIGRATION.STE_FINISH_PATCH('20250408-01-RFQ-REFERENCE');
