CALL MIGRATION.STE_START_PATCH('20250804-QTY-1PCT-DIFFERENCE');

/*
DROP TABLE MIGRATION.CSWN_POLINE IF exists; 
CREATE TABLE MIGRATION.CSWN_POLINE 
(	
   "PK_PO_ITEMS" BIGINT, 
	"TIMESTAMP" BIGINT, 
	"S_NSITEM_PO" BIGINT, 
	"S_ITEM_PO" BIGINT, 
	"DT_PO_ITEMS" BIGINT, 
	"TM_PO_ITEMS" BIGINT, 
	"PO_NST_REF" VARCHAR(2), 
	"PO_QTY" DECIMAL(28,12), 
	"PO_PENDING_QTY" DECIMAL(28,12), 
	"PO_INV_QTY" DECIMAL(28,12), 
	"PO_UNIT" VARCHAR(6), 
	"PO_UNIT_RATE" DECIMAL(28,12), 
	"PO_RCT_QTY" DECIMAL(28,12), 
	"PO_TP_FLG" INTEGER, 
	"PO_ITEM_DEL_DT" BIGINT, 
	"PO_ITEM_1EXTRA" DECIMAL(28,12), 
	"PO_DISCNT" INTEGER, 
	"PO_IT_NUMBER1" DECIMAL(28,12), 
	"PO_IT_STRING1" VARCHAR(20), 
	"PO_STOR_CD" VARCHAR(10),
	"PK_PORDER_" BIGINT, 
	"PO_REF" VARCHAR(10), 
	"DR_TXT1" VARCHAR(13), 
	"DR_TXT2" VARCHAR(10), 
	"PO_AMD_WHO" VARCHAR(16), 
	"PO_AMD_DT" BIGINT, 
	"PO_AMD_NO" BIGINT, 
	"PO_STRING1" VARCHAR(20), 
	"PO_DEM_WO_REF" VARCHAR(10), 
	PK_WIP_WO BIGINT, 
	ITEM_CD VARCHAR(20), 
	ITEM_DS VARCHAR(104), 
	CATEGORY VARCHAR(10),
	PK_SUPPLIER_ BIGINT,
	SUPL_CD VARCHAR(20), 
	SUPL_NAME VARCHAR(104), 
	PK_SUPL_ITEMS BIGINT,
	S_ITEM_REF VARCHAR(20), 
	AMD_USER_ID VARCHAR(16),
	CC_CD VARCHAR(16), 
	LINENUM INTEGER
)
 ORGANIZE BY ROW;

DROP TABLE MIGRATION.CSWN_PRLINE IF exists; 
CREATE TABLE MIGRATION.CSWN_PRLINE 
   (	
   "PK_PR_ITEMS" BIGINT, 
	"TIMESTAMP" BIGINT, 
	"S_NSITEM_PR" BIGINT, 
	"S_ITEM_PR" BIGINT, 
	"DT_PR_ITEMS" BIGINT, 
	"TM_PR_ITEMS" BIGINT, 
	"NEEDED_DT" BIGINT, 
	"PR_QTY" DECIMAL(28,12), 
	"PR_ORD_QTY" DECIMAL(28,12), 
	"PR_UNIT" VARCHAR(6), 
	"PR_NST_REF" VARCHAR(2), 
	"PR_TP_FLG" INTEGER, 
	"PR_PREF_SUPL" VARCHAR(20), 
	"PR_ITEM_EST_VAL" DECIMAL(28,12), 
	"PR_DEV_QTY" DECIMAL(28,12), 
	"PR_IT_NUMBER1" DECIMAL(28,12), 
	"PR_IT_STRING1" VARCHAR(20), 
	"PR_STOR_CD" VARCHAR(10), 
	PK_PREQUEST BIGINT,
	PR_REF VARCHAR(10), 
	PR_CC VARCHAR(16),  
	PR_STRING1 VARCHAR(20),
	PR_STRING2 VARCHAR(20), 
	PR_WO_REF VARCHAR(10),
	PK_WIP_WO BIGINT,
	ITEM_CD VARCHAR(20),
	ITEM_DS VARCHAR(104),
	BUY_PRICE DECIMAL(28,12),
	BUY_CURR VARCHAR(6), 
	LINENUM INTEGER
)
 ORGANIZE BY ROW;

DROP TABLE MIGRATION.CSWN_RFQLINE IF exists;
CREATE TABLE MIGRATION.CSWN_RFQLINE 
   (	
   	"PK_DV_ITEMS" BIGINT, 
	"TIMESTAMP" BIGINT, 
	"S_DV_ITEM" BIGINT, 
	"S_ITEM_DV" BIGINT, 
	"S_NSITEM_DV" BIGINT, 
	"S_DV_ITEM_GEN" BIGINT, 
	"DT_DV_ITEMS" BIGINT, 
	"TM_DV_ITEMS" BIGINT, 
	"DV_QTY" DECIMAL(28,12), 
	"DV_UNIT" VARCHAR(6), 
	"DV_UNIT_RATE" DECIMAL(28,12), 
	"DV_DELAY" INTEGER, 
	"DV_VALUE" DECIMAL(28,12), 
	"DV_DISCNT" INTEGER, 
	"DV_TO_ORDER" INTEGER, 
	"DV_IT_NUMBER1" DECIMAL(28,12), 
	"DV_IT_STRING1" VARCHAR(20), 
	"DV_STOR_CD" VARCHAR(10),
	ISAWARDED SMALLINT,
	PK_DEVIS BIGINT,
	DEVIS_CD VARCHAR(13),
	ITEM_CD VARCHAR(20),
	ITEM_DS VARCHAR(104),
	SUPL_CD VARCHAR(20),
	S_ITEM_REF VARCHAR(20),
	LINENUM INTEGER
);

DROP TABLE MIGRATION.CSWN_INVOICELINE IF exists;
CREATE TABLE MIGRATION.CSWN_INVOICELINE
(	
   	"PK_INV_ITEMS" BIGINT, 
	"TIMESTAMP" BIGINT, 
	"S_NSITEM_INV" INTEGER, 
	"S_INV_ITEM" INTEGER, 
	"S_ITEM_INV" INTEGER, 
	"DT_INV_ITEMS" BIGINT, 
	"TM_INV_ITEMS" BIGINT, 
	"INV_QTY" DECIMAL(28,12), 
	"INV_UNIT_RATE" DECIMAL(28,12), 
	"INV_ITEM_BASE_VAL" DECIMAL(28,12), 
	"INV_UNIT" VARCHAR(6 OCTETS), 
	"INV_IT_NUMBER1" DECIMAL(28,12), 
	"INV_IT_STRING1" VARCHAR(20), 
	"INV_PO_REF" VARCHAR(10 OCTETS), 
	PK_INVOICE_ BIGINT,
	INV_REF VARCHAR(10 OCTETS),
	INV_RCT_DT BIGINT,
	ITEM_CD VARCHAR(20 OCTETS),
	LINENUM INTEGER,
	SUPL_CD VARCHAR(20 OCTETS),
	STE_CSWNLOCALHANDLINGCHARGE DECIMAL(28,12),
	TAX1 DECIMAL(28,12),
	STE_CSWNDISCOUNT DECIMAL(28,12),
	TAX2 DECIMAL(28,12),
	STE_CSWNOTHERCHARGES DECIMAL(28,12),
	INV_OTH_CHR DECIMAL(28,12),
	PK_PORDER_ BIGINT
)
 ORGANIZE BY ROW;

DROP TABLE MIGRATION.CSWN_INVUSELINE IF exists;
CREATE TABLE MIGRATION.CSWN_INVUSELINE
(	
	PK_ISS_ITEMS BIGINT,
	TIMESTAMP BIGINT,
	ISS_ASK_QTY DECIMAL(28,12),
	ISS_QTY DECIMAL(28,12),
	ISS_VAL DECIMAL(28,12),
	RTN_TO_STORE DECIMAL(28,12),
	ISS_DT BIGINT,
	PK_DEM_ISS BIGINT,
	DEM_REF VARCHAR(10 OCTETS),
	DEM_TYPE INTEGER,
	USAGE_TYPE VARCHAR(20 OCTETS),
	ORIG_DEM_REF VARCHAR(10 OCTETS),
	PK_WIP_WO BIGINT,
	WO_WOID INTEGER,
	ITEM_CD VARCHAR(20 OCTETS),
	LINENUM INTEGER,
	RN INTEGER
)
 ORGANIZE BY ROW;
*/

/*
 select 'MIGRATION.CSWN_PRLINE' AS name, count(*) AS cnt from MIGRATION.CSWN_PRLINE
 UNION select 'MIGRATION.CSWN_RFQLINE', count(*) from MIGRATION.CSWN_RFQLINE
 UNION select 'MIGRATION.CSWN_POLINE', count(*) from MIGRATION.CSWN_POLINE
 UNION select 'MIGRATION.CSWN_INVOICELINE', count(*) from MIGRATION.CSWN_INVOICELINE
 UNION select 'MIGRATION.CSWN_INVUSELINE', count(*) from MIGRATION.CSWN_INVUSELINE
 UNION select 'MAXIMO.CSWN_PRLINE', count(*) from maximo.CSWN_PRLINE
 UNION select 'MAXIMO.CSWN_RFQLINE', count(*) from maximo.CSWN_RFQLINE
 UNION select 'MAXIMO.CSWN_POLINE', count(*) from maximo.CSWN_POLINE
 UNION select 'MAXIMO.CSWN_INVOICELINE', count(*) from maximo.CSWN_INVOICELINE
 UNION select 'MAXIMO.CSWN_INVUSELINE', count(*) from maximo.CSWN_INVUSELINE
*/

-- NEED TO BRING TABLE MIGRATION.CSWN_PRLINE FROM ON-PREM
-- NEED TO BRING TABLE MIGRATION.CSWN_RFQLINE FROM ON-PREM
-- NEED TO BRING TABLE MIGRATION.CSWN_POLINE FROM ON-PREM
-- NEED TO BRING TABLE MIGRATION.CSWN_INVOICELINE FROM ON-PREM
-- NEED TO BRING TABLE MIGRATION.CSWN_INVUSELINE FROM ON-PREM

-- ------------
-- QUANTITY
-- ------------

-- BACKUP: PRLINE
-- DROP TABLE "MIGRATION"."BAK_20250804_PRLINE_QTY" IF EXISTS;
CREATE TABLE "MIGRATION"."BAK_20250804_PRLINE_QTY"  (
  "PRLINEID" BIGINT NOT NULL , 
  "PRNUM" VARCHAR(10 OCTETS) , 
  "PRLINENUM" INTEGER , 
  "ITEMNUM" VARCHAR(30 OCTETS) , 
  "ORDERQTY" DECIMAL(18,2) , 
  "NEW_ORDERQTY" DECIMAL(18,2)
)   
ORGANIZE BY ROW;

--DELETE FROM "MIGRATION"."BAK_20250804_PRLINE_QTY";
INSERT INTO "MIGRATION"."BAK_20250804_PRLINE_QTY" (
	PRLINEID, PRNUM, PRLINENUM, ITEMNUM, ORDERQTY, NEW_ORDERQTY
)
SELECT A.PRLINEID, A.PRNUM, A.PRLINENUM, A.ITEMNUM, A.ORDERQTY, B.PR_QTY
FROM MAXIMO.PRLINE A
JOIN MIGRATION.CSWN_PRLINE B ON B.PK_PR_ITEMS=A.STE_MIGRATIONID
WHERE A.ORDERQTY!=B.PR_QTY AND ABS(A.ORDERQTY-B.PR_QTY)<1
;

-- BACKUP: QUOTATIONLINE
-- DROP TABLE "MIGRATION"."BAK_20250804_QUOTATIONLINE_QTY" IF EXISTS;
CREATE TABLE "MIGRATION"."BAK_20250804_QUOTATIONLINE_QTY"  (
  "QUOTATIONLINEID" BIGINT NOT NULL , 
  "RFQNUM" VARCHAR(15 OCTETS) , 
  "RFQLINENUM" INTEGER , 
  "ITEMNUM" VARCHAR(30 OCTETS) , 
  "VENDOR" VARCHAR(20 OCTETS) , 
  "ORDERQTY" DECIMAL(18,2) , 
  "NEW_ORDERQTY" DECIMAL(18,2)
)   
ORGANIZE BY ROW;

--DELETE FROM "MIGRATION"."BAK_20250804_QUOTATIONLINE_QTY";
INSERT INTO "MIGRATION"."BAK_20250804_QUOTATIONLINE_QTY" (
	QUOTATIONLINEID, RFQNUM, RFQLINENUM, ITEMNUM, VENDOR, ORDERQTY, NEW_ORDERQTY
)
SELECT A.QUOTATIONLINEID, A.RFQNUM, A.RFQLINENUM, A.ITEMNUM, A.VENDOR, A.ORDERQTY, ROUND(B.DV_QTY, 2) AS DV_QTY
FROM MAXIMO.QUOTATIONLINE A
JOIN MIGRATION.CSWN_RFQLINE B ON B.PK_DV_ITEMS=A.STE_MIGRATIONID
WHERE A.ORDERQTY!=ROUND(B.DV_QTY, 2) AND ABS(A.ORDERQTY-ROUND(B.DV_QTY, 2))<1
;

-- BACKUP: INVOICELINE
-- DROP TABLE "MIGRATION"."BAK_20250804_INVOICELINE_QTY" IF EXISTS;
CREATE TABLE "MIGRATION"."BAK_20250804_INVOICELINE_QTY"  (
  "INVOICELINEID" BIGINT NOT NULL , 
  "INVOICENUM" VARCHAR(15 OCTETS) , 
  "INVOICELINENUM" INTEGER , 
  "ITEMNUM" VARCHAR(30 OCTETS) , 
  "INVOICEQTY" DECIMAL(18,2) , 
  "NEW_INVOICEQTY" DECIMAL(18,2)
)   
ORGANIZE BY ROW;

--DELETE FROM "MIGRATION"."BAK_20250804_INVOICELINE_QTY";
INSERT INTO "MIGRATION"."BAK_20250804_INVOICELINE_QTY" (
	INVOICELINEID, INVOICENUM, INVOICELINENUM, ITEMNUM, INVOICEQTY, NEW_INVOICEQTY
)
SELECT A.INVOICELINEID, A.INVOICENUM, A.INVOICELINENUM, A.ITEMNUM, A.INVOICEQTY, B.INV_QTY
FROM MAXIMO.INVOICELINE A
JOIN MIGRATION.CSWN_INVOICELINE B ON B.PK_INV_ITEMS=A.STE_MIGRATIONID
WHERE A.INVOICEQTY!=B.INV_QTY AND ABS(A.INVOICEQTY-B.INV_QTY)<1;

-- BACKUP: INVUSELINE
-- DROP TABLE "MIGRATION"."BAK_20250804_INVUSELINE_QTY" IF EXISTS;
CREATE TABLE "MIGRATION"."BAK_20250804_INVUSELINE_QTY"  (
  "INVUSELINEID" BIGINT NOT NULL , 
  "INVUSENUM" VARCHAR(10 OCTETS) , 
  "INVUSELINENUM" INTEGER , 
  "ITEMNUM" VARCHAR(30 OCTETS) , 
  "QUANTITY" DECIMAL(18,2) , 
  "NEW_QUANTITY" DECIMAL(18,2)
)   
ORGANIZE BY ROW;

--DELETE FROM "MIGRATION"."BAK_20250804_INVUSELINE_QTY";
INSERT INTO "MIGRATION"."BAK_20250804_INVUSELINE_QTY" (
	INVUSELINEID, INVUSENUM, INVUSELINENUM, ITEMNUM, QUANTITY, NEW_QUANTITY
)
SELECT A.INVUSELINEID, A.INVUSENUM, A.INVUSELINENUM, A.ITEMNUM, A.QUANTITY, B.ISS_QTY
FROM MAXIMO.INVUSELINE A
JOIN MIGRATION.CSWN_INVUSELINE B ON B.PK_ISS_ITEMS=A.STE_MIGRATIONID
WHERE A.QUANTITY!=B.ISS_QTY AND ABS(A.QUANTITY-B.ISS_QTY)<1;

-- BACKUP: MATUSETRANS
-- DROP TABLE "MIGRATION"."BAK_20250804_MATUSETRANS_QTY" IF EXISTS;
CREATE TABLE "MIGRATION"."BAK_20250804_MATUSETRANS_QTY"  (
  "MATUSETRANSID" BIGINT NOT NULL , 
  "INVUSEID" BIGINT , 
  "INVUSELINEID" BIGINT , 
  "QUANTITY" DECIMAL(18,2) , 
  "NEW_QUANTITY" DECIMAL(18,2)
)   
ORGANIZE BY ROW;

--DELETE FROM "MIGRATION"."BAK_20250804_MATUSETRANS_QTY";
INSERT INTO "MIGRATION"."BAK_20250804_MATUSETRANS_QTY" (
	MATUSETRANSID, INVUSEID, INVUSELINEID, QUANTITY, NEW_QUANTITY
)
SELECT A.MATUSETRANSID, A.INVUSEID, A.INVUSELINEID, A.QUANTITY, (-1 * B.ISS_QTY) AS ISS_QTY
FROM MAXIMO.MATUSETRANS A
JOIN MIGRATION.CSWN_INVUSELINE B ON B.PK_ISS_ITEMS=A.STE_MIGRATIONID
WHERE 1=1
	AND A.ISSUETYPE='ISSUE'
	AND A.QUANTITY!=(-1*B.ISS_QTY) AND ABS(A.QUANTITY-(-1*B.ISS_QTY))<1;

-- CONTRACTLINE
-- FOR CONTRACTTYPE='PRICE' => NO NEED BECAUSE ORDERQTY IS ALWAYS =1
-- FOR CONTRACTTYPE='BLANKET' => NO NEED BECAUSE ORDERQTY IS ALWAYS =1

-- PRLINE
MERGE INTO MAXIMO.PRLINE A
USING (
	SELECT A.PRLINEID, A.PRNUM, A.PRLINENUM, A.ITEMNUM, A.ORDERQTY, B.PR_QTY
	FROM MAXIMO.PRLINE A
	JOIN MIGRATION.CSWN_PRLINE B ON B.PK_PR_ITEMS=A.STE_MIGRATIONID
	WHERE A.ORDERQTY!=B.PR_QTY AND ABS(A.ORDERQTY-B.PR_QTY)<1
) B ON B.PRLINEID=A.PRLINEID
WHEN MATCHED THEN
UPDATE SET
	ORDERQTY = B.PR_QTY
;

-- POLINE => NO DISCREPANCIES
-- NOTE: PONUM AA10016776 => 2 ENTRIES BECAUSE OF REVISION => IGNORED

-- RFQLINE => NO NEED TO CHECK, NOT IMPORTANT (THE IMPORTANT QTY ARE PRLINE, QUOTATIONLINE AND POLINE)

-- QUOTATIONLINE
-- NOTE: RFNUM SO04605825000 (PENTALIGHTING65EESGD) => NOT MIGRATED DATA!
MERGE INTO MAXIMO.QUOTATIONLINE A
USING (
	SELECT A.QUOTATIONLINEID, A.RFQNUM, A.RFQLINENUM, A.ITEMNUM, A.VENDOR, A.ORDERQTY, ROUND(B.DV_QTY, 2) AS DV_QTY
	FROM MAXIMO.QUOTATIONLINE A
	JOIN MIGRATION.CSWN_RFQLINE B ON B.PK_DV_ITEMS=A.STE_MIGRATIONID
	WHERE A.ORDERQTY!=ROUND(B.DV_QTY, 2) AND ABS(A.ORDERQTY-ROUND(B.DV_QTY, 2))<1
) B ON B.QUOTATIONLINEID=A.QUOTATIONLINEID
WHEN MATCHED THEN
UPDATE SET
	ORDERQTY = B.DV_QTY
;

-- INVOICELINE
MERGE INTO MAXIMO.INVOICELINE A
USING (
	SELECT A.INVOICELINEID, A.INVOICENUM, A.INVOICELINENUM, A.ITEMNUM, A.INVOICEQTY, B.INV_QTY
	FROM MAXIMO.INVOICELINE A
	JOIN MIGRATION.CSWN_INVOICELINE B ON B.PK_INV_ITEMS=A.STE_MIGRATIONID
	WHERE A.INVOICEQTY!=B.INV_QTY AND ABS(A.INVOICEQTY-B.INV_QTY)<1
) B ON B.INVOICELINEID=A.INVOICELINEID
WHEN MATCHED THEN
UPDATE SET
	INVOICEQTY = B.INV_QTY
;

-- INVUSELINE
-- NOTE: INVUSENUM 332535 (ITEMNUM=A44-GEN1-0001-0448XX -> GREASE, KLUBERLUB BE 41-1501, 25 KG/PAIL) => QTY=8; ORIGINAL COSWIN QTY (0.08) IS NOT CORRECT!
MERGE INTO MAXIMO.INVUSELINE A
USING (
	SELECT A.INVUSELINEID, A.INVUSENUM, A.INVUSELINENUM, A.ITEMNUM, A.QUANTITY, B.ISS_QTY
	FROM MAXIMO.INVUSELINE A
	JOIN MIGRATION.CSWN_INVUSELINE B ON B.PK_ISS_ITEMS=A.STE_MIGRATIONID
	WHERE A.QUANTITY!=B.ISS_QTY AND ABS(A.QUANTITY-B.ISS_QTY)<1
) B ON B.INVUSELINEID = A.INVUSELINEID
WHEN MATCHED THEN
UPDATE SET
	QUANTITY = B.ISS_QTY
;

-- MATUSETRANS (SAME SOURCE AS INVUSELINE)
MERGE INTO MAXIMO.MATUSETRANS A
USING (
	SELECT A.MATUSETRANSID, A.INVUSEID, A.INVUSELINEID, A.QUANTITY, (-1 * B.ISS_QTY) AS ISS_QTY
	FROM MAXIMO.MATUSETRANS A
	JOIN MIGRATION.CSWN_INVUSELINE B ON B.PK_ISS_ITEMS=A.STE_MIGRATIONID
	WHERE 1=1
		AND A.ISSUETYPE='ISSUE'
		AND A.QUANTITY!=(-1*B.ISS_QTY) AND ABS(A.QUANTITY-(-1*B.ISS_QTY))<1
) B ON B.MATUSETRANSID=A.MATUSETRANSID
WHEN MATCHED THEN
UPDATE SET
	QUANTITY = B.ISS_QTY
;

-- MATRECTRANS => DONT UPDATE, ALREADY MODIFIED WITH EACH RECEIVE

-- SERVRECTRANS (SAME SOURCE AS MATRECTRANS) => DONT UPDATE, ALREADY MODIFIED WITH EACH RECEIVE

-- WPITEM (SAME SOURCE AS INVUSELINE) => NO DISCREPANCIES

-- SPECIAL CASE: 0.069 => 0.07
UPDATE MAXIMO.INVOICELINE
SET UNITCOST=0.07
WHERE STE_MIGRATIONID=421;

-- SPECIAL CASE: 0.99 => 1 TO BE CONSISTENT WITH INVOICE UNITCOST
UPDATE MAXIMO.POLINE
SET UNITCOST=1
WHERE STE_MIGRATIONID=82241;

-- -------------
-- LINECOST
-- -------------

-- BACKUP: PRLINE
-- DROP TABLE "MIGRATION"."BAK_20250804_PRLINE_LINECOST" IF EXISTS;
CREATE TABLE "MIGRATION"."BAK_20250804_PRLINE_LINECOST"  (
  "PRLINEID" BIGINT NOT NULL , 
  "PRNUM" VARCHAR(10 OCTETS) , 
  "PRLINENUM" INTEGER , 
  "ITEMNUM" VARCHAR(30 OCTETS) , 
  "LINECOST" DECIMAL(10,2) , 
  "ORDERQTY" DECIMAL(15,2) , 
  "UNITCOST" DECIMAL(10,2) , 
  "NEW_LINECOST" DECIMAL(10,2),
  "NEW_UNITCOST" DECIMAL(10,2)
)   
ORGANIZE BY ROW;

--DELETE FROM "MIGRATION"."BAK_20250804_PRLINE_LINECOST";
INSERT INTO "MIGRATION"."BAK_20250804_PRLINE_LINECOST" (
	PRLINEID, PRNUM, PRLINENUM, ITEMNUM, LINECOST, ORDERQTY, UNITCOST, NEW_LINECOST, NEW_UNITCOST
)
SELECT A.PRLINEID, A.PRNUM, A.PRLINENUM, A.ITEMNUM, A.LINECOST, A.ORDERQTY, A.UNITCOST
	, CASE WHEN B.PR_ITEM_EST_VAL>99999999 THEN 99999999 ELSE CAST(B.PR_ITEM_EST_VAL AS DECIMAL(15,2)) END AS NEW_LINECOST
	, CASE WHEN (B.PR_ITEM_EST_VAL/A.ORDERQTY)>99999999 THEN 99999999 ELSE CAST(B.PR_ITEM_EST_VAL/A.ORDERQTY AS DECIMAL(15,2)) END AS NEW_UNITCOST
FROM MAXIMO.PRLINE A
JOIN MIGRATION.CSWN_PRLINE B ON B.PK_PR_ITEMS=A.STE_MIGRATIONID
WHERE 1=1
	AND (
		A.LINECOST != CAST(B.PR_ITEM_EST_VAL AS DECIMAL(15,2))
	)
;

-- BACKUP: POLINE
-- DROP TABLE "MIGRATION"."BAK_20250804_POLINE_LINECOST" IF EXISTS;
CREATE TABLE "MIGRATION"."BAK_20250804_POLINE_LINECOST"  (
  "POLINEID" BIGINT NOT NULL , 
  "PONUM" VARCHAR(15 OCTETS) , 
  "POLINENUM" INTEGER , 
  "ITEMNUM" VARCHAR(30 OCTETS) , 
  "LINECOST" DECIMAL(12,2) , 
  "ORDERQTY" DECIMAL(15,2) ,
  "UNITCOST" DECIMAL(12,2) , 
  "NEW_LINECOST" DECIMAL(12,2) 
)   
ORGANIZE BY ROW;

--DELETE FROM "MIGRATION"."BAK_20250804_POLINE_LINECOST";
INSERT INTO "MIGRATION"."BAK_20250804_POLINE_LINECOST" (
	POLINEID, PONUM, POLINENUM, ITEMNUM, LINECOST, ORDERQTY, UNITCOST, NEW_LINECOST
)
SELECT A.POLINEID, A.PONUM, A.POLINENUM, A.ITEMNUM, A.LINECOST, A.ORDERQTY, A.UNITCOST
	, CASE WHEN A.ORDERQTY*A.UNITCOST > 9999999999 THEN 9999999999 
		   ELSE CAST(A.ORDERQTY*A.UNITCOST AS DECIMAL(12,2)) 
	  END AS NEW_LINECOST
FROM MAXIMO.POLINE A
JOIN MIGRATION.CSWN_POLINE B ON B.PK_PO_ITEMS=A.STE_MIGRATIONID
WHERE 1=1
	AND (
		A.LINECOST!=CAST(A.ORDERQTY*A.UNITCOST AS DECIMAL(12,2))
	)
;

-- BACKUP: INVOICELINE
-- DROP TABLE "MIGRATION"."BAK_20250804_INVOICELINE_LINECOST" IF EXISTS;
CREATE TABLE "MIGRATION"."BAK_20250804_INVOICELINE_LINECOST"  (
  "INVOICELINEID" BIGINT NOT NULL , 
  "INVOICENUM" VARCHAR(15 OCTETS) , 
  "INVOICELINENUM" INTEGER , 
  "ITEMNUM" VARCHAR(30 OCTETS) , 
  "LINECOST" DECIMAL(12,2) , 
  "INVOICEQTY" DECIMAL(15,2) ,
  "UNITCOST" DECIMAL(10,2) , 
  "NEW_LINECOST" DECIMAL(12,2) 
)   
ORGANIZE BY ROW;

--DELETE FROM "MIGRATION"."BAK_20250804_INVOICELINE_LINECOST";
INSERT INTO "MIGRATION"."BAK_20250804_INVOICELINE_LINECOST" (
	INVOICELINEID, INVOICENUM, INVOICELINENUM, ITEMNUM, LINECOST, INVOICEQTY, UNITCOST, NEW_LINECOST
)
SELECT A.INVOICELINEID, A.INVOICENUM, A.INVOICELINENUM, A.ITEMNUM
	, A.LINECOST AS INVLINECOST, A.INVOICEQTY, A.UNITCOST AS INVUNITCOST
	, CASE WHEN A.INVOICEQTY*A.UNITCOST > 9999999999 THEN 9999999999 
		   ELSE CAST(A.INVOICEQTY*A.UNITCOST AS DECIMAL(12,2))
	  END AS NEW_LINECOST
FROM MAXIMO.INVOICELINE A
JOIN MIGRATION.CSWN_INVOICELINE B ON B.PK_INV_ITEMS=A.STE_MIGRATIONID
WHERE 1=1
	AND (
		A.LINECOST!=CAST(A.INVOICEQTY*A.UNITCOST AS DECIMAL(12,2))
	)
	--AND ABS(A.LINECOST - (A.INVOICEQTY*A.UNITCOST)) > 0.01
;

-- PRLINE
MERGE INTO MAXIMO.PRLINE A
USING MIGRATION.BAK_20250804_PRLINE_LINECOST B ON B.PRLINEID=A.PRLINEID
WHEN MATCHED THEN
UPDATE SET
	LINECOST = B.NEW_LINECOST,
	UNITCOST = B.NEW_UNITCOST
;

-- POLINE
MERGE INTO MAXIMO.POLINE A
USING MIGRATION.BAK_20250804_POLINE_LINECOST B ON B.POLINEID=A.POLINEID
WHEN MATCHED THEN
UPDATE SET
	LINECOST = B.NEW_LINECOST
;

-- INVOICELINE
MERGE INTO MAXIMO.INVOICELINE A
USING MIGRATION.BAK_20250804_INVOICELINE_LINECOST B ON B.INVOICELINEID=A.INVOICELINEID
WHEN MATCHED THEN
UPDATE SET
	LINECOST = B.NEW_LINECOST
;

-- ------------------------------------------------
-- REMIGRATE INVOICELINE.TAX1 AND INVOICELINE.TAX2 => NO DIFF WITH EXISTING MIGRATED DATA
-- ------------------------------------------------

--SELECT A.INVOICELINEID, A.INVOICENUM, A.INVOICELINENUM, A.ITEMNUM
--	, A.TAX1, A.TAX2, B.TAX1 AS NEW_TAX1, B.TAX2 AS NEW_TAX2
--FROM MAXIMO.INVOICELINE A
--JOIN MIGRATION.CSWN_INVOICELINE B ON B.PK_INV_ITEMS=A.STE_MIGRATIONID
--WHERE 1=1
--	AND (
--		A.TAX1!=CAST(B.TAX1 AS DECIMAL(10,2))
--		OR A.TAX2!=CAST(B.TAX2 AS DECIMAL(10,2))
--	)
--	--AND ABS(A.LINECOST - (A.INVOICEQTY*A.UNITCOST)) > 0.01
--;

-- -----------------------------------------------------
-- UPDATE INVOICE.BASETOTALCOST AND INVOICE.TOTALCOST
-- -----------------------------------------------------
-- DROP TABLE "MIGRATION"."BAK_20250804_INVOICE_TOTALCOST";
CREATE TABLE "MIGRATION"."BAK_20250804_INVOICE_TOTALCOST"  (
  "INVOICEID" BIGINT NOT NULL , 
  "INVOICENUM" VARCHAR(15 OCTETS) , 
  "BASETOTALCOST" DECIMAL(13,5) , 
  "TOTALTAX1" DECIMAL(10,2) ,
  "TOTALTAX2" DECIMAL(10,2) ,
  "TOTALCOST" DECIMAL(12,2) ,
  "NEW_BASETOTALCOST" DECIMAL(13,5) , 
  "NEW_TOTALTAX1" DECIMAL(10,2) ,
  "NEW_TOTALTAX2" DECIMAL(10,2) ,
  "NEW_TOTALCOST" DECIMAL(12,2) 
)   
ORGANIZE BY ROW;

-- DELETE FROM "MIGRATION"."BAK_20250804_INVOICE_TOTALCOST";
INSERT INTO "MIGRATION"."BAK_20250804_INVOICE_TOTALCOST" (
	INVOICEID, INVOICENUM, BASETOTALCOST, NEW_BASETOTALCOST
	, TOTALTAX1, TOTALTAX2, NEW_TOTALTAX1, NEW_TOTALTAX2
	, TOTALCOST, NEW_TOTALCOST
)
SELECT A.INVOICEID, A.INVOICENUM
	, A.BASETOTALCOST
	, CASE WHEN A.CURRENCYCODE='SGD' THEN B.TOTALCOST
		   ELSE B.TOTALCOST*A.EXCHANGERATE 
	  END AS NEW_BASETOTALCOST
	, A.TOTALTAX1, A.TOTALTAX2, B.TOTALTAX1 AS NEW_TOTALTAX1, B.TOTALTAX2 AS NEW_TOTALTAX2
	, A.TOTALCOST, B.TOTALCOST AS NEW_TOTALCOST
FROM MAXIMO.INVOICE A
JOIN (
	SELECT A.INVOICENUM, A.TOTALLINECOST, A.TOTALTAX1, A.TOTALTAX2
		, COALESCE(B.DISCOUNT,0) AS TOTALDISC
		, COALESCE(B.STE_CSWNLOCALHANDLINGCHARGE,0) AS TOTALFREIGHT
		, COALESCE(B.STE_CSWNOTHERCHARGES,0) AS TOTALOTHERS
		, COALESCE(B.STE_CSWNINVADJ,0) AS INVADJ
		, A.TOTALLINECOST+A.TOTALTAX1+A.TOTALTAX2
			+COALESCE(B.DISCOUNT,0)
			+COALESCE(B.STE_CSWNLOCALHANDLINGCHARGE,0)
			+COALESCE(B.STE_CSWNOTHERCHARGES,0)
			+COALESCE(B.STE_CSWNINVADJ,0) AS TOTALCOST
		, B.TOTALCOST AS ORIGTOTALCOST
	FROM (
		SELECT A.INVOICENUM
			, SUM(A.LINECOST) AS TOTALLINECOST
			, SUM(COALESCE(A.TAX1,0)) AS TOTALTAX1, SUM(COALESCE(A.TAX2,0)) AS TOTALTAX2
			--, SUM(COALESCE(A.STE_CSWNDISCOUNT,0)) AS TOTALDISC, SUM(COALESCE(A.STE_CSWNLOCALHANDLINGCHARGE,0)) AS TOTALFREIGHT
			--, SUM(COALESCE(A.STE_CSWNOTHERCHARGES,0)) AS TOTALOTHERS
		FROM MAXIMO.INVOICELINE A
		GROUP BY A.INVOICENUM
	) A
	JOIN MAXIMO.INVOICE B ON B.INVOICENUM=A.INVOICENUM
) B ON B.INVOICENUM=A.INVOICENUM
WHERE 1=1
	AND A.STE_MIGRATIONID IS NOT NULL
	AND (
		A.TOTALCOST!=CAST(B.TOTALCOST AS DECIMAL(12,2))
	)
;

MERGE INTO MAXIMO.INVOICE A
USING "MIGRATION"."BAK_20250804_INVOICE_TOTALCOST" B
ON B.INVOICEID=A.INVOICEID
WHEN MATCHED THEN
UPDATE SET
	A.TOTALCOST=B.NEW_TOTALCOST,
	A.BASETOTALCOST=B.NEW_BASETOTALCOST,
	A.TOTALTAX1=B.NEW_TOTALTAX1,
	A.TOTALTAX2=B.NEW_TOTALTAX2
;

-- --------------------
-- UPDATE INVOICETRANS
-- --------------------

CREATE TABLE "MIGRATION"."PATCH_20250804_INVOICETRANS"  (
	  "VENDOR" VARCHAR(20 OCTETS) NOT NULL , 
	  "INVOICENUM" VARCHAR(15 OCTETS) NOT NULL , 
	  "INVOICELINENUM" INTEGER , 
	  "COSTLINENUM" INTEGER , 
	  "GLDEBITACCT" VARCHAR(110 OCTETS) , 
	  "GLCREDITACCT" VARCHAR(110 OCTETS) , 
	  "CURRENCYCODE" VARCHAR(8 OCTETS) NOT NULL , 
	  "LINECOST" DECIMAL(15,5) NOT NULL , 
	  "TRANSDATE" TIMESTAMP NOT NULL , 
	  "ENTERBY" VARCHAR(100 OCTETS) NOT NULL , 
	  "TRANSTYPE" VARCHAR(12 OCTETS) NOT NULL , 
	  "CURRENCYLINECOST" DECIMAL(12,2) NOT NULL , 
	  "EXCHANGERATE" DECIMAL(14,7) NOT NULL , 
	  "FINANCIALPERIOD" VARCHAR(6 OCTETS) , 
	  "EXCHANGERATE2" DECIMAL(14,7) , 
	  "LINECOST2" DECIMAL(10,2) , 
	  "SENDERSYSID" VARCHAR(50 OCTETS) , 
	  "SOURCESYSID" VARCHAR(10 OCTETS) , 
	  "OWNERSYSID" VARCHAR(10 OCTETS) , 
	  "EXTERNALREFID" VARCHAR(10 OCTETS) , 
	  "SITEID" VARCHAR(8 OCTETS) NOT NULL , 
	  "ORGID" VARCHAR(8 OCTETS) NOT NULL , 
	  "INVOICETRANSID" BIGINT NOT NULL , 
	  "ACTUALDATE" TIMESTAMP NOT NULL , 
	  "STE_MIGRATIONID" BIGINT , 
	  "STE_MIGRATIONDATE" TIMESTAMP 
)   
ORGANIZE BY ROW;

INSERT INTO "MIGRATION"."PATCH_20250804_INVOICETRANS"
(
	INVOICENUM, VENDOR, INVOICELINENUM, COSTLINENUM, GLDEBITACCT, GLCREDITACCT, 
	CURRENCYCODE, LINECOST, TRANSDATE, ENTERBY, TRANSTYPE, CURRENCYLINECOST, EXCHANGERATE, FINANCIALPERIOD, 
	SITEID, ORGID, ACTUALDATE,
	STE_MIGRATIONID, STE_MIGRATIONDATE, INVOICETRANSID
)
SELECT 
	B.INVOICENUM, B.VENDOR, B.INVOICELINENUM, B.COSTLINENUM, B.GLDEBITACCT, B.GLCREDITACCT
	, B.CURRENCYCODE, B.LINECOST, B.TRANSDATE, B.ENTERBY, B.TRANSTYPE, B.CURRENCYLINECOST, B.EXCHANGERATE, FINANCIALPERIOD
	, B.SITEID, B.ORGID, B.ACTUALDATE
	, 20251201 AS STE_MIGRATIONID
	, ADD_HOURS(CURRENT_TIMESTAMP, 8) AS STE_MIGRATIONDATE
	, D.MAXID + ROW_NUMBER() OVER (ORDER BY B.INVOICENUM) AS INVOICETRANSID
FROM (
	SELECT A.INVOICENUM, A.INVOICEID
		, MAX(A.VENDOR) AS VENDOR
		, NULL AS INVOICELINENUM, NULL AS COSTLINENUM
		, NULL AS GLDEBITACCT, NULL AS GLCREDITACCT
		, MAX(A.CURRENCYCODE) AS CURRENCYCODE
		, SUM(A.LINECOST) * MAX(A.EXCHANGERATE) AS LINECOST
		, MAX(A.TRANSDATE) AS TRANSDATE
		, 'MAXADMIN' AS ENTERBY
		, 'TOTAL' AS TRANSTYPE
		, SUM(A.LINECOST) AS CURRENCYLINECOST
		, MAX(A.EXCHANGERATE) AS EXCHANGERATE
		, YEAR(MAX(A.ACTUALDATE)) AS FINANCIALPERIOD
		, 'NEL' AS SITEID, 'SBST' AS ORGID
		, MAX(A.ACTUALDATE) AS ACTUALDATE
	FROM 
	(
		SELECT A.PONUM, A.REVISIONNUM
			, C.INVOICENUM, C.INVOICEID
			, A.STATUS AS POSTATUS, A.RECEIPTS AS PORECEIPTS, C.STATUS AS INVSTATUS
			, CASE 
				/* #1 */ WHEN C.STATUS='PAID' AND A.RECEIPTS='COMPLETE' AND A.STATUS='CLOSE' THEN 'Y'
				/* #2 */ WHEN C.STATUS='PAID' AND A.RECEIPTS='COMPLETE' AND A.STATUS='APPR' THEN 'Y'
				/* #3 */ WHEN C.STATUS='PAID' AND A.RECEIPTS='PARTIAL' AND A.STATUS='APPR' THEN 'Y'
				/* #4 */ WHEN C.STATUS='APPR' AND A.RECEIPTS='COMPLETE' AND A.STATUS='CLOSE' THEN 'Y'
				/* #5 */ WHEN C.STATUS='APPR' AND A.RECEIPTS='COMPLETE' AND A.STATUS='APPR' THEN 'Y'
				/* #7 */ WHEN C.STATUS='ENTERED' AND A.RECEIPTS='PARTIAL' AND A.STATUS='APPR' THEN 'N'
				/* #8 */ WHEN C.STATUS='ENTERED' AND A.RECEIPTS='COMPLETE' AND A.STATUS='APPR' THEN 'N'
				-- ADDITIONAL USE CASES
				/* #9 */ WHEN C.STATUS='APPR' AND A.RECEIPTS='PARTIAL' AND A.STATUS='CLOSE' THEN 'Y'
				/* #10 -- DEPENDANCE ON PATCH FOR PORECEIPT/POSTATUS */ --WHEN C.STATUS='APPR' AND A.RECEIPTS='NONE' AND A.STATUS='WAPPR' THEN 'Y'
				/* #11 */ WHEN C.STATUS='APPR' AND A.RECEIPTS='PARTIAL' AND A.STATUS='APPR' THEN 'Y'
				ELSE 'N'
			  END INVTRANS
			/*, F.receivedqty, F.acceptedqty, F.returnedqty, F.winspqty, F.pendingqty */
			/*, CASE WHEN G.MATRECTRANSID IS NOT NULL THEN 'Y' ELSE 'N' END AS ACCRUAL */
			, ROW_NUMBER() OVER (PARTITION BY A.PONUM, A.REVISIONNUM 
				ORDER BY C.INVOICENUM DESC) RN
			, A.VENDOR, C.CHANGEDATE AS TRANSDATE, C.ENTERDATE AS ACTUALDATE
			, C.CURRENCYCODE, C.EXCHANGERATE, C.EXCHANGEDATE
			, COALESCE(D.LINECOST,0) AS LINECOST
		FROM MAXIMO.PO A
		-- JOIN MAXIMO.POLINE B ON B.PONUM=A.PONUM AND B.REVISIONNUM=A.REVISIONNUM
		JOIN MAXIMO.INVOICE C ON C.PONUM=A.PONUM
		LEFT JOIN MAXIMO.INVOICELINE D ON D.PONUM=A.PONUM AND D.INVOICENUM=C.INVOICENUM
		/* LEFT JOIN MAXIMO.STE_RPT_PO_LIST F ON F.PONUM=A.PONUM AND F.POLINENUM=B.POLINENUM */
		/*
		LEFT JOIN (
			SELECT 
				A.MATRECTRANSID,
				M.PONUM, M.POREVISIONNUM, A.ITEMNUM, L.POLINENUM 
			FROM MAXIMO.STE_RPT_ACCRUAL_STK A
			JOIN MAXIMO.MATRECTRANS M ON M.MATRECTRANSID=A.MATRECTRANSID
			JOIN MAXIMO.POLINE L ON L.PONUM=M.PONUM AND L.REVISIONNUM=M.POREVISIONNUM AND L.ITEMNUM=A.ITEMNUM	
		) G ON G.PONUM=A.PONUM AND G.POLINENUM=B.POLINENUM
		*/
		WHERE A.STE_MIGRATIONID IS NOT NULL
	) A
	WHERE 1=1
		AND A.INVTRANS='Y'
		--AND A.ACCEPTEDQTY=0
	--ORDER BY A.PONUM, A.POLINENUM
	GROUP BY A.INVOICENUM, A.INVOICEID
) B
JOIN (
	SELECT MAX(INVOICETRANSID) AS MAXID FROM MAXIMO.INVOICETRANS
) D ON 1=1
;

-- UPDATED ROWS
-- DROP TABLE "MIGRATION"."BAK_20250804_INVOICETRANS";
CREATE TABLE "MIGRATION"."BAK_20250804_INVOICETRANS"  (
  "INVOICETRANSID" BIGINT NOT NULL , 
  "INVOICENUM" VARCHAR(15 OCTETS) , 
  "LINECOST" DECIMAL(15,5) ,
  "CURRENCYLINECOST" DECIMAL(12,2) ,
  "NEW_LINECOST" DECIMAL(15,5) , 
  "NEW_CURRENCYLINECOST" DECIMAL(12,2) 
)   
ORGANIZE BY ROW;

--DELETE FROM "MIGRATION"."BAK_20250804_INVOICETRANS";
INSERT INTO "MIGRATION"."BAK_20250804_INVOICETRANS" (
	INVOICETRANSID, INVOICENUM, LINECOST, CURRENCYLINECOST, NEW_LINECOST, NEW_CURRENCYLINECOST
)
SELECT B.INVOICETRANSID, B.INVOICENUM, B.LINECOST, B.CURRENCYLINECOST, A.LINECOST AS NEW_LINECOST, A.CURRENCYLINECOST AS NEW_CURRENCYLINECOST
FROM "MIGRATION"."PATCH_20250804_INVOICETRANS" A
JOIN MAXIMO.INVOICETRANS B ON 1=1
	AND B.INVOICENUM=A.INVOICENUM AND B.TRANSTYPE='TOTAL'
WHERE 1=1
	AND (
		B.LINECOST!=CAST(A.LINECOST AS DECIMAL(15,5))
	)
;

MERGE INTO MAXIMO.INVOICETRANS A
USING "MIGRATION"."BAK_20250804_INVOICETRANS" B
ON B.INVOICETRANSID=A.INVOICETRANSID
WHEN MATCHED THEN
UPDATE SET
	A.LINECOST=B.NEW_LINECOST,
	A.CURRENCYLINECOST=B.NEW_CURRENCYLINECOST
;
	
-- NEW ROWS
INSERT INTO MAXIMO.INVOICETRANS
(
	INVOICENUM, VENDOR, INVOICELINENUM, COSTLINENUM, GLDEBITACCT, GLCREDITACCT, 
	CURRENCYCODE, LINECOST, TRANSDATE, ENTERBY, TRANSTYPE, CURRENCYLINECOST, EXCHANGERATE, FINANCIALPERIOD, 
	SITEID, ORGID, ACTUALDATE,
	STE_MIGRATIONID, STE_MIGRATIONDATE, INVOICETRANSID
)
SELECT 
	A.INVOICENUM, A.VENDOR, A.INVOICELINENUM, A.COSTLINENUM, A.GLDEBITACCT, A.GLCREDITACCT, 
	A.CURRENCYCODE, A.LINECOST, A.TRANSDATE, A.ENTERBY, A.TRANSTYPE, A.CURRENCYLINECOST, A.EXCHANGERATE, A.FINANCIALPERIOD, 
	A.SITEID, A.ORGID, A.ACTUALDATE,
	A.STE_MIGRATIONID, A.STE_MIGRATIONDATE
	, D.MAXID + ROW_NUMBER() OVER (ORDER BY A.INVOICENUM) AS INVOICETRANSID
FROM "MIGRATION"."PATCH_20250804_INVOICETRANS" A
LEFT JOIN MAXIMO.INVOICETRANS B ON 1=1
	AND B.INVOICENUM=A.INVOICENUM AND B.TRANSTYPE='TOTAL'
JOIN (
	SELECT MAX(INVOICETRANSID) AS MAXID FROM MAXIMO.INVOICETRANS
) D ON 1=1
WHERE 1=1
	AND B.INVOICETRANSID IS NULL
;

CALL MIGRATION.STE_UPDATE_SEQ('INVOICETRANSSEQ', 'INVOICETRANS', 'INVOICETRANSID');

-- --------------------
-- UPDATE INVOICEMATCH
-- --------------------

-- DROP TABLE "MIGRATION"."PATCH_20250804_INVOICEMATCH";
CREATE TABLE "MIGRATION"."PATCH_20250804_INVOICEMATCH"  (
	  "VENDOR" VARCHAR(20 OCTETS) NOT NULL , 
	  "INVOICENUM" VARCHAR(15 OCTETS) NOT NULL , 
	  "INVOICELINENUM" INTEGER NOT NULL , 
	  "PONUM" VARCHAR(10 OCTETS) , 
	  "POLINENUM" INTEGER , 
	  "TRANSTYPE" VARCHAR(16 OCTETS) NOT NULL , 
	  "TRANSDATE" TIMESTAMP , 
	  "QUANTITY" DECIMAL(15,2) , 
	  "LINECOST" DECIMAL(10,2) NOT NULL , 
	  "COSTLINENUM" INTEGER NOT NULL , 
	  "MATRECTRANSID" BIGINT , 
	  "SERVRECTRANSID" BIGINT , 
	  "SITEID" VARCHAR(8 OCTETS) NOT NULL , 
	  "ORGID" VARCHAR(8 OCTETS) NOT NULL , 
	  "USERMATCHED" INTEGER NOT NULL , 
	  "INVOICEMATCHID" BIGINT NOT NULL , 
	  "CONVERSION" DECIMAL(18,5) , 
	  "POREVISIONNUM" INTEGER , 
	  "POSITEID" VARCHAR(8 OCTETS) , 
	  "REVERSED" INTEGER NOT NULL , 
	  "STE_MIGRATIONID" BIGINT , 
	  "STE_MIGRATIONDATE" TIMESTAMP )   
ORGANIZE BY ROW;

--DELETE FROM "MIGRATION"."PATCH_20250804_INVOICEMATCH";
INSERT INTO "MIGRATION"."PATCH_20250804_INVOICEMATCH"
(
	VENDOR, INVOICENUM, INVOICELINENUM, PONUM, POLINENUM, 
	TRANSTYPE, TRANSDATE, QUANTITY, LINECOST, COSTLINENUM, MATRECTRANSID, SERVRECTRANSID, 
	SITEID, ORGID, USERMATCHED, INVOICEMATCHID, CONVERSION, POREVISIONNUM, POSITEID, REVERSED,
	STE_MIGRATIONID, STE_MIGRATIONDATE
)
SELECT A.VENDOR, A.INVOICENUM, A.INVOICELINENUM, A.PONUM, A.POLINENUM
	, 'PURCHORDR' AS TRANSTYPE
	, COALESCE(B.TRANSDATE, C.TRANSDATE) AS TRANSDATE
	, COALESCE(B.QUANTITY, C.QUANTITY) AS QUANTITY
	, COALESCE(B.LINECOST, C.LINECOST) AS LINECOST
	, A.COSTLINENUM, B.MATRECTRANSID, C.SERVRECTRANSID
	, 'NEL' AS SITEID, 'SBST' AS ORGID, 1 AS USERMATCHED
	, D.MAXID + ROW_NUMBER() OVER (ORDER BY A.PONUM, B.POLINENUM) AS INVOICEMATCHID
	, COALESCE(B.CONVERSION, 0) AS CONVERSION
	, A.REVISIONNUM AS POREVISIONNUM, 'NEL' AS POSITEID
	, 0 AS REVERSED
	, 20251201 AS STE_MIGRATIONID
	, ADD_HOURS(CURRENT_TIMESTAMP, 8) AS STE_MIGRATIONDATE
FROM 
(
	SELECT A.PONUM, A.REVISIONNUM, B.POLINENUM
		, B.ITEMNUM, B.ORDERQTY AS QUANTITY, B.LINECOST
		, C.INVOICENUM, D.INVOICELINENUM, E.COSTLINENUM
		, A.STATUS AS POSTATUS, A.RECEIPTS AS PORECEIPTS, C.STATUS AS INVSTATUS
		, CASE 
			WHEN C.INVOICENUM IS NULL OR D.INVOICELINENUM IS NULL THEN 'N'
			/* #1 */ WHEN C.STATUS='PAID' AND A.RECEIPTS='COMPLETE' AND A.STATUS='CLOSE' THEN 'Y'
			/* #2 */ WHEN C.STATUS='PAID' AND A.RECEIPTS='COMPLETE' AND A.STATUS='APPR' THEN 'Y'
			/* #3 */ WHEN C.STATUS='PAID' AND A.RECEIPTS='PARTIAL' AND A.STATUS='APPR' THEN 'Y'
			/* #4 */ WHEN C.STATUS='APPR' AND A.RECEIPTS='COMPLETE' AND A.STATUS='CLOSE' THEN 'Y'
			/* #5 */ WHEN C.STATUS='APPR' AND A.RECEIPTS='COMPLETE' AND A.STATUS='APPR' THEN 'Y'
			/* #7 */ WHEN C.STATUS='ENTERED' AND A.RECEIPTS='PARTIAL' AND A.STATUS='APPR' THEN 'Y'
			/* #8 */ WHEN C.STATUS='ENTERED' AND A.RECEIPTS='COMPLETE' AND A.STATUS='APPR' THEN 'Y'
			-- ADDITIONAL USE CASES
			/* #9 */ WHEN C.STATUS='APPR' AND A.RECEIPTS='PARTIAL' AND A.STATUS='CLOSE' THEN 'Y'
			/* #10 -- DEPENDANCE ON PATCH FOR PORECEIPT/POSTATUS */ --WHEN C.STATUS='APPR' AND A.RECEIPTS='NONE' AND A.STATUS='WAPPR' THEN 'Y'
			/* #11 */ WHEN C.STATUS='APPR' AND A.RECEIPTS='PARTIAL' AND A.STATUS='APPR' THEN 'Y'
			ELSE 'N'
		  END INVMATCH
		, CASE 
			WHEN C.INVOICENUM IS NULL OR D.INVOICELINENUM IS NULL THEN 'N'
			/* #1 */ WHEN C.STATUS='PAID' AND A.RECEIPTS='COMPLETE' AND A.STATUS='CLOSE' THEN 'Y'
			/* #2 */ WHEN C.STATUS='PAID' AND A.RECEIPTS='COMPLETE' AND A.STATUS='APPR' THEN 'Y'
			/* #3 */ WHEN C.STATUS='PAID' AND A.RECEIPTS='PARTIAL' AND A.STATUS='APPR' THEN 'Y'
			/* #4 */ WHEN C.STATUS='APPR' AND A.RECEIPTS='COMPLETE' AND A.STATUS='CLOSE' THEN 'Y'
			/* #5 */ WHEN C.STATUS='APPR' AND A.RECEIPTS='COMPLETE' AND A.STATUS='APPR' THEN 'Y'
			/* #7 */ WHEN C.STATUS='ENTERED' AND A.RECEIPTS='PARTIAL' AND A.STATUS='APPR' THEN 'N'
			/* #8 */ WHEN C.STATUS='ENTERED' AND A.RECEIPTS='COMPLETE' AND A.STATUS='APPR' THEN 'N'
			-- ADDITIONAL USE CASES
			/* #9 */ WHEN C.STATUS='APPR' AND A.RECEIPTS='PARTIAL' AND A.STATUS='CLOSE' THEN 'Y'
			/* #10 -- DEPENDANCE ON PATCH FOR PORECEIPT/POSTATUS */ --WHEN C.STATUS='APPR' AND A.RECEIPTS='NONE' AND A.STATUS='WAPPR' THEN 'Y'
			/* #11 */ WHEN C.STATUS='APPR' AND A.RECEIPTS='PARTIAL' AND A.STATUS='APPR' THEN 'Y'
			ELSE 'N'
		  END INVTRANS
		/*, F.receivedqty, F.acceptedqty, F.returnedqty, F.winspqty, F.pendingqty */
		/*, CASE WHEN G.MATRECTRANSID IS NOT NULL THEN 'Y' ELSE 'N' END AS ACCRUAL */
		, ROW_NUMBER() OVER (PARTITION BY A.PONUM, A.REVISIONNUM, B.POLINENUM 
			ORDER BY (CASE WHEN D.INVOICELINENUM IS NOT NULL THEN 1 ELSE 0 END) DESC, 
				C.INVOICENUM DESC, D.INVOICELINENUM DESC, E.COSTLINENUM DESC) RN
		, A.VENDOR, A.STATUSDATE
	FROM MAXIMO.PO A
	JOIN MAXIMO.POLINE B ON B.PONUM=A.PONUM AND B.REVISIONNUM=A.REVISIONNUM
	LEFT JOIN MAXIMO.INVOICE C ON C.PONUM=A.PONUM
	LEFT JOIN MAXIMO.INVOICELINE D ON D.INVOICENUM=C.INVOICENUM AND D.POLINENUM=B.POLINENUM
	LEFT JOIN MAXIMO.INVOICECOST E ON E.INVOICENUM=C.INVOICENUM AND E.INVOICELINENUM=D.INVOICELINENUM
	/* LEFT JOIN MAXIMO.STE_RPT_PO_LIST F ON F.PONUM=A.PONUM AND F.POLINENUM=B.POLINENUM */
	/*
	LEFT JOIN (
		SELECT 
			A.MATRECTRANSID,
			M.PONUM, M.POREVISIONNUM, A.ITEMNUM, L.POLINENUM 
		FROM MAXIMO.STE_RPT_ACCRUAL_STK A
		JOIN MAXIMO.MATRECTRANS M ON M.MATRECTRANSID=A.MATRECTRANSID
		JOIN MAXIMO.POLINE L ON L.PONUM=M.PONUM AND L.REVISIONNUM=M.POREVISIONNUM AND L.ITEMNUM=A.ITEMNUM	
	) G ON G.PONUM=A.PONUM AND G.POLINENUM=B.POLINENUM
	*/
	WHERE A.STE_MIGRATIONID IS NOT NULL
) A
LEFT JOIN MAXIMO.MATRECTRANS B ON B.PONUM=A.PONUM AND B.POLINENUM=A.POLINENUM AND B.POREVISIONNUM=A.REVISIONNUM
	AND B.ISSUETYPE='RECEIPT' AND B.INVOICENUM=A.INVOICENUM
LEFT JOIN MAXIMO.SERVRECTRANS C ON C.PONUM=A.PONUM AND C.POLINENUM=A.POLINENUM AND C.POREVISIONNUM=A.REVISIONNUM
	AND C.ISSUETYPE IN ('RECEIPT','INVOICE') AND C.INVOICENUM=A.INVOICENUM
JOIN (
	SELECT MAX(INVOICEMATCHID) AS MAXID FROM MAXIMO.INVOICEMATCH
) D ON 1=1
WHERE 1=1
	AND A.INVMATCH='Y'
	--AND A.ACCEPTEDQTY=0
	AND (B.MATRECTRANSID IS NOT NULL OR C.SERVRECTRANSID IS NOT NULL)
	--NOTE: TOTAL 625 INVOICE-INVOICELINE HAS NO MATCHING RECEIPT
	--AND B.MATRECTRANSID IS NULL AND C.SERVRECTRANSID IS NULL
	--NOTE: VALIDATE SAMPLING
	--AND A.PONUM IN ('BB60019435', 'BB60010185', 'BB60024345', 'BB60023513', 'BB60020914', 'OS0146/018')
ORDER BY A.PONUM, A.POLINENUM
;

-- UPDATED ROWS
-- DROP TABLE "MIGRATION"."BAK_20250804_INVOICEMATCH";
CREATE TABLE "MIGRATION"."BAK_20250804_INVOICEMATCH"  (
  "INVOICEMATCHID" BIGINT NOT NULL , 
  "INVOICENUM" VARCHAR(15 OCTETS) , 
  "INVOICELINENUM" INTEGER , 
  "MATRECTRANSID" BIGINT , 
  "SERVRECTRANSID" BIGINT , 
  "QUANTITY" DECIMAL(15,2) ,
  "LINECOST" DECIMAL(10,2) ,
  "NEW_QUANTITY" DECIMAL(15,2) , 
  "NEW_LINECOST" DECIMAL(10,2) 
)   
ORGANIZE BY ROW;

--DELETE FROM "MIGRATION"."BAK_20250804_INVOICEMATCH";
INSERT INTO "MIGRATION"."BAK_20250804_INVOICEMATCH" (
	INVOICEMATCHID, INVOICENUM, INVOICELINENUM, MATRECTRANSID, SERVRECTRANSID
	, QUANTITY, LINECOST, NEW_QUANTITY, NEW_LINECOST
)
SELECT B.INVOICEMATCHID
	, B.INVOICENUM, B.INVOICELINENUM, B.MATRECTRANSID, B.SERVRECTRANSID
	, B.QUANTITY, B.LINECOST, A.QUANTITY AS NEW_QUANTITY, A.LINECOST AS NEW_LINECOST
	--, A.MATRECTRANSID, A.SERVRECTRANSID
FROM "MIGRATION"."PATCH_20250804_INVOICEMATCH" A
JOIN MAXIMO.INVOICEMATCH B ON 1=1
	AND (COALESCE(B.MATRECTRANSID,0)=COALESCE(A.MATRECTRANSID,1) 
		OR COALESCE(B.SERVRECTRANSID,0)=COALESCE(A.SERVRECTRANSID,1)
	)
	AND B.INVOICENUM=A.INVOICENUM AND B.INVOICELINENUM=A.INVOICELINENUM
WHERE 1=1
	--AND B.INVOICEMATCHID IS NULL
	AND (B.QUANTITY!=CAST(A.QUANTITY AS DECIMAL(15,2)) 
		OR B.LINECOST!=CAST(A.LINECOST AS DECIMAL(10,2))
	)
;

--SELECT * FROM "MIGRATION"."PATCH_20250804_INVOICEMATCH" WHERE SERVRECTRANSID=120164;

MERGE INTO MAXIMO.INVOICEMATCH A
USING "MIGRATION"."BAK_20250804_INVOICEMATCH" B
ON B.INVOICEMATCHID=A.INVOICEMATCHID
WHEN MATCHED THEN
UPDATE SET
	A.QUANTITY=B.NEW_QUANTITY, 
	A.LINECOST=B.NEW_LINECOST
;

-- NEW ROWS
INSERT INTO MAXIMO.INVOICEMATCH
(
	VENDOR, INVOICENUM, INVOICELINENUM, PONUM, POLINENUM, 
	TRANSTYPE, TRANSDATE, QUANTITY, LINECOST, COSTLINENUM, MATRECTRANSID, SERVRECTRANSID, 
	SITEID, ORGID, USERMATCHED, CONVERSION, POREVISIONNUM, POSITEID, REVERSED,
	STE_MIGRATIONID, STE_MIGRATIONDATE, INVOICEMATCHID
)
SELECT 
	A.VENDOR, A.INVOICENUM, A.INVOICELINENUM, A.PONUM, A.POLINENUM, 
	A.TRANSTYPE, A.TRANSDATE, A.QUANTITY, A.LINECOST, A.COSTLINENUM, A.MATRECTRANSID, A.SERVRECTRANSID, 
	A.SITEID, A.ORGID, A.USERMATCHED, A.CONVERSION, A.POREVISIONNUM, A.POSITEID, A.REVERSED,
	A.STE_MIGRATIONID, A.STE_MIGRATIONDATE
	, D.MAXID + ROW_NUMBER() OVER (ORDER BY A.PONUM, A.POLINENUM) AS INVOICEMATCHID
FROM "MIGRATION"."PATCH_20250804_INVOICEMATCH" A
LEFT JOIN MAXIMO.INVOICEMATCH B ON 1=1
	AND (B.MATRECTRANSID=A.MATRECTRANSID OR B.SERVRECTRANSID=A.SERVRECTRANSID)
	AND B.INVOICENUM=A.INVOICENUM AND B.INVOICELINENUM=A.INVOICELINENUM
JOIN (
	SELECT MAX(INVOICEMATCHID) AS MAXID FROM MAXIMO.INVOICEMATCH
) D ON 1=1
WHERE 1=1
	AND B.INVOICEMATCHID IS NULL
;

CALL MIGRATION.STE_UPDATE_SEQ('INVOICEMATCHSEQ', 'INVOICEMATCH', 'INVOICEMATCHID');


--SELECT A.INVOICELINEID, A.INVOICENUM, A.INVOICELINENUM, A.ITEMNUM
--	, A.LINECOST, A.INVOICEQTY, A.UNITCOST
--	, CAST(B.INV_ITEM_BASE_VAL AS DECIMAL(12,2)) AS NEW_LINECOST
--	, CAST(B.INV_ITEM_BASE_VAL/A.INVOICEQTY AS DECIMAL(12,2)) AS NEW_UNITCOST
--	, (A.INVOICEQTY*A.UNITCOST) - CAST(B.INV_ITEM_BASE_VAL AS DECIMAL(12,2))
--	, A.INVOICEQTY * CAST(B.INV_ITEM_BASE_VAL/A.INVOICEQTY AS DECIMAL(12,2)) AS CALCVAL
--	, CAST(B.INV_UNIT_RATE*B.INV_QTY AS DECIMAL(12,2)) AS ORIGCALCVAL
--	, A.LINECOST AS INVLINECOST --, A.INVOICEQTY, A.UNITCOST AS INVUNITCOST
--	, A.INVOICEQTY*A.UNITCOST AS CALC_INVLINECOST
--	, C.LINECOST AS POLINECOST --, C.ORDERQTY, C.UNITCOST AS POUNITCOST
--	, C.ORDERQTY*C.UNITCOST AS CALC_POLINECOST
--	, CAST(B.INV_UNIT_RATE AS DECIMAL(12,2)) AS ORIGUNITCOST, A.UNITCOST AS INVUNITCOST, C.UNITCOST AS POUNITCOST
--	, A.STE_MIGRATIONID, C.STE_MIGRATIONID
--FROM MAXIMO.INVOICELINE A
--JOIN MIGRATION.CSWN_INVOICELINE B ON B.PK_INV_ITEMS=A.STE_MIGRATIONID
--LEFT JOIN MAXIMO.POLINE C ON C.PONUM=A.PONUM AND C.ITEMNUM=A.ITEMNUM
--WHERE 1=1 
--	AND (
--		A.LINECOST!=A.INVOICEQTY*A.UNITCOST
--	)
--	AND ABS(A.LINECOST - (A.INVOICEQTY*A.UNITCOST)) > 0.01
--
--	AND A.INVOICEQTY*A.UNITCOST=CAST(B.INV_ITEM_BASE_VAL AS DECIMAL(12,2))
--	AND A.LINECOST!=A.INVOICEQTY*A.UNITCOST
--	-- AND C.LINECOST!=C.ORDERQTY*C.UNITCOST
--	--AND A.UNITCOST!=C.UNITCOST AND ABS(A.UNITCOST-C.UNITCOST)<=0.01
--	--AND C.ORDERQTY*C.UNITCOST!=A.INVOICEQTY*A.UNITCOST
--	AND ABS(A.LINECOST - (A.INVOICEQTY*A.UNITCOST)) > 0.01
--;
--
--SELECT A.INVOICELINEID, A.INVOICENUM, A.INVOICELINENUM, A.PONUM, C.POLINENUM, A.ITEMNUM
----	, CAST(B.INV_UNIT_RATE*B.INV_QTY AS DECIMAL(12,2)) AS ORIGCALCVAL
--	, A.LINECOST AS INVLINECOST --, A.INVOICEQTY, A.UNITCOST AS INVUNITCOST
--	, A.INVOICEQTY*A.UNITCOST AS CALC_INVLINECOST
--	, C.LINECOST AS POLINECOST --, C.ORDERQTY, C.UNITCOST AS POUNITCOST
--	, C.ORDERQTY*C.UNITCOST AS CALC_POLINECOST
--	, CAST(B.INV_ITEM_BASE_VAL AS DECIMAL(12,2)) AS CSWN_INVLINECOST
--	, CAST(D.PO_UNIT_RATE*D.PO_QTY AS DECIMAL(12,2)) AS CSWN_POLINECOST
--	, E.CURRENCYCODE
--	, E.EXCHANGERATE
--	, CAST(B.INV_ITEM_BASE_VAL AS DECIMAL(12,2))-A.LINECOST AS DIFF
--	, (CAST(B.INV_ITEM_BASE_VAL AS DECIMAL(12,2))-A.LINECOST) * E.EXCHANGERATE AS DIFF_SGD
--	, A.UNITCOST AS INVUNITCOST, C.UNITCOST AS POUNITCOST
--	, A.INVOICEQTY, C.ORDERQTY
--	, A.STE_MIGRATIONID, C.STE_MIGRATIONID
--FROM MAXIMO.INVOICELINE A
--JOIN MIGRATION.CSWN_INVOICELINE B ON B.PK_INV_ITEMS=A.STE_MIGRATIONID
--LEFT JOIN MAXIMO.POLINE C ON C.PONUM=A.PONUM AND C.ITEMNUM=A.ITEMNUM
--LEFT JOIN MIGRATION.CSWN_POLINE D ON D.PK_PO_ITEMS=C.STE_MIGRATIONID
--JOIN MAXIMO.INVOICE E ON E.INVOICENUM=A.INVOICENUM
--WHERE 1=1 
--	AND A.LINECOST != CAST(B.INV_ITEM_BASE_VAL AS DECIMAL(12,2))
--	--AND A.UNITCOST!=C.UNITCOST
--	AND A.INVOICEQTY=C.ORDERQTY
--	AND A.LINECOST!=C.LINECOST

CALL MIGRATION.STE_FINISH_PATCH('20250804-QTY-1PCT-DIFFERENCE');