CALL MIGRATION.STE_START_PATCH('20250811-02-QTY-1PCT-DIFFERENCE');

-- CONTRACTLINE
-- PRLINE
-- POLINE
-- RFQLINE
-- QUOTATIONLINE
-- INVOICELINE
-- INVUSELINE
-- MATRECTRANS
-- MATUSETRANS
-- SERVRECTRANS
-- WPITEM


CALL MIGRATION.STE_FINISH_PATCH('20250811-02-QTY-1PCT-DIFFERENCE');