UPDATE MAXIMO.LOCATIONS SET TYPE='TRAIN' WHERE TYPE='RST';

UPDATE maximo.routes SET ste_loctype='TRAIN' WHERE STE_LOCTYPE='RST'; 
UPDATE maximo.PM SET ste_loctype='TRAIN' WHERE STE_LOCTYPE='RST';
UPDATE maximo.JOBPLAN SET ste_loctype='TRAIN' WHERE STE_LOCTYPE='RST'; 