CALL MIGRATION.STE_START_PATCH('20250530-01-CONTRACTLINE');

--CREATE TABLE "MAXIMO"."CSWN_CONTRACTLINE" 
--   (	
--	"PK_SUPPL_AGREE_ITEM" BIGINT, 
--	"TIMESTAMP" DECIMAL(10,0), 
--	"SAGREE_CODE" VARCHAR(10), 
--	"SAGREE_STATUS" DECIMAL(5,0), 
--	"SUPL_CD" VARCHAR(20),
--	"ITEM_CD" VARCHAR(20), 
--	"ITEM_SHORT" VARCHAR(100), 
--	"NSITEM_CD" VARCHAR(20), 
--	"NSITEM_SHORT" VARCHAR(100), 
--	"S_ITEM_UNIT" VARCHAR(6), 
--	"S_LAT_UNIT_RATE" DECIMAL(28,12), 
--	"S_ITEM_REF" VARCHAR(20), 
--	"YTD_QTY" DECIMAL(28,12), 
--	"TOD_QTY" DECIMAL(28,12), 
--	"LYR_QTY" DECIMAL(28,12), 
--	"YTD_PO_VAL" DECIMAL(28,12), 
--	"TOD_PO_VAL" DECIMAL(28,12), 
--	"LYR_PO_VAL" DECIMAL(28,12), 
--	"YTD_REJ_QTY" DECIMAL(28,12), 
--	"TOD_REJ_QTY" DECIMAL(28,12), 
--	"LYR_REJ_QTY" DECIMAL(28,12), 
--	"YTD_PO_NO" DECIMAL(5,0), 
--	"TOD_PO_NO" DECIMAL(5,0), 
--	"LYR_PO_NO" DECIMAL(5,0), 
--	"YTD_DEL_NO" DECIMAL(5,0), 
--	"TOD_DEL_NO" DECIMAL(5,0), 
--	"LYR_DEL_NO" DECIMAL(5,0), 
--	"YTD_REJ_NO" DECIMAL(5,0), 
--	"TOD_REJ_NO" DECIMAL(5,0), 
--	"LYR_REJ_NO" DECIMAL(5,0), 
--	"S_L_PO" VARCHAR(10), 
--	"S_L_DT_PO" DECIMAL(10,0), 
--	"PRI_TRND" DECIMAL(28,12), 
--	"S_AVG_LEAD_DYS" DECIMAL(5,0), 
--	"REP_ORDR_FLG" DECIMAL(3,0), 
--	"S_BASE_MIN_ORD" DECIMAL(28,12), 
--	"S_DISC_QORV" DECIMAL(3,0), 
--	"S_PRT_RMK_FLG" DECIMAL(3,0),
--	LINENUM INTEGER
--);

-- BRING DATA IN "MAXIMO"."CSWN_CONTRACTLINE" FROM ON-PREM

CREATE TABLE MIGRATION.BAK_20250530_CONTRACTLINE (
	CONTRACTLINEID BIGINT,
	CONTRACTNUM VARCHAR(10),
	CONTRACTLINENUM INTEGER,
	ITEMNUM VARCHAR(30),
	UNITCOST DECIMAL(10,2),
	NEW_UNITCOST DECIMAL(10,2),
	STE_MIGRATIONID BIGINT
)
;

INSERT INTO MIGRATION.BAK_20250530_CONTRACTLINE (
	CONTRACTLINEID, CONTRACTNUM, CONTRACTLINENUM, ITEMNUM, UNITCOST, NEW_UNITCOST, STE_MIGRATIONID
)
SELECT 
	A.CONTRACTLINEID, A.CONTRACTNUM, A.CONTRACTLINENUM, A.ITEMNUM, A.UNITCOST, B.S_LAT_UNIT_RATE AS NEW_UNITCOST, A.STE_MIGRATIONID
FROM MAXIMO.CONTRACTLINE A
JOIN MAXIMO.CSWN_CONTRACTLINE B ON B.PK_SUPPL_AGREE_ITEM=A.STE_MIGRATIONID
WHERE A.UNITCOST!=B.S_LAT_UNIT_RATE
;

MERGE INTO MAXIMO.CONTRACTLINE A
USING (
	SELECT 
		A.CONTRACTLINEID, A.CONTRACTNUM, A.CONTRACTLINENUM, A.ITEMNUM, A.UNITCOST, B.S_LAT_UNIT_RATE AS NEW_UNITCOST, A.STE_MIGRATIONID
	FROM MAXIMO.CONTRACTLINE A
	JOIN MAXIMO.CSWN_CONTRACTLINE B ON B.PK_SUPPL_AGREE_ITEM=A.STE_MIGRATIONID
	WHERE A.UNITCOST!=B.S_LAT_UNIT_RATE
) B ON B.CONTRACTLINEID=A.CONTRACTLINEID
WHEN MATCHED THEN
UPDATE SET
	UNITCOST=B.NEW_UNITCOST
;

CALL MIGRATION.STE_FINISH_PATCH('20250530-01-CONTRACTLINE');