CALL MIGRATION.STE_START_PATCH('20260514-MATUSETRANS-COST');

-- NOTE:
-- Currently MATUSETRANS.UNITCOST is set to ACTUALCOST which is migrated from ISS_ITEMS.ISS_VAL.
-- This is not correct. Looking at coswin table ISS_ITEMS, the field ISS_VAL is the total value of the issue.
-- So to get the unit cost, it has to be calculated as ISS_VAL/ISS_QTY

CREATE TABLE IF NOT EXISTS "MIGRATION"."BAK_20260514_MATUSETRANS"  (
  "MATUSETRANSID" BIGINT NOT NULL , 
  "ITEMNUM" VARCHAR(30 OCTETS) , 
  "STORELOC" VARCHAR(16 OCTETS) , 
  "TRANSDATE" TIMESTAMP NOT NULL , 
  "QUANTITY" DECIMAL(15,2) NOT NULL,
  "UNITCOST" DECIMAL(13,5) NOT NULL , 
  "ACTUALCOST" DECIMAL(13,5) NOT NULL , 
  "LINECOST" DECIMAL(13,5) NOT NULL , 
  "CURRENCYCODE" VARCHAR(8 OCTETS) NOT NULL , 
  "CURRENCYUNITCOST" DECIMAL(10,2) , 
  "CURRENCYLINECOST" DECIMAL(10,2) , 
  "NEW_UNITCOST" DECIMAL(13,5) NOT NULL , 
  "NEW_LINECOST" DECIMAL(13,5) NOT NULL )    
 ORGANIZE BY ROW;

-- UPDATE ISSUE UNITCOST WHEN UNITCOST=0 AND ACTUALCOST!=0
-- NOTE: ONLY UPDATE RECORDS WITH LINECOST<=99999999 BECAUSE CURRENTLY LINECOST DATATYPE IS DECIMAL(13,5) WHICH ONLY ALLOW 8 DIGIT NUMBER
INSERT INTO "MIGRATION"."BAK_20260514_MATUSETRANS"(
	MATUSETRANSID, ITEMNUM, STORELOC, TRANSDATE, QUANTITY, UNITCOST, ACTUALCOST, LINECOST, CURRENCYCODE, CURRENCYUNITCOST, CURRENCYLINECOST,
	NEW_UNITCOST, NEW_LINECOST
)
SELECT 
	MATUSETRANSID, ITEMNUM, STORELOC, TRANSDATE, QUANTITY, UNITCOST, ACTUALCOST, LINECOST, CURRENCYCODE, CURRENCYUNITCOST, CURRENCYLINECOST,
	ABS(ACTUALCOST/QUANTITY) AS NEW_UNITCOST, 
	CASE WHEN QUANTITY>=0 THEN -1*ABS(ACTUALCOST) ELSE ABS(ACTUALCOST) END AS NEW_LINECOST
	--, ISSUETYPE, QUANTITY
FROM maximo.matusetrans
WHERE STE_MIGRATIONID IS NOT NULL
;

MERGE INTO MAXIMO.MATUSETRANS A
USING "MIGRATION"."BAK_20260514_MATUSETRANS" B
ON B.MATUSETRANSID=A.MATUSETRANSID
WHEN MATCHED THEN
UPDATE SET
	UNITCOST=B.NEW_UNITCOST,
	LINECOST=B.NEW_LINECOST,
	ACTUALCOST=B.NEW_UNITCOST,
	CURRENCYUNITCOST=B.NEW_UNITCOST,
	CURRENCYLINECOST=B.NEW_LINECOST,
	EXCHANGERATE=1
;

CALL MIGRATION.STE_FINISH_PATCH('20260514-MATUSETRANS-COST');