CALL MIGRATION.STE_START_PATCH('20260430_INSPECTION_WEIGHTAGE');

-- IMPORTANT: BRING MIGRATION.PATCH_20260430_INSPECTION_CHECKLIST FROM ON-PREM

-- IMPORTANT
-- 1. Resize (in database AND in maximo db configuration) inspfieldresult.txtresponse ke varchar(1000)
-- 2. Resize (in maximo db configuration - database column is already 4 decimal point) 
--    inspquestion.ste_weightage and inspfield.ste_weightage to 4 decimal points.

--DROP TABLE "MIGRATION"."PATCH_20260430_INSPECTION_CHECKLIST";
--
--CREATE TABLE "MIGRATION"."PATCH_20260430_INSPECTION_CHECKLIST"  (
--	  "ID" INTEGER , 
--	  "DESCRIPTION" VARCHAR(1000 OCTETS) , 
--	  "LEVEL1" INTEGER , 
--	  "LEVEL2" INTEGER , 
--	  "LEVEL3" INTEGER , 
--	  "ROWTYPE" VARCHAR(50 OCTETS) , 
--	  "FIELDTYPE" VARCHAR(50 OCTETS) , 
--	  "WEIGHTAGE" DECIMAL(8,4) , 
--	  "BASELINE" INTEGER 
--)    
-- ORGANIZE BY ROW;
--
--DELETE FROM MIGRATION.PATCH_20260430_INSPECTION_CHECKLIST;
--
--INSERT INTO MIGRATION.PATCH_20260430_INSPECTION_CHECKLIST
--(ID, DESCRIPTION, LEVEL1, LEVEL2, LEVEL3, ROWTYPE, FIELDTYPE, WEIGHTAGE, BASELINE)
--SELECT ID, DESCRIPTION, LEVEL1, LEVEL2, LEVEL3, ROWTYPE, FIELDTYPE
--	, CASE WHEN TRIM(COALESCE(WEIGHTAGE,''))='' THEN NULL
--		   ELSE CAST(WEIGHTAGE AS DECIMAL(8,4))
--	  END AS WEIGHTAGE
--	, BASELINE
--FROM MIGRATION.PATCH_INSPECTION_CHECKLIST
--WHERE ID>1;
--
--SELECT * FROM MIGRATION.PATCH_20260430_INSPECTION_CHECKLIST WHERE WEIGHTAGE IS NULL;
--SELECT * FROM MIGRATION.PATCH_20260430_INSPECTION_CHECKLIST WHERE WEIGHTAGE IS NOT NULL;
--
--SELECT * FROM MIGRATION.PATCH_20260430_INSPECTION_CHECKLIST WHERE ID=158051;
--SELECT * FROM MIGRATION.PATCH_INSPECTION_CHECKLIST WHERE ID=158051;
--
--SELECT * FROM MIGRATION.PATCH_20260430_INSPECTION_CHECKLIST WHERE ID=162773;
--SELECT * FROM MIGRATION.PATCH_INSPECTION_CHECKLIST WHERE ID=162773;

--SELECT * FROM MAXIMO.INSPQUESTION WHERE STE_MIGRATIONID=162773

-- DROP TABLE IF EXISTS "MIGRATION"."BAK_INSPQUESTION_20260430";
CREATE TABLE IF NOT EXISTS "MIGRATION"."BAK_INSPQUESTION_20260430"  (
	"INSPQUESTIONID" BIGINT, 
	"DESCRIPTION" VARCHAR(1000 OCTETS) , 
	"STE_WEIGHTAGE" DECIMAL(8,4) , 
	"NEW_WEIGHTAGE" DECIMAL(8,4) , 
	"STE_MIGRATIONID" BIGINT
	)   
 ORGANIZE BY ROW;

INSERT INTO "MIGRATION"."BAK_INSPQUESTION_20260430" (
	INSPQUESTIONID, DESCRIPTION, STE_WEIGHTAGE, NEW_WEIGHTAGE, STE_MIGRATIONID
)
SELECT B.INSPQUESTIONID, B.DESCRIPTION, B.STE_WEIGHTAGE, A.WEIGHTAGE AS NEW_WEIGHTAGE
	, A.ID AS STE_MIGRATIONID 
FROM MIGRATION.PATCH_20260430_INSPECTION_CHECKLIST A
JOIN MAXIMO.INSPQUESTION B ON B.STE_MIGRATIONID=A.ID AND B.DESCRIPTION=A.DESCRIPTION 
	AND B.STE_WEIGHTAGE!=A.WEIGHTAGE
WHERE A.ROWTYPE='QUESTION';

-- TODO: NEED TO CONSIDER THOSE WITH UNITS AND BASELINE FIELD
CREATE TABLE IF NOT EXISTS "MIGRATION"."BAK_INSPFIELD_20260430"  (
	"INSPFIELDID" BIGINT, 
	"DESCRIPTION" VARCHAR(1000 OCTETS) , 
	"STE_WEIGHTAGE" DECIMAL(8,4) , 
	"NEW_WEIGHTAGE" DECIMAL(8,4) , 
	"STE_MIGRATIONID" BIGINT
	)   
 ORGANIZE BY ROW;

INSERT INTO "MIGRATION"."BAK_INSPFIELD_20260430" (
	INSPFIELDID, DESCRIPTION, STE_WEIGHTAGE, NEW_WEIGHTAGE, STE_MIGRATIONID
)
SELECT C.INSPFIELDID, C.DESCRIPTION, C.STE_WEIGHTAGE, A.WEIGHTAGE AS NEW_WEIGHTAGE 
	, A.ID AS STE_MIGRATIONID 
FROM MIGRATION.PATCH_20260430_INSPECTION_CHECKLIST A
JOIN MAXIMO.INSPFIELD B ON B.STE_MIGRATIONID=A.ID 
	AND B.DESCRIPTION=A.DESCRIPTION 
	AND B.STE_WEIGHTAGE!=A.WEIGHTAGE
JOIN MAXIMO.INSPFIELD C ON C.INSPFORMNUM=B.INSPFORMNUM AND C.REVISION=B.REVISION
	AND C.STE_MIGRATIONID=B.STE_MIGRATIONID
WHERE A.ROWTYPE='FIELD';

INSERT INTO "MIGRATION"."BAK_INSPFIELD_20260430" (
	INSPFIELDID, DESCRIPTION, STE_WEIGHTAGE, NEW_WEIGHTAGE, STE_MIGRATIONID
)
SELECT D.INSPFIELDID, D.DESCRIPTION, D.STE_WEIGHTAGE, A.WEIGHTAGE AS NEW_WEIGHTAGE 
	, A.ID AS STE_MIGRATIONID
	--, A.DESCRIPTION, LENGTH(D.DESCRIPTION), LENGTH(A.DESCRIPTION)
FROM MIGRATION.PATCH_20260430_INSPECTION_CHECKLIST A
JOIN (
	SELECT A.INSPFORMNUM, MAX(A.REVISION) AS REVISION
	FROM MAXIMO.INSPECTIONFORM A
	GROUP BY A.INSPFORMNUM
) B ON 1=1
JOIN MAXIMO.INSPFIELD C ON C.INSPFORMNUM=B.INSPFORMNUM AND C.REVISION=B.REVISION
	AND C.STE_MIGRATIONID=A.ID
	AND C.STE_WEIGHTAGE!=A.WEIGHTAGE
	AND C.DESCRIPTION NOT LIKE '%BASELINE%'
JOIN MAXIMO.INSPFIELD D ON D.INSPFORMNUM=B.INSPFORMNUM AND D.REVISION=B.REVISION
	AND D.STE_MIGRATIONID=C.STE_MIGRATIONID
LEFT JOIN "MIGRATION"."BAK_INSPFIELD_20260430" X ON X.INSPFIELDID=D.INSPFIELDID
WHERE A.ROWTYPE='FIELD'
	AND A.DESCRIPTION!=C.DESCRIPTION
	AND SUBSTR(A.DESCRIPTION, 1, INSTR(A.DESCRIPTION, ':', 1) + 5) 
			= SUBSTR(C.DESCRIPTION, 1, INSTR(A.DESCRIPTION, ':', 1) + 5) 
	AND X.INSPFIELDID IS NULL
ORDER BY D.INSPFIELDID
;

-- UPDATE INSPQUESTION
MERGE INTO MAXIMO.INSPQUESTION A
USING "MIGRATION"."BAK_INSPQUESTION_20260430" B ON B.INSPQUESTIONID=A.INSPQUESTIONID
WHEN MATCHED THEN
UPDATE SET 
	A.STE_WEIGHTAGE=B.NEW_WEIGHTAGE
;

-- UPDATE INSPFIELD
MERGE INTO MAXIMO.INSPFIELD A
USING "MIGRATION"."BAK_INSPFIELD_20260430" B ON B.INSPFIELDID=A.INSPFIELDID
WHEN MATCHED THEN
UPDATE SET 
	A.STE_WEIGHTAGE=B.NEW_WEIGHTAGE
;

CALL MIGRATION.STE_FINISH_PATCH('20260430_INSPECTION_WEIGHTAGE');