-- DROP PROCEDURE MAXIMO.PRC_RPT_WORKORDER_OPSHOURS_WEEKLY;

--#SET TERMINATOR /

CREATE OR REPLACE PROCEDURE MAXIMO.STE_RPT_INSPECTION_LIST_V2(
	IN P_STARTDATE DATE, IN P_ENDDATE DATE, IN P_MAINTENTITY VARCHAR(20) 
)
LANGUAGE SQL
SPECIFIC STE_RPT_INSPECTION_LIST_V2
DYNAMIC RESULT SETS 1
MODIFIES SQL DATA
BEGIN
   DECLARE V_VERSION VARCHAR(10) DEFAULT 'v2.1';
   DECLARE V_CURRENT_TS TIMESTAMP DEFAULT NULL;
  
   DECLARE C1 CURSOR WITH RETURN TO CLIENT FOR
	SELECT 
		V_CURRENT_TS AS "TIMESTAMP", V_VERSION AS VERSION, P_STARTDATE AS STARTDATE, P_ENDDATE AS ENDDATE--, P_MAINTENTITY AS P_MAINTENTITY
		, A.INSPECTIONRESULTID, A.RESULTNUM, A.INSPFORMNUM, A.REVISION, A.REFERENCEOBJECT, A.REFERENCEOBJECTID AS WONUM
		, A.ASSET AS ASSETNUM, A.LOCATION AS LOCATIONCODE, A.CREATEDBY, A.CREATEDATE, A.DUEDATE, A.STATUS
		--, B.NAME, B.STE_TEMPLATE
		, COALESCE(C.DATERESPONSE, A.CREATEDATE) AS ASSESSMENTDATE, D.TXTRESPONSE AS ASSESSOR1, E.TXTRESPONSE AS ASSESSOR2
		, F.STE_CWEQCODE AS EQPTCODE, F.DESCRIPTION AS ASSET, G.DESCRIPTION AS LOCATION
		, A.STE_PHYSICALSCORE, A.STE_FUNCTIONALSCORE, A.STE_RESULTROWSTAMP
		, F.STE_MAINTDEPT, H.STE_MAINTENTITY
	FROM MAXIMO.INSPECTIONRESULT A
	JOIN MAXIMO.INSPECTIONFORM B ON B.INSPFORMNUM=A.INSPFORMNUM AND B.REVISION=A.REVISION
	LEFT JOIN (
		SELECT A.INSPFIELDRESULTID, A.RESULTNUM, A.INSPFORMNUM, A.REVISION, A.DATERESPONSE
		FROM MAXIMO.INSPFIELDRESULT A
		JOIN MAXIMO.INSPFIELD B ON B.INSPFIELDNUM=A.INSPFIELDNUM 
			AND B.INSPQUESTIONNUM=A.INSPQUESTIONNUM
			AND B.INSPFORMNUM=A.INSPFORMNUM AND B.REVISION=A.REVISION
		--JOIN MAXIMO.INSPQUESTION C ON C.INSPQUESTIONNUM=A.INSPQUESTIONNUM
		--	AND C.INSPFORMNUM=A.INSPFORMNUM AND C.REVISION=A.REVISION
		JOIN MAXIMO.INSPECTIONRESULT D ON D.RESULTNUM=A.RESULTNUM
		WHERE 1=1
			AND D.CREATEDATE BETWEEN P_STARTDATE AND P_ENDDATE
			AND B.DESCRIPTION='Date of Assessment'
	) C ON C.INSPFORMNUM=A.INSPFORMNUM AND C.REVISION=A.REVISION AND C.RESULTNUM=A.RESULTNUM
	LEFT JOIN (
		SELECT A.INSPFIELDRESULTID, A.RESULTNUM, A.INSPFORMNUM, A.REVISION, A.TXTRESPONSE
		FROM MAXIMO.INSPFIELDRESULT A
		JOIN MAXIMO.INSPFIELD B ON B.INSPFIELDNUM=A.INSPFIELDNUM 
			AND B.INSPQUESTIONNUM=A.INSPQUESTIONNUM
			AND B.INSPFORMNUM=A.INSPFORMNUM AND B.REVISION=A.REVISION
		--JOIN MAXIMO.INSPQUESTION C ON C.INSPQUESTIONNUM=A.INSPQUESTIONNUM
		--	AND C.INSPFORMNUM=A.INSPFORMNUM AND C.REVISION=A.REVISION
		JOIN MAXIMO.INSPECTIONRESULT D ON D.RESULTNUM=A.RESULTNUM
		WHERE 1=1
			AND D.CREATEDATE BETWEEN P_STARTDATE AND P_ENDDATE
			AND B.DESCRIPTION='Assessor 1'
			--AND A.RESULTNUM='IR10000022'
	) D ON D.INSPFORMNUM=A.INSPFORMNUM AND D.REVISION=A.REVISION AND D.RESULTNUM=A.RESULTNUM
	LEFT JOIN (
		SELECT A.INSPFIELDRESULTID, A.RESULTNUM, A.INSPFORMNUM, A.REVISION, A.TXTRESPONSE
		FROM MAXIMO.INSPFIELDRESULT A
		JOIN MAXIMO.INSPFIELD B ON B.INSPFIELDNUM=A.INSPFIELDNUM 
			AND B.INSPQUESTIONNUM=A.INSPQUESTIONNUM
			AND B.INSPFORMNUM=A.INSPFORMNUM AND B.REVISION=A.REVISION
		--JOIN MAXIMO.INSPQUESTION C ON C.INSPQUESTIONNUM=A.INSPQUESTIONNUM
		--	AND C.INSPFORMNUM=A.INSPFORMNUM AND C.REVISION=A.REVISION
		JOIN MAXIMO.INSPECTIONRESULT D ON D.RESULTNUM=A.RESULTNUM
		WHERE 1=1
			AND D.CREATEDATE BETWEEN P_STARTDATE AND P_ENDDATE
			AND B.DESCRIPTION='Assessor 2'
	) E ON E.INSPFORMNUM=A.INSPFORMNUM AND E.REVISION=A.REVISION AND E.RESULTNUM=A.RESULTNUM
	JOIN MAXIMO.ASSET F ON F.ASSETNUM=A.ASSET
	JOIN MAXIMO.LOCATIONS G ON G.LOCATION=A.LOCATION
	JOIN MAXIMO.WORKORDER H ON H.WONUM=A.REFERENCEOBJECTID
	WHERE 1=1
		AND (B.STE_TEMPLATE IN ('ACA', 'ACA1', 'ACA2', 'ACA3'))
		AND A.CREATEDATE>=P_STARTDATE AND A.CREATEDATE<=P_ENDDATE
		AND (P_MAINTENTITY IS NULL OR H.STE_MAINTENTITY=P_MAINTENTITY)
	ORDER BY COALESCE(C.DATERESPONSE, A.CREATEDATE)
    ;
   
   -- UPDATE FIRST
   MERGE INTO MAXIMO.INSPECTIONRESULT A
   USING (
	    WITH ASSESSMENTRESULT AS (
			-- AGGREGATE IN PHYSICAL AND FUNCTIONAL LEVEL
			SELECT 
				C.RESULTNUM, C.INSPFORMNUM, C.REVISION, C.GROUPFLAG
				, SUM(C.SCORE * COALESCE(C.GROUPWEIGHTAGE,1)) AS SCORE
				, SUM(C.BASELINE * COALESCE(C.GROUPWEIGHTAGE,1)) AS BASELINE
				, MAX(C.ROWSTAMP) AS ROWSTAMP
			FROM (
				-- AGGREGATE IN GROUP LEVEL
				SELECT 
					B.RESULTNUM, B.INSPFORMNUM, B.REVISION, B.GROUPID
					, SUM(B.SCORE * COALESCE(B.QUESTIONWEIGHTAGE,1)) AS SCORE
					, SUM(B.BASELINE * COALESCE(B.QUESTIONWEIGHTAGE,1)) AS BASELINE
					, MAX(COALESCE(C.STE_WEIGHTAGE,1)) AS GROUPWEIGHTAGE
					, CASE WHEN B.GROUPID%2=1 THEN 'PHYSICAL' ELSE 'FUNCTIONAL' END AS GROUPFLAG
					, MAX(B.ROWSTAMP) AS ROWSTAMP
				FROM (
					-- AGGREGATE IN QUESTION LEVEL
					SELECT 
						A.RESULTNUM, A.INSPFORMNUM, A.REVISION, A.GROUPID, A.INSPQUESTIONNUM
						, SUM(CAST(COALESCE(A.SCORE,0) AS INTEGER) * COALESCE(A.FIELDWEIGHTAGE,1)) AS SCORE
						, SUM(CAST(COALESCE(A.BASELINE,0) AS INTEGER) * COALESCE(A.FIELDWEIGHTAGE,1)) AS BASELINE
						, MAX(A.QUESTIONWEIGHTAGE) AS QUESTIONWEIGHTAGE
						--, MAX(A.QUESTIONBASELINE) AS QUESTIONBASELINE
						, MAX(A.ROWSTAMP) AS ROWSTAMP
					FROM (
						SELECT 
							B.RESULTNUM, B.INSPFORMNUM, B.REVISION, C.GROUPID, C.INSPQUESTIONNUM, D.INSPFIELDNUM
							, X.INSPFIELDRESULTID, X.INSPFIELDRESULTNUM, X.TXTRESPONSE
							-- DEFAULT FOR NOTYET-FILLED SCORE = 0
						    , CASE WHEN X.TXTRESPONSE IS NULL THEN 0
							       WHEN INSTR(X.TXTRESPONSE, '(')=0 OR INSTR(X.TXTRESPONSE, ')')=0 THEN 0
						           ELSE SUBSTRING(X.TXTRESPONSE, INSTR(X.TXTRESPONSE, '(') + 1, 
						    			INSTR(X.TXTRESPONSE, ')') - INSTR(X.TXTRESPONSE, '(') - 1)
						      END AS SCORE
						    , COALESCE(Y.NUMRESPONSE, 0) AS BASELINE
							--, B.ASSET AS ASSETNUM, B.LOCATION, B.REFERENCEOBJECTID AS WONUM
							--, C.DESCRIPTION AS QUESTION, C.GROUPID, C.SEQUENCE AS QUESTIONSEQ, C.GROUPSEQ
							--, D.INSPFIELDID, D.DESCRIPTION AS FIELD, D.SEQUENCE AS FIELDSEQ
							, COALESCE(C.STE_WEIGHTAGE,1) AS QUESTIONWEIGHTAGE /*, COALESCE(C.STE_BASELINE,0) AS QUESTIONBASELINE */
							, COALESCE(D.STE_WEIGHTAGE,1) AS FIELDWEIGHTAGE /*, COALESCE(D.STE_BASELINE,0) AS FIELDBASELINE */
							, CASE WHEN COALESCE(X.ROWSTAMP,0)>COALESCE(Y.ROWSTAMP,0) THEN COALESCE(X.ROWSTAMP,0)
								   ELSE COALESCE(Y.ROWSTAMP,0)
							  END AS ROWSTAMP
						FROM MAXIMO.INSPECTIONRESULT B
						JOIN MAXIMO.INSPECTIONFORM E ON E.INSPFORMNUM=B.INSPFORMNUM AND E.REVISION=B.REVISION
						JOIN MAXIMO.INSPQUESTION C ON C.INSPFORMNUM=B.INSPFORMNUM AND C.REVISION=B.REVISION
						-- ACTUAL FIELD
						JOIN MAXIMO.INSPFIELD D ON D.INSPFORMNUM=B.INSPFORMNUM AND D.REVISION=B.REVISION
							AND D.INSPQUESTIONNUM=C.INSPQUESTIONNUM
							AND D.FIELDTYPE='SO' AND MOD(D.SEQUENCE, 2)=0
						LEFT JOIN MAXIMO.INSPFIELDRESULT X ON X.RESULTNUM=B.RESULTNUM
							AND X.INSPQUESTIONNUM=C.INSPQUESTIONNUM
							AND X.INSPFIELDNUM=D.INSPFIELDNUM
						-- BASELINE FIELD
						LEFT JOIN MAXIMO.INSPFIELD G ON G.INSPFORMNUM=B.INSPFORMNUM AND G.REVISION=B.REVISION
							AND G.INSPQUESTIONNUM=C.INSPQUESTIONNUM
							AND G.FIELDTYPE='SO' AND G.SEQUENCE=D.SEQUENCE-1 
						LEFT JOIN MAXIMO.INSPFIELDRESULT Y ON Y.RESULTNUM=B.RESULTNUM
							AND Y.INSPQUESTIONNUM=C.INSPQUESTIONNUM
							AND Y.INSPFIELDNUM=G.INSPFIELDNUM
						/*
						JOIN (
							SELECT A.RESULTNUM, MAX(COALESCE(A.STE_RESULTROWSTAMP,0)) AS OLDRESULTROWSTAMP, MAX(B.ROWSTAMP) AS NEWRESULTROWSTAMP
							FROM MAXIMO.INSPECTIONRESULT A
							JOIN MAXIMO.INSPFIELDRESULT B ON B.RESULTNUM=A.RESULTNUM
							JOIN MAXIMO.INSPFIELD D ON D.INSPFORMNUM=A.INSPFORMNUM AND D.REVISION=A.REVISION
								AND D.INSPFIELDNUM=B.INSPFIELDNUM
								AND D.FIELDTYPE='SO'
							WHERE 1=1
								AND A.CREATEDATE BETWEEN P_STARTDATE AND P_ENDDATE
							GROUP BY A.RESULTNUM
						) H ON H.RESULTNUM=B.RESULTNUM AND H.OLDRESULTROWSTAMP<H.NEWRESULTROWSTAMP
						*/
						WHERE 1=1
							AND B.CREATEDATE BETWEEN P_STARTDATE AND P_ENDDATE
							AND (
								(E.STE_TEMPLATE='ACA1' AND (C.GROUPID=3 OR C.GROUPID=4) AND COALESCE(C.SEQUENCE,0)>0)
								OR (E.STE_TEMPLATE='ACA2' AND (C.GROUPID=3 OR C.GROUPID=4) AND COALESCE(C.SEQUENCE,0)>0)
								OR (E.STE_TEMPLATE IN ('ACA3') AND C.GROUPID>2 AND C.GROUPID<91 AND COALESCE(C.SEQUENCE,0)>0)
							)
						ORDER BY B.RESULTNUM, C.INSPQUESTIONNUM, D.INSPFIELDNUM
					) A
					GROUP BY A.RESULTNUM, A.INSPFORMNUM, A.REVISION, A.GROUPID, A.INSPQUESTIONNUM
				) B
				LEFT JOIN MAXIMO.INSPQUESTION C ON 1=1
					AND C.INSPFORMNUM=B.INSPFORMNUM AND C.REVISION=B.REVISION
					AND C.GROUPID=B.GROUPID AND COALESCE(C.SEQUENCE,0)=0
				GROUP BY B.RESULTNUM, B.INSPFORMNUM, B.REVISION, B.GROUPID
			) C
			GROUP BY C.RESULTNUM, C.INSPFORMNUM, C.REVISION, C.GROUPFLAG
	    )
		SELECT
			A.RESULTNUM, A.INSPFORMNUM, A.REVISION
			, A.SCORE AS PHYSICALSCORE, A.BASELINE AS PHYSICALBASELINE
			, B.SCORE AS FUNCTIONALSCORE, B.BASELINE AS FUNCTIONALBASELINE
			, CASE WHEN A.ROWSTAMP>B.ROWSTAMP THEN A.ROWSTAMP ELSE B.ROWSTAMP END AS RESULTROWSTAMP
			, A.ROWSTAMP AS PHYSICALROWSTAMP, B.ROWSTAMP AS FUNCTIONALROWSTAMP
		FROM ASSESSMENTRESULT A
		JOIN ASSESSMENTRESULT B ON B.RESULTNUM=A.RESULTNUM
			-- AND B.INSPFORMNUM=A.INSPFORMNUM AND B.REVISION=A.REVISION
			AND B.GROUPFLAG='FUNCTIONAL'
		WHERE 1=1
			AND A.GROUPFLAG='PHYSICAL'
   ) B ON B.RESULTNUM=A.RESULTNUM
   WHEN MATCHED THEN
   UPDATE SET
   		STE_RESULTROWSTAMP=B.RESULTROWSTAMP,
   		STE_PHYSICALSCORE=B.PHYSICALSCORE,
   		STE_PHYSICALBASELINE=B.PHYSICALBASELINE,
   		STE_FUNCTIONALSCORE=B.FUNCTIONALSCORE,
   		STE_FUNCTIONALBASELINE=B.FUNCTIONALBASELINE
   ;

   SET V_CURRENT_TS=CURRENT_TIMESTAMP;

--   IF (UPPER(P_STARTDATE)='NULL' OR P_STARTDATE='') THEN SET P_STARTDATE=CURRENT_TIMESTAMP; END IF;
--   IF (UPPER(P_ENDDATE)='NULL' OR P_ENDDATE='') THEN SET P_ENDDATE=CURRENT_TIMESTAMP; END IF;
   IF (UPPER(P_MAINTENTITY)='NULL' OR P_MAINTENTITY='') THEN SET P_MAINTENTITY=NULL; END IF;

   OPEN C1;

END;
/

CALL MAXIMO.STE_RPT_INSPECTION_LIST_V2('2026-01-01', '2026-12-31', NULL);