CALL MIGRATION.STE_START_PATCH('20260510-PO-POSTATUS');

-- WAPPR POSTATUS
INSERT INTO MAXIMO.POSTATUS (
	PONUM, STATUS, CHANGEDATE, CHANGEBY, SITEID, ORGID, REVISIONNUM, POSTATUSID
)
SELECT A.PONUM, 'WAPPR' AS POSTATUS
	, COALESCE(A.ORDERDATE, A.STATUSDATE) AS POCHANGEDATE, COALESCE(A.PURCHASEAGENT, 'MAXADMIN') AS POCHANGEBY
	, A.SITEID, A.ORGID, A.REVISIONNUM
	, C.MAXID + ROW_NUMBER() OVER (ORDER BY A.PONUM) AS POSTATUSID
	--, A.STATUS, A.STATUSDATE, A.ORDERDATE, A.CHANGEDATE
	--, A.STE_POCREATEDDATEINCOUPA, A.STE_CREATIONDATE, A.STE_EMAIL_APPR_TRACEDATE
	--, A.STE_MIGRATIONID
FROM MAXIMO.PO A
LEFT JOIN MAXIMO.POSTATUS B ON B.PONUM=A.PONUM AND B.STATUS='WAPPR'
JOIN (
	SELECT MAX(POSTATUSID) AS MAXID FROM MAXIMO.POSTATUS
) C ON 1=1
WHERE B.PONUM IS NULL
	AND A.STE_MIGRATIONID IS NOT NULL
;

-- APPR POSTATUS
INSERT INTO MAXIMO.POSTATUS (
	PONUM, STATUS, CHANGEDATE, CHANGEBY, SITEID, ORGID, REVISIONNUM, POSTATUSID
)
SELECT A.PONUM, 'APPR' AS POSTATUS, A.STATUSDATE AS POCHANGEDATE, COALESCE(A.CHANGEBY, 'MAXADMIN') AS POCHANGEBY
	, A.SITEID, A.ORGID, A.REVISIONNUM
	, C.MAXID + ROW_NUMBER() OVER (ORDER BY A.PONUM) AS POSTATUSID
	--, A.STATUS, A.STATUSDATE, A.ORDERDATE, A.CHANGEDATE
	--, A.STE_POCREATEDDATEINCOUPA, A.STE_CREATIONDATE, A.STE_EMAIL_APPR_TRACEDATE
	--, A.STE_MIGRATIONID
FROM MAXIMO.PO A
LEFT JOIN MAXIMO.POSTATUS B ON B.PONUM=A.PONUM AND B.STATUS='APPR'
JOIN (
	SELECT MAX(POSTATUSID) AS MAXID FROM MAXIMO.POSTATUS
) C ON 1=1
WHERE B.PONUM IS NULL
	--AND A.STE_MIGRATIONID IS NOT NULL
	AND A.STATUS NOT IN ('WAPPR', 'CAN')
;

-- CURRENT STATUS FOR POSTATUS
INSERT INTO MAXIMO.POSTATUS (
	PONUM, STATUS, CHANGEDATE, CHANGEBY, SITEID, ORGID, REVISIONNUM, POSTATUSID
)
SELECT A.PONUM, A.STATUS AS POSTATUS, A.STATUSDATE AS POCHANGEDATE, COALESCE(A.CHANGEBY, 'MAXADMIN') AS POCHANGEBY
	, A.SITEID, A.ORGID, A.REVISIONNUM
	, C.MAXID + ROW_NUMBER() OVER (ORDER BY A.PONUM) AS POSTATUSID
	--, A.STATUS, A.STATUSDATE, A.ORDERDATE, A.CHANGEDATE
	--, A.STE_POCREATEDDATEINCOUPA, A.STE_CREATIONDATE, A.STE_EMAIL_APPR_TRACEDATE
	--, A.STE_MIGRATIONID
FROM MAXIMO.PO A
LEFT JOIN MAXIMO.POSTATUS B ON B.PONUM=A.PONUM AND B.STATUS=A.STATUS
JOIN (
	SELECT MAX(POSTATUSID) AS MAXID FROM MAXIMO.POSTATUS
) C ON 1=1
WHERE B.PONUM IS NULL
	--AND A.STE_MIGRATIONID IS NOT NULL
	AND A.STATUS NOT IN ('WAPPR', 'CAN', 'APPR')
;

CALL MIGRATION.STE_UPDATE_SEQ('POSTATUSSEQ', 'POSTATUS', 'POSTATUSID');

CALL MIGRATION.STE_FINISH_PATCH('20260510-PO-POSTATUS');