CALL MIGRATION.STE_START_PATCH('20260123-REPORT-ACCRUAL-NS-ITEMNUM');

CREATE OR REPLACE VIEW MAXIMO.STE_RPT_ACCRUAL_STK AS
SELECT
	'2.8' AS VERSION
	, m.MATRECTRANSID
	, m.STE_MIGRATIONID AS PK_RCT_ITEMS
	, m.PACKINGSLIPNUM AS PACKINGSLIPNUM
	, CAST(m.ACTUALDATE AS DATE) AS TRANSDATE
	, m.ACTUALDATE AS TRANSDATETIME
	, m.LINECOST AS LINECOST
	, 'STK' AS STK_NS
	, m.ITEMNUM
	, i.STE_CSWNITEMNO AS COSWIN_ITEM_CODE
	, i.DESCRIPTION AS ITEM_DESCRIPTION
	, m.STE_CSWNGRNNUM AS GRNUM
	, m.STE_CSWNGRNDATE AS GRDATE
	, c.STE_CSWNSAPVNDCODE AS SAP_VENDOR_CODE
	, c.NAME AS SUPPLIER_NAME
	, m.GLDEBITACCT
	, m.COSTCENTER
	, m.SAP_GL_CODE
	--, coa.GLCOMP02 AS COSTCENTER 
	--, coa.GLCOMP03 AS SAP_GL_CODE 
	--, coalesce(pc.QUANTITY, m.STE_CSWNACPQTY) AS QUANTITY_PER_CC
	, CASE WHEN m.COMPLETEDDATE<='2025-03-30' THEN COALESCE(m.STE_CSWNACPQTY, m.QUANTITY) 
		   ELSE m.QUANTITY
	  END AS QUANTITY
	, m.ORDERQTY
	, l.INVOICEQTY
	, COALESCE(t1.ACCEPTEDQTY,0) + COALESCE(t2.ACCEPTEDQTY,0) AS ACCEPTEDQTY
	--, m.STATUS
	, m.PL_GLDEBITACCT
	, m.PL_COSTCENTER
	, m.PL_SAP_GL_CODE
	, m.PONUM, m.POREVISIONNUM, m.POLINENUM
FROM (
	SELECT m.* 
	, CASE WHEN m.GLDEBITACCT IS NULL THEN NULL
	       WHEN length(m.GLDEBITACCT) - length(replace(m.GLDEBITACCT,'-','')) >= 2 THEN
				SUBSTR(m.GLDEBITACCT, LOCATE('-', m.GLDEBITACCT)+1, LOCATE('-', m.GLDEBITACCT, LOCATE('-', m.GLDEBITACCT)+1)-LOCATE('-', m.GLDEBITACCT)-1)
		   ELSE SUBSTR(m.GLDEBITACCT, LOCATE('-', m.GLDEBITACCT)+1)
	  END AS COSTCENTER
	, CASE WHEN m.GLDEBITACCT IS NULL THEN NULL
	       WHEN length(m.GLDEBITACCT) - length(replace(m.GLDEBITACCT,'-','')) < 2 THEN NULL
		   ELSE SUBSTR(m.GLDEBITACCT, LOCATE('-', m.GLDEBITACCT, LOCATE('-', m.GLDEBITACCT)+1)+1)
	  END AS SAP_GL_CODE
	, pl.ORDERQTY
	, pl.GLDEBITACCT AS PL_GLDEBITACCT
	, CASE WHEN pl.GLDEBITACCT IS NULL THEN NULL
	       WHEN length(pl.GLDEBITACCT) - length(replace(pl.GLDEBITACCT,'-','')) >= 2 THEN
				SUBSTR(pl.GLDEBITACCT, LOCATE('-', pl.GLDEBITACCT)+1, LOCATE('-', pl.GLDEBITACCT, LOCATE('-', pl.GLDEBITACCT)+1)-LOCATE('-', pl.GLDEBITACCT)-1)
		   ELSE SUBSTR(pl.GLDEBITACCT, LOCATE('-', pl.GLDEBITACCT)+1)
	  END AS PL_COSTCENTER
	, CASE WHEN m.GLDEBITACCT IS NULL THEN NULL
	       WHEN length(pl.GLDEBITACCT) - length(replace(pl.GLDEBITACCT,'-','')) < 2 THEN NULL
		   ELSE SUBSTR(pl.GLDEBITACCT, LOCATE('-', pl.GLDEBITACCT, LOCATE('-', pl.GLDEBITACCT)+1)+1)
	  END AS PL_SAP_GL_CODE
	FROM (
		-- no inspection and migrated data
		SELECT m.matrectransid, m.ponum, m.polinenum, m.porevisionnum, m.transdate, m.statusdate AS completeddate, m.statusdate AS actualdate
			, m.itemnum, (m.quantity-m.rejectqty) AS quantity, m.linecost, m.STE_CSWNGRNNUM, m.STE_CSWNGRNDATE, m.PACKINGSLIPNUM
			, m.GLDEBITACCT, m.STE_MIGRATIONID, M.STE_CSWNACPQTY, M.STE_CSWNRCTQTY, M.STE_CSWNRTNTOSUPL, M.STE_CSWNRCTSTATUS
		FROM maximo.MATRECTRANS m
		WHERE m.ISSUETYPE='RECEIPT' AND m.STATUS='COMP' AND m.FROMSTORELOC IS NULL AND m.TOSTORELOC!='L100000019292'	
			--AND m.ponum='AA10016094'
		
		UNION
		
		-- inspection
		SELECT r.matrectransid, r.ponum, r.polinenum, r.porevisionnum, r.transdate, m.transdate AS completeddate, m.actualdate AS actualdate
			, r.itemnum, (m.quantity+COALESCE(rtn.quantity,0)) AS quantity, m.linecost, r.STE_CSWNGRNNUM, r.STE_CSWNGRNDATE, r.PACKINGSLIPNUM
			, r.GLDEBITACCT, r.STE_MIGRATIONID, r.STE_CSWNACPQTY, r.STE_CSWNRCTQTY, r.STE_CSWNRTNTOSUPL, r.STE_CSWNRCTSTATUS
			--, rtn.tostoreloc, r.tostoreloc, m.tostoreloc
		FROM maximo.MATRECTRANS r
		-- JOIN maximo.MATRECTRANS m ON r.matrectransid=m.receiptref
		JOIN (
			SELECT m.receiptref, m.tostoreloc
				, sum(m.quantity) AS quantity, sum(m.linecost) AS linecost, max(m.transdate) AS transdate, max(m.actualdate) AS actualdate
			FROM maximo.MATRECTRANS m
			WHERE m.ISSUETYPE='TRANSFER' 
				AND m.STATUS='COMP' 
				AND m.FROMSTORELOC='L100000019292' 
				AND m.TOSTORELOC IS NOT NULL 
				AND m.TOSTORELOC!='L100000019292'
			GROUP BY m.receiptref, m.tostoreloc
		) m ON m.receiptref=r.matrectransid
        LEFT JOIN (
        	SELECT rtn.receiptref, rtn.tostoreloc, sum(rtn.quantity) AS quantity 
        	FROM maximo.matrectrans rtn
        	WHERE rtn.issuetype = 'RETURN'
        	GROUP BY rtn.receiptref, rtn.tostoreloc
        ) rtn ON 1=1
        	AND rtn.receiptref=m.receiptref AND rtn.tostoreloc=m.tostoreloc 
		WHERE 1=1
			--AND r.ponum='AA10016094'
			--and r.STE_CSWNGRNNUM='GRN25/0307'
	) m
	JOIN maximo.POLINE pl ON pl.PONUM=m.PONUM AND pl.POLINENUM=m.POLINENUM AND pl.REVISIONNUM=m.POREVISIONNUM
) m
JOIN maximo.PO po ON po.PONUM=m.PONUM AND po.REVISIONNUM=m.POREVISIONNUM
JOIN maximo.COMPANIES c ON c.COMPANY=po.VENDOR 
JOIN maximo.ITEM i ON i.ITEMNUM=m.ITEMNUM
--JOIN maximo.POLINE pl ON pl.PONUM=m.PONUM AND pl.POLINENUM=m.POLINENUM AND pl.REVISIONNUM=m.POREVISIONNUM
LEFT JOIN maximo.CHARTOFACCOUNTS coa ON coa.GLACCOUNT=m.GLDEBITACCT
-- LEFT JOIN maximo.STE_CSWNRECEIPT_PER_CC pc ON pc.MATRECTRANSID=m.MATRECTRANSID
-- total invoiced
LEFT JOIN (
	SELECT l.PONUM, l.POLINENUM, l.POREVISIONNUM, SUM(INVOICEQTY) AS INVOICEQTY
	FROM maximo.INVOICELINE l
	GROUP BY l.PONUM, l.POLINENUM, l.POREVISIONNUM
) l ON l.PONUM=m.PONUM AND l.POLINENUM=m.POLINENUM AND l.POREVISIONNUM=m.POREVISIONNUM
-- total received and accepted
LEFT JOIN (
	-- no inspection and migrated data
	SELECT m.ponum, m.polinenum, m.porevisionnum, sum(m.quantity-m.rejectqty) AS ACCEPTEDQTY
	FROM maximo.MATRECTRANS m
	WHERE m.ISSUETYPE='RECEIPT' AND m.STATUS='COMP' AND m.FROMSTORELOC IS NULL AND m.TOSTORELOC!='L100000019292'	
	GROUP BY m.PONUM, m.POLINENUM, m.POREVISIONNUM
) t1 ON t1.PONUM=m.PONUM AND t1.POLINENUM=m.POLINENUM AND t1.POREVISIONNUM=m.POREVISIONNUM
LEFT JOIN (
	-- with inspection
	SELECT r.ponum, r.polinenum, r.porevisionnum, sum(m.quantity+COALESCE(rtn.quantity,0)) AS ACCEPTEDQTY
	FROM maximo.MATRECTRANS m
	JOIN maximo.MATRECTRANS r ON r.matrectransid=m.receiptref
	LEFT JOIN maximo.matrectrans rtn ON rtn.issuetype='RETURN' AND rtn.receiptref=m.receiptref AND rtn.tostoreloc=m.tostoreloc 
	WHERE m.ISSUETYPE='TRANSFER' AND m.STATUS='COMP' AND m.FROMSTORELOC='L100000019292' AND m.TOSTORELOC IS NOT NULL AND m.TOSTORELOC!='L100000019292'
	GROUP BY r.ponum, r.polinenum, r.porevisionnum
) t2 ON t2.PONUM=m.PONUM AND t2.POLINENUM=m.POLINENUM AND t2.POREVISIONNUM=m.POREVISIONNUM
-- Ideally we created records here for migrated data. But at the moment, none is created
LEFT JOIN maximo.INVOICEMATCH im ON im.MATRECTRANSID=m.MATRECTRANSID
WHERE 1=1
	--AND m.ISSUETYPE IN ('RECEIPT')	-- MOVED TO SUBQUERY
	AND po.STATUS IN (SELECT VALUE FROM MAXIMO.SYNONYMDOMAIN WHERE DOMAINID='POSTATUS' AND MAXVALUE IN ('APPR', 'INPRG', 'CLOSE', 'REVISE'))
	-- Accrual: Receipt which has not been invoiced
	AND COALESCE(l.INVOICEQTY,0) < m.ORDERQTY
	AND COALESCE(l.INVOICEQTY,0) < (COALESCE(t1.ACCEPTEDQTY,0) + COALESCE(t2.ACCEPTEDQTY,0))
	AND im.INVOICEMATCHID IS NULL
	-- valid qty
	AND (
		-- before migration, use ACP_QTY
		(m.COMPLETEDDATE<='2025-03-30' AND COALESCE(m.STE_CSWNACPQTY, m.QUANTITY) > 0)
		-- after migration, use QUANTITY
		OR (m.COMPLETEDDATE>'2025-03-30' AND m.QUANTITY>0)
	)
	--AND m.INSPECTEDQTY <> m.REJECTQTY
	-- Valid SAPGL
	--AND ( coa.GLCOMP03 IS NOT NULL ) 
	--AND ( coa.GLCOMP03 BETWEEN '100000' AND '299999' ) 
	--AND ( coa.GLCOMP03 <> '113601' ) 
	-- Valid costcenter: not necessary since now costcenter is part of GLDEBITACCT
	--AND ( coa.GLCOMP02 IS NOT NULL ) 
	-- LEGACY FROM COSWIN: receiptval > 0
	AND m.LINECOST>0
	-- LEGACY FROM COSWIN: receiptstatus != fully invoiced
	AND ( CHR(COALESCE(m.STE_CSWNRCTSTATUS,50)) <> '3' )	-- 51
	-- LEGACY FROM COSWIN
	AND ( m.PONUM <> 'EE10005692' ) 
	AND ( m.PONUM <> 'EE10005693' )  
	AND ( coalesce(m.STE_CSWNRCTQTY,1) <> coalesce(m.STE_CSWNRTNTOSUPL,0) )  
	--AND m.STATUS NOT IN ('WINSP', 'WASSET')	-- MOVED TO SUBQUERY
	--AND m.STE_CSWNGRNNUM IN ('25/0264', '25/0263')
;

CREATE OR REPLACE VIEW MAXIMO.STE_RPT_ACCRUAL_NS AS
SELECT
	'2.4' AS VERSION
	, m.SERVRECTRANSID
	, m.STE_MIGRATIONID AS PK_RCT_ITEMS
	, m.PACKINGSLIPNUM AS PACKINGSLIPNUM
	, CAST(m.TRANSDATE AS DATE) AS TRANSDATE
	, m.TRANSDATE AS TRANSDATETIME
	, m.LINECOST AS LINECOST
	, 'NS' AS STK_NS
	, COALESCE(m.ITEMNUM,COALESCE(m.ASSETITEMNUM,m.PLDESC)) AS ITEMNUM
	, i.STE_CSWNITEMNO AS COSWIN_ITEM_CODE
	, COALESCE(i.DESCRIPTION,po.DESCRIPTION) AS ITEM_DESCRIPTION
	, m.STE_CSWNGRNNUM AS GRNUM
	, m.STE_CSWNGRNDATE AS GRDATE
	, c.STE_CSWNSAPVNDCODE AS SAP_VENDOR_CODE
	, c.NAME AS SUPPLIER_NAME
	, m.GLDEBITACCT
	, m.COSTCENTER
	, m.SAP_GL_CODE
	--, coa.GLCOMP02 AS COSTCENTER 
	--, coa.GLCOMP03 AS SAP_GL_CODE 
	--, coalesce(pc.QUANTITY, m.STE_CSWNACPQTY) AS QUANTITY_PER_CC
	, CASE WHEN m.TRANSDATE<='2025-03-30' THEN COALESCE(m.STE_CSWNACPQTY, m.QUANTITY) 
		   ELSE m.QUANTITY
	  END AS QUANTITY
	, m.ORDERQTY
	, l.INVOICEQTY
	, t.ACCEPTEDQTY
	--, m.STATUS
	, m.PL_GLDEBITACCT
	, m.PL_COSTCENTER
	, m.PL_SAP_GL_CODE
	, m.PONUM, m.POREVISIONNUM, m.POLINENUM
FROM (
	SELECT m.* 
	, CASE WHEN m.GLDEBITACCT IS NULL THEN NULL
	       WHEN length(m.GLDEBITACCT) - length(replace(m.GLDEBITACCT,'-','')) >= 2 THEN
				SUBSTR(m.GLDEBITACCT, LOCATE('-', m.GLDEBITACCT)+1, LOCATE('-', m.GLDEBITACCT, LOCATE('-', m.GLDEBITACCT)+1)-LOCATE('-', m.GLDEBITACCT)-1)
		   ELSE SUBSTR(m.GLDEBITACCT, LOCATE('-', m.GLDEBITACCT)+1)
	  END AS COSTCENTER
	, CASE WHEN m.GLDEBITACCT IS NULL THEN NULL
	       WHEN length(m.GLDEBITACCT) - length(replace(m.GLDEBITACCT,'-','')) < 2 THEN NULL
		   ELSE SUBSTR(m.GLDEBITACCT, LOCATE('-', m.GLDEBITACCT, LOCATE('-', m.GLDEBITACCT)+1)+1)
	  END AS SAP_GL_CODE
	, pl.ORDERQTY
	, pl.GLDEBITACCT AS PL_GLDEBITACCT
	, CASE WHEN pl.GLDEBITACCT IS NULL THEN NULL
	       WHEN length(pl.GLDEBITACCT) - length(replace(pl.GLDEBITACCT,'-','')) >= 2 THEN
				SUBSTR(pl.GLDEBITACCT, LOCATE('-', pl.GLDEBITACCT)+1, LOCATE('-', pl.GLDEBITACCT, LOCATE('-', pl.GLDEBITACCT)+1)-LOCATE('-', pl.GLDEBITACCT)-1)
		   ELSE SUBSTR(pl.GLDEBITACCT, LOCATE('-', pl.GLDEBITACCT)+1)
	  END AS PL_COSTCENTER
	, CASE WHEN m.GLDEBITACCT IS NULL THEN NULL
	       WHEN length(pl.GLDEBITACCT) - length(replace(pl.GLDEBITACCT,'-','')) < 2 THEN NULL
		   ELSE SUBSTR(pl.GLDEBITACCT, LOCATE('-', pl.GLDEBITACCT, LOCATE('-', pl.GLDEBITACCT)+1)+1)
	  END AS PL_SAP_GL_CODE
	, pl.DESCRIPTION AS PLDESC
	, a.ITEMNUM AS ASSETITEMNUM
	FROM maximo.SERVRECTRANS m
	JOIN maximo.POLINE pl ON pl.PONUM=m.PONUM AND pl.POLINENUM=m.POLINENUM AND pl.REVISIONNUM=m.POREVISIONNUM
	LEFT JOIN maximo.ASSET a ON a.ASSETNUM=m.ASSETNUM
) m 
JOIN maximo.PO po ON po.PONUM=m.PONUM AND po.REVISIONNUM=m.POREVISIONNUM
LEFT JOIN maximo.COMPANIES c ON c.COMPANY=po.VENDOR 
LEFT JOIN maximo.ITEM i ON i.ITEMNUM=COALESCE(m.ITEMNUM,m.ASSETITEMNUM)
--JOIN maximo.POLINE pl ON pl.PONUM=m.PONUM AND pl.POLINENUM=m.POLINENUM AND pl.REVISIONNUM=m.POREVISIONNUM
LEFT JOIN maximo.CHARTOFACCOUNTS coa ON coa.GLACCOUNT=m.GLDEBITACCT
-- LEFT JOIN maximo.STE_CSWNRECEIPT_PER_CC pc ON pc.MATRECTRANSID=m.MATRECTRANSID
-- total invoiced
LEFT JOIN (
	SELECT l.PONUM, l.POLINENUM, l.POREVISIONNUM, SUM(INVOICEQTY) AS INVOICEQTY
	FROM maximo.INVOICELINE l
	GROUP BY l.PONUM, l.POLINENUM, l.POREVISIONNUM
) l ON l.PONUM=m.PONUM AND l.POLINENUM=m.POLINENUM AND l.POREVISIONNUM=m.POREVISIONNUM
-- total received and accepted
LEFT JOIN (
	SELECT m.PONUM, m.POLINENUM, m.POREVISIONNUM, SUM(m.QUANTITY) AS ACCEPTEDQTY
	FROM maximo.SERVRECTRANS m
	GROUP BY m.PONUM, m.POLINENUM, m.POREVISIONNUM
) t ON t.PONUM=m.PONUM AND t.POLINENUM=m.POLINENUM AND t.POREVISIONNUM=m.POREVISIONNUM
-- Ideally we created records here for migrated data. But at the moment, none is created
LEFT JOIN maximo.INVOICEMATCH im ON im.SERVRECTRANSID=m.SERVRECTRANSID
WHERE 1=1
	AND m.ISSUETYPE IN ('RECEIPT')
	AND m.STATUS='COMP'
	AND po.STATUS IN (SELECT VALUE FROM MAXIMO.SYNONYMDOMAIN WHERE DOMAINID='POSTATUS' AND MAXVALUE IN ('APPR', 'INPRG', 'CLOSE', 'REVISE'))
	-- Accrual: Receipt which has not been invoiced
	--AND COALESCE(l.INVOICEQTY,0) < pl.ORDERQTY
	--AND COALESCE(l.INVOICEQTY,0) < COALESCE(t.ACCEPTEDQTY,0)
	AND im.INVOICEMATCHID IS NULL
	-- Service Accrual: no partial invoice in coswin)
	AND (m.STE_MIGRATIONID IS NULL OR COALESCE(l.INVOICEQTY,0)=0)
	-- Accrual: valid qty
	AND (
		-- before migration, use ACP_QTY
		(m.TRANSDATE<='2025-03-30' AND COALESCE(m.STE_CSWNACPQTY, m.QUANTITY) > 0)
		-- after migration, use QUANTITY
		OR (m.TRANSDATE>'2025-03-30' AND m.QUANTITY>0)
	)
	--AND m.INSPECTEDQTY <> m.REJECTQTY
	-- Valid SAPGL
	--AND ( coa.GLCOMP03 IS NOT NULL ) 
	--AND ( coa.GLCOMP03 BETWEEN '100000' AND '299999' ) 
	--AND ( coa.GLCOMP03 <> '113601' ) 
	-- Valid costcenter: not necessary since now costcenter is part of GLDEBITACCT
	--AND ( coa.GLCOMP02 IS NOT NULL ) 
	-- LEGACY FROM COSWIN: receiptval > 0
	AND m.LINECOST>0
	-- LEGACY FROM COSWIN: receiptstatus != fully invoiced
	AND ( CHR(COALESCE(m.STE_CSWNRCTSTATUS,50)) <> '3' )	-- 51
	-- LEGACY FROM COSWIN
	AND ( m.PONUM <> 'EE10005692' ) 
	AND ( m.PONUM <> 'EE10005693' )  
	AND ( coalesce(m.STE_CSWNRCTQTY,1) <> coalesce(m.STE_CSWNRTNTOSUPL,0) )  
	-- AND m.STATUS NOT IN ('WINSP', 'WASSET')
;

CALL MIGRATION.STE_FINISH_PATCH('20260123-REPORT-ACCRUAL-NS-ITEMNUM');