CREATE SCHEMA MIGRATION;

CREATE TABLE MIGRATION."STE_MIGRATION_MARKER"  (
	"TABLE_NAME" VARCHAR(50 OCTETS) NOT NULL , 
	"LAST_PKEY" DECIMAL(8,0) NOT NULL , 
	"LAST_TIMESTAMP" DECIMAL(10,0) NOT NULL , 
	"MIGRATION_TIMESTAMP" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)   
ORGANIZE BY ROW;

ALTER TABLE MIGRATION."STE_MIGRATION_MARKER" 
	ADD CONSTRAINT "STE_MIGRATION_MARKER_PK" PRIMARY KEY ("TABLE_NAME")
	ENFORCED;
	
-- FOR DELTA MIGRATION (COSWIN TIMESTAMP)
ALTER TABLE MAXIMO.ASSET ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.ASSETLOCUSERCUST ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.ASSETMETER ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.STE_CSWNASSETSLHIST ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.ASSETTRANS ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.ASSETSPEC ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.SPAREPART ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.ROUTE_STOP ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.ASSETANCESTOR ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.ASSETWORKZONE ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.TLOAMASSETGRP ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.INVENTORY ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.INVVENDOR ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.INVBALANCES ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.INVCOST ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.MR ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.MRLINE ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.CONTRACT ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.CONTRACTLINE ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.PR ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.PRLINE ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.RFQ ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.RFQLINE ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.RFQVENDOR ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.QUOTATIONLINE ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.PO ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.POLINE ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.INVOICE ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.INVOICELINE ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.INVOICECOST ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.MATRECTRANS ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.CONTRACTPURCH ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.WORKORDER ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.LABTRANS ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.TICKET ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.FAILUREREPORT ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.WPLABOR ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.WPITEM ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.MATUSETRANS ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.SERVRECTRANS ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.CHARTOFACCOUNTS ADD "STE_MIGRATIONTS" INTEGER;

-- RUNNING NUMBER COLUMN FOR STE_MIGRATION_USER_LOOKUP
ALTER TABLE MAXIMO.STE_MIGRATION_USER_LOOKUP ADD PKEY BIGINT;
alter table MAXIMO.STE_MIGRATION_USER_LOOKUP alter column PKEY set GENERATED ALWAYS AS IDENTITY (start with 1 increment by 1);

-- contract
ALTER TABLE MAXIMO.CONTRACT ADD "STE_CSWNDATE" DATE;
ALTER TABLE MAXIMO.CONTRACT ADD "STE_CSWNDEDUEDATE" DATE;
ALTER TABLE MAXIMO.CONTRACT ADD "STE_CSWNSAPGL" VARCHAR(110);
ALTER TABLE MAXIMO.CONTRACT ADD STE_REMARKS VARCHAR(3200);

-- pr
ALTER TABLE MAXIMO.PR ADD STE_CSWNSAPGL VARCHAR(20);

-- rfq
ALTER TABLE MAXIMO.RFQ ADD STE_CSWNSAPGL VARCHAR(20);
ALTER TABLE MAXIMO.RFQ ADD STE_PRNUM VARCHAR(12);
ALTER TABLE MAXIMO.RFQ ADD STE_REMARKS VARCHAR(3200);

-- rfqline
ALTER TABLE MAXIMO.RFQLINE ADD STE_CSWNSAPGL VARCHAR(20);
ALTER TABLE MAXIMO.RFQLINE ADD STE_CSWNCC VARCHAR(16);

-- po
ALTER TABLE MAXIMO.PO ADD STE_PRNUM VARCHAR(12);

-- poline
ALTER TABLE MAXIMO.POLINE ADD STE_CSWNSAPGL VARCHAR(20);
ALTER TABLE MAXIMO.POLINE ADD STE_CSWNCC VARCHAR(16);

-- invoice
ALTER TABLE MAXIMO.INVOICE ADD STE_CSWNSAPGL VARCHAR(20);

-- MR
ALTER TABLE MAXIMO.MR ADD STE_REMARKS VARCHAR(3200);
ALTER TABLE MAXIMO.MR ADD STE_CSWNDEMTODATE TIMESTAMP;
ALTER TABLE MAXIMO.MR ADD STE_CSWNCC VARCHAR(16);

-- INVTRANS
ALTER TABLE MAXIMO.INVTRANS ADD "STE_MIGRATIONID" BIGINT;
ALTER TABLE MAXIMO.INVTRANS ADD "STE_MIGRATIONDATE" TIMESTAMP;
ALTER TABLE MAXIMO.INVTRANS ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.INVTRANS ADD STE_CSWNCC	VARCHAR(16);
ALTER TABLE MAXIMO.INVTRANS ADD STE_SCCODE	VARCHAR(10);
ALTER TABLE MAXIMO.INVTRANS ADD STE_ADJVAL	DECIMAL(22,10);
ALTER TABLE MAXIMO.INVTRANS ADD STE_ADJUNITCOST	DECIMAL(22,10);

-- SERVRECTRANS
ALTER TABLE MAXIMO.SERVRECTRANS ADD "STE_DODATE" TIMESTAMP; 
ALTER TABLE MAXIMO.SERVRECTRANS ADD "STE_GRNREFTYPE" VARCHAR(50 OCTETS); 
ALTER TABLE MAXIMO.SERVRECTRANS ADD "STE_CSWNCC" VARCHAR(16 OCTETS); 
ALTER TABLE MAXIMO.SERVRECTRANS ADD "STE_CSWNDNDATE" TIMESTAMP; 
ALTER TABLE MAXIMO.SERVRECTRANS ADD "STE_CSWNGRNDATE" TIMESTAMP; 
ALTER TABLE MAXIMO.SERVRECTRANS ADD "STE_CSWNGRNNUM" VARCHAR(10 OCTETS); 
ALTER TABLE MAXIMO.SERVRECTRANS ADD "STE_CSWNINSPREF" VARCHAR(10 OCTETS); 
ALTER TABLE MAXIMO.SERVRECTRANS ADD "STE_CSWNINSPSTATUS" INTEGER; 
ALTER TABLE MAXIMO.SERVRECTRANS ADD "STE_CSWNRCTSTATUS" INTEGER; 
ALTER TABLE MAXIMO.SERVRECTRANS ADD "STE_CSWNRECEIPTTYPE" INTEGER; 
ALTER TABLE MAXIMO.SERVRECTRANS ADD "STE_CSWNSAPGL" VARCHAR(20 OCTETS); 
ALTER TABLE MAXIMO.SERVRECTRANS ADD "STE_MIGRATIONDATE" TIMESTAMP; 
ALTER TABLE MAXIMO.SERVRECTRANS ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.SERVRECTRANS ADD "STE_MIGRATIONNSITEMPK" VARCHAR(200 OCTETS); 
ALTER TABLE MAXIMO.SERVRECTRANS ADD "STE_MIGRATIONITEMPK" VARCHAR(200 OCTETS); 
ALTER TABLE MAXIMO.SERVRECTRANS ADD "STE_MIGRATIONID" BIGINT;

-- INVENTORY
ALTER TABLE MAXIMO.INVENTORY ADD STE_CSWNPOPULATION DECIMAL(22,10);
ALTER TABLE MAXIMO.INVENTORY ADD STE_CSWNSTKRISK DECIMAL(22,10);
ALTER TABLE MAXIMO.INVENTORY ADD STE_CYCLICREORDER	DECIMAL(5,0);
ALTER TABLE MAXIMO.INVENTORY ADD STE_NODAYSCYCL	DECIMAL(5,0);
ALTER TABLE MAXIMO.INVENTORY ADD STE_CSWNSUPPLIER	VARCHAR(20);
ALTER TABLE MAXIMO.INVENTORY ADD STE_FIRSTPROCDATE	DATE;

-- INVVENDOR
ALTER TABLE MAXIMO.INVVENDOR ADD STE_REMARKS VARCHAR(3200);

-- matusetrans
ALTER TABLE MAXIMO.MATUSETRANS ADD STE_ISSUENUM	VARCHAR(8);

-- MACRECTRANS
ALTER TABLE MAXIMO.MACRECTRANS ADD STE_CSWNRECEIPTREMARK VARCHAR(3200);