CREATE SCHEMA MIGRATION;

CREATE TABLE MIGRATION."STE_MIGRATION_MARKER"  (
	"TABLE_NAME" VARCHAR(50 OCTETS) NOT NULL , 
	"LAST_PKEY" DECIMAL(8,0) NOT NULL , 
	"LAST_TIMESTAMP" DECIMAL(10,0) NOT NULL , 
	"MIGRATION_TIMESTAMP" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)   
ORGANIZE BY ROW;

ALTER TABLE MIGRATION."STE_MIGRATION_MARKER" 
	ADD CONSTRAINT "STE_MIGRATION_MARKER_PK" PRIMARY KEY ("TABLE_NAME")
	ENFORCED;
	
-- FOR DELTA MIGRATION (COSWIN TIMESTAMP)
ALTER TABLE MAXIMO.ASSET ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.ASSETLOCUSERCUST ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.ASSETMETER ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.STE_CSWNASSETSLHIST ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.ASSETTRANS ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.ASSETSPEC ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.SPAREPART ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.ROUTE_STOP ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.ASSETANCESTOR ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.ASSETWORKZONE ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.TLOAMASSETGRP ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.INVENTORY ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.INVVENDOR ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.INVBALANCES ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.INVCOST ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.MR ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.MRLINE ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.CONTRACT ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.CONTRACTLINE ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.PR ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.PRLINE ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.RFQ ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.RFQLINE ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.RFQVENDOR ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.QUOTATIONLINE ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.PO ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.POLINE ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.INVOICE ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.INVOICELINE ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.INVOICECOST ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.MATRECTRANS ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.CONTRACTPURCH ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.WORKORDER ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.LABTRANS ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.TICKET ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.FAILUREREPORT ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.WPLABOR ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.WPITEM ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.MATUSETRANS ADD "STE_MIGRATIONTS" INTEGER;

-- RUNNING NUMBER COLUMN
alter table MAXIMO.STE_MIGRATION_USER_LOOKUP alter column ID set GENERATED ALWAYS AS IDENTITY (start with 1 increment by 1)