CREATE SCHEMA MIGRATION;

CREATE TABLE MIGRATION."STE_MIGRATION_MARKER"  (
	"TABLE_NAME" VARCHAR(50 OCTETS) NOT NULL , 
	"LAST_PKEY" DECIMAL(8,0) NOT NULL , 
	"LAST_TIMESTAMP" DECIMAL(10,0) NOT NULL , 
	"MIGRATION_TIMESTAMP" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)   
ORGANIZE BY ROW;

ALTER TABLE MIGRATION."STE_MIGRATION_MARKER" 
	ADD CONSTRAINT "STE_MIGRATION_MARKER_PK" PRIMARY KEY ("TABLE_NAME")
	ENFORCED;
	
-- FOR DELTA MIGRATION (COSWIN TIMESTAMP)
ALTER TABLE MAXIMO.ASSET ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.ASSETLOCUSERCUST ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.ASSETMETER ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.STE_CSWNASSETSLHIST ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.ASSETTRANS ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.ASSETSPEC ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.SPAREPART ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.ROUTE_STOP ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.ASSETANCESTOR ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.ASSETWORKZONE ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.TLOAMASSETGRP ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.INVENTORY ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.INVVENDOR ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.INVBALANCES ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.INVCOST ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.MR ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.MRLINE ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.CONTRACT ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.CONTRACTLINE ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.PR ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.PRLINE ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.RFQ ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.RFQLINE ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.RFQVENDOR ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.QUOTATIONLINE ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.PO ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.POLINE ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.INVOICE ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.INVOICELINE ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.INVOICECOST ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.MATRECTRANS ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.CONTRACTPURCH ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.WORKORDER ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.LABTRANS ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.TICKET ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.FAILUREREPORT ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.WPLABOR ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.WPITEM ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.MATUSETRANS ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.SERVRECTRANS ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.CHARTOFACCOUNTS ADD "STE_MIGRATIONTS" INTEGER;

-- RUNNING NUMBER COLUMN FOR STE_MIGRATION_USER_LOOKUP
ALTER TABLE MAXIMO.STE_MIGRATION_USER_LOOKUP ADD PKEY BIGINT;
alter table MAXIMO.STE_MIGRATION_USER_LOOKUP alter column PKEY set GENERATED ALWAYS AS IDENTITY (start with 1 increment by 1);

-- contract
ALTER TABLE MAXIMO.CONTRACT ADD "STE_CSWNDATE" DATE;
ALTER TABLE MAXIMO.CONTRACT ADD "STE_CSWNDEDUEDATE" DATE;
ALTER TABLE MAXIMO.CONTRACT ADD "STE_CSWNSAPGL" VARCHAR(110);
ALTER TABLE MAXIMO.CONTRACT ADD STE_REMARKS VARCHAR(3200);

-- pr
ALTER TABLE MAXIMO.PR ADD STE_CSWNSAPGL VARCHAR(20);

-- rfq
ALTER TABLE MAXIMO.RFQ ADD STE_CSWNSAPGL VARCHAR(20);
ALTER TABLE MAXIMO.RFQ ADD STE_PRNUM VARCHAR(12);
ALTER TABLE MAXIMO.RFQ ADD STE_REMARKS VARCHAR(3200);

-- rfqline
ALTER TABLE MAXIMO.RFQLINE ADD STE_CSWNSAPGL VARCHAR(20);
ALTER TABLE MAXIMO.RFQLINE ADD STE_CSWNCC VARCHAR(16);

-- po
ALTER TABLE MAXIMO.PO ADD STE_PRNUM VARCHAR(12);

-- poline
ALTER TABLE MAXIMO.POLINE ADD STE_CSWNSAPGL VARCHAR(20);
ALTER TABLE MAXIMO.POLINE ADD STE_CSWNCC VARCHAR(16);

-- invoice
ALTER TABLE MAXIMO.INVOICE ADD STE_CSWNSAPGL VARCHAR(20);

-- MR
ALTER TABLE MAXIMO.MR ADD STE_REMARKS VARCHAR(3200);
ALTER TABLE MAXIMO.MR ADD STE_CSWNDEMTODATE TIMESTAMP;
ALTER TABLE MAXIMO.MR ADD STE_CSWNCC VARCHAR(16);

-- INVTRANS
ALTER TABLE MAXIMO.INVTRANS ADD "STE_MIGRATIONID" BIGINT;
ALTER TABLE MAXIMO.INVTRANS ADD "STE_MIGRATIONDATE" TIMESTAMP;
ALTER TABLE MAXIMO.INVTRANS ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.INVTRANS ADD STE_CSWNCC	VARCHAR(16);
ALTER TABLE MAXIMO.INVTRANS ADD STE_SCCODE	VARCHAR(10);
ALTER TABLE MAXIMO.INVTRANS ADD STE_ADJVAL	DECIMAL(22,10);
ALTER TABLE MAXIMO.INVTRANS ADD STE_ADJUNITCOST	DECIMAL(22,10);

-- SERVRECTRANS
ALTER TABLE MAXIMO.SERVRECTRANS ADD "STE_DODATE" TIMESTAMP; 
ALTER TABLE MAXIMO.SERVRECTRANS ADD "STE_GRNREFTYPE" VARCHAR(50 OCTETS); 
ALTER TABLE MAXIMO.SERVRECTRANS ADD "STE_CSWNCC" VARCHAR(16 OCTETS); 
ALTER TABLE MAXIMO.SERVRECTRANS ADD "STE_CSWNDNDATE" TIMESTAMP; 
ALTER TABLE MAXIMO.SERVRECTRANS ADD "STE_CSWNGRNDATE" TIMESTAMP; 
ALTER TABLE MAXIMO.SERVRECTRANS ADD "STE_CSWNGRNNUM" VARCHAR(10 OCTETS); 
ALTER TABLE MAXIMO.SERVRECTRANS ADD "STE_CSWNINSPREF" VARCHAR(10 OCTETS); 
ALTER TABLE MAXIMO.SERVRECTRANS ADD "STE_CSWNINSPSTATUS" INTEGER; 
ALTER TABLE MAXIMO.SERVRECTRANS ADD "STE_CSWNRCTSTATUS" INTEGER; 
ALTER TABLE MAXIMO.SERVRECTRANS ADD "STE_CSWNRECEIPTTYPE" INTEGER; 
ALTER TABLE MAXIMO.SERVRECTRANS ADD "STE_CSWNSAPGL" VARCHAR(20 OCTETS); 
ALTER TABLE MAXIMO.SERVRECTRANS ADD "STE_MIGRATIONDATE" TIMESTAMP; 
ALTER TABLE MAXIMO.SERVRECTRANS ADD "STE_MIGRATIONTS" INTEGER;
ALTER TABLE MAXIMO.SERVRECTRANS ADD "STE_MIGRATIONNSITEMPK" VARCHAR(200 OCTETS); 
ALTER TABLE MAXIMO.SERVRECTRANS ADD "STE_MIGRATIONITEMPK" VARCHAR(200 OCTETS); 
ALTER TABLE MAXIMO.SERVRECTRANS ADD "STE_MIGRATIONID" BIGINT;

-- INVENTORY
ALTER TABLE MAXIMO.INVENTORY ADD STE_CSWNPOPULATION DECIMAL(22,10);
ALTER TABLE MAXIMO.INVENTORY ADD STE_CSWNSTKRISK DECIMAL(22,10);
ALTER TABLE MAXIMO.INVENTORY ADD STE_CYCLICREORDER	DECIMAL(5,0);
ALTER TABLE MAXIMO.INVENTORY ADD STE_NODAYSCYCL	DECIMAL(5,0);
ALTER TABLE MAXIMO.INVENTORY ADD STE_CSWNSUPPLIER	VARCHAR(20);
ALTER TABLE MAXIMO.INVENTORY ADD STE_FIRSTPROCDATE	DATE;

-- INVVENDOR
ALTER TABLE MAXIMO.INVVENDOR ADD STE_REMARKS VARCHAR(3200);

-- matusetrans
ALTER TABLE MAXIMO.MATUSETRANS ADD STE_ISSUENUM	VARCHAR(8);

-- MACRECTRANS
ALTER TABLE MAXIMO.MATRECTRANS ADD STE_CSWNRECEIPTREMARK VARCHAR(3200);

-- glcomponents
ALTER TABLE MAXIMO.GLCOMPONENTS ADD "STE_MIGRATIONID" BIGINT;
ALTER TABLE MAXIMO.GLCOMPONENTS ADD "STE_MIGRATIONDATE" TIMESTAMP;
ALTER TABLE MAXIMO.GLCOMPONENTS ADD "STE_MIGRATIONSOURCE" VARCHAR(50);
ALTER TABLE MAXIMO.GLCOMPONENTS ADD "STE_COSTCENTREDEPT" VARCHAR(50);

-- ITEM
ALTER TABLE MAXIMO.ITEM ADD "STE_CSWNITEMNO" VARCHAR(30);
ALTER TABLE MAXIMO.ITEM ADD "STE_SPARECRITICAL" VARCHAR(2);

CREATE INDEX ASSET_STE_MIGRATIONID_IDX ON MAXIMO.ASSET (STE_MIGRATIONID);
CREATE INDEX ITEM_STE_MIGRATIONID_IDX ON MAXIMO.ITEM (STE_MIGRATIONID);
CREATE INDEX WORKORDER_STE_MIGRATIONID_IDX ON MAXIMO.WORKORDER (STE_MIGRATIONID);
CREATE INDEX TICKET_STE_MIGRATIONID_IDX ON MAXIMO.TICKET (STE_MIGRATIONID);
CREATE INDEX JPASSETSPLINK_STE_MIGRATIONID_IDX ON MAXIMO.JPASSETSPLINK (STE_MIGRATIONID);

ALTER TABLE MAXIMO.AMCREW ADD "STE_MIGRATIONSOURCE" VARCHAR(50);

-- COSWIN.FREE_TBL1 definition

CREATE TABLE "MAXIMO"."CSWN_FREE_TBL1" 
   (	
   	"PK_FREE_TBL1" BIGINT NOT NULL, 
	"TIMESTAMP" DECIMAL(10,0) DEFAULT 1 NOT NULL, 
	"TBL1_CODE" VARCHAR(20) NOT NULL, 
	"TBL1_DESCRIPTION" VARCHAR(100), 
	"TBL1_NUMBER1" DECIMAL(8,0), 
	"TBL1_DATE1" DECIMAL(10,0), 
	"TBL1_STRING1" VARCHAR(20), 
	"TBL1_STRING2" VARCHAR(20), 
	"TBL1_STRING3" VARCHAR(20)
   ) ;

--ALTER TABLE MAXIMO.CSWN_FREE_TBL1 ADD CONSTRAINT CSWN_FREE_TBL1_UNIQUE UNIQUE (PK_FREE_TBL1);
--CREATE UNIQUE INDEX CSWN_FREE_TBL1_PK_FREE_TBL1_IDX ON MAXIMO.CSWN_FREE_TBL1 (PK_FREE_TBL1);

CREATE TABLE "MAXIMO"."CSWN_FREE_TBL6" 
   (	
    "PK_FREE_TBL6" BIGINT NOT NULL, 
	"TIMESTAMP" DECIMAL(10,0) DEFAULT 1 NOT NULL, 
	"TBL6_CODE" VARCHAR(30) NOT NULL, 
	"TBL6_DESCRIPTION" VARCHAR(110), 
	"TBL6_NUMBER1" DECIMAL(15,0), 
	"TBL6_DATE1" DECIMAL(10,0), 
	"TBL6_STRING1" VARCHAR(20), 
	"TBL6_STRING2" VARCHAR(20), 
	"TBL6_STRING3" VARCHAR(20)
   );

CREATE TABLE "MAXIMO"."CSWN_T_AMS_PARAM_T" 
   (	
    "PK_T_AMS_PARAM_T" BIGINT NOT NULL, 
	"CODE" VARCHAR(20), 
	"VALUE" VARCHAR(20), 
	"DESCRIPTION" VARCHAR(200)
   ) ; 

CREATE TABLE "MAXIMO"."CSWN_T_AMS_PERMIT_T" 
   (	
   	"PK_T_AMS_PERMIT_T" BIGINT NOT NULL,
	"PERMIT_TYPE" VARCHAR(20)
   );
  
CREATE TABLE "MAXIMO"."CSWN_T_FAC_PARAM_T" 
   (	
    "PK_T_FAC_PARAM_T" BIGINT NOT NULL, 
	"TIMESTAMP" DECIMAL(10,0) DEFAULT 1 NOT NULL,  
	"FAC_MMS_PARAM" VARCHAR(20), 
	"FAC_MMS_DESC" VARCHAR(40), 
	"FAC_VALUE" VARCHAR(20)
   );
  
CREATE TABLE "MAXIMO"."CSWN_T_KERN_FAC" 
   (	
    "PK_T_KERN_FAC" BIGINT NOT NULL, 
	"TIMESTAMP" DECIMAL(10,0) DEFAULT 1 NOT NULL, 
	"KFAC_NO" VARCHAR(10) NOT NULL, 
	"KFAC_DESC" VARCHAR(40) 
   ); 
  
CREATE TABLE "MAXIMO"."CSWN_T_LCC_CF_T" 
   (	
    "PK_T_LCC_CF_T" BIGINT NOT NULL,
	"TIMESTAMP" DECIMAL(10,0) DEFAULT 1 NOT NULL, 
	"LCC_CURCF_ID" DECIMAL(10,0) NOT NULL, 
	"LCC_CURCF_COST_TYPE_DESC" VARCHAR(40), 
	"LCC_CURCF_COST_SECT1_DESC" VARCHAR(40), 
	"LCC_CURCF_COST_SECT2_DESC" VARCHAR(40), 
	"LCC_CURCF_COST_DESC" VARCHAR(40)
   );
  
CREATE TABLE "MAXIMO"."CSWN_T_LCC_MEAN_T" 
   (	
    "PK_T_LCC_MEAN_T" BIGINT NOT NULL, 
	"TIMESTAMP" DECIMAL(10,0) DEFAULT 1 NOT NULL, 
	"LCCMN_EQCD" VARCHAR(20) NOT NULL, 
	"LCCMN_TOTAL_COST" DECIMAL(15,0), 
	"LCCMN_MMMC_COST" DECIMAL(15,0), 
	"LCCMN_EQP_HIST" DECIMAL(10,0), 
	"LCCMN_EQP_MTH" DECIMAL(10,0), 
	"LCCMN_EQP_YR" DECIMAL(10,0), 
	"LCCMN_EQ_ZONE" VARCHAR(10), 
	"LCCMN_EQ_UNIT" VARCHAR(10), 
	"LCCMN_EQ_COSC" VARCHAR(16), 
	"LCCMN_EQ_CATG" VARCHAR(10), 
	"LCCMN_EQ_LOCT" VARCHAR(16), 
	"LCCMN_EQ_AUTH" VARCHAR(16)
   );
  
CREATE TABLE "MAXIMO"."CSWN_T_POSS_CONFLICT" 
   (	
    "PK_T_POSS_CONFLICT" BIGINT NOT NULL, 
	"P_MAIN_TAR_ID" VARCHAR(14) NOT NULL, 
	"P_MAIN_TAR_STATUS" DECIMAL(5,0), 
	"P_MAIN_TAR_SUBMTER_ID" VARCHAR(16), 
	"P_MAIN_TAR_POSESSION" DECIMAL(5,0), 
	"P_MAIN_TAR_PM_PIC" VARCHAR(40), 
	"P_MAIN_TAR_WK_DESC" VARCHAR(40), 
	"P_MAIN_TAR_BGN_DT" DECIMAL(10,0), 
	"P_MAIN_TAR_END_DT" DECIMAL(10,0), 
	"P_MAIN_TAR_ENTRY_TIME" DECIMAL(10,0), 
	"P_MAIN_TAR_EXIT_TIME" DECIMAL(10,0), 
	"P_MAIN_TAR_TRACK_SECT" VARCHAR(10), 
	"P_MAIN_TAR_BK_IN_ST" VARCHAR(10), 
	"P_MAIN_TAR_SW_OFF_PWR" DECIMAL(5,0), 
	"P_MAIN_TAR_PM_PIC_ID" VARCHAR(10), 
	"P_MAIN_TAR_PHONE" VARCHAR(15), 
	"P_MAIN_TTS_CODE" VARCHAR(20) NOT NULL, 
	"P_DISP_FLG" DECIMAL(1,0), 
	"P_DATEFROM" VARCHAR(25), 
	"P_DATETO" VARCHAR(25)
   );
  
CREATE TABLE "MAXIMO"."CSWN_T_TAS_ATAR" 
   (	
    "PK_T_TAS_ATAR" BIGINT NOT NULL, 
	"TIMESTAMP" DECIMAL(10,0) DEFAULT 1 NOT NULL, 
	"TAR_ID" VARCHAR(14) NOT NULL, 
	"TAR_STATUS" DECIMAL(5,0), 
	"TAR_SUBMTER_ID" VARCHAR(16), 
	"TAR_REQTER_ID" VARCHAR(16), 
	"TAR_SUB_DATE" DECIMAL(10,0), 
	"TAR_APPVED_BY" VARCHAR(16), 
	"TAR_APPVAL_DT" DECIMAL(10,0), 
	"TAR_LATE_URG" VARCHAR(10), 
	"TAR_POSESSION" DECIMAL(5,0), 
	"TAR_PM_PIC" VARCHAR(40), 
	"TAR_PRIORTY" VARCHAR(10), 
	"TAR_WO" DECIMAL(10,0), 
	"TAR_PTW" VARCHAR(10), 
	"TAR_WK_DESC" VARCHAR(40), 
	"TAR_BGN_DT" DECIMAL(10,0), 
	"TAR_END_DT" DECIMAL(10,0), 
	"TAR_ENTRY_TIME" DECIMAL(10,0), 
	"TAR_EXIT_TIME" DECIMAL(10,0), 
	"TAR_EQPT_LOC" VARCHAR(199), 
	"TAR_TRACK_SECT" VARCHAR(10), 
	"TAR_BK_IN_ST" VARCHAR(10), 
	"TAR_SW_OFF_PWR" DECIMAL(5,0), 
	"TAR_SUBMTER_MAIL" VARCHAR(40), 
	"TAR_APPVER_MAIL" VARCHAR(40), 
	"TAR_REQTER_NAME" VARCHAR(40), 
	"TAR_REQTER_CPNY" VARCHAR(40), 
	"TAR_BKINST_MAIL" VARCHAR(40), 
	"TAR_SUB_TIME" DECIMAL(10,0), 
	"TAR_REJECT_BY" VARCHAR(16), 
	"TAR_REJECT_DT" DECIMAL(10,0), 
	"TAR_REJECT_REA" VARCHAR(100), 
	"TAR_PM_PIC_ID" VARCHAR(10), 
	"TAR_PM_PIC_MAIL" VARCHAR(40), 
	"TAR_PIC_QEXP_DT" DECIMAL(10,0), 
	"TAR_AUTHORITY" VARCHAR(16), 
	"TAR_REJECT_MAIL" VARCHAR(40), 
	"TAR_SM_NO" VARCHAR(10), 
	"TAR_STRING1" VARCHAR(20), 
	"TAR_STRING2" VARCHAR(20), 
	"TAR_NUMBER1" DECIMAL(10,0), 
	"TAR_NUMBER2" DECIMAL(10,0), 
	"TAR_STRING3" VARCHAR(40), 
	"TAR_STRING4" VARCHAR(40), 
	"TAR_NUMBER3" DECIMAL(10,0), 
	"TAR_NUMBER4" DECIMAL(10,0), 
	"TAR_PHONE" VARCHAR(15), 
	"TAR_JOBR_REF_NO" VARCHAR(10), 
	"TAR_ID_STORE" VARCHAR(14)
   );

CREATE TABLE "MAXIMO"."CSWN_T_TAS_ATOA" 
   (	
   	"PK_T_TAS_ATOA" BIGINT, 
	"TIMESTAMP" DECIMAL(10,0) DEFAULT 1 NOT NULL, 
	"TAS_TAR_TOA" DECIMAL(15,0), 
	"TOA_ID" VARCHAR(10), 
	"TOA_STATUS" DECIMAL(5,0), 
	"TOA_REL_DATE" DECIMAL(10,0), 
	"TOA_REL_TM" DECIMAL(10,0), 
	"TOA_AUTHOR" VARCHAR(16), 
	"TOA_SECT_DEPT" VARCHAR(20), 
	"TOA_CLOSE_DT" DECIMAL(10,0), 
	"TOA_CLOSE_TM" DECIMAL(10,0), 
	"TOA_TAR_NO" VARCHAR(14), 
	"TOA_PM_PIC" VARCHAR(40), 
	"TOA_PMPIC_ACHK" DECIMAL(5,0), 
	"TOA_PMPIC_MCHK" DECIMAL(5,0), 
	"TOA_NO_OF_EMP" DECIMAL(5,0), 
	"TOA_BK_IN_ST" VARCHAR(10), 
	"TOA_WO" DECIMAL(10,0), 
	"TOA_PTW" VARCHAR(10), 
	"TOA_STRING1" VARCHAR(20), 
	"TOA_STRING2" VARCHAR(20), 
	"TOA_NUMBER1" DECIMAL(10,0), 
	"TOA_NUMBER2" DECIMAL(10,0), 
	"TOA_STRING3" VARCHAR(40), 
	"TOA_STRING4" VARCHAR(40), 
	"TOA_NUMBER3" DECIMAL(10,0), 
	"TOA_NUMBER4" DECIMAL(10,0), 
	"TOA_PP_ID" VARCHAR(10), 
	"TOA_PP_NAME" VARCHAR(40)
   ); 
  
CREATE TABLE "MAXIMO"."CSWN_T_TAS_CUT_OFF_DT" 
   (	
    "PK_T_TAS_CUT_OFF_DT" BIGINT NOT NULL, 
	"TIMESTAMP" DECIMAL(10,0) DEFAULT 1 NOT NULL, 
	"COD_PERIOD_ID" DECIMAL(10,0) NOT NULL, 
	"COD_ST_DT" DECIMAL(10,0), 
	"COD_END_DT" DECIMAL(10,0), 
	"COD_CUT_OFF_DT" DECIMAL(10,0), 
	"COD_ST_TM" DECIMAL(10,0), 
	"COD_END_TM" DECIMAL(10,0), 
	"COD_CUT_OFF_TM" DECIMAL(10,0), 
	"COD_PUB_DT" DECIMAL(10,0), 
	"COD_PUB_TM" DECIMAL(10,0), 
	"COD_SPARE_1" DECIMAL(10,0), 
	"COD_SPARE_2" DECIMAL(10,0)
   );
  
CREATE TABLE "MAXIMO"."CSWN_T_TAS_E_SECT" 
   (	
    "PK_T_TAS_E_SECT" BIGINT NOT NULL, 
	"TIMESTAMP" DECIMAL(10,0) DEFAULT 1 NOT NULL, 
	"TES_CODE" VARCHAR(20) NOT NULL, 
	"TES_LOC_1" VARCHAR(20), 
	"TES_LOC_2" VARCHAR(20), 
	"TES_LOC_3" VARCHAR(20), 
	"TES_LOC_4" VARCHAR(20), 
	"TES_LOC_5" VARCHAR(20), 
	"TES_LOC_6" VARCHAR(20)
   ); 

CREATE TABLE "MAXIMO"."CSWN_T_TAS_NEMP" 
   (	
    "PK_T_TAS_NEMP" BIGINT NOT NULL,
	"TIMESTAMP" DECIMAL(10,0) DEFAULT 1 NOT NULL, 
	"NEMP_EMNO" VARCHAR(10) NOT NULL, 
	"NEMP_NAME" VARCHAR(40), 
	"NEMP_E_MAIL" VARCHAR(40), 
	"NEMP_PASSPORT" VARCHAR(20)
   ); 
  
CREATE TABLE "MAXIMO"."CSWN_T_TAS_PM_PIC" 
   (	
    "PK_T_TAS_PM_PIC" BIGINT NOT NULL,
	"TIMESTAMP" DECIMAL(10,0) DEFAULT 1 NOT NULL, 
	"PP_ID" VARCHAR(10) NOT NULL, 
	"PP_PM_PIC" VARCHAR(10), 
	"PP_NAME" VARCHAR(40), 
	"PP_E_MAIL" VARCHAR(40), 
	"PP_Q_EXP_DT" DECIMAL(10,0)
   ); 

CREATE TABLE "MAXIMO"."CSWN_T_TAS_ST_MGR" 
   (	
    "PK_T_TAS_ST_MGR" BIGINT NOT NULL, 
	"TIMESTAMP" DECIMAL(10,0) DEFAULT 1 NOT NULL, 
	"SM_NO" VARCHAR(10) NOT NULL, 
	"ST_NAME" VARCHAR(40), 
	"ST_MGR_ID" VARCHAR(10), 
	"ST_MGR_EMAIL" VARCHAR(40)
   ); 

CREATE TABLE "MAXIMO"."CSWN_T_TAS_T_SECT" 
   (	
    "PK_T_TAS_T_SECT" BIGINT NOT NULL,
	"TIMESTAMP" DECIMAL(10,0) DEFAULT 1 NOT NULL, 
	"TTS_CODE" VARCHAR(20) NOT NULL, 
	"TTS_LOC_1" VARCHAR(20), 
	"TTS_LOC_2" VARCHAR(20), 
	"TTS_LOC_3" VARCHAR(20), 
	"TTS_LOC_4" VARCHAR(20), 
	"TTS_LOC_5" VARCHAR(20), 
	"TTS_LOC_6" VARCHAR(20)
   ); 
 
CREATE TABLE "MAXIMO"."CSWN_T_TAS_TAR_E_SECT" 
   (	
    "PK_T_TAS_TAR_E_SECT" BIGINT NOT NULL, 
	"TIMESTAMP" DECIMAL(10,0) DEFAULT 1 NOT NULL, 
	"TAS_TAR_E_SECT" DECIMAL(15,0), 
	"TES_EQPT_CODE" VARCHAR(20)
   ); 

CREATE TABLE "MAXIMO"."CSWN_T_TAS_TAR_T_SECT" 
   (	
    "PK_T_TAS_TAR_T_SECT" BIGINT NOT NULL, 
	"TIMESTAMP" DECIMAL(10,0) DEFAULT 1 NOT NULL, 
	"TAS_TAR_T_SECT" DECIMAL(8,0), 
	"TTS_TTS_CODE" VARCHAR(20)
   ); 

CREATE TABLE "MAXIMO"."CSWN_T_TAS_TRACE" 
   (	
    "PK_T_TAS_TRACE" BIGINT NOT NULL,
	"TIMESTAMP" DECIMAL(10,0) DEFAULT 1 NOT NULL, 
	"TR_PROC_NAME" VARCHAR(50), 
	"TR_DATE_TIME" VARCHAR(25), 
	"TR_ERROR_MSG" VARCHAR(300)
   ); 

CREATE TABLE "MAXIMO"."CSWN_T_TAS_TRACE" 
   (	
    "PK_T_TAS_TRACE" BIGINT NOT NULL, 
	"TIMESTAMP" DECIMAL(10,0) DEFAULT 1 NOT NULL, 
	"TR_PROC_NAME" VARCHAR(50), 
	"TR_DATE_TIME" VARCHAR(25), 
	"TR_ERROR_MSG" VARCHAR(300)
   ); 

CREATE TABLE "MAXIMO"."CSWN_T_TAR_CMMT" 
   (	
    "PK_T_TAR_CMMT" BIGINT NOT NULL, 
	"TIMESTAMP" DECIMAL(10,0) DEFAULT 1 NOT NULL, 
	"TAS_TAR_CMMT" DECIMAL(15,0), 
	"TAR_CMMT_TXT" VARCHAR(32000) 
   ); 

CREATE TABLE "MAXIMO"."CSWN_T_TAR_LATE" 
   (	
    "PK_T_TAR_LATE" BIGINT NOT NULL, 
	"TIMESTAMP" DECIMAL(10,0) DEFAULT 1 NOT NULL, 
	"TAS_TAR_LATE" DECIMAL(15,0), 
	"TAR_LATE_TXT" VARCHAR(32000)
   );
 
CREATE TABLE "MAXIMO"."CSWN_T_TOA_CMMT" 
   (	
    "PK_T_TOA_CMMT" BIGINT NOT NULL, 
	"TIMESTAMP" DECIMAL(10,0) DEFAULT 1 NOT NULL, 
	"TAS_TOA_CMMT" DECIMAL(15,0), 
	"TOA_CMMT_TXT" VARCHAR(32000)
   ); 

ALTER TABLE MAXIMO.MATRECTRANS ADD "STE_CSWNACPQTY" DECIMAL(15,2);
ALTER TABLE MAXIMO.MATRECTRANS ADD "STE_CSWNRTNTOSUPL" DECIMAL(15,2);
ALTER TABLE MAXIMO.SERVRECTRANS ADD "STE_CSWNACPQTY" DECIMAL(15,2);
ALTER TABLE MAXIMO.SERVRECTRANS ADD "STE_CSWNRTNTOSUPL" DECIMAL(15,2);

ALTER TABLE MAXIMO.MATRECTRANS ADD "STE_CSWNRCTQTY" DECIMAL(15,2);
ALTER TABLE MAXIMO.MATRECTRANS ADD "STE_CSWNRCTVAL" DECIMAL(13,5);
ALTER TABLE MAXIMO.SERVRECTRANS ADD "STE_CSWNRCTQTY" DECIMAL(15,2);
ALTER TABLE MAXIMO.SERVRECTRANS ADD "STE_CSWNRCTVAL" DECIMAL(13,5);

ALTER TABLE MAXIMO.SYNONYMDOMAIN ADD "STE_MIGRATIONID" BIGINT;
ALTER TABLE MAXIMO.SYNONYMDOMAIN ADD "STE_MIGRATIONDATE" TIMESTAMP;
ALTER TABLE MAXIMO.SYNONYMDOMAIN ADD "STE_MIGRATIONSOURCE" VARCHAR(50);
ALTER TABLE MAXIMO.SYNONYMDOMAIN ADD "STE_MIGRATIONTS" INTEGER;

ALTER TABLE MAXIMO.ALNDOMAIN ADD "STE_MIGRATIONID" BIGINT;
ALTER TABLE MAXIMO.ALNDOMAIN ADD "STE_MIGRATIONDATE" TIMESTAMP;
ALTER TABLE MAXIMO.ALNDOMAIN ADD "STE_MIGRATIONSOURCE" VARCHAR(50);
ALTER TABLE MAXIMO.ALNDOMAIN ADD "STE_MIGRATIONTS" INTEGER;

ALTER TABLE MAXIMO.MR ADD "STE_CSWNDEMTYPE" INTEGER;
ALTER TABLE MAXIMO.ITEM ADD "STE_NONSTOCKFLAG" VARCHAR(1);
ALTER TABLE MAXIMO.INVOICELINE ADD "STE_CSWNITEMBASEVAL" DECIMAL(18,2);
ALTER TABLE MAXIMO.COMPMASTER ADD "STE_CSWNSUPLTYPE" VARCHAR(1);
ALTER TABLE MAXIMO.COMPANIES ADD "STE_CSWNSUPLTYPE" VARCHAR(1);
ALTER TABLE MAXIMO.INVOICE ADD "STE_CSWNSTRING3" VARCHAR(20);
ALTER TABLE MAXIMO.INVOICE ADD "STE_CSWNISSUEDATE" DATE;

CREATE TABLE "MAXIMO"."STE_CSWNRECEIPT_PER_CC" 
   (	
    "PK_RCT_CC_INT" BIGINT NOT NULL,
	"TIMESTAMP" DECIMAL(10,0) DEFAULT 1 NOT NULL, 
	"RCT_QTY" DECIMAL(15,2), 
	"ACP_QTY" DECIMAL(15,2), 
	"RTN_TO_SUPL" DECIMAL(15,2), 
	"RCT_VAL" DECIMAL(13,5), 
	"QUANTITY" DECIMAL(15,2), 
	"LINECOST" DECIMAL(13,5), 
	"COSTCENTER" VARCHAR(16), 
	"SAPGL" VARCHAR(20), 
	"GLDEBITACCT" VARCHAR(110), 
    "MATRECTRANSID" BIGINT,
    "SERVRECTRANSID" BIGINT,
	"LINENUM" INT
   ); 

ALTER TABLE MAXIMO.LOCATIONS ALTER COLUMN STE_TUNNEL
 SET DATA TYPE  VARCHAR(8) ;
CALL SYSPROC.ADMIN_CMD('REORG TABLE MAXIMO.LOCATIONS');

ALTER TABLE MAXIMO.LOCATIONS ALTER COLUMN STE_TRAINAREA
 SET DATA TYPE  VARCHAR(4) ;
CALL SYSPROC.ADMIN_CMD('REORG TABLE MAXIMO.LOCATIONS');

ALTER TABLE MAXIMO.STE_ITEM_MAINTENTITY ADD "STE_MIGRATIONID" BIGINT;
ALTER TABLE MAXIMO.STE_ITEM_MAINTENTITY ADD "STE_MIGRATIONDATE" TIMESTAMP;
ALTER TABLE MAXIMO.ROUTES ADD "STE_LOCTYPE" VARCHAR(16);

ALTER TABLE MAXIMO.LOCATIONS ALTER COLUMN STE_VIADUCT
 SET DATA TYPE  VARCHAR(8) ;
CALL SYSPROC.ADMIN_CMD('REORG TABLE MAXIMO.LOCATIONS');

ALTER TABLE MAXIMO.LOCATIONS ALTER COLUMN STE_TRACKNO
 SET DATA TYPE  VARCHAR(8) ;
CALL SYSPROC.ADMIN_CMD('REORG TABLE MAXIMO.LOCATIONS');

ALTER TABLE MAXIMO.LOCATIONS ALTER COLUMN STE_VIADUCTCOLUMNPIERCODE
 SET DATA TYPE  VARCHAR(8) ;
CALL SYSPROC.ADMIN_CMD('REORG TABLE MAXIMO.LOCATIONS');

ALTER TABLE MAXIMO.PLUSTWOQUALFLG ADD "STE_MIGRATIONID" BIGINT;
ALTER TABLE MAXIMO.PLUSTWOQUALFLG ADD "STE_MIGRATIONDATE" TIMESTAMP;
ALTER TABLE MAXIMO.WOANCESTOR ADD "STE_MIGRATIONID" BIGINT;
ALTER TABLE MAXIMO.WOANCESTOR ADD "STE_MIGRATIONDATE" TIMESTAMP;
ALTER TABLE MAXIMO.WOSERVICEADDRESS ADD "STE_MIGRATIONID" BIGINT;
ALTER TABLE MAXIMO.WOSERVICEADDRESS ADD "STE_MIGRATIONDATE" TIMESTAMP;
ALTER TABLE MAXIMO.WOSTATUS ADD "STE_MIGRATIONID" BIGINT;
ALTER TABLE MAXIMO.WOSTATUS ADD "STE_MIGRATIONDATE" TIMESTAMP;
ALTER TABLE MAXIMO.WORKVIEW ADD "STE_MIGRATIONID" BIGINT;
ALTER TABLE MAXIMO.WORKVIEW ADD "STE_MIGRATIONDATE" TIMESTAMP;

CREATE TABLE MAXIMO.CSWN_RES_SUPV 
(	
   	"PK_RES_SUPV" BIGINT NOT NULL,
	"TIMESTAMP" DECIMAL(10,0) DEFAULT 1 NOT NULL, 
	"RS_SUPV" VARCHAR(6), 
	"RS_NAME" VARCHAR(100), 
	"RS_STRING1" VARCHAR(20)
);

CREATE TABLE MAXIMO.CSWN_RES_SUPV_RES_EMPL
(
	PK_RES_EMPL BIGINT NOT NULL,
	RE_EMNO VARCHAR(10),
	RE_FBDT DECIMAL(10,0),
	PK_RES_SUPV BIGINT NOT NULL,
	RS_SUPV VARCHAR(26)
)

ALTER TABLE MAXIMO.LOCANCESTOR ADD "STE_MIGRATIONID" BIGINT;
ALTER TABLE MAXIMO.LOCANCESTOR ADD "STE_MIGRATIONDATE" TIMESTAMP;
ALTER TABLE MAXIMO.LOCHIERARCHY ADD "STE_MIGRATIONID" BIGINT;
ALTER TABLE MAXIMO.LOCHIERARCHY ADD "STE_MIGRATIONDATE" TIMESTAMP;

ALTER TABLE MAXIMO.LABORSTATUS ADD "STE_MIGRATIONID" BIGINT;
ALTER TABLE MAXIMO.LABORSTATUS ADD "STE_MIGRATIONDATE" TIMESTAMP;
ALTER TABLE MAXIMO.LABTRANS ADD "STE_MIGRATIONWOREF" BIGINT;

ALTER TABLE MAXIMO.LOCOPER ADD "STE_MIGRATIONID" BIGINT;
ALTER TABLE MAXIMO.LOCOPER ADD "STE_MIGRATIONDATE" TIMESTAMP;
ALTER TABLE MAXIMO.LOCSTATUS ADD "STE_MIGRATIONID" BIGINT;
ALTER TABLE MAXIMO.LOCSTATUS ADD "STE_MIGRATIONDATE" TIMESTAMP;

CREATE TABLE MAXIMO.CSWN_EQP_DEFR 
   (	
   	"PK_EQP_DEFR" BIGINT, 
	"TIMESTAMP" DECIMAL(10,0) DEFAULT 1 NOT NULL, 
	"EQ_DR_08" BIGINT, 
	"EQ_DR_09" BIGINT, 
	"CT_DR_11" BIGINT, 
	"CT_DR_12" BIGINT, 
	"CT_DR_13" BIGINT, 
	"CT_DR_14" BIGINT, 
	"WO_DR_59" BIGINT, 
	"IDX_WO_DR_59" DECIMAL(10,0), 
	"DR_SYCD" VARCHAR(10), 
	"DR_DFCD" VARCHAR(10), 
	"DR_CACD" VARCHAR(10), 
	"DR_ACCD" VARCHAR(10), 
	"DR_REP_DT" DECIMAL(10,0), 
	"DR_REP_TM" DECIMAL(10,0), 
	"DR_REPDD" DECIMAL(5,0), 
	"DR_REPWK" DECIMAL(5,0), 
	"DR_REPYR" DECIMAL(5,0), 
	"DR_DURT" DECIMAL(10,2), 
	"DR_WOID" DECIMAL(10,0), 
	"DR_REP_ML" DOUBLE, 
	"DR_TOT_COST" DECIMAL(10,2), 
	"DR_JOBREQUEST" VARCHAR(10)
   ); 

ALTER TABLE MAXIMO.CSWN_EQP_DEFR ALTER COLUMN DR_REP_ML
 SET DATA TYPE DOUBLE ;
CALL SYSPROC.ADMIN_CMD('REORG TABLE MAXIMO.CSWN_EQP_DEFR');

ALTER TABLE MAXIMO.ROUTES ADD "STE_CSWNAUTHORITY" VARCHAR(16);
ALTER TABLE MAXIMO.WORKORDER ADD "STE_CSWNEQAUTHORITY" VARCHAR(16);
ALTER TABLE MAXIMO.STE_ALTFAILURECODE ADD "STE_MIGRATIONID" BIGINT;
ALTER TABLE MAXIMO.STE_ALTFAILURECODE ADD "STE_MIGRATIONDATE" TIMESTAMP;

ALTER TABLE MAXIMO.ITEM ADD "STE_LINE" VARCHAR(8);
ALTER TABLE MAXIMO.ASSET ADD "STE_ORIGITEMNUM" VARCHAR(30);

ALTER TABLE MAXIMO.INVRESERVE ADD "STE_MIGRATIONID" BIGINT;
ALTER TABLE MAXIMO.INVRESERVE ADD "STE_MIGRATIONDATE" TIMESTAMP;
ALTER TABLE MAXIMO.INVUSE ADD "STE_MIGRATIONID" BIGINT;
ALTER TABLE MAXIMO.INVUSE ADD "STE_MIGRATIONDATE" TIMESTAMP;
ALTER TABLE MAXIMO.INVUSELINE ADD "STE_MIGRATIONID" BIGINT;
ALTER TABLE MAXIMO.INVUSELINE ADD "STE_MIGRATIONDATE" TIMESTAMP;

-- DROP TABLE MAXIMO.CSWN_LABTRANS;
CREATE TABLE MAXIMO.CSWN_LABTRANS (
	PK_WIP_WE BIGINT,
	"TIMESTAMP" BIGINT,
	WE_EMNO VARCHAR(10),
	PK_RES_EMPL BIGINT,
	RE_EMNO VARCHAR(10),
	RE_BRCD VARCHAR(10),
	RE_NAME VARCHAR(100),
	RE_RATE DECIMAL(22, 10),
	RT_TDCD VARCHAR(10),
	RT_NAME VARCHAR(100),
	RT_DEF_RATE INTEGER,
	RT_RATE DECIMAL(22, 10),
	WE_ONDT BIGINT,
	WE_ONTM BIGINT,
	WE_OFDT BIGINT,
	WE_OFTM BIGINT,
	WE_WKHR DECIMAL(22, 10),
	WE_TOHR DECIMAL(22, 10),
	WE_SHID DECIMAL(22, 10),
	WE_RATEID INTEGER,
	WE_EMSTU INTEGER,
	WE_PLHR DECIMAL(22, 10),
	WE_LAST_FLG INTEGER,
	WE_DISTRIB INTEGER,
	WE_NUMBER1 DECIMAL(22, 10),
	WE_STRING1 VARCHAR(20),
	WO_STATUS VARCHAR(16),
	WE_WOSTU INTEGER,
	PK_WIP_WO BIGINT,
	WO_WOID BIGINT,
	WO_EQCD VARCHAR(20),
	WO_SYCD VARCHAR(20),
	WO_WOSTU INTEGER,
	PK_EQP_TOPO BIGINT,
	EQ_LEVL INTEGER
);

CREATE INDEX TICKET_CLASS_IDX ON MAXIMO.TICKET (CLASS,STE_MIGRATIONID);

-- SR
CREATE TABLE MAXIMO.CSWN_SR (
	PK_EQP_JOBR BIGINT,
	"TIMESTAMP" BIGINT,
	EQ_JR_39 BIGINT,
	JR_REF_NO VARCHAR(10),
	JR_REQ_DT BIGINT,
	JR_REQ_TM BIGINT,
	JR_REQBY_ID VARCHAR(20),
	JR_REQBY_NAME VARCHAR(100),
	JR_REQBY_PH VARCHAR(15),
	JR_TARGET_DT BIGINT,
	JR_EQCD VARCHAR(20),
	JR_ZONE VARCHAR(10),
	JR_UNIT VARCHAR(10),
	JR_COSTCENT VARCHAR(16),
	JR_SUPV VARCHAR(6),
	JR_JOB_ID VARCHAR(16),
	JR_SCH_DT BIGINT,
	JR_COMP_DT BIGINT,
	JR_PRIME_REF VARCHAR(10),
	JR_WO_REF BIGINT,
	JR_FRDT BIGINT,
	JR_FRTM BIGINT,
	JR_TODT BIGINT,
	JR_TOTM BIGINT,
	JR_DN_TIME DECIMAL(22, 10),
	JR_SANC_NOTE1 VARCHAR(30),
	JR_SANC_NOTE2 VARCHAR(30),
	JR_VISA VARCHAR(10),
	JR_TYPE INTEGER,
	JR_STAT INTEGER,
	JR_FLAG1 INTEGER,
	JR_FLAG2 INTEGER,
	JR_NUMBER1 DECIMAL(22, 10),
	JR_NUMBER2 DECIMAL(22, 10),
	JR_DATE1 BIGINT,
	JR_STRING1 VARCHAR(20),
	JR_STRING2 VARCHAR(20),
	JR_SRCEQP_CD VARCHAR(20),
	JR_PRIORITY VARCHAR(10),
	JR_SRC_WO BIGINT,
	JR_ACTION_AUTH VARCHAR(16),
	JR_REQUEST_AUTH VARCHAR(16),
	WO_WOID BIGINT,
	PK_EQP_TOPO BIGINT, 
	EQ_EQCD VARCHAR(20),
	EQ_LEVL INTEGER,
	FAILURECLASS VARCHAR(20),
	PROBLEMCODE VARCHAR(20),
	DR_REP_DT BIGINT, 
	DR_REP_TM BIGINT, 
	DR_TOT_COST DECIMAL(22, 10),
	STATUS_TEXT VARCHAR(16),
	PRIORITY SMALLINT
);

-- WORKORDER
--DROP TABLE MAXIMO.CSWN_WO;
CREATE TABLE MAXIMO.CSWN_WO ( 
	PK_WIP_WO BIGINT,
	TIMESTAMP BIGINT,
	WO_JOB_ID VARCHAR(16),
	EJ_JOB_ID VARCHAR(16),
	JD_JOB_DS VARCHAR(100),
	WO_EQCD VARCHAR(20),
	WO_SYCD VARCHAR(20),
	PK_EQP_TOPO BIGINT, 
	EQ_EQCD VARCHAR(20),
	EQ_DESC VARCHAR(100), 
	EQ_AUTHORITY VARCHAR(16),
	WO_WOID BIGINT, 
	WO_PLID INTEGER, 
	WO_ZONE VARCHAR(10), 
	WO_UNIT VARCHAR(10), 
	WO_COSC VARCHAR(16), 
	CC_NAME VARCHAR(100), 
	WO_EQLEVL INTEGER, 
	WO_EQ_PHON VARCHAR(13), 
	WO_JBTYU VARCHAR(6), 
	C1_DESC VARCHAR(100),
	WO_JBCLU VARCHAR(6), 
	C2_DESC VARCHAR(100),
	WO_SUP_CD VARCHAR(6),
	WO_REP_BY VARCHAR(20),
	WO_REQNO VARCHAR(10), 
	JR_REF_NO VARCHAR(10),
	WO_CON_REF VARCHAR(10), 
	WO_PRJ_REF VARCHAR(10), 
	WO_DURN INTEGER, 
	WO_PUO_FL INTEGER, 
	WO_IEX_FL INTEGER, 
	WO_TPTY INTEGER, 
	WO_HIST INTEGER, 
	WO_WOSTU INTEGER, 
	WO_STATUS VARCHAR(16),
	WO_WOSTX INTEGER, 
	PK_DIR_WOST BIGINT,
	C3_DESC VARCHAR(100),
	WO_SCH_DT BIGINT, 
	WO_ISS_DT BIGINT, 
	WO_REP_DT BIGINT, 
	WO_REP_TM BIGINT, 
	WO_STR_DT BIGINT, 
	WO_STR_TM BIGINT, 
	WO_FIN_DT BIGINT, 
	WO_FIN_TM BIGINT, 
	WO_LUP_DT BIGINT, 
	WO_MAN_DT BIGINT, 
	WO_MAN_TM BIGINT, 
	WO_LAB_SCOST DECIMAL(22, 10), 
	WO_MAT_SCOST DECIMAL(22, 10), 
	WO_LAB_ACOST DECIMAL(22, 10), 
	WO_MAT_ACOST DECIMAL(22, 10), 
	WO_MSC_ACOST DECIMAL(22, 10), 
	WO_REC_ACOST DECIMAL(22, 10), 
	WO_PLN_HRS DECIMAL(22, 10), 
	WO_ACT_HRS DECIMAL(22, 10), 
	WO_DN_TIME DECIMAL(22, 10), 
	WO_JBML VARCHAR(50), 
	WO_TOT_CUM_UNTS VARCHAR(50), 
	WO_LOCT VARCHAR(16), 
	PREV_WO_WOID BIGINT, 
	WO_EQP_SRL VARCHAR(24), 
	WO_FOR_REP INTEGER, 
	WO_SPEC_VALUE DECIMAL(22, 10), 
	WO_PLN_JOB INTEGER, 
	WO_PREV_SRL_NO VARCHAR(24), 
	WO_REPL_MASK INTEGER, 
	WO_STRING1 VARCHAR(20), 
	WO_STRING2 VARCHAR(20), 
	WO_STRING3 VARCHAR(20), 
	WO_PRIORITY VARCHAR(10), 
	PY_CODE VARCHAR(10),
	PY_DESCRIPTION VARCHAR(100),
	WO_TARGET_DT BIGINT, 
	WO_SAFETY_INVOLVED INTEGER, 
	WO_FM_ACOST DECIMAL(22, 10), 
	WO_FM_SCOST DECIMAL(22, 10), 
	WO_ACTION_AUTH VARCHAR(16), 
	WO_REQUEST_AUTH VARCHAR(16), 
	CE_TYPE VARCHAR(10),
	CE_DESC VARCHAR(100), 
	WO_CRITICALITY INTEGER, 
	CRITICALITY_TEXT VARCHAR(16),
	WO_ALLOCATIONSTATUS INTEGER, 
	PROBLEMCODE VARCHAR(25),
	DR_REP_DT BIGINT,
	DR_REP_TM BIGINT, 
	DR_TOT_COST DECIMAL(22, 10),
	WO_WORK_PERMIT VARCHAR(10), 
	WP_CODE VARCHAR(10),
	WP_TYPE VARCHAR(10),
	WP_JOB_DESC VARCHAR(100),
	CHILDREN INTEGER,
	CHILD_LABORS INTEGER,
	CHILD_WKHR INTEGER,
	LABORS INTEGER,
	LABORS_WKHR INTEGER,
	TRADES INTEGER,
	TRADE_WKHR INTEGER,
	TRADE_WKHR2 INTEGER,
	STE_WASHCODE VARCHAR(8),
	WORKTYPE VARCHAR(8),
	WORKORDERTYPE VARCHAR(8)
);

CREATE INDEX CSWN_WO_WORKORDERTYPE_IDX ON MAXIMO.CSWN_WO (WORKORDERTYPE);

ALTER TABLE MAXIMO.INVUSE ALTER COLUMN STE_CSWNDEMREF
 SET DATA TYPE  VARCHAR(10) ;
ALTER TABLE MAXIMO.INVUSE ALTER COLUMN STE_CSWNORIGDEMREF
 SET DATA TYPE  VARCHAR(10) ;
CALL SYSPROC.ADMIN_CMD('REORG TABLE MAXIMO.INVUSE');

ALTER TABLE MAXIMO.INVUSE ADD "STE_CSWNISSREF" VARCHAR(10);
ALTER TABLE MAXIMO.MRLINE ADD "STE_MIGRATIONSOURCE" VARCHAR(50);
ALTER TABLE MAXIMO.MR ADD "STE_CSWNDEMREF" VARCHAR(10);
ALTER TABLE MAXIMO.ITEM ADD "STE_CSWNBUYCURR" VARCHAR(8);

ALTER TABLE MAXIMO.GLCOMPONENTS ALTER COLUMN STE_COSTCENTREDEPT
 SET DATA TYPE  VARCHAR(8) ;
CALL SYSPROC.ADMIN_CMD('REORG TABLE MAXIMO.GLCOMPONENTS');

ALTER TABLE MAXIMO.MATUSETRANS DROP COLUMN STE_ORIGMRNUM;
ALTER TABLE MAXIMO.PR ADD "STE_CSWNPRREF" VARCHAR(10);
ALTER TABLE MAXIMO.RFQ ADD "STE_CSWNRFQREF" VARCHAR(13);
ALTER TABLE MAXIMO.RFQ ADD "STE_PONUM" VARCHAR(10);
ALTER TABLE MAXIMO.PO ADD "STE_CSWNPOREF" VARCHAR(10);

ALTER TABLE MAXIMO.ITEM ADD "STE_CSWNITEMCC" VARCHAR(10);
ALTER TABLE MAXIMO.MRSTATUS ADD "STE_MIGRATIONID" BIGINT;
ALTER TABLE MAXIMO.MRSTATUS ADD "STE_MIGRATIONDATE" TIMESTAMP;
ALTER TABLE MAXIMO.INVSTATUS ADD "STE_MIGRATIONID" BIGINT;
ALTER TABLE MAXIMO.INVSTATUS ADD "STE_MIGRATIONDATE" TIMESTAMP;

ALTER TABLE MAXIMO.MRCOST ADD "STE_MIGRATIONID" BIGINT;
ALTER TABLE MAXIMO.MRCOST ADD "STE_MIGRATIONDATE" TIMESTAMP;
ALTER TABLE MAXIMO.ITEMSTATUS ADD "STE_MIGRATIONID" BIGINT;
ALTER TABLE MAXIMO.ITEMSTATUS ADD "STE_MIGRATIONDATE" TIMESTAMP;
ALTER TABLE MAXIMO.ITEMORGSTATUS ADD "STE_MIGRATIONID" BIGINT;
ALTER TABLE MAXIMO.ITEMORGSTATUS ADD "STE_MIGRATIONDATE" TIMESTAMP;
ALTER TABLE MAXIMO.INVUSELINESPLIT ADD "STE_MIGRATIONID" BIGINT;
ALTER TABLE MAXIMO.INVUSELINESPLIT ADD "STE_MIGRATIONDATE" TIMESTAMP;
ALTER TABLE MAXIMO.INVUSESTATUS ADD "STE_MIGRATIONID" BIGINT;
ALTER TABLE MAXIMO.INVUSESTATUS ADD "STE_MIGRATIONDATE" TIMESTAMP;
ALTER TABLE MAXIMO.INVUSE ADD "STE_COSWINCC" VARCHAR(16);
ALTER TABLE MAXIMO.TICKET ADD "STE_COSWINCC" VARCHAR(16);
ALTER TABLE MAXIMO.INVENTORY ADD "STE_COSWINCC" VARCHAR(16);
ALTER TABLE MAXIMO.ASSET ADD "STE_CSWNEQCOSC" VARCHAR(16);

ALTER TABLE MAXIMO.ASSETTRANS ADD "STE_CSWNEMZONE" VARCHAR(10);
ALTER TABLE MAXIMO.RFQVENDOR ADD "STE_CSWNDEVISCD" VARCHAR(13);
ALTER TABLE MAXIMO.RFQVENDOR ADD "STE_CSWNREFDEVISCD" VARCHAR(13);
ALTER TABLE MAXIMO.RFQVENDOR ADD "STE_CSWNPOREF" VARCHAR(10);
ALTER TABLE MAXIMO.RFQVENDOR ADD "STE_CSWNPRREF" VARCHAR(10);
ALTER TABLE MAXIMO.RFQVENDOR ADD "STE_REMARKS" VARCHAR(100);

ALTER TABLE MAXIMO.QUOTATIONLINE ADD "STE_CSWNDEVISCD" VARCHAR(13);
ALTER TABLE MAXIMO.QUOTATIONLINE ADD "STE_CSWNREFDEVISCD" VARCHAR(13);

ALTER TABLE MAXIMO.ASSETTRANS ADD "STE_CSWNEMZONE" VARCHAR(10);
ALTER TABLE MAXIMO.INVVENDOR ADD "STE_CSWNLATUNITRATE" DECIMAL(18,6);
ALTER TABLE MAXIMO.INVVENDOR ADD "STE_CSWNBUYPRICE" DECIMAL(18,6);
ALTER TABLE MAXIMO.INVVENDOR ADD "STE_CSWNLASTDATE" DATE;

CREATE TABLE "MAXIMO"."CSWN_INVENTORY"  
(
	  "PK_STORES_ITEMS" BIGINT , 
	  "TIMESTAMP" BIGINT , 
	  "IS_STOR_CD" VARCHAR(10 OCTETS) , 
	  "ITEM_CD" VARCHAR(20 OCTETS) , 
	  "ITEM_CC" VARCHAR(16 OCTETS) , 
	  "ITEM_MEMO" VARCHAR(100 OCTETS) , 
	  "ITEM_STRING2" VARCHAR(20 OCTETS) , 
	  "ORDER_UNITS" VARCHAR(20 OCTETS) , 
	  "STOCK_UNITS" VARCHAR(6 OCTETS) , 
	  "ABC_CLASS" INTEGER , 
	  "ABCTYPE" VARCHAR(2 OCTETS) , 
	  "CNT_FREQ" INTEGER , 
	  "ORG_SUPL_CD" VARCHAR(20 OCTETS) , 
	  "STKOUT_RISKP" DECIMAL(18,6) , 
	  "DT_FIRST_PROC" DECIMAL(10,0) , 
	  "ITEM_NUMBER1" DECIMAL(18,6) , 
	  "PK_ITEM_INFO" BIGINT , 
	  "MAX_QTY" DECIMAL(18,6) , 
	  "MIN_QTY" DECIMAL(18,6) , 
	  "VAL_METHOD" INTEGER , 
	  "AVG_LEAD_TIME" INTEGER , 
	  "MAX_LEAD_TIME" INTEGER , 
	  "MIN_LEAD_TIME" INTEGER , 
	  "Y_1_CON_QTY" DECIMAL(18,6) , 
	  "Y_2_CON_QTY" DECIMAL(18,6) , 
	  "I_FREE_QTY" DECIMAL(18,6) , 
	  "I_RES_QTY" DECIMAL(18,6) , 
	  "I_INSP_QTY" DECIMAL(18,6) , 
	  "REORD_LEVEL" DECIMAL(18,6) , 
	  "ECON_ORD_QTY" DECIMAL(18,6) , 
	  "I_CYCLE" INTEGER , 
	  "I_CYCLIC_REORDER" INTEGER , 
	  "PK_ITEM_GROUP" BIGINT , 
	  "GRP_CNT_FREQ" INTEGER , 
	  "GRP_PR_AUTO" INTEGER , 
	  "GRP_PO_AUTO" INTEGER , 
	  "SUPL_CD" VARCHAR(20 OCTETS) , 
	  "S_ITEM_REF" VARCHAR(20 OCTETS) 
)   
 IN "MAXDATA"  
 ORGANIZE BY ROW;

CREATE TABLE "MAXIMO"."CSWN_INVVENDOR"  
(
	  "PK_SUPL_ITEMS" BIGINT , 
	  "TIMESTAMP" BIGINT , 
	  "DT_SUPL_ITEMS" BIGINT , 
	  "TM_SUPL_ITEMS" BIGINT , 
	  "S_ITEM_REF" VARCHAR(20 OCTETS) , 
	  "S_ITEM_UNIT" VARCHAR(6 OCTETS) , 
	  "YTD_QTY" DECIMAL(18,6) , 
	  "TOD_QTY" DECIMAL(18,6) , 
	  "LYR_QTY" DECIMAL(18,6) , 
	  "YTD_PO_VAL" DECIMAL(18,6) , 
	  "TOD_PO_VAL" DECIMAL(18,6) , 
	  "LYR_PO_VAL" DECIMAL(18,6) , 
	  "YTD_REJ_QTY" DECIMAL(18,6) , 
	  "TOD_REJ_QTY" DECIMAL(18,6) , 
	  "LYR_REJ_QTY" DECIMAL(18,6) , 
	  "YTD_PO_NO" INTEGER , 
	  "TOD_PO_NO" INTEGER , 
	  "LYR_PO_NO" INTEGER , 
	  "YTD_DEL_NO" INTEGER , 
	  "TOD_DEL_NO" INTEGER , 
	  "LYR_DEL_NO" INTEGER , 
	  "YTD_REJ_NO" INTEGER , 
	  "TOD_REJ_NO" INTEGER , 
	  "LYR_REJ_NO" INTEGER , 
	  "S_L_PO" VARCHAR(10 OCTETS) , 
	  "S_L_DT_PO" BIGINT , 
	  "PRI_TRND" DECIMAL(18,6) , 
	  "S_AVG_LEAD_DYS" INTEGER , 
	  "REP_ORDR_FLG" INTEGER , 
	  "S_LAT_UNIT_RATE" DECIMAL(18,6) , 
	  "S_BASE_MIN_ORD" DECIMAL(18,6) , 
	  "S_DISC_QORV" INTEGER , 
	  "S_PRT_RMK_FLG" INTEGER , 
	  "ITEM_CD" VARCHAR(20 OCTETS) , 
	  "ITEM_DS" VARCHAR(104 OCTETS) , 
	  "BUY_PRICE" DECIMAL(18,6) , 
	  "I_VAT_CD" INTEGER , 
	  "PLAN_DAYS" INTEGER , 
	  "SUPL_CD" VARCHAR(20 OCTETS) , 
	  "AVG_LEAD_TIME" INTEGER , 
	  "MIN_LEAD_TIME" INTEGER , 
	  "MAX_LEAD_TIME" INTEGER 
)   
 IN "USERSPACE1"  
 ORGANIZE BY ROW;

CREATE TABLE "MAXIMO"."CSWN_INVBALANCES"  (
		  "PK_LOCATIONS_" BIGINT , 
		  "IS_STOR_CD" VARCHAR(10 OCTETS) , 
		  "BIN_REF" VARCHAR(16 OCTETS) , 
		  "ITEM_CD" VARCHAR(20 OCTETS) , 
		  "L_SCNT_DT" BIGINT , 
		  "DT_LOCATION" BIGINT , 
		  "LOC_PROC_DT" BIGINT , 
		  "LOC_FREE_QTY" INTEGER , 
		  "LOC_RES_QTY" INTEGER , 
		  "LOC_FROZEN_QTY" INTEGER , 
		  "TIMESTAMP" BIGINT )   
;

CREATE TABLE "MAXIMO"."CSWN_MATRECTRANS" 
   (	
   	"PK_RCT_ITEMS" BIGINT, 
   	TIMESTAMP BIGINT,
   	DT_RCT_ITEMS BIGINT,
   	TM_RCT_ITEMS BIGINT,
	"RCT_QTY" DECIMAL(28,12), 
	"ACP_QTY" DECIMAL(28,12), 
	"RTN_TO_SUPL" DECIMAL(28,12), 
	"RCT_UNIT" VARCHAR(6), 
	"RCT_UNIT_RATE" DECIMAL(28,12), 
	"RCT_VAL" DECIMAL(28,12), 
	"INSP_REF" VARCHAR(9), 
	"INSP_DT" BIGINT, 
	"INSP_STAT" INTEGER, 
	"RCT_TP_FLG" INTEGER, 
	"RCT_INV_QTY" DECIMAL(28,12), 
	"RCT_RCL_QTY" DECIMAL(28,12), 
	"RCT_ACT_NO" INTEGER, 
	"RCT_IT_NUMBER1" DECIMAL(28,12), 
	"RCT_IT_STRING1" VARCHAR(20), 
	"RCT_PO_REF" VARCHAR(10), 
	MRSTATUS VARCHAR(12),
	DN_REF VARCHAR(10),
 	RCT_TYPE INTEGER,
	RCT_TYPE_TXT VARCHAR(12),
	RCT_DT BIGINT,		
	DT_RECEIPT BIGINT,
	TM_RECEIPT BIGINT,
	GRN_REF VARCHAR(10),
	GRN_DT BIGINT, 		
	RCT_STATUS INTEGER,
	RCT_STRING1 VARCHAR(20),
	RCT_STRING2 VARCHAR(20),
	DN_DT BIGINT,		
	TRANSPORT VARCHAR(15),
	RCT_DEM_WO_REF VARCHAR(10),
	RCT_SUPL_CD VARCHAR(20),
	RECEIPT_CODE VARCHAR(10),
	RCT_PACKAGE VARCHAR(20),
	LINENUM SMALLINT,
	S_CURR_CD VARCHAR(6),
	ITEM_CD VARCHAR(20),
	INV_REF VARCHAR(16), 
	PO_AMD_NO INTEGER,
	RN INTEGER
);

CREATE TABLE "MAXIMO"."CSWN_RFQ"  
(
	  "PK_DEVIS" BIGINT , 
	  "TIMESTAMP" BIGINT , 
	  "S_SUPL_DV" BIGINT , 
	  "DT_DEVIS" BIGINT , 
	  "TM_DEVIS" BIGINT , 
	  "DEVIS_CD" VARCHAR(13 OCTETS) , 
	  "DEVIS_DATE" BIGINT , 
	  "DV_INCHARGE" VARCHAR(16 OCTETS) , 
	  "DV_TEXT" VARCHAR(100 OCTETS) , 
	  "DV_CC_CD" VARCHAR(16 OCTETS) , 
	  "DV_STATUS" INTEGER , 
	  "DV_PO_CD" VARCHAR(10 OCTETS) , 
	  "DV_PREQ_REF" VARCHAR(10 OCTETS) , 
	  "DV_PAY_MOD" VARCHAR(6 OCTETS) , 
	  "DV_WOID" VARCHAR(10 OCTETS) , 
	  "DV_STRING1" VARCHAR(20 OCTETS) , 
	  "DV_STRING2" VARCHAR(20 OCTETS) , 
	  "DV_EXP_RET" BIGINT , 
	  "REF_DEVIS_CD" VARCHAR(13 OCTETS) , 
	  "PK_SUPPLIER_" BIGINT , 
	  "SUPL_CD" VARCHAR(20 OCTETS) , 
	  "SUPL_NAME" VARCHAR(100 OCTETS) , 
	  "S_CURR_CD" VARCHAR(6 OCTETS) 
)   
 IN "MAXDATA"  
 ORGANIZE BY ROW;

CREATE TABLE "MAXIMO"."CSWN_RFQLINE" 
   (	
   	"PK_DV_ITEMS" BIGINT, 
	"TIMESTAMP" BIGINT, 
	"S_DV_ITEM" BIGINT, 
	"S_ITEM_DV" BIGINT, 
	"S_NSITEM_DV" BIGINT, 
	"S_DV_ITEM_GEN" BIGINT, 
	"DT_DV_ITEMS" BIGINT, 
	"TM_DV_ITEMS" BIGINT, 
	"DV_QTY" DECIMAL(28,12), 
	"DV_UNIT" VARCHAR(6), 
	"DV_UNIT_RATE" DECIMAL(28,12), 
	"DV_DELAY" INTEGER, 
	"DV_VALUE" DECIMAL(28,12), 
	"DV_DISCNT" INTEGER, 
	"DV_TO_ORDER" INTEGER, 
	"DV_IT_NUMBER1" DECIMAL(28,12), 
	"DV_IT_STRING1" VARCHAR(20), 
	"DV_STOR_CD" VARCHAR(10),
	ISAWARDED SMALLINT,
	PK_DEVIS BIGINT,
	DEVIS_CD VARCHAR(13),
	ITEM_CD VARCHAR(20),
	ITEM_DS VARCHAR(104),
	SUPL_CD VARCHAR(20),
	S_ITEM_REF VARCHAR(20),
	LINENUM INTEGER
);

CREATE TABLE "MAXIMO"."CSWN_PO"  
(
	  "PK_PORDER_" BIGINT , 
	  "TIMESTAMP" BIGINT , 
	  "S_SUPL_PO" BIGINT , 
	  "DT_PORDER" BIGINT , 
	  "TM_PORDER" BIGINT , 
	  "PO_REF" VARCHAR(10 OCTETS) , 
	  "PO_DT" BIGINT , 
	  "PO_TYPE" INTEGER , 
	  "PO_STATUS" INTEGER , 
	  "PO_AUT_BY" VARCHAR(16 OCTETS) , 
	  "PO_CURR_CD" VARCHAR(6 OCTETS) , 
	  "PO_APR_QORV" INTEGER , 
	  "PO_AMD_NO" INTEGER , 
	  "PO_AMD_DT" BIGINT , 
	  "PO_AMD_WHO" VARCHAR(16 OCTETS) , 
	  "PO_CHASE_DT" BIGINT , 
	  "PO_VALUE" DECIMAL(15,2) , 
	  "PO_DEM_WO_REF" VARCHAR(10 OCTETS) , 
	  "PO_BLKT_REF" VARCHAR(10 OCTETS) , 
	  "PO_VALID_FM" BIGINT , 
	  "PO_VALID_TO" BIGINT , 
	  "PO_DELVD_VALUE" DECIMAL(15,2) , 
	  "PO_PENDG_VALUE" DECIMAL(15,2) , 
	  "PO_PRT_NOS" INTEGER , 
	  "DR_TXT1" VARCHAR(13 OCTETS) , 
	  "DR_TXT2" VARCHAR(10 OCTETS) , 
	  "PO_PREQ_REF" VARCHAR(10 OCTETS) , 
	  "PO_PART_VALUE" DECIMAL(15,2) , 
	  "PO_PAY_DET" VARCHAR(6 OCTETS) , 
	  "PO_REQ_BY" VARCHAR(16 OCTETS) , 
	  "PO_PRT_DT" BIGINT , 
	  "PO_STRING1" VARCHAR(20 OCTETS) , 
	  "PO_STRING2" VARCHAR(20 OCTETS) , 
	  "PO_ORIG_ORDER" VARCHAR(10 OCTETS) , 
	  "PK_SUPPLIER_" BIGINT , 
	  "SUPL_CD" VARCHAR(20 OCTETS) , 
	  "SUPL_NAME" VARCHAR(100 OCTETS) , 
	  "S_CURR_CD" VARCHAR(6 OCTETS) , 
	  "PO_ITEM_DEL_DT" BIGINT , 
	  "PO_STATUS_TEXT" VARCHAR(20 OCTETS) , 
	  "RECEIPT_TEXT" VARCHAR(20 OCTETS) , 
	  "REQ_BY_ID" VARCHAR(100 OCTETS) , 
	  "BLKT_RN" INTEGER , 
	  "VENDDELIVERYDATE" TIMESTAMP , 
	  "RFQCLOSEDATE" TIMESTAMP 
)   
 IN "MAXDATA"  
 ORGANIZE BY ROW;

CREATE TABLE "MAXIMO"."CSWN_WOACTIVITY"  
(
	  "PK_WIP_WA" BIGINT , 
	  "TIMESTAMP" BIGINT , 
	  "WA_NO" INTEGER , 
	  "WA_ACT" VARCHAR(10 OCTETS) , 
	  "WA_EXEC_STATUS" INTEGER , 
	  "WA_DT" BIGINT , 
	  "WA_DURN" DECIMAL(18,6) , 
	  "WA_WO_GEN" BIGINT , 
	  "WA_MULTIPLE" INTEGER , 
	  "WA_PLANNED" INTEGER , 
	  "WA_EQCD" VARCHAR(20 OCTETS) , 
	  "WA_ELEM" VARCHAR(40 OCTETS) , 
	  "WA_VAL1" DECIMAL(18,6) , 
	  "WA_VAL2" DECIMAL(18,6) , 
	  "WA_OP_TYPE" VARCHAR(20 OCTETS) , 
	  "WA_DEVICE" VARCHAR(20 OCTETS) , 
	  "WA_EQP_STAT" VARCHAR(20 OCTETS) , 
	  "WA_UNIT1" VARCHAR(6 OCTETS) , 
	  "WA_UNIT2" VARCHAR(6 OCTETS) , 
	  "ACT_DESC" VARCHAR(104 OCTETS) , 
	  "PK_EQP_TOPO" BIGINT , 
	  "EQ_LEVL" INTEGER , 
	  "PK_WIP_WO" BIGINT , 
	  "WO_WOID" VARCHAR(10 OCTETS) , 
	  "LABORS" INTEGER , 
	  "LABORS_WKHR" DECIMAL(18,6) 
)   
 IN "MAXDATA"  
 ORGANIZE BY ROW;

CREATE TABLE "MAXIMO"."CSWN_POLINE" 
(	
   "PK_PO_ITEMS" BIGINT, 
	"TIMESTAMP" BIGINT, 
	"S_NSITEM_PO" BIGINT, 
	"S_ITEM_PO" BIGINT, 
	"DT_PO_ITEMS" BIGINT, 
	"TM_PO_ITEMS" BIGINT, 
	"PO_NST_REF" VARCHAR(2), 
	"PO_QTY" DECIMAL(28,12), 
	"PO_PENDING_QTY" DECIMAL(28,12), 
	"PO_INV_QTY" DECIMAL(28,12), 
	"PO_UNIT" VARCHAR(6), 
	"PO_UNIT_RATE" DECIMAL(28,12), 
	"PO_RCT_QTY" DECIMAL(28,12), 
	"PO_TP_FLG" INTEGER, 
	"PO_ITEM_DEL_DT" BIGINT, 
	"PO_ITEM_1EXTRA" DECIMAL(28,12), 
	"PO_DISCNT" INTEGER, 
	"PO_IT_NUMBER1" DECIMAL(28,12), 
	"PO_IT_STRING1" VARCHAR(20), 
	"PO_STOR_CD" VARCHAR(10),
	"PK_PORDER_" BIGINT, 
	"PO_REF" VARCHAR(10), 
	"DR_TXT1" VARCHAR(13), 
	"DR_TXT2" VARCHAR(10), 
	"PO_AMD_WHO" VARCHAR(16), 
	"PO_AMD_DT" BIGINT, 
	"PO_AMD_NO" BIGINT, 
	"PO_STRING1" VARCHAR(20), 
	"PO_DEM_WO_REF" VARCHAR(10), 
	PK_WIP_WO BIGINT, 
	ITEM_CD VARCHAR(20), 
	ITEM_DS VARCHAR(104), 
	CATEGORY VARCHAR(10),
	PK_SUPPLIER_ BIGINT,
	SUPL_CD VARCHAR(20), 
	SUPL_NAME VARCHAR(104), 
	PK_SUPL_ITEMS BIGINT,
	S_ITEM_REF VARCHAR(20), 
	AMD_USER_ID VARCHAR(16),
	CC_CD VARCHAR(16), 
	LINENUM INTEGER
)
 IN "MAXDATA"  
 ORGANIZE BY ROW;

CREATE TABLE "MAXIMO"."CSWN_PRLINE" 
   (	
   "PK_PR_ITEMS" BIGINT, 
	"TIMESTAMP" BIGINT, 
	"S_NSITEM_PR" BIGINT, 
	"S_ITEM_PR" BIGINT, 
	"DT_PR_ITEMS" BIGINT, 
	"TM_PR_ITEMS" BIGINT, 
	"NEEDED_DT" BIGINT, 
	"PR_QTY" DECIMAL(28,12), 
	"PR_ORD_QTY" DECIMAL(28,12), 
	"PR_UNIT" VARCHAR(6), 
	"PR_NST_REF" VARCHAR(2), 
	"PR_TP_FLG" INTEGER, 
	"PR_PREF_SUPL" VARCHAR(20), 
	"PR_ITEM_EST_VAL" DECIMAL(28,12), 
	"PR_DEV_QTY" DECIMAL(28,12), 
	"PR_IT_NUMBER1" DECIMAL(28,12), 
	"PR_IT_STRING1" VARCHAR(20), 
	"PR_STOR_CD" VARCHAR(10), 
	PK_PREQUEST BIGINT,
	PR_REF VARCHAR(10), 
	PR_CC VARCHAR(16),  
	PR_STRING1 VARCHAR(20),
	PR_STRING2 VARCHAR(20), 
	PR_WO_REF VARCHAR(10),
	PK_WIP_WO BIGINT,
	ITEM_CD VARCHAR(20),
	ITEM_DS VARCHAR(104),
	BUY_PRICE DECIMAL(28,12),
	BUY_CURR VARCHAR(6), 
	LINENUM INTEGER
)
 IN "MAXDATA"  
 ORGANIZE BY ROW;