SELECT ID, PERSONID, DISPLAYNAME, SAPID, LANID, EMAIL, MAINTENTITY, DEPARTMENT, MAIN_BUSINESS_ROLE, MAINTENANCE_POC, ASSET_POC, RAISE_PR, REMARKS
FROM MIGRATION.SBST_USER_MASTER;

-- DUPLICATE DATA
MERGE INTO MAXIMO.PERSON AS A
USING (
	SELECT p.PERSONUID, p.PERSONID AS OLDPERSONID, p.STATUS, m.*
	FROM MIGRATION.SBST_USER_MASTER m 
	JOIN maximo.PERSON p ON m.SAPID=p.PERSONID 
	WHERE p.PERSONID NOT IN (SELECT PERSONID FROM MIGRATION.SBST_USER_MASTER)
) AS B ON B.PERSONUID=A.PERSONUID
WHEN MATCHED THEN
UPDATE SET 
	PERSONID=CONCAT('X',B.OLDPERSONID),
	STATUS='INACTIVE';

-- SELECT * FROM maximo.PERSON p WHERE P.PERSONID IN ('123038');
-- SELECT * FROM maximo.PERSON p WHERE P.PERSONUID IN (67599, 67316);
-- 129611
-- 123038

MERGE INTO MAXIMO.PERSON AS A
USING (
	SELECT p.PERSONUID, p.PERSONID AS OLDPERSONID, p.STATUS, m.*
	FROM MIGRATION.SBST_USER_MASTER m 
	LEFT JOIN maximo.PERSON p ON m.PERSONID=p.PERSONID
) AS B ON B.PERSONUID=A.PERSONUID
WHEN MATCHED THEN
UPDATE SET 
	PERSONID=B.SAPID,
	DISPLAYNAME=B.DISPLAYNAME,
	DEPARTMENT=B.DEPARTMENT,
	STE_CSWNBARCODE=B.LANID,
	STE_LANID=B.LANID,
	STATUS='ACTIVE'
;

MERGE INTO MAXIMO.PERSONGROUPTEAM AS A
USING (
	SELECT p.PERSONGROUPTEAMID, p.RESPPARTYGROUP, m.*
	FROM MIGRATION.SBST_USER_MASTER m 
	JOIN maximo.PERSONGROUPTEAM p ON m.SAPID=p.RESPPARTYGROUP
	WHERE p.RESPPARTYGROUP NOT IN (SELECT PERSONID FROM MIGRATION.SBST_USER_MASTER)
) AS B ON B.PERSONGROUPTEAMID=A.PERSONGROUPTEAMID
WHEN MATCHED THEN
UPDATE SET 
	RESPPARTYGROUP=CONCAT('X',B.SAPID), 
	RESPPARTY=CONCAT('X',B.SAPID)
;

MERGE INTO MAXIMO.PERSONGROUPTEAM AS A
USING (
	SELECT p.PERSONGROUPTEAMID, p.RESPPARTYGROUP, m.*
	FROM MIGRATION.SBST_USER_MASTER m 
	JOIN maximo.PERSONGROUPTEAM p ON m.PERSONID=p.RESPPARTYGROUP
) AS B ON B.PERSONGROUPTEAMID=A.PERSONGROUPTEAMID
WHEN MATCHED THEN
UPDATE SET 
	RESPPARTYGROUP=B.SAPID, 
	RESPPARTY=B.SAPID
;

-- LABOR
MERGE INTO MAXIMO.LABOR AS A
USING (
	SELECT p.LABORID, p.LABORCODE, m.*
	FROM MIGRATION.SBST_USER_MASTER m 
	JOIN MAXIMO.LABOR p ON m.SAPID=p.LABORCODE
	WHERE p.LABORCODE NOT IN (SELECT PERSONID FROM MIGRATION.SBST_USER_MASTER)
) AS B ON B.LABORID=A.LABORID
WHEN MATCHED THEN
UPDATE SET 
	LABORCODE=CONCAT('X',B.SAPID)
;

MERGE INTO MAXIMO.LABOR AS A
USING (
	SELECT p.LABORID, p.LABORCODE, m.*
	FROM MIGRATION.SBST_USER_MASTER m 
	JOIN MAXIMO.LABOR p ON m.PERSONID=p.LABORCODE
) AS B ON B.LABORID=A.LABORID
WHEN MATCHED THEN
UPDATE SET 
	LABORCODE=B.SAPID
;

MERGE INTO MAXIMO.LABORQUAL AS A
USING (
	SELECT p.LABORQUALID, p.LABORCODE, m.*
	FROM MIGRATION.SBST_USER_MASTER m 
	JOIN MAXIMO.LABORQUAL p ON m.SAPID=p.LABORCODE
	WHERE p.LABORCODE NOT IN (SELECT PERSONID FROM MIGRATION.SBST_USER_MASTER)
) AS B ON B.LABORQUALID=A.LABORQUALID
WHEN MATCHED THEN
UPDATE SET 
	LABORCODE=CONCAT('X',B.SAPID)
;

MERGE INTO MAXIMO.LABORQUAL AS A
USING (
	SELECT p.LABORQUALID, p.LABORCODE, m.*
	FROM MIGRATION.SBST_USER_MASTER m 
	JOIN MAXIMO.LABORQUAL p ON m.PERSONID=p.LABORCODE
) AS B ON B.LABORQUALID=A.LABORQUALID
WHEN MATCHED THEN
UPDATE SET 
	LABORCODE=B.SAPID
;

-- SELECT * FROM MAXIMO.LABORQUAL WHERE laborcode='X123038'

MERGE INTO MAXIMO.AMCREWLABOR AS A
USING (
	SELECT p.AMCREWLABORID, p.LABORCODE, m.*
	FROM MIGRATION.SBST_USER_MASTER m 
	JOIN MAXIMO.AMCREWLABOR p ON m.SAPID=p.LABORCODE
	WHERE p.LABORCODE NOT IN (SELECT PERSONID FROM MIGRATION.SBST_USER_MASTER)
) AS B ON B.AMCREWLABORID=A.AMCREWLABORID
WHEN MATCHED THEN
UPDATE SET 
	LABORCODE=CONCAT('X',B.SAPID)
;

MERGE INTO MAXIMO.AMCREWLABOR AS A
USING (
	SELECT p.AMCREWLABORID, p.LABORCODE, m.*
	FROM MIGRATION.SBST_USER_MASTER m 
	JOIN MAXIMO.AMCREWLABOR p ON m.PERSONID=p.LABORCODE
) AS B ON B.AMCREWLABORID=A.AMCREWLABORID
WHEN MATCHED THEN
UPDATE SET 
	LABORCODE=B.SAPID
;

-- MR
MERGE INTO MAXIMO.MR AS A
USING (
	SELECT p.MRID, p.REQUESTEDBY, p.STE_MIGRATIONDEMANDER, c.PERSONID
	FROM MIGRATION.SBST_USER_MASTER m 
	JOIN MAXIMO.MR p ON m.SAPID=p.REQUESTEDBY OR m.PERSONID=p.REQUESTEDBY
	JOIN (
		SELECT DISTINCT UPPER(TRIM(DISPLAY_NAME)) AS DISPLAY_NAME, PERSONID
		FROM MIGRATION.STE_MIGRATION_USER_LOOKUP
	) AS c ON c.DISPLAY_NAME=TRIM(UPPER(p.REQUESTEDBY))
	WHERE p.REQUESTEDBY!=c.PERSONID
) AS B ON B.MRID=A.MRID
WHEN MATCHED THEN
UPDATE SET 
	REQUESTEDBY=B.PERSONID
;

MERGE INTO MAXIMO.MR AS A
USING (
	SELECT p.MRID, p.REQUESTEDFOR, p.STE_MIGRATIONDEMANDER, c.PERSONID
	FROM MIGRATION.SBST_USER_MASTER m 
	JOIN MAXIMO.MR p ON m.SAPID=p.REQUESTEDFOR OR m.PERSONID=p.REQUESTEDFOR
	JOIN (
		SELECT DISTINCT UPPER(TRIM(DISPLAY_NAME)) AS DISPLAY_NAME, PERSONID
		FROM MIGRATION.STE_MIGRATION_USER_LOOKUP
	) AS c ON c.DISPLAY_NAME=TRIM(UPPER(p.REQUESTEDFOR))
	WHERE p.REQUESTEDFOR!=c.PERSONID
) AS B ON B.MRID=A.MRID
WHEN MATCHED THEN
UPDATE SET 
	REQUESTEDFOR=B.PERSONID
;

-- CONTRACT
MERGE INTO MAXIMO.CONTRACT AS A
USING (
	SELECT p.CONTRACTID, p.PURCHASEAGENT, p.STE_CREATEDBY, c.PERSONID
	FROM MIGRATION.SBST_USER_MASTER m 
	JOIN MAXIMO.CONTRACT p ON m.SAPID=p.PURCHASEAGENT OR m.PERSONID=p.PURCHASEAGENT
	JOIN (
		SELECT DISTINCT UPPER(TRIM(DISPLAY_NAME)) AS DISPLAY_NAME, PERSONID
		FROM MIGRATION.STE_MIGRATION_USER_LOOKUP
	) AS c ON c.DISPLAY_NAME=TRIM(UPPER(p.PURCHASEAGENT))
	WHERE p.PURCHASEAGENT!=c.PERSONID
) AS B ON B.CONTRACTID=A.CONTRACTID
WHEN MATCHED THEN
UPDATE SET 
	PURCHASEAGENT=B.PERSONID
;

MERGE INTO MAXIMO.CONTRACT AS A
USING (
	SELECT p.CONTRACTID, p.CHANGEBY, p.STE_CREATEDBY, c.PERSONID
	FROM MIGRATION.SBST_USER_MASTER m 
	JOIN MAXIMO.CONTRACT p ON m.SAPID=p.CHANGEBY OR m.PERSONID=p.CHANGEBY
	JOIN (
		SELECT DISTINCT UPPER(TRIM(DISPLAY_NAME)) AS DISPLAY_NAME, PERSONID
		FROM MIGRATION.STE_MIGRATION_USER_LOOKUP
	) AS c ON c.DISPLAY_NAME=TRIM(UPPER(p.CHANGEBY))
	WHERE p.CHANGEBY!=c.PERSONID
) AS B ON B.CONTRACTID=A.CONTRACTID
WHEN MATCHED THEN
UPDATE SET 
	CHANGEBY=B.PERSONID
;

-- PR
MERGE INTO MAXIMO.PR AS A
USING (
	SELECT p.PRID, p.REQUESTEDBY, p.STE_MIGRATIONREQBY, c.PERSONID
	FROM MIGRATION.SBST_USER_MASTER m 
	JOIN MAXIMO.PR p ON m.SAPID=p.REQUESTEDBY OR m.PERSONID=p.REQUESTEDBY
	JOIN (
		SELECT DISTINCT UPPER(TRIM(DISPLAY_NAME)) AS DISPLAY_NAME, PERSONID
		FROM MIGRATION.STE_MIGRATION_USER_LOOKUP
	) AS c ON c.DISPLAY_NAME=TRIM(UPPER(p.REQUESTEDBY))
	WHERE p.REQUESTEDBY!=c.PERSONID
) AS B ON B.PRID=A.PRID
WHEN MATCHED THEN
UPDATE SET 
	REQUESTEDBY=B.PERSONID
;

MERGE INTO MAXIMO.PRLINE AS A
USING (
	SELECT p.PRLINEID, p.REQUESTEDBY, c.PERSONID
	FROM MIGRATION.SBST_USER_MASTER m 
	JOIN MAXIMO.PRLINE p ON m.SAPID=p.REQUESTEDBY OR m.PERSONID=p.REQUESTEDBY
	JOIN (
		SELECT DISTINCT UPPER(TRIM(DISPLAY_NAME)) AS DISPLAY_NAME, PERSONID
		FROM MIGRATION.STE_MIGRATION_USER_LOOKUP
	) AS c ON c.DISPLAY_NAME=TRIM(UPPER(p.REQUESTEDBY))
	WHERE p.REQUESTEDBY!=c.PERSONID
) AS B ON B.PRLINEID=A.PRLINEID
WHEN MATCHED THEN
UPDATE SET 
	REQUESTEDBY=B.PERSONID
;

-- PO
MERGE INTO MAXIMO.PO AS A
USING (
	SELECT p.POID, p.PURCHASEAGENT, p.STE_MIGRATIONREQBY, c.PERSONID
	FROM MIGRATION.SBST_USER_MASTER m 
	JOIN MAXIMO.PO p ON m.SAPID=p.PURCHASEAGENT OR m.PERSONID=p.PURCHASEAGENT
	JOIN (
		SELECT DISTINCT UPPER(TRIM(DISPLAY_NAME)) AS DISPLAY_NAME, PERSONID
		FROM MIGRATION.STE_MIGRATION_USER_LOOKUP
	) AS c ON c.DISPLAY_NAME=TRIM(UPPER(p.PURCHASEAGENT))
	WHERE p.PURCHASEAGENT!=c.PERSONID
) AS B ON B.POID=A.POID
WHEN MATCHED THEN
UPDATE SET 
	PURCHASEAGENT=B.PERSONID
;

MERGE INTO MAXIMO.POLINE AS A
USING (
	SELECT p.POLINEID, p.REQUESTEDBY, c.PERSONID
	FROM MIGRATION.SBST_USER_MASTER m 
	JOIN MAXIMO.POLINE p ON m.SAPID=p.REQUESTEDBY OR m.PERSONID=p.REQUESTEDBY
	JOIN (
		SELECT DISTINCT UPPER(TRIM(DISPLAY_NAME)) AS DISPLAY_NAME, PERSONID
		FROM MIGRATION.STE_MIGRATION_USER_LOOKUP
	) AS c ON c.DISPLAY_NAME=TRIM(UPPER(p.REQUESTEDBY))
	WHERE p.REQUESTEDBY!=c.PERSONID
) AS B ON B.POLINEID=A.POLINEID
WHEN MATCHED THEN
UPDATE SET 
	REQUESTEDBY=B.PERSONID
;

MERGE INTO MAXIMO.POLINE AS A
USING (
	SELECT p.POLINEID, p.ENTERBY, c.PERSONID
	FROM MIGRATION.SBST_USER_MASTER m 
	JOIN MAXIMO.POLINE p ON m.SAPID=p.ENTERBY OR m.PERSONID=p.ENTERBY
	JOIN (
		SELECT DISTINCT UPPER(TRIM(DISPLAY_NAME)) AS DISPLAY_NAME, PERSONID
		FROM MIGRATION.STE_MIGRATION_USER_LOOKUP
	) AS c ON c.DISPLAY_NAME=TRIM(UPPER(p.ENTERBY))
	WHERE p.ENTERBY!=c.PERSONID
) AS B ON B.POLINEID=A.POLINEID
WHEN MATCHED THEN
UPDATE SET 
	ENTERBY=B.PERSONID
;

-- INVOICE
MERGE INTO MAXIMO.INVOICE AS A
USING (
	SELECT p.INVOICEID, p.ENTERBY, p.STE_MIGRATIONREQBY, c.PERSONID
	FROM MIGRATION.SBST_USER_MASTER m 
	JOIN MAXIMO.INVOICE p ON m.SAPID=p.ENTERBY OR m.PERSONID=p.ENTERBY
	JOIN (
		SELECT DISTINCT UPPER(TRIM(DISPLAY_NAME)) AS DISPLAY_NAME, PERSONID
		FROM MIGRATION.STE_MIGRATION_USER_LOOKUP
	) AS c ON c.DISPLAY_NAME=TRIM(UPPER(p.ENTERBY))
	WHERE p.ENTERBY!=c.PERSONID
) AS B ON B.INVOICEID=A.INVOICEID
WHEN MATCHED THEN
UPDATE SET 
	ENTERBY=B.PERSONID
;

MERGE INTO MAXIMO.INVOICELINE AS A
USING (
	SELECT p.INVOICELINEID, p.ENTERBY, p.STE_MIGRATIONREQBY, c.PERSONID
	FROM MIGRATION.SBST_USER_MASTER m 
	JOIN MAXIMO.INVOICELINE p ON m.SAPID=p.ENTERBY OR m.PERSONID=p.ENTERBY
	JOIN (
		SELECT DISTINCT UPPER(TRIM(DISPLAY_NAME)) AS DISPLAY_NAME, PERSONID
		FROM MIGRATION.STE_MIGRATION_USER_LOOKUP
	) AS c ON c.DISPLAY_NAME=TRIM(UPPER(p.ENTERBY))
	WHERE p.ENTERBY!=c.PERSONID
) AS B ON B.INVOICELINEID=A.INVOICELINEID
WHEN MATCHED THEN
UPDATE SET 
	ENTERBY=B.PERSONID
;

-- WORKORDER
MERGE INTO MAXIMO.WORKORDER AS A
USING (
	SELECT p.WORKORDERID, p.REPORTEDBY, p.STE_MIGRATIONREPBY, c.PERSONID
	FROM MIGRATION.SBST_USER_MASTER m 
	JOIN MAXIMO.WORKORDER p ON m.SAPID=p.REPORTEDBY OR m.PERSONID=p.REPORTEDBY
	JOIN (
		SELECT DISTINCT UPPER(TRIM(DISPLAY_NAME)) AS DISPLAY_NAME, PERSONID
		FROM MIGRATION.STE_MIGRATION_USER_LOOKUP
	) AS c ON c.DISPLAY_NAME=TRIM(UPPER(p.REPORTEDBY))
	WHERE p.REPORTEDBY!=c.PERSONID
) AS B ON B.WORKORDERID=A.WORKORDERID
WHEN MATCHED THEN
UPDATE SET 
	REPORTEDBY=B.PERSONID
;
	
-- SR
MERGE INTO MAXIMO.TICKET AS A
USING (
	SELECT p.TICKETID, p.REPORTEDBY, p.STE_MIGRATIONREQBYID, c.PERSONID
	FROM MIGRATION.SBST_USER_MASTER m 
	JOIN MAXIMO.TICKET p ON m.SAPID=p.REPORTEDBY OR m.PERSONID=p.REPORTEDBY
	JOIN (
		SELECT DISTINCT UPPER(TRIM(DISPLAY_NAME)) AS DISPLAY_NAME, PERSONID
		FROM MIGRATION.STE_MIGRATION_USER_LOOKUP
	) AS c ON c.DISPLAY_NAME=TRIM(UPPER(p.REPORTEDBY))
	WHERE p.REPORTEDBY!=c.PERSONID
) AS B ON B.TICKETID=A.TICKETID
WHEN MATCHED THEN
UPDATE SET 
	REPORTEDBY=B.PERSONID
;

-- JOBLABOR
MERGE INTO MAXIMO.JOBLABOR AS A
USING (
	SELECT p.JOBLABORID, p.LABORCODE, m.*
	FROM MIGRATION.SBST_USER_MASTER m 
	JOIN MAXIMO.JOBLABOR p ON m.SAPID=p.LABORCODE
	WHERE p.LABORCODE NOT IN (SELECT PERSONID FROM MIGRATION.SBST_USER_MASTER)
) AS B ON B.JOBLABORID=A.JOBLABORID
WHEN MATCHED THEN
UPDATE SET 
	LABORCODE=CONCAT('X',B.SAPID)
;

MERGE INTO MAXIMO.JOBLABOR AS A
USING (
	SELECT p.JOBLABORID, p.LABORCODE, m.*
	FROM MIGRATION.SBST_USER_MASTER m 
	JOIN MAXIMO.JOBLABOR p ON m.PERSONID=p.LABORCODE
) AS B ON B.JOBLABORID=A.JOBLABORID
WHEN MATCHED THEN
UPDATE SET 
	LABORCODE=B.SAPID
;

