SELECT ID, PERSONID, DISPLAYNAME, SAPID, LANID, EMAIL, MAINTENTITY, DEPARTMENT, MAIN_BUSINESS_ROLE, MAINTENANCE_POC, ASSET_POC, RAISE_PR, REMARKS
FROM MIGRATION.SBST_USER_MASTER;

-- DELETE DUPLICATE DATA
	SELECT p.*
	FROM MIGRATION.SBST_USER_MASTER m 
	JOIN maximo.PERSON p ON m.SAPID=p.PERSONID

MERGE INTO MAXIMO.PERSON AS A
USING (
	SELECT p.PERSONUID, p.PERSONID AS OLDPERSONID, p.STATUS, p.DISPLAYNAME, m.*
	FROM MIGRATION.SBST_USER_MASTER m 
	JOIN maximo.PERSON p ON m.PERSONID=p.PERSONID
) AS B ON B.PERSONUID=A.PERSONUID
WHEN MATCHED THEN
UPDATE SET 
	PERSONID=B.SAPID,
	DISPLAYNAME=B.DISPLAYNAME,
	DEPARTMENT=B.DEPARTMENT,
	STE_CSWNBARCODE=B.LANID,
	STE_LANID=B.LANID
;

MERGE INTO MAXIMO.PERSON AS A
USING (
	SELECT p.PERSONGROUPTEAMID, p.RESPPARTYGROUP, m.*
	FROM MIGRATION.SBST_USER_MASTER m 
	JOIN maximo.PERSONGROUPTEAM p ON m.PERSONID=p.RESPPARTYGROUP
) AS B ON B.PERSONGROUPTEAMID=A.PERSONGROUPTEAMID
WHEN MATCHED THEN
UPDATE SET 
	RESPPARTYGROUP=B.SAPID, 
	RESPPARTY=B.SAPID
;

-- JUST REGENERATE THE LOOKUP
MERGE INTO MIGRATION.STE_MIGRATION_USER_LOOKUP AS A
USING (
	SELECT p.PKEY, m.*
	FROM MIGRATION.SBST_USER_MASTER m 
	JOIN MIGRATION.STE_MIGRATION_USER_LOOKUP p ON m.PERSONID=p.PERSONID
) AS B ON B.PKEY=A.PKEY
WHEN MATCHED THEN
UPDATE SET 
	PERSONID=B.SAPID
;

MERGE INTO MAXIMO.LABOR AS A
USING (
	SELECT p.LABORID, p.LABORCODE, m.*
	FROM MIGRATION.SBST_USER_MASTER m 
	JOIN MAXIMO.LABOR p ON m.PERSONID=p.LABORCODE
) AS B ON B.LABORID=A.LABORID
WHEN MATCHED THEN
UPDATE SET 
	LABORCODE=B.SAPID
;

-- TODO CREATE NEW LABOR?
	SELECT p.LABORID, p.LABORCODE, m.*
	FROM MIGRATION.SBST_USER_MASTER m 
	LEFT JOIN MAXIMO.LABOR p ON m.SAPID=p.LABORCODE;


MERGE INTO MAXIMO.LABORQUAL AS A
USING (
	SELECT p.LABORQUALID, p.LABORCODE, m.*
	FROM MIGRATION.SBST_USER_MASTER m 
	JOIN MAXIMO.LABORQUAL p ON m.PERSONID=p.LABORCODE
) AS B ON B.LABORQUALID=A.LABORQUALID
WHEN MATCHED THEN
UPDATE SET 
	LABORCODE=B.SAPID
;

